{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ARLPBIDEV;ARLPBI_STAGE",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ARLPBIDEV",
            "database": "ARLPBI_STAGE"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "arlpbidev;ARLPBI_STAGE",
          "Username": "DOMAIN\\PBI-ETL",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Customer Master",
        "columns": [
          {
            "name": "Customer Number",
            "dataType": "string",
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Account Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "AcctCreateDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Sales Organization",
            "dataType": "string",
            "sourceColumn": "SalesOrganization"
          },
          {
            "name": "Default Ship Plant",
            "dataType": "string",
            "sourceColumn": "DefaultPlant"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesDistrict"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritory"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_CUSTOMER_MASTER = Source{[Schema=\"dbo\",Item=\"VW_CUSTOMER_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_CUSTOMER_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Complaint Documents",
        "columns": [
          {
            "name": "Complaint Number",
            "dataType": "string",
            "sourceColumn": "ComplaintNoKey"
          },
          {
            "name": "Complaint Line Number",
            "dataType": "string",
            "sourceColumn": "ComplaintLineNo"
          },
          {
            "name": "Complaint Type",
            "dataType": "string",
            "sourceColumn": "ComplaintType"
          },
          {
            "name": "Billing Block Indicator",
            "dataType": "string",
            "sourceColumn": "BillingBlockIndicator"
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Complaint Amount",
            "dataType": "double",
            "sourceColumn": "ComplaintValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS,{\"ComplaintNoKey\", \"ComplaintLineNo\", \"ComplaintType\", \"BillingBlockIndicator\", \"EnteredBy\", \"EnterDateKey\", \"ReasonCodeKey\", \"CustomerOrgKey\", \"PlantNoKey\", \"MaterialNoKey\", \"ComplaintValueUSD\", \"CreditIssueValueUSD\", \"OpenValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Reason Code",
        "columns": [
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Reason Code Description",
            "dataType": "string",
            "sourceColumn": "ReasonCodeDescription"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data]",
                "in",
                "    dbo_VW_REASON_CODE"
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "isKey": true,
            "sourceColumn": "PK_Date",
            "formatString": "MM/dd/yyyy",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Year Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal_Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal_Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month_Name_Abbrev",
            "sortByColumn": "Year_Month_Sort_Key",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Current Month",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Month",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is MTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Mtd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Calendar YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Calendar_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Fiscal YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Fiscal_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Year_Month_Sort_Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Year_Month_Sort_Key"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_Calendar = Source{[Schema=\"dbo\",Item=\"VW_Calendar\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_Calendar,{{\"PK_Date\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"PK_Date\", \"Year_Name\", \"Month_Of_Year\", \"Quarter_Of_Year_Name\", \"Fiscal_Year_Name\", \"Fiscal_Month_Of_Year\", \"Fiscal_Quarter_Of_Year_Name\", \"Month_Name_Abbrev\", \"Year_Month_Sort_Key\", \"Is_Current_Month\", \"Is_Mtd\", \"Is_Calendar_Ytd\", \"Is_Fiscal_Ytd\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year Number"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Calendar Quarter Name"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          },
          {
            "name": "Fiscal Hierarchy",
            "levels": [
              {
                "name": "Fiscal Quarter",
                "ordinal": 1,
                "column": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Number"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DAX Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Measure Column",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{1}"
            }
          }
        ],
        "measures": [
          {
            "name": "Gross Sales",
            "expression": " SUM('Sales Invoice Documents'[Gross Sales Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales",
            "expression": " SUM('Sales Invoice Documents'[Net Sales Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Cost of Goods",
            "expression": " SUM('Sales Invoice Documents'[Overall Cost Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Gross Margin",
            "expression": " [Gross Sales] - [Cost of Goods]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Margin",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Margin",
            "expression": " [Net Sales] - [Cost of Goods]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Margin",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Gross Margin %",
            "expression": " DIVIDE([Gross Margin], [Gross Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales\\Margin"
          },
          {
            "name": "Net Margin %",
            "expression": " DIVIDE( [Net Margin], [Net Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales\\Margin"
          },
          {
            "name": "Complaint Value",
            "expression": " SUM('Complaint Documents'[Complaint Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued",
            "expression": " SUM('Complaint Documents'[Credit Issued Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Value",
            "expression": " SUM('Complaint Documents'[Open Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Complaint Count",
            "expression": " DISTINCTCOUNT( 'Complaint Documents'[Complaint Number] ) + 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Count"
          },
          {
            "name": "PQ Complaint Count",
            "expression": " CALCULATE( [Complaint Count], FILTER( 'Reason Code', 'Reason Code'[Department] = \"Q\") )",
            "formatString": "#,0",
            "displayFolder": "Complaints\\Count"
          },
          {
            "name": "PQ Complaint Value",
            "expression": " CALCULATE( [Complaint Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Credit Issued",
            "expression": " CALCULATE( [Credit Issued], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Open Value",
            "expression": " CALCULATE( [Open Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index",
            "expression": " DIVIDE( [PQ Complaint Value], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Credited)",
            "expression": " DIVIDE( [PQ Credit Issued], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Open)",
            "expression": " DIVIDE( [PQ Open Value], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Hold Amount",
            "expression": " SUM('Hold Tag Documents'[Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Hold Tags\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Hold Quantity",
            "expression": " SUM('Hold Tag Documents'[Quantity]) + 0",
            "formatString": "#,0.00",
            "displayFolder": "Hold Tags\\Sum"
          },
          {
            "name": "Hold Tag Count",
            "expression": " DISTINCTCOUNT( 'Hold Tag Documents'[Notification Number] ) + 0",
            "formatString": "#,0",
            "displayFolder": "Hold Tags\\Count"
          },
          {
            "name": "Current S-Block Value",
            "expression": " SUM('Blocked Inventory'[SBlock Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Q-Block Value",
            "expression": " SUM('Blocked Inventory'[QBlock Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Expired Value",
            "expression": " SUM('Expired Inventory'[Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Blocked Inv Value",
            "expression": " [Current S-Block Value] + [Current Q-Block Value] + [Current Expired Value]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor Cost",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Cost]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Labor\"",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Setup Cost",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Cost]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Setup\"",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Overhead Cost",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Cost]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Absorption Cost",
            "expression": " [Earned Labor Cost] + [Earned Setup Cost] + [Earned Overhead Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor Hours",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Hours]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Labor\"",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Absorption\\Sum"
          },
          {
            "name": "Earned Setup Hours",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Hours]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Setup\"",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Absorption\\Sum"
          },
          {
            "name": "Earned Overhead Hours",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Hours]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Absorption\\Sum"
          },
          {
            "name": "Earned Labor & Setup Cost",
            "expression": " [Earned Labor Cost] + [Earned Setup Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor & Setup Hours",
            "expression": " [Earned Labor Hours] + [Earned Setup Hours]",
            "formatString": "#,0.00",
            "displayFolder": "Absorption\\Sum"
          }
        ]
      },
      {
        "name": "Sales Invoice Documents",
        "columns": [
          {
            "name": "Invoice Number",
            "dataType": "string",
            "sourceColumn": "SaleDocNoKey"
          },
          {
            "name": "Invoice Line Number",
            "dataType": "string",
            "sourceColumn": "SaleLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales Amount",
            "dataType": "double",
            "sourceColumn": "GrossSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales Amount",
            "dataType": "double",
            "sourceColumn": "NetSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Overall Cost Amount",
            "dataType": "double",
            "sourceColumn": "CostValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Material Cost Amount",
            "dataType": "double",
            "sourceColumn": "MaterialExtPriceUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "double",
            "sourceColumn": "DiscountValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_SALES = Source{[Schema=\"dbo\",Item=\"VW_SALES\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_VW_SALES,{\"MANDT\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Hold Tag Documents",
        "columns": [
          {
            "name": "Notification Number",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Notification Type",
            "dataType": "string",
            "sourceColumn": "NotificationType"
          },
          {
            "name": "Notification Code",
            "dataType": "string",
            "sourceColumn": "NotificationCode"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Reference Number",
            "dataType": "string",
            "sourceColumn": "ReferenceNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Notification Text",
            "dataType": "string",
            "sourceColumn": "NotificationText"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "HoldQuantityValue",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "HoldValueUSD",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_HOLDTAGS = Source{[Schema=\"dbo\",Item=\"VW_HOLDTAGS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_HOLDTAGS,{\"NotificationNoKey\", \"NotificationType\", \"NotificationCode\", \"EnterDateKey\", \"ReferenceNo\", \"MaterialNoKey\", \"BatchNoKey\", \"NotificationText\", \"QuantityUoM\", \"HoldQuantityValue\", \"HoldValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "NotificationNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "SBlock Quantity",
            "dataType": "double",
            "sourceColumn": "SBlockQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "SBlock Amount",
            "dataType": "double",
            "sourceColumn": "SBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Quantity",
            "dataType": "double",
            "sourceColumn": "QBlockQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "QBlock Amount",
            "dataType": "double",
            "sourceColumn": "QBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_BLOCK,{\"MaterialNoKey\", \"BatchNoKey\", \"NotificationNoKey\", \"PlantNo\", \"StorageLoc\", \"SBlockQuantityValue\", \"SBlockAmountUSD\", \"QBlockQuantityValue\", \"QBlockAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expired Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "sourceColumn": "MfgDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Goods Receipt Date",
            "dataType": "dateTime",
            "sourceColumn": "GoodsReceiptDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Expiration Date",
            "dataType": "dateTime",
            "sourceColumn": "ExpirationDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "ExpiredQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "ExpiredAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_EXPIRED = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_EXPIRED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_EXPIRED,{\"MaterialNoKey\", \"BatchNo\", \"PlantNo\", \"MfgDate\", \"GoodsReceiptDate\", \"ExpirationDate\", \"StockQuantityValue\", \"ExpiredQuantityValue\", \"StockAmountUSD\", \"ExpiredAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory Snapshots",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "SBlock Value",
            "dataType": "double",
            "sourceColumn": "SBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Value",
            "dataType": "double",
            "sourceColumn": "QBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expired Value",
            "dataType": "double",
            "sourceColumn": "ExpiredValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Blocked Inv Value",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " 'Blocked Inventory Snapshots'[SBlock Value] + 'Blocked Inventory Snapshots'[QBlock Value] + 'Blocked Inventory Snapshots'[Expired Value] + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_DAILY_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"DAILY_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DAILY_INVENTORY_BLOCK,{{\"SnapshotDateKey\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"SnapshotDateKey\", \"PlantNoKey\", \"SBlockValueUSD\", \"QBlockValueUSD\", \"ExpiredValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Absorption",
        "columns": [
          {
            "name": "Process Order",
            "dataType": "string",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "SuperiorMaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SuperiorMaterialNoKey"
          },
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "CostElementKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "BusTransType"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Hours",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "NetValue",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_ABSORPTION\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Classification",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color Number",
            "dataType": "string",
            "sourceColumn": "ColorNumber"
          },
          {
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "sourceColumn": "CommercializationDate"
          },
          {
            "name": "Film Type",
            "dataType": "string",
            "sourceColumn": "FilmType"
          },
          {
            "name": "Liner",
            "dataType": "string",
            "sourceColumn": "Liner"
          },
          {
            "name": "Product Series",
            "dataType": "string",
            "sourceColumn": "ProductSeries"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_CLASSIFICATION = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_CLASSIFICATION\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_CLASSIFICATION"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Master",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialDescription"
          },
          {
            "name": "Material Number - Description",
            "dataType": "string",
            "sourceColumn": "MaterialNoDescription"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "sourceColumn": "MaterialType"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "X Distribution Status",
            "dataType": "string",
            "sourceColumn": "XDistributionStatus"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasure"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_MASTER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Product Hierarchy",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL1"
          },
          {
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL2"
          },
          {
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL3"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_PRODHIERARCHY = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_PRODHIERARCHY\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_PRODHIERARCHY"
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Center Names",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Cost Center Name",
            "dataType": "string",
            "sourceColumn": "CostCenterName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Operations Category",
            "dataType": "string",
            "sourceColumn": "OperationsCategory"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COST_CENTER_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_CENTER_NAMES\"]}[Data]",
                "in",
                "    dbo_VW_COST_CENTER_NAMES"
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Element Names",
        "columns": [
          {
            "name": "Cost Element",
            "dataType": "string",
            "sourceColumn": "CostElement"
          },
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Sub Category",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "Category Renamed",
            "dataType": "string",
            "sourceColumn": "CatRenamed"
          },
          {
            "name": "Is Controllable Expense",
            "dataType": "boolean",
            "sourceColumn": "IsControllableExpense"
          },
          {
            "name": "Is Labor",
            "dataType": "boolean",
            "sourceColumn": "IsLabor"
          },
          {
            "name": "Is Supplies",
            "dataType": "boolean",
            "sourceColumn": "IsSupplies"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COST_ELEMENT_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_ELEMENT_NAMES\"]}[Data]",
                "in",
                "    dbo_VW_COST_ELEMENT_NAMES"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7a5e16ad-98c3-4fca-972e-81cd14cf4bdc",
        "toCardinality": "many",
        "fromTable": "Complaint Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "7ad599af-e270-40c4-9adb-251c9dca4378",
        "fromTable": "Complaint Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "7bc6c5a0-4655-407a-bc13-1cd3a65eca38",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "9aea2de3-d4c1-473e-bf03-55a3a8d409f5",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "90d80725-4955-4415-8778-f3b670ded05f",
        "fromTable": "Complaint Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "1196625d-915c-4f90-8a7e-4a4e307c34c4",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "72c7c6a1-aabc-4bfc-8491-7d49d9138e2e",
        "fromTable": "Blocked Inventory",
        "fromColumn": "NotificationNoKey",
        "toTable": "Hold Tag Documents",
        "toColumn": "Notification Number",
        "isActive": false
      },
      {
        "name": "3f9dd1f7-3ac5-4bce-b233-68a54ac9862f",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "bf66fd75-c362-4675-abd4-420fb281ca3f",
        "fromTable": "Absorption",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "637bbb79-1df9-41df-9f01-6327cb2e1ca5",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Material Classification",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "8dbdc264-a57e-48f4-8ccf-064f378c4788",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Product Hierarchy",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "22d61dbe-0265-4bd3-b686-8d76e4f1d50f",
        "fromTable": "Complaint Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "c2395825-7531-4dd0-9c3e-d4e7a214fb64",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "d104f71c-fb20-42c2-a158-df74a0040f19",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "774c8489-a2be-42c4-8a1b-8dffc10c2904",
        "fromTable": "Blocked Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "75f7059e-5891-4145-8c3b-08cf13009c2f",
        "fromTable": "Expired Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "22f5ffae-1a73-4d36-815b-33b46aefbcf9",
        "fromTable": "Absorption",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "48c5cf15-f0eb-40f5-94a2-1dc0d8170fe9",
        "fromTable": "Absorption",
        "fromColumn": "CostCenterKey",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "ee91563a-f093-480b-b5c9-79419b8fcce9",
        "fromTable": "Absorption",
        "fromColumn": "CostElementKey",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      }
    ],
    "perspectives": [
      {
        "name": "Absorption Dashboard",
        "tables": [
          {
            "name": "Absorption",
            "columns": [
              {
                "name": "Cost"
              },
              {
                "name": "CostCenterKey"
              },
              {
                "name": "CostElementKey"
              },
              {
                "name": "Hours"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order"
              },
              {
                "name": "SuperiorMaterialNoKey"
              },
              {
                "name": "Transaction Type"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Absorption Cost"
              },
              {
                "name": "Earned Labor Cost"
              },
              {
                "name": "Earned Overhead Cost"
              },
              {
                "name": "Earned Setup Cost"
              },
              {
                "name": "Earned Labor Hours"
              },
              {
                "name": "Earned Overhead Hours"
              },
              {
                "name": "Earned Setup Hours"
              },
              {
                "name": "Earned Labor & Setup Cost"
              },
              {
                "name": "Earned Labor & Setup Hours"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Year_Month_Sort_Key"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Material Classification",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Product Series"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              }
            ]
          },
          {
            "name": "Product Hierarchy",
            "columns": [
              {
                "name": "Material Number"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Sub Category"
              }
            ]
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}