{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "ARLPBI_STAGE",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ARLPBIDEV",
            "database": "ARLPBI_STAGE"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "arlpbidev;ARLPBI_STAGE",
          "Username": "DOMAIN\\PBI-ETL",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Customer Master",
        "columns": [
          {
            "name": "Customer Number",
            "dataType": "string",
            "description": "SAP Source: KNA1.KUNNR",
            "sourceColumn": "CustomerNoKey",
            "displayFolder": "Master"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Country",
            "dataType": "string",
            "description": "SAP Source: KNA1.LAND1",
            "sourceColumn": "Country",
            "displayFolder": "Master"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "description": "SAP Source: KNA1.NAME1",
            "sourceColumn": "CustomerName",
            "displayFolder": "Master"
          },
          {
            "name": "Account Creation Date",
            "dataType": "dateTime",
            "description": "SAP Source: KNA1.ERDAT",
            "sourceColumn": "AcctCreateDate",
            "formatString": "Short Date",
            "displayFolder": "Master",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Sales Organization",
            "dataType": "string",
            "description": "SAP Source: KNVV.VKORG",
            "sourceColumn": "SalesOrganization",
            "displayFolder": "Sales Related"
          },
          {
            "name": "Default Ship Plant",
            "dataType": "string",
            "description": "SAP Source: KNVV.VWERK",
            "sourceColumn": "DefaultPlant",
            "displayFolder": "Master"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "description": "SAP Source: KNVV.BZIRK; If the sales territory name contains \"Fleet\", this value is changed to \"FLEET\"",
            "sourceColumn": "SalesDistrict",
            "sortByColumn": "SalesRegionSortKey",
            "displayFolder": "Sales Related"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "description": "SAP Source: KNVV.VKBUR",
            "sourceColumn": "SalesTerritory",
            "displayFolder": "Sales Related"
          },
          {
            "type": "calculated",
            "name": "Is New Customer",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "description": "A customer is new if the account is created in the last 12 months",
            "expression": " 'Customer Master'[Account Creation Date] >= [Date 12 Months Ago]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "Master"
          },
          {
            "name": "Sales Person",
            "dataType": "string",
            "description": "Assigned manually; Contact IT for more details",
            "sourceColumn": "SalesPerson",
            "displayFolder": "Sales Related"
          },
          {
            "name": "SalesRegionSortKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesRegionSortKey"
          },
          {
            "name": "Sales Territory Name",
            "dataType": "string",
            "description": "SAP Source: TVKBT.BEZEI",
            "sourceColumn": "SalesTerritoryName",
            "displayFolder": "Sales Related"
          },
          {
            "name": "Price List Code",
            "dataType": "string",
            "description": "SAP Source: KNVV.PLTYP",
            "sourceColumn": "PriceListCode",
            "displayFolder": "Master"
          },
          {
            "name": "Price List Name",
            "dataType": "string",
            "description": "SAP Source: T189T.PTEXT",
            "sourceColumn": "PriceListName",
            "displayFolder": "Master"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_CUSTOMER_MASTER = Source{[Schema=\"dbo\",Item=\"VW_CUSTOMER_MASTER\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_CUSTOMER_MASTER, \"SalesRegionSortKey\", each if [SalesDistrict] = \"DOM\" then 1 else if [SalesDistrict] = \"FLEET\" then 2 else if [SalesDistrict] = \"EUROPE\" then 3 else if [SalesDistrict] = \"LA\" then 4 else if [SalesDistrict] = \"AUS\" then 5 else if [SalesDistrict] = \"ASIA\" then 6 else 9999, type number)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ]
      },
      {
        "name": "Complaint Documents",
        "columns": [
          {
            "name": "Complaint Number",
            "dataType": "string",
            "sourceColumn": "ComplaintNoKey"
          },
          {
            "name": "Complaint Line Number",
            "dataType": "string",
            "sourceColumn": "ComplaintLineNo"
          },
          {
            "name": "Complaint Type",
            "dataType": "string",
            "sourceColumn": "ComplaintType"
          },
          {
            "name": "Billing Block Indicator",
            "dataType": "string",
            "sourceColumn": "BillingBlockIndicator"
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Complaint Amount",
            "dataType": "double",
            "sourceColumn": "ComplaintValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Last Credit Date",
            "dataType": "dateTime",
            "sourceColumn": "LastCreditDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Cycle Time",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " IF([Last Credit Date], DATEDIFF('Complaint Documents'[Enter Date], [Last Credit Date], DAY), BLANK())"
          },
          {
            "type": "calculated",
            "name": "Category",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              " IF(",
              "    AND(",
              "        RELATED( 'Reason Code'[Department] ) = \"Q\",",
              "        RELATED( 'Material Master'[Material Type] ) = \"HAWA\"",
              "    ),",
              "    \"Buyout\",",
              "    RELATED( 'Reason Code'[Class] )",
              ")"
            ],
            "displayFolder": "Reason Code"
          },
          {
            "name": "ComplaintLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ComplaintLineKey"
          },
          {
            "type": "calculated",
            "name": "Reason Code Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Reason Code'[Reason Code Description] )",
            "displayFolder": "Reason Code"
          },
          {
            "type": "calculated",
            "name": "Department",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Reason Code'[Department] )",
            "displayFolder": "Reason Code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS,{\"ComplaintLineKey\", \"ComplaintNoKey\", \"ComplaintLineNo\", \"ComplaintType\", \"BillingBlockIndicator\", \"EnteredBy\", \"EnterDateKey\", \"LastCreditDateKey\", \"ReasonCodeKey\", \"CustomerOrgKey\", \"PlantNoKey\", \"MaterialNoKey\", \"ComplaintValueUSD\", \"CreditIssueValueUSD\", \"OpenValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "description": "Calendar table used to filter or group multiple fact tables",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PK_Date",
            "formatString": "Short Date",
            "displayFolder": "Individual Attributes",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Calendar Year Number",
            "dataType": "string",
            "sourceColumn": "Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "sourceColumn": "Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "sourceColumn": "Fiscal_Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Name",
            "dataType": "string",
            "sourceColumn": "Fiscal_Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "description": "Sorted by fiscal period",
            "sourceColumn": "Month_Name_Abbrev",
            "sortByColumn": "Fiscal Period",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Current Month",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Month",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is MTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Mtd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Calendar YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Calendar_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Fiscal YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Fiscal_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Year_Month_Sort_Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Year_Month_Sort_Key"
          },
          {
            "name": "Calendar Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Week_Of_Year"
          },
          {
            "name": "Is Last 2 Fiscal Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last2_Fiscal_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 13 Months",
            "dataType": "boolean",
            "sourceColumn": "Is_Last13_Months",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Current Fiscal Year",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Fiscal_Year",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day_Of_Month",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Weekday",
            "dataType": "boolean",
            "sourceColumn": "Is_Weekday",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 2 Calendar Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last2_Calendar_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Fiscal Year Month Name",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year_Month_Name",
            "sortByColumn": "Year_Month_Sort_Key",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name (Calendar)",
            "dataType": "string",
            "sourceColumn": "Month_Name_Abbrev_Calendar",
            "sortByColumn": "Calendar Month Number",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Last 3 Fiscal Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last3_Fiscal_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 3 Calendar Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last3_Calendar_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Week Group",
            "dataType": "string",
            "sourceColumn": "Group_Week",
            "sortByColumn": "Year_Week_Sort_Key",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Next 3 Months",
            "dataType": "boolean",
            "sourceColumn": "Is_Next3_Months",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Recent Weeks",
            "dataType": "boolean",
            "description": "True if date is between 8 weeks ago and 2 weeks forward (relative to today)",
            "sourceColumn": "Is_Recent_Weeks",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Weekday",
            "dataType": "int64",
            "sourceColumn": "Day_Of_Week",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Year_Week_Sort_Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Year_Week_Sort_Key"
          },
          {
            "name": "Start of Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Start_Of_Month",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Weekday Name",
            "dataType": "string",
            "sourceColumn": "Weekday_Name",
            "sortByColumn": "Weekday",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is After 13 Months Ago",
            "dataType": "boolean",
            "sourceColumn": "Is_After_13MonthsAgo",
            "displayFolder": "Helper Attributes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_Calendar = Source{[Schema=\"dbo\",Item=\"VW_Calendar\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_Calendar,{{\"PK_Date\", type date}, {\"Start_Of_Month\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"PK_Date\", \"Year_Name\", \"Month_Of_Year\", \"Quarter_Of_Year_Name\", \"Fiscal_Year_Name\", \"Fiscal_Month_Of_Year\", \"Fiscal_Quarter_Of_Year_Name\", \"Day_Of_Month\", \"Fiscal_Year_Month_Name\", \"Month_Name_Abbrev\", \"Month_Name_Abbrev_Calendar\", \"Week_Of_Year\", \"Year_Month_Sort_Key\", \"Weekday_Name\", \"Day_Of_Week\", \"Is_Weekday\", \"Is_Current_Month\", \"Is_Current_Fiscal_Year\", \"Is_Mtd\", \"Is_Calendar_Ytd\", \"Is_Fiscal_Ytd\", \"Is_Last2_Fiscal_Years\", \"Is_Last2_Calendar_Years\", \"Is_Last3_Fiscal_Years\", \"Is_Last3_Calendar_Years\", \"Is_Last13_Months\", \"Is_After_13MonthsAgo\", \"Is_Next3_Months\", \"Is_Recent_Weeks\", \"Year_Week_Sort_Key\", \"Group_Week\", \"Start_Of_Month\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year Number"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Calendar Quarter Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name (Calendar)"
              }
            ]
          },
          {
            "name": "Fiscal Hierarchy",
            "levels": [
              {
                "name": "Fiscal Quarter",
                "ordinal": 1,
                "column": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Number"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DAX Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Sales Invoice",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Complaints",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Inventory",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Expenses",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Sales Orders",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Purchase Orders",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "GRIR",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Absorption Measures",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Engineering",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Shop Orders",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Machine Status",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Odoo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Warehouse",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Testing",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{1}"
            }
          }
        ],
        "measures": [
          {
            "name": "Gross Sales",
            "description": "(SAP Source: Sum of CE110US.ERLOS)",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Gross Sales Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents', 'Sales Invoice Documents'[Gross Sales Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Gross Sales Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Gross Sales Amount] )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Sales",
            "description": "Net of gross sales and discounts; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Net Sales Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents',  'Sales Invoice Documents'[Net Sales Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Net Sales Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Net Sales Amount] )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Overall Cost",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Overall Cost Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents', 'Sales Invoice Documents'[Overall Cost Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Overall Cost Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Overall Cost Amount] )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Gross Margin",
            "description": "Net of gross sales and overall cost; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " SUM( 'Sales Invoice Documents'[Gross Margin Amount] )",
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [Net Sales] - [Overall Cost]",
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Gross Margin %",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE([Gross Margin], [Gross Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Margin %",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [Net Margin], [Net Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales"
          },
          {
            "name": "Complaint Value",
            "expression": " SUM('Complaint Documents'[Complaint Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued",
            "expression": " SUM('Complaint Documents'[Credit Issued Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Value",
            "expression": " SUM('Complaint Documents'[Open Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Complaint Count",
            "expression": " DISTINCTCOUNT( 'Complaint Documents'[Complaint Number] ) + 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Complaint Count], FILTER( 'Reason Code', 'Reason Code'[Department] = \"Q\") )",
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Value",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Complaint Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Credit Issued",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Credit Issued], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Open Value",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Open Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Credited)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Credit Issued], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Open)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Open Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Hold Amount",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " SUM('Hold Tag Documents'[Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Hold Tags",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Hold Quantity",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " SUM('Hold Tag Documents'[Quantity])",
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Hold Tags"
          },
          {
            "name": "Hold Tag Count",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " DISTINCTCOUNT( 'Hold Tag Documents'[Notification Number] )",
            "formatString": "#,0",
            "displayFolder": "Hold Tags"
          },
          {
            "name": "Current S-Block Value",
            "expression": " SUM('Blocked Inventory'[SBlock Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Q-Block Value",
            "expression": " SUM('Blocked Inventory'[QBlock Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Blocked Inv Value",
            "expression": " [Current S-Block Value] + [Current Q-Block Value] + [Current Expired Value]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Expired Value",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Expired Inventory'[Stock Amount] ),",
              "    FILTER(",
              "        ALL( 'Expired Inventory'[Expiration Date] ),",
              "        'Expired Inventory'[Expiration Date] <= [Report Date]",
              "    )",
              ")",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index (Target)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"PQI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Cycle Time",
            "description": "Date grouping: 'Complaint Documents'[Last Credit Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Complaint Documents'[Cycle Time] ),",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\"",
              "    ),",
              "    USERELATIONSHIP('Calendar'[Date], 'Complaint Documents'[Last Credit Date])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "Expenses Amount",
            "description": "Date grouping: 'Expenses'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Expenses[Amount]) + 0,",
              "    ALL( Plant[Plant] )",
              ")"
            ],
            "formatString": "$#,##0;($#,##0);\"-\"",
            "displayFolder": "Expenses"
          },
          {
            "name": "Expenses Plan",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( Target_Expenses[TargetValue]),",
              "    FILTER(",
              "        ALL( Target_Expenses[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_Expenses[CalendarTimeKey]",
              "        )",
              "    ),",
              "    FILTER(",
              "        ALL( Target_Expenses[CostCenterKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Cost Center Names'[Cost Center] ),",
              "            'Cost Center Names'[Cost Center], Target_Expenses[CostCenterKey]",
              "        )",
              "    ),",
              "    FILTER(",
              "        ALL( Target_Expenses[CostElementKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Cost Element Names'[Cost Element] ),",
              "            'Cost Element Names'[Cost Element], Target_Expenses[CostElementKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "$#,##0;($#,##0);\"-\"",
            "displayFolder": "Expenses"
          },
          {
            "name": "SQ Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complaint Count], ",
              "    FILTER(",
              "        'Reason Code', ",
              "        'Reason Code'[Department] = \"S\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "SQ Complaint Value",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Complaint Documents - Credited'[Credit Issued Amount] ) + 0,",
              "    'Complaint Documents'[Billing Block Indicator] = \"\",",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"S\"",
              "    ),",
              "    USERELATIONSHIP(",
              "        'Calendar'[Date],",
              "        'Complaint Documents - Credited'[Credit Issued Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CA Complaint Value",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Complaint Documents - Credited'[Credit Issued Amount] ) + 0,",
              "    'Complaint Documents'[Billing Block Indicator] = \"\",",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"S1\"",
              "    ),",
              "    USERELATIONSHIP(",
              "        'Calendar'[Date],",
              "        'Complaint Documents - Credited'[Credit Issued Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CA Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complaint Count], ",
              "    FILTER(",
              "        'Reason Code', ",
              "        'Reason Code'[Department] = \"S1\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "Service Quality Index",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": " DIVIDE( [SQ Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "Customer Accommodation Index",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": " DIVIDE( [CA Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "Service Quality Index (Target)",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"SQI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Customer Accommodation Index (Target)",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"CAI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " SUM( 'Sales Order Documents'[Order Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales Orders",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sales Order Cost Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " SUM( 'Sales Order Documents'[Cost Amount] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales Orders",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Date 12 Months Ago",
            "expression": " EOMONTH( EDATE( [Report Date], -12), -1) + 1",
            "formatString": "Short Date",
            "isHidden": true,
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Sales Order Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DISTINCTCOUNT(  'Sales Order Documents'[Order Number] )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Sales], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Sales], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Margin], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin %], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin %], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Margin%], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Margin%], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Margin], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " IF( NOT( OR(ISBLANK([FYTD Gross Sales]), ISBLANK([FYTD PY Gross Sales]) ) ), [FYTD Gross Sales] - [FYTD PY Gross Sales], BLANK() )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Gross Sales Budget",
            "description": "Budget numbers submitted by Sales to IT; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Target_Sales[GrossSales] ),",
              "    TREATAS(",
              "        VALUES( 'Customer Master'[Sales Territory] ),",
              "        Target_Sales[SalesTerritoryKey]",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "        Target_Sales[CalendarTimeKey]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales"
          },
          {
            "name": "Backorder Amount",
            "description": "Total customer open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship on or before the end of current month; Internal open amount is ordered minus allocated minus shipped amount; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Margin",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Order Documents'[Margin Amount] ),",
              "        \"Local\", SUM( 'Sales Order Documents'[Margin Amount Local] ),",
              "        SUM( 'Sales Order Documents'[Margin Amount] )",
              "    ),",
              "    SUM( 'Sales Order Documents'[Margin Amount] )  ",
              ") + 0"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Margin",
            "description": "Total margin of internally open sales order items (TA, ZCON, and ZDSP) originally scheduled to ship on or before the end of current month; Internal open amount is ordered minus allocated minus shipped amount; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Margin],",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " SUM( 'Sales Invoice Documents'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Sales"
          },
          {
            "name": "MTD PY Var Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " IF( NOT( OR(ISBLANK([MTD Gross Sales]), ISBLANK([MTD PY Gross Sales]) ) ), [MTD Gross Sales] - [MTD PY Gross Sales], BLANK() )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var% Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [MTD PY Var Gross Sales], [MTD PY Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var% Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [FYTD PY Var Gross Sales], [FYTD PY Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Quantity Sold], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Quantity Sold], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Yesterday",
            "expression": " TODAY() - 1",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Beginning of Month",
            "expression": " EOMONTH( [Report Date], -1 ) + 1",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "End of Month",
            "expression": " EOMONTH( [Report Date], 0 )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "MTD Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Amount], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [MTD Sales Order Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "IF( ",
              "    AND( ",
              "        NOT(ISBLANK([MTD Sales Order Amount])), ",
              "        NOT(ISBLANK([MTD PY Sales Order Amount])) ",
              "    ), ",
              "    [MTD Sales Order Amount] - [MTD PY Sales Order Amount], ",
              "    BLANK() ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var% Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [MTD PY Var Sales Order Amount], [MTD PY Sales Order Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Amount], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [FYTD Sales Order Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "IF( ",
              "    AND( ",
              "        NOT(ISBLANK([FYTD Sales Order Amount])), ",
              "        NOT(ISBLANK([FYTD PY Sales Order Amount])) ",
              "    ), ",
              "    [FYTD Sales Order Amount] - [FYTD PY Sales Order Amount], ",
              "    BLANK() ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var% Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [FYTD PY Var Sales Order Amount], [FYTD PY Sales Order Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "SO Internal Open Quantity",
            "description": "If processing status is not complete, this value is ordered minus allocated minus shipped quantities; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Internal Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Customer Open Quantity",
            "description": "If billing status is not complete, this value is ordered minus shipped quantities; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              "  ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Customer Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Internal Open Amount",
            "description": "If processing status is not complete, this value is ordered minus allocated minus shipped amount;Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Internal Open Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Internal Open Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Internal Open Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Internal Open Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Customer Open Amount",
            "description": "If billing status is not complete, this value is ordered minus shipped amount; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Customer Open Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Customer Open Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Customer Open Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Customer Open Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Ordered Quantity",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": "SUM( 'Sales Order Documents'[Order Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Allocated Quantity",
            "description": "Total quantity in delivery notes issued without an actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "VAR alloc = ",
              "    CALCULATE(",
              "        SUM( 'Sales Order Documents'[Allocated Quantity] ),",
              "        USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              "    )",
              "RETURN",
              "    IF( alloc, alloc, BLANK() )"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Shipped Quantity",
            "description": "Total quantity in delivery notes issued with actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Shipped Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "In Stock Measure",
            "description": "Applies to open orders only; Indicates if an item is available in stock (FIFO by first scheduled ship date); Note that this calculation is report-side which means the material is not actually allocated to the order in SAP",
            "expression": " PRODUCT( 'Sales Order Documents'[In Stock] )",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Gross Margin% Budget",
            "description": "Budget numbers submitted by Sales to IT",
            "expression": [
              "",
              "IF(",
              "    ISFILTERED( 'Customer Master' ),",
              "    CALCULATE(",
              "        CALCULATE(",
              "            AVERAGE( Target_Sales[GrossMarginMTD] ),",
              "            FILTER( Target_Sales, Target_Sales[GrossMarginMTD] <> 0 ),",
              "            TREATAS(",
              "                VALUES( 'Customer Master'[Sales Territory] ),",
              "                Target_Sales[SalesTerritoryKey]",
              "            ),",
              "            TREATAS(",
              "                VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "                Target_Sales[CalendarTimeKey]",
              "            )",
              "        ),",
              "        DATESMTD( 'Calendar'[Date] )",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin% Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "IF(",
              "    ISFILTERED( 'Customer Master' ),",
              "    CALCULATE(",
              "        CALCULATE(",
              "            AVERAGE( Target_Sales[GrossMarginYTD] ),",
              "            FILTER( Target_Sales, Target_Sales[GrossMarginYTD] <> 0 ),",
              "            TREATAS(",
              "                VALUES( 'Customer Master'[Sales Territory] ),",
              "                Target_Sales[SalesTerritoryKey]",
              "            ),",
              "            TREATAS(",
              "                VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "                Target_Sales[CalendarTimeKey]",
              "            )",
              "        ),",
              "        DATESMTD( 'Calendar'[Date] )",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [MTD Gross Sales] + [Backorder Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [MTD Gross Margin] + [Backorder Margin]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [MTD Gross Sales & Backorder Margin], [MTD Gross Sales & Backorder] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              " ",
              "VAR WeightVal = ",
              "    DIVIDE( ",
              "        [MTD PY Gross Sales], ",
              "        CALCULATE( [MTD PY Gross Sales], ALL('Material Master') ) ",
              "    )",
              "",
              "RETURN",
              "    SWITCH(TRUE(),",
              "        ISFILTERED( 'Material Master' ), CALCULATE( [Gross Sales Budget], DATESMTD( 'Calendar'[Date] ) ) * WeightVal,",
              "        ISFILTERED( 'Customer Master' ), CALCULATE( [Gross Sales Budget], DATESMTD( 'Calendar'[Date] ) ),",
              "        BLANK()",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              " ",
              "VAR WeightVal = ",
              "    DIVIDE( ",
              "        [FYTD PY Gross Sales], ",
              "        CALCULATE( [FYTD PY Gross Sales], ALL('Material Master') ) ",
              "    )",
              "",
              "RETURN",
              "    SWITCH(TRUE(),",
              "        ISFILTERED( 'Material Master' ), CALCULATE( [Gross Sales Budget], DATESYTD( 'Calendar'[Date], \"09/30\" ) ) * WeightVal,",
              "        ISFILTERED( 'Customer Master' ), CALCULATE( [Gross Sales Budget], DATESYTD( 'Calendar'[Date], \"09/30\" ) ),",
              "        BLANK()",
              "    )"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales & Backorder",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [FYTD Gross Sales] + [Backorder Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales & Backorder Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [FYTD Gross Margin] + [Backorder Margin]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales & Backorder Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [FYTD Gross Sales & Backorder Margin], [FYTD Gross Sales & Backorder] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PO Ordered Quantity",
            "expression": " SUM( 'Purchase Orders'[Ordered Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Open Quantity",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Orders - Deliveries'[Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Purchase Orders - Deliveries'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Ordered Amount",
            "expression": " SUM( 'Purchase Orders'[Ordered Amount] )",
            "formatString": "#,0",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Open Amount",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Orders - Deliveries'[Open Amount] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Purchase Orders - Deliveries'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Delivered Quantity",
            "expression": " SUM( 'Stock Transfer Orders'[Delivered Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO In Transit Quantity",
            "expression": " SUM( 'Stock Transfer Orders'[In Transit Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "GRIR Amount (Document)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM('Goods and Invoice Receipts'[Amount (Document)])",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Amount (Local)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM('Goods and Invoice Receipts'[Amount (Local)])",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Amount (Local2)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM( 'Goods and Invoice Receipts'[Amount (Local2)] )",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Quantity",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM( 'Goods and Invoice Receipts'[Quantity] )",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Open Amount",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", [GRIR Amount (Local2)],",
              "            \"Local\", [GRIR Amount (Local)],",
              "            [GRIR Amount (Local2)]",
              "        ),",
              "        [GRIR Amount (Local2)]",
              "    ),",
              "    FILTER(",
              "        'Goods and Invoice Receipts',",
              "        'Goods and Invoice Receipts'[Clearing Date] > MAX( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Open Quantity",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [GRIR Quantity],",
              "    FILTER(",
              "        'Goods and Invoice Receipts',",
              "        'Goods and Invoice Receipts'[Clearing Date] > MAX( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "PO Invoice Receipt Amount",
            "description": "Sum of invoice receipt amount in purchase order history. See 'Time Intelligence' folder for the FYTD versions; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " SUM( 'Purchase Order Invoices'[Amount] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Invoice Receipt Quantity",
            "description": "Sum of invoice receipt quantity in purchase order history (in purchase order unit). See 'Time Intelligence' folder for the FYTD versions; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " SUM( 'Purchase Order Invoices'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "FYTD PO Invoice Receipt Amount",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [PO Invoice Receipt Amount], DATESYTD( 'Calendar'[Date] , \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Quantity",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [PO Invoice Receipt Quantity], DATESYTD( 'Calendar'[Date] , \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Amount",
            "description": "Last positive invoice receipt amount from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number.",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Amount], FILTER( 'Purchase Order Invoices', 'Purchase Order Invoices'[PostingRank] = 1 ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Quantity",
            "description": "Last positive invoice receipt quantity from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Quantity], FILTER( 'Purchase Order Invoices', 'Purchase Order Invoices'[PostingRank] = 1 ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Amount",
            "description": "Last positive invoice receipt amount from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD Last PO Invoice Receipt Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Quantity",
            "description": "Last positive invoice receipt quantity from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD Last PO Invoice Receipt Quantity], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Unit Price",
            "description": "FYTD total invoice receipt amount divided quantity; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Unit Price",
            "description": "Amount divided quantity of the last invoice receipt in purchase order history on current fiscal year; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD Last PO Invoice Receipt Amount], [FYTD Last PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Amount in PY Price",
            "description": "Current year's invoice receipt amount using prior fiscal year's last unit price. If the material is not sold in the previous fiscal year, use current fiscal year's amount; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Order Invoices'[Amount at Last PY Price] ),",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Difference",
            "description": "Difference between current fiscal year's actual invoice receipt amount and the amount using prior fiscal year's last unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Order Invoices'[Price Difference] ),",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Unit Price",
            "description": "Amount divided quantity of the last invoice receipt in purchase order history on previous fiscal year; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD PY Last PO Invoice Receipt Amount], [FYTD PY Last PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Index%",
            "description": "Current fiscal year's invoice receipt amount as a percentage of the same amount using prior fiscal year's unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "IF(",
              "    [FYTD PO Invoice Receipt Amount in PY Price] = 0,",
              "    BLANK(),",
              "    DIVIDE([FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Amount in PY Price]) - 1",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Index",
            "description": "Current fiscal year's invoice receipt amount divided by the same amount using prior fiscal year's unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " ROUND(DIVIDE( [FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Amount in PY Price] ), 4)",
            "formatString": "0.0000",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY PO Invoice Receipt Amount",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY PO Invoice Receipt Quantity",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Quantity], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Backorder Amount (Past Due)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship before the current month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] < [Beginning of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Amount (Current Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship on current month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] >= [Beginning of Month]",
              "            && 'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "End of Next Month",
            "expression": " EOMONTH( [Report Date], 1 )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Backorder Amount (Next Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship starting next month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] > [End of Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] > [End of Month]",
              "            && 'Sales Order Documents'[First Delivery Date] <= [End of Next Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Amount (Beyond Next Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship after next month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] > [End of Next Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] > [End of Next Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Earned Labor",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Absorption[Amount] ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Sub Category] IN {\"Labor\", \"Setup\"}",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Earned Overhead",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Absorption[Amount] ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": " [Earned Labor] + [Earned Overhead]",
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Sales Order Lines Automated",
            "description": "Number of sales order line items entered by BATCHUSER (sales order automation); Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " COUNTROWS( FILTER( 'Sales Order Documents', 'Sales Order Documents'[Entered By] = \"BATCHUSER\" ) )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Line Count",
            "description": "Number of sales order line items; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " COUNTROWS( 'Sales Order Documents' )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Lines Automated Entry%",
            "description": "Number of sales order line items entered by BATCHUSER divided by sales order line count entered by Customer Service and BATCHUSER; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "DIVIDE( ",
              "    [Sales Order Lines Automated],",
              "    [Sales Order Line Count (Automated + Manual)]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Lines Manual",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], FILTER( 'SAP Users', 'SAP Users'[Department] = \"CUSTOMER SERVICE\") )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "FYTD Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [FYTD Sales Order Line Count], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Sales Order Lines Automated Entry%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated Entry%], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Lines Automated Entry%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated Entry%], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Sales Order Lines Automated (No Changes)",
            "description": "Number of sales order line items entered by BATCHUSER (sales order automation) without manual changes from Customer Service; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated], 'Sales Order Documents'[Has Changes (CS)] = 0 )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [Sales Order Lines Automated (No Changes)], [Sales Order Lines Automated] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "FYTD Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Automation Efficiency%], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Automation Efficiency%], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Sales Order Lines Manual Entry%",
            "description": "Number of sales order line items entered by Customer Service divided by sales order line count entered by Customer Service and BATCHUSER; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [Sales Order Lines Manual], [Sales Order Line Count (Automated + Manual)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Line Count (Automated + Manual)",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " [Sales Order Lines Manual] + [Sales Order Lines Automated]",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [Absorption], DATESMTD( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [MTD Absorption], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD PO Backorder Amount",
            "description": "Sum of open UB, NB, and ZNB purchase orders with GR requirement scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": [
              " ",
              "CALCULATE( ",
              "    SUM( 'Backorder Snapshots'[Incoming Amount] ), ",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] = MAX( 'Calendar'[Date] ) - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD Var PO Open Amount",
            "description": "Variance of PO Open Amount to prior day's open amount (PD PO Backorder Amount) which is the sum of open UB, NB, and ZNB purchase orders with GR requirement scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": " [PO Open Amount] - [PD PO Backorder Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "SO Customer Open Margin",
            "description": "If billing status is not complete, this value is margin amount of non-shipped; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Customer Open Margin Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Customer Open Margin Amount (Local)] ),",
              "            SUM( 'Sales Order Documents'[Customer Open Margin Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Customer Open Margin Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "PD SO Customer Open Amount",
            "description": "Sum of open TA and ZCON sales orders with with active/pre-launch product status, no credit block, has product tier code, and scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date]). Excludes BURLINGTON GRAPHICS customer.",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM('Backorder Snapshots'[Outgoing Amount]),",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] = [Report Date] - 1",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD Var SO Customer Open Amount",
            "description": "Variance of SO Customer Open Amount to prior day's open amount (PD SO Customer Open Amount) which is the sum of open TA and ZCON sales orders with with active/pre-launch product status, no credit block, has product tier code, and scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": " [SO Customer Open Amount] - [PD SO Customer Open Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "GR Linear Footage",
            "description": "Total footage of postings with movement types 101, 102, 531, and 532.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Goods Issues and Receipts'[Linear Feet] ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"101\", \"531\", \"102\", \"532\"}",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GR Square Footage",
            "description": "Total square footage of postings with movement types 101, 102, 531, and 532.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Goods Issues and Receipts'[Square Feet] ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"101\", \"531\", \"102\", \"532\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"555\", \"700\" }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GI Linear Footage",
            "description": "Total footage of postings with movement types 261, 262, 551, and 552.",
            "expression": [
              "",
              "CALCULATE(",
              "    ABS( SUM( 'Goods Issues and Receipts'[Linear Feet] ) ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"261\", \"551\", \"262\", \"552\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"600\", \"700\", \"733\", \"734\", \"735\", \"736\", \"88\", \"182\", \"782\"}",
              "            && 'Goods Issues and Receipts'[Reason Code] <> \"0000\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GI Scrap Rate",
            "description": "GI Footage over GR Footage",
            "expression": " DIVIDE( [GI Linear Footage], [GR Linear Footage] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Linear Footage",
            "expression": " SUM ('Goods Issues and Receipts'[Linear Feet])",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Square Footage",
            "expression": " SUM ('Goods Issues and Receipts'[Square Feet])",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Quantity",
            "expression": " SUM( 'Goods Issues and Receipts'[Quantity])",
            "formatString": "#,0.00",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Amount",
            "expression": " SUM( 'Goods Issues and Receipts'[Amount] )",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "SO Allocated Amount",
            "description": "Total value of items in delivery notes issued without an actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Allocated Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Allocated Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Allocated Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Allocated Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Shipped Amount",
            "description": "Total value of items in delivery notes issued with actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Shipped Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Shipped Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Shipped Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Shipped Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "CONV Production Hours",
            "description": "The number of hours across all converting employees when they are producing material",
            "expression": " SUM( 'Converting Man Hours'[Production Hours] )",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Available Hours",
            "description": "The total number of hours converting is scheduled to work within a shift (excluding breaks and lunch)",
            "expression": " SUM( 'Converting Man Hours'[Available Hours] )",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour",
            "description": "Total number of square footage over total production hours in Converting",
            "expression": " DIVIDE( [GR Square Footage], [CONV Production Hours] )",
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour (Target)",
            "description": "These values are provided by Converting at the beginning of the fiscal year. If none provided, the default value used is 5,000.",
            "expression": [
              " ",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"Sqftmh\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK( TargetVal ),",
              "        5000,",
              "        TargetVal",
              "    )",
              " "
            ],
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour (Target Variance)",
            "expression": " [CONV Square Feet per Man Hour] - [CONV Square Feet per Man Hour (Target)]",
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Uptime Hours",
            "expression": " SUM( 'Converting Uptime'[Uptime Seconds] ) / 60 / 60",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Availability",
            "description": "Converting uptime hours divided by available hours",
            "expression": [
              " ",
              "AVERAGEX(",
              "    VALUES( 'Converting Uptime'[Machine Name] ),",
              "    CALCULATE(",
              "        AVERAGEX(",
              "            VALUES( 'Calendar'[Date] ),",
              "            DIVIDE( [CONV Uptime Hours], [CONV Available Hours] )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Converting"
          },
          {
            "name": "PD GR Linear Footage",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GR Linear Footage],PREVIOUSDAY('Calendar'[Date]) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD GI Linear Footage",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GI Linear Footage], PREVIOUSDAY( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD GI Scrap Rate",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GI Scrap Rate], PREVIOUSDAY( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Current S-Block Quantity",
            "expression": " SUM( 'Blocked Inventory'[SBlock Quantity] )",
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Current Q-Block Quantity",
            "expression": " SUM( 'Blocked Inventory'[QBlock Quantity] )",
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Current Expired Quantity",
            "description": "Sum of 'Expired Inventory'[Stock Amount] where the [Expiration Date] is less than or equal to [Report Date]. Can be toggled between quantity and amount values (default = quantity)",
            "expression": [
              "",
              "VAR Qty =",
              "    CALCULATE(",
              "        SUM( 'Expired Inventory'[Stock Quantity] ),",
              "        FILTER(",
              "            ALL( 'Expired Inventory'[Expiration Date] ),",
              "            'Expired Inventory'[Expiration Date] <= [Report Date]",
              "        )",
              "    )",
              "",
              "VAR Amt =",
              "    CALCULATE(",
              "        SUM( 'Expired Inventory'[Stock Amount] ),",
              "        FILTER(",
              "            ALL( 'Expired Inventory'[Expiration Date] ),",
              "            'Expired Inventory'[Expiration Date] <= [Report Date]",
              "        )",
              "    )",
              "",
              "RETURN",
              "    IF(",
              "        HASONEVALUE( '_Value to Use'[Value] ),",
              "        SWITCH(",
              "            VALUES( '_Value to Use'[Value] ),",
              "            \"Quantity\", Qty,",
              "            \"Amount\", Amt,",
              "            Qty",
              "        ),",
              "        Qty",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Upstream Actual Production Footage",
            "description": "Sum of 'Upstream Logs - Simplified'[Footage] of production records excluding FEs",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Upstream Actual Footage],",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] = \"Production\"",
              "            && LEFT('Upstream Logs - Simplified'[Causes], 4) = \"Roll\"",
              "            && NOT(CONTAINSSTRING('Upstream Logs - Simplified'[Causes], \"FE\"))",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Ideal Production Footage",
            "description": "Sum of 'Upstream Logs - Simplified'[Footage] of production records excluding FEs",
            "expression": [
              " ",
              "CALCULATE(",
              "    [Upstream Ideal Footage],",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] = \"Production\"",
              "            && LEFT('Upstream Logs - Simplified'[Causes], 4) = \"Roll\"",
              "            && NOT(CONTAINSSTRING('Upstream Logs - Simplified'[Causes], \"FE\"))",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Uptime Minutes",
            "description": "Sum of duration between 'Start Time' and 'Stop Time' in minutes of production records excluding FEs",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Upstream Logs - Simplified'[Duration Minutes] ),",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] = \"Production\"",
              "            && NOT(CONTAINSSTRING('Upstream Logs - Simplified'[Causes], \"FE\"))",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Runtime Minutes",
            "description": "Sum of duration between 'Start Time' and 'Stop Time' in minutes of all records except end of production, EOS, and FEs",
            "expression": [
              "",
              "VAR CAST = ",
              "    CALCULATE(",
              "        SUM( 'Upstream Logs - Simplified'[Duration Minutes] ),",
              "        FILTER(",
              "            'Upstream Logs - Simplified',",
              "            'Upstream Logs - Simplified'[Category] <> \"End of Production\"",
              "                && 'Upstream Logs - Simplified'[Further Detail] <> \"EOS\"",
              "                && NOT(CONTAINSSTRING('Upstream Logs - Simplified'[Causes], \"FE\"))",
              "        )",
              "    )",
              "",
              "VAR COAT = ",
              "    CALCULATE(",
              "        SUM( 'Upstream Logs - Simplified'[Duration Minutes] ),",
              "        FILTER(",
              "            'Upstream Logs - Simplified',",
              "            'Upstream Logs - Simplified'[Category] <> \"End of Production\"",
              "                && 'Upstream Logs - Simplified'[Further Detail] <> \"EOS\"",
              "                && 'Upstream Logs - Simplified'[Non Uptime Reason] <> \"PLANNED DT\"",
              "                && NOT(CONTAINSSTRING('Upstream Logs - Simplified'[Causes], \"FE\"))",
              "        )",
              "    )",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED(_Machines[Department]), CAST,",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), COAT,",
              "    CAST",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Actual Footage",
            "description": "Sum of 'Upstreal Logs - Simplified'[Footage]",
            "expression": " SUM('Upstream Logs - Simplified'[Footage])",
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Ideal Footage",
            "description": "Sum of 'Upstreal Logs - Simplified'[Ideal Footage]. Ideal footage is derived from the specification linespeed and duration between 'Start Time' and 'Stop Time' in minutes",
            "expression": "SUM('Upstream Logs - Simplified'[Ideal Footage])",
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Downtime Hours",
            "description": "Sum of duration between 'Start Time' and 'Stop Time' in minutes of unplanned clean up and unplanned downtime records",
            "expression": [
              "",
              "CALCULATE(",
              "    DIVIDE( SUM( 'Upstream Logs - Simplified'[Duration Minutes] ), 60 ) + 0,",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] IN { \"Clean Up\", \"Downtime\" }",
              "            && LEFT('Upstream Logs - Simplified'[Causes], 9) = \"Unplanned\"",
              "    )",
              ")"
            ],
            "formatString": "#,###0.00 \"hr\";-#,###0.00 #,###0.00 \"hr\";0 \"hr\"",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "CAST Clean Up Count",
            "expression": "COUNTROWS(FILTER('Upstream Logs - Simplified', 'Upstream Logs - Simplified'[Category] = \"Clean Up\" && 'Upstream Logs - Simplified'[Causes] IN { \"Planned\", \"Unplanned\", \"Unplanned - Casting\" })) + 0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "COAT Clean Up Count",
            "expression": "COUNTROWS(FILTER('Upstream Logs - Raw', 'Upstream Logs - Raw'[Category] = \"Clean Up\" && 'Upstream Logs - Raw'[Causes] IN { \"Planned\", \"Unplanned\" })) + 0",
            "formatString": "#,0",
            "isHidden": true
          },
          {
            "name": "Upstream Planned CU Count",
            "description": "Number of planned clean up records. For casting, the clean ups from 'Upstream Logs - Simplified' table is counted where consecutively similar clean ups are combined into one clean up. For coating, it is the raw count of clean ups in 'Upstream Logs - Raw'.",
            "expression": [
              "",
              "VAR CAST = CALCULATE( [CAST Clean Up Count], 'Upstream Logs - Simplified'[Causes] = \"Planned\" )",
              "VAR COAT = CALCULATE( [COAT Clean Up Count], 'Upstream Logs - Raw'[Causes] = \"Planned\" )",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED(_Machines[Department]), CAST,",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), COAT,",
              "    CAST + COAT",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Unplanned CU Count",
            "description": "Number of unplanned clean up records. For casting, the clean ups from 'Upstream Logs - Simplified' table is counted where consecutively similar clean ups are combined into one clean up. For coating, it is the raw count of clean ups in 'Upstream Logs - Raw'",
            "expression": [
              "",
              "VAR CAST = CALCULATE( [CAST Clean Up Count], 'Upstream Logs - Simplified'[Causes] = \"Unplanned - Casting\" )",
              "VAR COAT = CALCULATE( [COAT Clean Up Count], 'Upstream Logs - Raw'[Causes] = \"Unplanned\" )",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED(_Machines[Department]), CAST,",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), COAT,",
              "    CAST + COAT",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Performance",
            "description": "Upstream actual production footage divided by ideal production footage",
            "expression": [
              " ",
              "CALCULATE(",
              "    DIVIDE( [Upstream Actual Production Footage], [Upstream Ideal Production Footage] ),",
              "    ALL(",
              "        'Upstream Logs - Simplified'[Category],",
              "        'Upstream Logs - Simplified'[Causes],",
              "        'Upstream Logs - Simplified'[Further Detail],",
              "        'Upstream Logs - Simplified'[Comments],",
              "        'Upstream Logs - Simplified'[Non Uptime Reason],",
              "        'Upstream Logs - Simplified'[Specification Number],",
              "        'Upstream Logs - Simplified'[Efficiency Hitter]",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Availability",
            "description": "Upstream uptime duration minutes divided by runtime duration minutes",
            "expression": [
              " ",
              "CALCULATE(",
              "    DIVIDE( [Upstream Uptime Minutes], [Upstream Runtime Minutes] ),",
              "    ALL(",
              "        'Upstream Logs - Simplified'[Category],",
              "        'Upstream Logs - Simplified'[Causes],",
              "        'Upstream Logs - Simplified'[Further Detail],",
              "        'Upstream Logs - Simplified'[Comments],",
              "        'Upstream Logs - Simplified'[Non Uptime Reason],",
              "        'Upstream Logs - Simplified'[Specification Number],",
              "        'Upstream Logs - Simplified'[Efficiency Hitter]",
              "    )",
              ")",
              ""
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Overall Equipment Efficiency",
            "description": "Product of upstream availability, performance, and quality",
            "expression": "[Upstream Availability] * [Upstream Performance] * [Upstream Quality]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream First Pass Reliability",
            "description": "Number of planned clean ups divided by the total planned and unplanned clean ups",
            "expression": " DIVIDE( [Upstream Planned CU Count], [Upstream Planned CU Count] + [Upstream Unplanned CU Count] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Changeover Time",
            "description": "Average duration of clean up records in 'Upstream Logs - Simplified'",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Upstream Logs - Simplified'[Duration Minutes] ),",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] = \"Clean Up\"",
              "    )",
              ")"
            ],
            "formatString": "#,### \"min\"",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "CAST Overall Equipment Efficiency (Target)",
            "expression": [
              "",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"OEE_CAST\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )    ",
              "RETURN",
              "    IF(",
              "        ISBLANK(TargetVal),",
              "        0.85,",
              "        TargetVal",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "COAT Overall Equipment Efficiency (Target)",
            "expression": [
              "",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"OEE_COAT\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )    ",
              "RETURN",
              "    IF(",
              "        ISBLANK(TargetVal),",
              "        0.85,",
              "        TargetVal",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Overall Equipment Efficiency (Target)",
            "description": "Monthly target data supplied by Engineering once every fiscal year",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED('_Machines'[Department]), [CAST Overall Equipment Efficiency (Target)],",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), [COAT Overall Equipment Efficiency (Target)],",
              "    ([CAST Overall Equipment Efficiency (Target)] + [COAT Overall Equipment Efficiency (Target)]) / 2",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "CAST First Pass Reliability (Target)",
            "expression": [
              "",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"FPass_CAST\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )    ",
              "RETURN",
              "    IF(",
              "        ISBLANK(TargetVal),",
              "        0.95,",
              "        TargetVal",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "COAT First Pass Reliability (Target)",
            "expression": [
              "",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"FPass_COAT\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )    ",
              "RETURN",
              "    IF(",
              "        ISBLANK(TargetVal),",
              "        0.95,",
              "        TargetVal",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream First Pass Reliability (Target)",
            "description": "Monthly target data supplied by Engineering once every fiscal year",
            "expression": [
              "",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED('_Machines'[Department]), [CAST First Pass Reliability (Target)],",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), [COAT First Pass Reliability (Target)],",
              "    ([CAST First Pass Reliability (Target)] + [COAT First Pass Reliability (Target)]) / 2",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Changeover Time (Target)",
            "description": "Average duration of clean up records YTD last fiscal year in 'Upstream Logs - Simplified'",
            "expression": [
              "",
              "CALCULATE(",
              "    [Upstream Changeover Time],",
              "    SAMEPERIODLASTYEAR(DATESYTD( 'Calendar'[Date], \"09/30\"))",
              ")"
            ],
            "formatString": "#,### \"min\"",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Performance Impact",
            "description": "Impact on the overall performance of the department. Best used if analyzed by Further Detail, Comments, Non Uptime Reason, or Efficiency Hitter in 'Upstream Logs - Simplified'.",
            "expression": [
              "",
              "DIVIDE(",
              "    [Upstream Ideal Production Footage] - [Upstream Actual Production Footage],",
              "    CALCULATE(",
              "        [Upstream Ideal Production Footage],",
              "        ALL(",
              "            'Upstream Logs - Simplified'[Category],",
              "            'Upstream Logs - Simplified'[Causes],",
              "            'Upstream Logs - Simplified'[Further Detail],",
              "            'Upstream Logs - Simplified'[Comments],",
              "            'Upstream Logs - Simplified'[Non Uptime Reason],",
              "            'Upstream Logs - Simplified'[Specification Number],",
              "            'Upstream Logs - Simplified'[Efficiency Hitter]",
              "        ),",
              "        ALL(_Machines[Machine Name])",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Availability Impact",
            "description": "Impact on the overall availablility of the department. Best used if analyzed by Further Detail, Comments, Non Uptime Reason, or Efficiency Hitter in 'Upstream Logs - Simplified'.",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        [Upstream Runtime Minutes],",
              "        FILTER(",
              "            'Upstream Logs - Simplified',",
              "            'Upstream Logs - Simplified'[Category] <> \"Production\"",
              "        )",
              "    ),",
              "    CALCULATE(",
              "        [Upstream Runtime Minutes],",
              "        ALL(",
              "            'Upstream Logs - Simplified'[Category],",
              "            'Upstream Logs - Simplified'[Causes],",
              "            'Upstream Logs - Simplified'[Further Detail],",
              "            'Upstream Logs - Simplified'[Comments],",
              "            'Upstream Logs - Simplified'[Non Uptime Reason],",
              "            'Upstream Logs - Simplified'[Specification Number],",
              "            'Upstream Logs - Simplified'[Efficiency Hitter]",
              "        ),",
              "        ALL(_Machines[Machine Name])",
              "    )",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Quality",
            "description": "A fixed number defined by Engineering",
            "expression": [
              "",
              "VAR CAST = 0.95",
              "VAR COAT = 0.98",
              "",
              "RETURN",
              "SWITCH(TRUE(),",
              "    \"CAST\" IN ALLSELECTED(_Machines[Department]), CAST,",
              "    \"COAT\" IN ALLSELECTED(_Machines[Department]), COAT,",
              "    0.95",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Overall Equipment Efficiency Impact",
            "description": "Impact on the overall equipment efficiency of the department. Best used if analyzed by Further Detail, Comments, Non Uptime Reason, or Efficiency Hitter in 'Upstream Logs - Simplified'.",
            "expression": "(( [Upstream Availability] + [Upstream Availability Impact] ) * ( [Upstream Performance] + [Upstream Performance Impact] ) * [Upstream Quality] ) - [Upstream Overall Equipment Efficiency]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Days Since Last Unplanned Clean Up",
            "description": "Number of days between yesterday and the last unplanned clean up before yesterday",
            "expression": [
              "",
              "VAR Last_Date = ",
              "    SWITCH( TRUE(),",
              "        \"CAST\" IN ALLSELECTED(_Machines[Department]),",
              "        CALCULATE(",
              "            MAX( 'Upstream Logs - Simplified'[Production Date] ),",
              "            FILTER(",
              "                'Upstream Logs - Simplified',",
              "                'Upstream Logs - Simplified'[Production Date] <= [Report Date]",
              "                    && 'Upstream Logs - Simplified'[Category] = \"Clean Up\"",
              "                    && 'Upstream Logs - Simplified'[Causes] = \"Unplanned - Casting\"",
              "            )    ",
              "        ),",
              "        \"COAT\" IN ALLSELECTED(_Machines[Department]),",
              "        CALCULATE(",
              "            MAX( 'Upstream Logs - Raw'[Production Date] ),",
              "            FILTER(",
              "                'Upstream Logs - Raw',",
              "                'Upstream Logs - Raw'[Production Date] <= [Report Date]",
              "                    && 'Upstream Logs - Raw'[Category] = \"Clean Up\"",
              "                    && 'Upstream Logs - Raw'[Causes] = \"Unplanned\"",
              "            )    ",
              "        )",
              "    )",
              "",
              "RETURN",
              "DATEDIFF(Last_Date, [Yesterday], DAY)"
            ],
            "formatString": "#,###0 \"days\"",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "Upstream Changeover Scrap",
            "description": "Average footage of clean up records. In Casting, this value is the caliper scrap. In Coating, it is the combined footage of consecutive clean up and setup records.",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Upstream Logs - Simplified'[Scrap Footage] ),",
              "    FILTER(",
              "        'Upstream Logs - Simplified',",
              "        'Upstream Logs - Simplified'[Category] = \"Clean Up\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "MTD Sales Order Amount %Grand",
            "expression": [
              "",
              "DIVIDE(",
              "    [MTD Sales Order Amount],",
              "    CALCULATE(",
              "        [MTD Sales Order Amount],",
              "        ALL( 'Customer Master' ),",
              "        ALL( 'Material Master' )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Budget Var% Gross Sales",
            "expression": [
              "",
              "VAR VarVal = IF( OR( ISBLANK([MTD Gross Sales]), ISBLANK([MTD Gross Sales Budget]) ), BLANK(), [MTD Gross Sales] - [MTD Gross Sales Budget] )",
              "",
              "RETURN",
              "    DIVIDE(",
              "        VarVal,",
              "        [MTD Gross Sales Budget]",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Budget Var% Gross Sales",
            "expression": [
              "",
              "VAR VarVal = IF( OR( ISBLANK([FYTD Gross Sales]), ISBLANK([FYTD Gross Sales Budget]) ), BLANK(), [FYTD Gross Sales] - [FYTD Gross Sales Budget] )",
              "",
              "RETURN",
              "    DIVIDE(",
              "        VarVal,",
              "        [FYTD Gross Sales Budget]",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Report Date",
            "expression": " CALCULATE( Max( 'Calendar'[Date] ), FILTER(  ALLSELECTED('Calendar'), 'Calendar'[Date] <= [Yesterday] ) )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Upstream Overall Equipment Efficiency (Target Var)",
            "expression": "[Upstream Overall Equipment Efficiency] - [Upstream Overall Equipment Efficiency (Target)]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Upstream Logs"
          },
          {
            "name": "YTD Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales], DATESYTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin], DATESYTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin %], DATESYTD( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD PY Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [YTD Gross Sales], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD PY Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [YTD Gross Margin], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD PY Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [YTD Gross Margin%], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD PY Var% Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [YTD PY Var Gross Sales], [YTD PY Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "YTD PY Var Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " IF( NOT( OR(ISBLANK([YTD Gross Sales]), ISBLANK([YTD PY Gross Sales]) ) ), [YTD Gross Sales] - [YTD PY Gross Sales], BLANK() )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Current Unrestricted Stock Quantity",
            "description": "Sum of 'Current Inventory'[Unrestricted Stock Quantity']. Can be toggled between quantity and amount values (default = quantity)",
            "expression": [
              "",
              "VAR Qty = SUM('Current Inventory'[Unrestricted Stock Quantity])",
              "VAR Amt = SUM('Current Inventory'[Unrestricted Stock Amount (USD)])",
              "RETURN",
              "    IF(",
              "        HASONEVALUE( '_Value to Use'[Value] ),",
              "        SWITCH(",
              "            VALUES( '_Value to Use'[Value] ),",
              "            \"Quantity\", Qty,",
              "            \"Amount\", Amt,",
              "            Qty",
              "        ),",
              "        Qty",
              "    )",
              ""
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Current Safety Stock Quantity",
            "expression": [
              "",
              "AVERAGEX(",
              "    VALUES( 'Current Inventory'[MaterialPlantKey] ),",
              "    AVERAGE('Current Inventory'[Safety Stock Quantity])",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Current Available Quantity",
            "description": "Difference between 'Current Unrestricted Stock Quantity', 'SO Allocated Quantity', 'SO Allocated Quantity', and 'SO Internal Open Quantity'",
            "expression": " [Current Unrestricted Stock Quantity] - [SO Allocated Quantity] - [SO Internal Open Quantity]",
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Helper_12MoAgo",
            "expression": "YEAR([Date 12 Months Ago]) * 100 + MONTH([Date 12 Months Ago])",
            "isHidden": true,
            "displayFolder": ".Helpers"
          },
          {
            "name": "Helper_CurrMo",
            "expression": "YEAR([Beginning of Month]) * 100 + MONTH([Beginning of Month])",
            "isHidden": true,
            "displayFolder": ".Helpers"
          },
          {
            "name": "PO Goods Receipt Quantity",
            "expression": " SUM('Purchase Orders'[Goods Receipt Quantity])",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "Cumulative Expired Value",
            "description": "Cumulative stock amount by expiration date. Best used with 'Calendar' and its hierarchies.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Expired Inventory'[Stock Amount] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Expired Inventory'[Expiration Date] ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] <= MAX( 'Calendar'[Date] )",
              "            && 'Calendar'[Date] <> BLANK()",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor (Budget)",
            "description": "SAP Source: ZFORECAST.LABOR (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( Target_Absorption[Labor] ),",
              "    Target_Absorption[ForecastType] = \"B\",",
              "    TREATAS(",
              "        VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "        Target_Absorption[CalendarTimeKey]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Earned Overhead (Budget)",
            "description": "SAP Source: ZFORECAST.OH (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( Target_Absorption[Overhead] ),",
              "    Target_Absorption[ForecastType] = \"B\",",
              "    TREATAS(",
              "        VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "        Target_Absorption[CalendarTimeKey]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Absorption (Budget)",
            "description": "Sum of 'Earned Labor (Budget)' and 'Earned Overhead (Budget)'",
            "expression": " [Earned Labor (Budget)] + [Earned Overhead (Budget)]",
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "MTD Earned Labor (Budget)",
            "description": "SAP Source: ZFORECAST.LABOR (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    [Earned Labor (Budget)],",
              "    DATESMTD( 'Calendar'[Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Earned Overhead (Budget)",
            "description": "SAP Source: ZFORECAST.OH (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    [Earned Overhead (Budget)],",
              "    DATESMTD( 'Calendar'[Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Absorption (Budget)",
            "expression": " [MTD Earned Labor (Budget)] + [MTD Earned Overhead (Budget)]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Earned Labor (Budget)",
            "description": "SAP Source: ZFORECAST.LABOR (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    [Earned Labor (Budget)],",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Earned Overhead (Budget)",
            "description": "SAP Source: ZFORECAST.LABOR (Type = 'B')",
            "expression": [
              "",
              "CALCULATE(",
              "    [Earned Overhead (Budget)],",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Absorption (Budget)",
            "expression": " [FYTD Earned Labor (Budget)] + [FYTD Earned Overhead (Budget)]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Earned Labor",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [Earned Labor], DATESMTD( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Earned Overhead",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [Earned Overhead], DATESMTD( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Days In Month",
            "expression": " CALCULATE( COUNTROWS( 'Calendar' ), ALL( 'Calendar' ), VALUES( 'Calendar'[Year_Month_Sort_Key] ))",
            "isHidden": true,
            "displayFolder": ".Dates"
          },
          {
            "name": "Days Count",
            "expression": " CALCULATE( COUNTROWS( 'Calendar' ), FILTER( 'Calendar', 'Calendar'[Date] <= [Report Date] ) )",
            "isHidden": true
          },
          {
            "name": "Current Inventory Amount",
            "expression": [
              "",
              "SUMX(",
              "    'Current Inventory',",
              "    'Current Inventory'[Unrestricted Stock Amount (USD)]",
              "        + 'Current Inventory'[Blocked Stock Amount (USD)]",
              "        + 'Current Inventory'[Inspection Stock Amount (USD)]",
              ") +",
              "[PO In Transit Amount] +",
              "[Current Open WIP Value]"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PO In Transit Amount",
            "expression": [
              " SUM( 'Stock Transfer Orders'[In Transit Amount] )",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "Current Open WIP Value",
            "expression": " SUM( 'Open WIP'[Net Cost Amount] )",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Inventory",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Last Inventory Amount",
            "expression": [
              "",
              "VAR RefDate =",
              "    CALCULATE(",
              "        MAX('Calendar'[Date]),",
              "        FILTER( 'Calendar', 'Calendar'[Date] <= [Report Date])",
              "    )",
              "",
              "RETURN",
              "    CALCULATE(",
              "        SUM( 'Current Inventory Snapshots'[Amount] ),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] = RefDate",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PD Inventory Amount",
            "expression": [
              "",
              "VAR RefDate =",
              "    CALCULATE(",
              "        MAX('Calendar'[Date]),",
              "        FILTER( 'Calendar', 'Calendar'[Date] < [Report Date])",
              "    )",
              "",
              "RETURN",
              "    CALCULATE(",
              "        SUM( 'Current Inventory Snapshots'[Amount] ),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] = RefDate",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PD Var Inventory Amount",
            "expression": " [Last Inventory Amount] - [PD Inventory Amount]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "S/O Count",
            "expression": "DISTINCTCOUNT( 'Shop Orders'[Process Order Number] )",
            "formatString": "#,0",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O Ordered Quantity",
            "expression": " SUM( 'Shop Orders'[Order Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O Delivered Quantity",
            "expression": " SUM( 'Shop Orders'[Delivered Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O Scheduled Count",
            "expression": [
              "",
              "CALCULATE(",
              "    [S/O Count],",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Shop Orders'[Basic Start Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O Completed Count",
            "expression": [
              "",
              "CALCULATE(",
              "    [S/O Count],",
              "    FILTER(",
              "        'Shop Orders',",
              "        'Shop Orders'[Close Indicator] = \"X\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O With Hold Tag Count",
            "expression": [
              "",
              "CALCULATE(",
              "    [S/O Count],",
              "    FILTER(",
              "        'Shop Orders',",
              "        'Shop Orders'[Notification Number] <> BLANK()",
              "    )",
              ")"
            ],
            "formatString": "0",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "S/O With Hold Tag %",
            "expression": "DIVIDE( [S/O With Hold Tag Count], [S/O Count] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "Min Date",
            "expression": "MIN( 'Calendar'[Date] )",
            "formatString": "MM/dd/yyyy",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Max Date",
            "expression": "MAX( 'Calendar'[Date] )",
            "formatString": "MM/dd/yyyy",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "FYTD S/O Completed Count",
            "expression": [
              "",
              "CALCULATE(",
              "    [S/O Completed Count],",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY S/O Completed Count",
            "expression": "CALCULATE( [FYTD S/O Completed Count], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD S/O Scheduled Count",
            "expression": "CALCULATE( [S/O Scheduled Count], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "S/O Scheduled Quantity (Upstream)",
            "description": "Sum of 'Upstream Schedule'[Target Quantity]; This value is the total target quantity in the daily schedule files created by Planning",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Upstream Schedule'[Target Quantity] ),",
              "    'Upstream Schedule'[Ranking Desc] = 1",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Shop Orders"
          },
          {
            "name": "MTD S/O Remake Reason Hour",
            "expression": [
              "",
              "CALCULATE(",
              "    CALCULATE(",
              "        SUM( 'Upstream Schedule'[Processing Hour] ),",
              "        DATESMTD( 'Calendar'[Date] ),",
              "        'Upstream Schedule'[Ranking Desc] = 1",
              "    ),",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] <= [Report Date]",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Month End S/O Remake Reason Hour",
            "expression": [
              "",
              "CALCULATE(",
              "    CALCULATE(",
              "        SUM( 'Upstream Schedule'[Processing Hour] ),",
              "        DATESMTD( 'Calendar'[Date] ),",
              "        'Upstream Schedule'[Ranking Desc] = 1",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar' ),",
              "        'Calendar'[Date] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,0.0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Report Production Date",
            "expression": "[Report Date] + TIME(6, 0, 0)",
            "formatString": "MM/dd/yyyy HH:mm",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "MStat Last Process Order Number",
            "description": "Last process order ran in the machine. This measure is designed to be analyzed by machine.",
            "expression": [
              "",
              "VAR LastActDate = ",
              "    CALCULATE(",
              "        MAX('Machine Status'[Actual Start Time]),",
              "        FILTER(",
              "            'Machine Status',",
              "            'Machine Status'[Plan Start Time] <> BLANK()",
              "                && 'Machine Status'[Actual Start Time] <> BLANK()",
              "                && 'Machine Status'[Actual Start Time] >= [Report Production Date]",
              "        )",
              "    )",
              "RETURN",
              "    LOOKUPVALUE('Machine Status'[Process Order Number],'Machine Status'[Actual Start Time], LastActDate, BLANK() )"
            ],
            "formatString": "\"0\"",
            "displayFolder": "Machine Status"
          },
          {
            "name": "MStat Last Actual Start Time",
            "description": "Start time of the last process order ran in the machine. This measure is designed when analyzing by machine.",
            "expression": "LOOKUPVALUE('Machine Status'[Actual Start Time],'Machine Status'[Process Order Number], [MStat Last Process Order Number], BLANK() )",
            "formatString": "MM/dd/yyyy HH:mm",
            "displayFolder": "Machine Status",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "MStat Last Plan Start Time",
            "description": "Scheduled start time of last process order ran in the machine. This measure is designed when analyzing by machine.",
            "expression": "LOOKUPVALUE('Machine Status'[Plan Start Time],'Machine Status'[Process Order Number], [MStat Last Process Order Number], BLANK() )",
            "formatString": "MM/dd/yyyy HH:mm",
            "displayFolder": "Machine Status",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "MStat Net Hours Loss/Gain",
            "description": "Difference between [Last Actual Start Time] and [Last Plan Start Time] measures in hours.",
            "expression": [
              "",
              "CALCULATE(",
              "    DATEDIFF( [MStat Last Actual Start Time], [MStat Last Plan Start Time], MINUTE) / 60,",
              "    FILTER(",
              "        'Machine Status',",
              "        'Machine Status'[Plan Start Time] <> BLANK()",
              "            && 'Machine Status'[Actual Stop Time] >= [Report Production Date]",
              "            && 'Machine Status'[Actual Start Time] <= [Now Date]",
              "    )",
              ")"
            ],
            "formatString": "#,##0.0 \"hr\"",
            "displayFolder": "Machine Status"
          },
          {
            "name": "MStat Skipped S/O Duration Hour",
            "description": "Total duration of process orders scheduled between current production date and now. Skipped process orders have data in schedule files but none in machine data.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('Machine Status'[Plan Duration Hour] ),",
              "    FILTER(",
              "        'Machine Status',",
              "        'Machine Status'[Actual Start Time] = BLANK()",
              "            && 'Machine Status'[Plan Stop Time] >= [Report Production Date]",
              "            && 'Machine Status'[Plan Stop Time] <= [Now Date]",
              "    )",
              ")"
            ],
            "formatString": "#,##0.0 \"hr\"",
            "displayFolder": "Machine Status"
          },
          {
            "name": "MStat Effective Net Hours Loss/Gain",
            "description": "Difference between [Net Hours Loss/Gain] and [Skipped S/O Duration Hours] measures.",
            "expression": "[MStat Net Hours Loss/Gain] - [MStat Skipped S/O Duration Hour]",
            "formatString": "#,##0.0 \"hr\"",
            "displayFolder": "Machine Status"
          },
          {
            "name": "MStat Net Footage Variance",
            "description": "Variance between the actual and scheduled footage between start of current production date and now.",
            "expression": [
              "",
              "VAR Actual = ",
              "    CALCULATE(",
              "        SUM( 'Machine Status'[Actual Footage] ),",
              "        FILTER(",
              "            'Machine Status',",
              "            'Machine Status'[Actual Stop Time] >= [Report Production Date]",
              "                && 'Machine Status'[Actual Stop Time] <= [Now Date]",
              "                && 'Machine Status'[Plan Start Time] <> BLANK()",
              "        )",
              "    )",
              "VAR Plan = ",
              "    CALCULATE(",
              "        SUM( 'Machine Status'[Plan Footage] ),",
              "        FILTER(",
              "            'Machine Status',",
              "            'Machine Status'[Actual Stop Time] >= [Report Production Date]",
              "                && 'Machine Status'[Actual Stop Time] <= [Now Date]",
              "                && 'Machine Status'[Plan Start Time] <> BLANK()",
              "        )",
              "    )",
              "RETURN",
              "    Actual - Plan",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Machine Status"
          },
          {
            "name": "MStat Data Integrity",
            "description": "Percentage of which the production log has data (has start and stop datetimes) within a given timeframe. The closer to 100% the better but it is expected the number to be not exactly 100%. Anything above 100% indicates the log has overlapping records which means there is an error in the data logging. When the value is low, see the last datetime stamp recorded then ask operators for more details.",
            "expression": [
              "",
              "VAR Required = DATEDIFF([Prior Production Date], [Now Date], SECOND) / 60",
              "VAR Actual = ",
              "    CALCULATE(",
              "        SUM( 'Upstream Logs - Simplified'[Duration Minutes] ),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] >= [Report Date] - 1",
              "        ),",
              "        FILTER(",
              "            'Upstream Logs - Simplified',",
              "            'Upstream Logs - Simplified'[Start Time] <= [Now Date]",
              "        )",
              "    )",
              "",
              "RETURN",
              "    DIVIDE( Actual, Required )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Machine Status"
          },
          {
            "name": "Prior Production Date",
            "expression": " ([Report Date] - 1) + TIME(6, 0, 0)",
            "formatString": "MM/dd/yyyy HH:mm",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Now Date",
            "expression": "NOW() + TIME(0,0,0)",
            "formatString": "MM/dd/yyyy HH:mm",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Last Backorder Snapshot Amount",
            "expression": [
              "",
              "VAR RefDate =",
              "    CALCULATE(",
              "        MAX('Calendar'[Date]),",
              "        FILTER( 'Calendar', 'Calendar'[Date] <= [Report Date])",
              "    )",
              "",
              "RETURN",
              "    CALCULATE(",
              "        SUM('Backorder Snapshots'[Outgoing Amount]),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] = RefDate",
              "        )",
              "    )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Last Shortage Amount% Snapshot",
            "expression": [
              "",
              "VAR RefDate =",
              "    CALCULATE(",
              "        MAX('Calendar'[Date]),",
              "        FILTER( 'Calendar', 'Calendar'[Date] <= [Report Date])",
              "    )",
              "",
              "VAR LastShortage = ",
              "    CALCULATE(",
              "        SUM( 'Backorder Snapshots'[Shortage Amount] ),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] = RefDate",
              "        )",
              "    )",
              "",
              "RETURN",
              "    DIVIDE( LastShortage, [Last Inventory Amount] )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Accumulated Inventory Balance",
            "description": "Accumulated balance as of this month relative to [Report Date]",
            "expression": [
              "",
              "VAR LastVisibleDate =",
              "    MAX ( 'Calendar'[Date] )",
              "VAR FirstVisibleDate =",
              "    MIN ( 'Calendar'[Date] )",
              "VAR LastDateWithData =",
              "    CALCULATE (",
              "        MAX ( 'Inventory Balance (Totals)'[MonthDateKey] ),",
              "        REMOVEFILTERS ()",
              "    )",
              "VAR Result =",
              "    IF (",
              "        FirstVisibleDate <= LastDateWithData,",
              "        CALCULATE (",
              "            SUM( 'Inventory Balance (Totals)'[Amount (Group Currency)] ),",
              "            'Calendar'[Date] <= LastVisibleDate ",
              "        )",
              "    )",
              "RETURN",
              "    Result"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Prior Accumulated Inventory Balance",
            "description": "Accumulated balance as of end of last month relative to [Report Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Accumulated Inventory Balance],",
              "    DATEADD( 'Calendar'[Date], -1, MONTH )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "Inventory Balance",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Inventory Balance (Items)'[Amount (Local Currency 2)] ),",
              "        \"Local\", SUM( 'Inventory Balance (Items)'[Amount (Local Currency)] ),",
              "        SUM( 'Inventory Balance (Items)'[Amount (Local Currency 2)] )",
              "    ),",
              "    SUM( 'Inventory Balance (Items)'[Amount (Local Currency)] )  ",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Purchases)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Purchases\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Produced)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Produced\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Transfers)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Transfers\"",
              ") +",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Document Type] IN {\"AB\", \"ZA\"},",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Sales)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Sales\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Scrap)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Scrap\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Write-offs)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Write-offs\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Accruals)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Accruals\"",
              ") +",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Document Type] = \"SA\",",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (Reversals)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"Reversals\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance (PPV)",
            "expression": [
              "",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"PPV\"",
              ") +",
              "CALCULATE(",
              "    [MTD Inventory Balance],",
              "    'Inventory Balance (Items)'[Document Type] = \"PR\",",
              "    'Inventory Balance (Items)'[Movement Type Category] = \"\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "MTD Inventory Balance",
            "expression": "CALCULATE( [Inventory Balance], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "Check Inventory Balance",
            "description": "Value is 1 (or TRUE) if the [MTD Accumulated Inventory Balance] from 'Inventory Balance (Totals)' equals the sum of [MTD Prior Accumulated Inventory Balance] from 'Inventory Balance (Totals)' and [MTD Inventory Balance] from 'Inventory Balance (Items)'",
            "expression": [
              "",
              "VAR breakdown = ",
              "    [MTD Inventory Balance (Purchases)]",
              "    + [MTD Inventory Balance (Produced)]",
              "    + [MTD Inventory Balance (Transfers)]",
              "    + [MTD Inventory Balance (Sales)]",
              "    + [MTD Inventory Balance (Scrap)]",
              "    + [MTD Inventory Balance (Write-offs)]",
              "    + [MTD Inventory Balance (Accruals)]",
              "    + [MTD Inventory Balance (Reversals)]",
              "    + [MTD Inventory Balance (PPV)]",
              "",
              "RETURN",
              "    IF(",
              "        ISBLANK( [MTD Prior Accumulated Inventory Balance] ),",
              "        BLANK(),",
              "        IF(",
              "            ROUND([MTD Prior Accumulated Inventory Balance] + [MTD Inventory Balance], 2) = ROUND([MTD Accumulated Inventory Balance], 2),",
              "            1,",
              "            0",
              "        )",
              "    )"
            ],
            "formatString": "0",
            "displayFolder": "Inventory Balance"
          },
          {
            "name": "End of Next 3 Months",
            "expression": " EOMONTH( [Report Date], 3 )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "MStat Indicator",
            "description": "Log error / typo (-1); Skipped S/O (0); Other (1)",
            "expression": "MAX( 'Machine Status'[Status] )",
            "formatString": "0",
            "displayFolder": "Machine Status"
          },
          {
            "name": "Sample Request Count",
            "expression": [
              "",
              "CALCULATE(",
              "    DISTINCTCOUNT( 'Sales Order Documents'[Order Number] ),",
              "    FILTER(",
              "        'Sales Order Documents',",
              "        'Sales Order Documents'[Sample Category] <> \"Not Applicable\"",
              "    )",
              ") +",
              "DISTINCTCOUNT( 'Odoo Sample Requests (Open)'[Ticket Number] )"
            ],
            "formatString": "#,0",
            "displayFolder": "Sample Requests"
          },
          {
            "name": "Sample Request Cost Amount",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Cost Amount] ),",
              "    FILTER(",
              "        'Sales Order Documents',",
              "        'Sales Order Documents'[Sample Category] <> \"Not Applicable\"",
              "    )",
              ") +",
              "SUM( 'Odoo Sample Requests (Open)'[Cost Amount] )"
            ],
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "Sample Requests",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Beginning of Last Month",
            "expression": "EDATE([Beginning of Month], -1)",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Average Monthly Consumption (Last 3 Months)",
            "description": "Monthly average of sum of 'Inventory Consumption'[Quantity] posted in the previous 3 calendar months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR NumOfMonths = 3",
              "VAR Age = DATEDIFF( MAX( 'Material Master'[Created Date] ), [Report Date], MONTH )",
              "VAR Result = ",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Inventory Consumption (Dynamic)],",
              "            DATESINPERIOD(",
              "                'Calendar'[Start of Month],",
              "                [Beginning of Last Month],",
              "                -NumOfMonths,",
              "                MONTH)",
              "        ) + 0,",
              "        NumOfMonths",
              "    )",
              "RETURN",
              "    IF(",
              "        (Result || [Current Unrestricted Stock Quantity]) && Age >= NumOfMonths,",
              "        ABS( Result ),",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Average Monthly Consumption (Last 6 Months)",
            "description": "Monthly average of sum of 'Inventory Consumption'[Quantity] posted in the previous 6 calendar months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR NumOfMonths = 6",
              "VAR Age = DATEDIFF( MAX( 'Material Master'[Created Date] ), [Report Date], MONTH )",
              "VAR Result = ",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Inventory Consumption (Dynamic)],",
              "            DATESINPERIOD(",
              "                'Calendar'[Start of Month],",
              "                [Beginning of Last Month],",
              "                -NumOfMonths,",
              "                MONTH)",
              "        ) + 0,",
              "        NumOfMonths",
              "    )",
              "RETURN",
              "    IF(",
              "        (Result || [Current Unrestricted Stock Quantity]) && Age >= NumOfMonths,",
              "        ABS( Result ),",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Average Monthly Consumption (Last 12 Months)",
            "description": "Monthly average of sum of 'Inventory Consumption'[Quantity] posted in the previous 12 calendar months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR NumOfMonths = 12",
              "VAR Age = DATEDIFF( MAX( 'Material Master'[Created Date] ), [Report Date], MONTH )",
              "VAR Result = ",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Inventory Consumption (Dynamic)],",
              "            DATESINPERIOD(",
              "                'Calendar'[Start of Month],",
              "                [Beginning of Last Month],",
              "                -NumOfMonths,",
              "                MONTH)",
              "        ) + 0,",
              "        NumOfMonths",
              "    )",
              "RETURN",
              "    IF(",
              "        (Result || [Current Unrestricted Stock Quantity]) && Age >= NumOfMonths,",
              "        ABS( Result ),",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Average Monthly Consumption (Last 24 Months)",
            "description": "Monthly average of sum of 'Inventory Consumption'[Quantity] posted in the previous 24 calendar months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR NumOfMonths = 24",
              "VAR Age = DATEDIFF( MAX( 'Material Master'[Created Date] ), [Report Date], MONTH )",
              "VAR Result = ",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Inventory Consumption (Dynamic)],",
              "            DATESINPERIOD(",
              "                'Calendar'[Start of Month],",
              "                [Beginning of Last Month],",
              "                -NumOfMonths,",
              "                MONTH)",
              "        ) + 0,",
              "        NumOfMonths",
              "    )",
              "RETURN",
              "    IF(",
              "        (Result || [Current Unrestricted Stock Quantity]) && Age >= NumOfMonths,",
              "        ABS( Result ),",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Average Monthly Consumption (Last 36 Months)",
            "description": "Monthly average of sum of 'Inventory Consumption'[Quantity] posted in the previous 36 calendar months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR NumOfMonths = 36",
              "VAR Age = DATEDIFF( MAX( 'Material Master'[Created Date] ), [Report Date], MONTH )",
              "VAR Result = ",
              "    DIVIDE(",
              "        CALCULATE(",
              "            [Inventory Consumption (Dynamic)],",
              "            DATESINPERIOD(",
              "                'Calendar'[Start of Month],",
              "                [Beginning of Last Month],",
              "                -NumOfMonths,",
              "                MONTH)",
              "        ) + 0,",
              "        NumOfMonths",
              "    )",
              "RETURN",
              "    IF(",
              "        (Result || [Current Unrestricted Stock Quantity]) && Age >= NumOfMonths,",
              "        ABS( Result ),",
              "        BLANK() ",
              "    )"
            ],
            "formatString": "#,##0.00;-#,##0.00;\"-\"",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Time Supply",
            "description": "[Current Unrestricted Stock Quantity] divided by [Average Monthly Consumption (Last 12 Months)]. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "DIVIDE(",
              "    [Current Unrestricted Stock Quantity],",
              "    [Average Monthly Consumption (Last 12 Months)]",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Annual Consumption (Next 12 Months)",
            "description": "If time supply < 12, then [Current Unrestricted Stock Quantity], else, [Average Monthly Consumption (Last 12 Months)] * 12. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "IF(",
              "    [Inventory Time Supply] < 12,",
              "    [Current Unrestricted Stock Quantity],",
              "    [Average Monthly Consumption (Last 12 Months)] * 12",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Annual Consumption (After 12th Month)",
            "description": "If unrestricted stock is equal to consumption in the next 12 months, then 0. Else if consumption in the last 12 months is the same as the difference of current stock and consumption in the next 12 months, then value is the consumption in the next 12 months. Otherwise, value is the difference between current stock and consumption in the next 12 months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR Usage = [Average Monthly Consumption (Last 12 Months)] * 12",
              "VAR Net = [Current Unrestricted Stock Quantity] - [Inventory Annual Consumption (Next 12 Months)]",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        [Current Unrestricted Stock Quantity] = [Inventory Annual Consumption (Next 12 Months)], BLANK(),",
              "        Usage < Net, Usage,",
              "        Net",
              "    )"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Annual Consumption (After 24th Month)",
            "description": "If unrestricted stock is equal to consumption in the next 24 months, then 0. Else if consumption in the last 12 months is the same as the difference of current stock and consumption in the next 24 months, then value is the consumption in the next 24 months. Otherwise, value is the difference between current stock and consumption in the next 24 months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR Usage = [Average Monthly Consumption (Last 12 Months)] * 12",
              "VAR Net = [Current Unrestricted Stock Quantity] - [Inventory Annual Consumption (Next 12 Months)] - [Inventory Annual Consumption (After 12th Month)]",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        [Current Unrestricted Stock Quantity] = ([Inventory Annual Consumption (Next 12 Months)] + [Inventory Annual Consumption (After 12th Month)]), BLANK(),",
              "        Usage < Net, Usage,",
              "        Net",
              "    )"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Annual Consumption (After 36th Month)",
            "description": "If unrestricted stock is equal to consumption in the next 36 months, then 0. Else if consumption in the last 12 months is the same as the difference of current stock and consumption in the next 36 months, then value is the consumption in the next 36 months. Otherwise, value is the difference between current stock and consumption in the next 36 months. Can be toggled between quantity and amount values (default = quantity).",
            "expression": [
              "",
              "VAR Usage = [Average Monthly Consumption (Last 12 Months)] * 12",
              "VAR Net = [Current Unrestricted Stock Quantity] - [Inventory Annual Consumption (Next 12 Months)] - [Inventory Annual Consumption (After 12th Month)] - [Inventory Annual Consumption (After 24th Month)]",
              "RETURN",
              "    SWITCH(",
              "        TRUE(),",
              "        [Current Unrestricted Stock Quantity] = ([Inventory Annual Consumption (Next 12 Months)] + [Inventory Annual Consumption (After 12th Month)] + [Inventory Annual Consumption (After 24th Month)]), BLANK(),",
              "        Usage < Net, Usage,",
              "        Net",
              "    )"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Inventory"
          },
          {
            "name": "Inventory Consumption (Dynamic)",
            "description": "Sum of 'Inventory Consumption'[Quantity].Can be toggled between quantity and amount values (default = quantity)",
            "expression": [
              "",
              "VAR Qty = SUM( 'Inventory Consumption'[Quantity] )",
              "VAR Amt = SUM( 'Inventory Consumption'[Amount (In Current Price)] )",
              "RETURN",
              "    IF(",
              "        HASONEVALUE( '_Value to Use'[Value] ),",
              "        SWITCH(",
              "            VALUES( '_Value to Use'[Value] ),",
              "            \"Quantity\", Qty,",
              "            \"Amount\", Amt,",
              "            Qty",
              "        ),",
              "        Qty",
              "    )"
            ],
            "formatString": "#,0.00",
            "isHidden": true,
            "displayFolder": "Inventory"
          },
          {
            "name": "WH Shipment Amount",
            "description": "Total amount (in USD) of material transactions with 601, 641, 643, and Z43 movement types",
            "expression": [
              "",
              "ABS(",
              "    CALCULATE(",
              "        SUM( 'Inventory Consumption'[Amount] ),",
              "        FILTER(",
              "            'Inventory Consumption',",
              "            'Inventory Consumption'[Movement Type] IN { \"601\", \"641\", \"643\", \"Z43\" }",
              "                && 'Inventory Consumption'[Posting Date] <= [Last Working Day]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Warehouse",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "WH Picked Weight (Shipping)",
            "description": "Total weight of materials picked from finished good racks (starting with X) and 901 555. Data is based on the weight in transfer orders (sum of 'Transfer Orders (Shipping)'[Weight]) done by users in ORDER ASSEMBLY and WAREHOUSE OPERATIONS departments.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Transfer Orders (Shipping)'[Weight] ),",
              "    FILTER(",
              "        'SAP Users',",
              "        'SAP Users'[Department] IN { \"ORDER ASSEMBLY\", \"WAREHOUSE OPERATIONS\" }",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Expenses per Units Picked",
            "description": "Total expenses amount assigned to \"DIST\" department divided by [WH Shipment Amount]",
            "expression": [
              "",
              "DIVIDE(",
              "    CALCULATE(",
              "        [Expenses Amount],",
              "        'Cost Center Names'[Department] = \"DIST\",",
              "        ALL( Plant[Plant] )",
              "    ),",
              "    [WH Picked Weight (Shipping)]",
              ")"
            ],
            "formatString": "0.0000",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Shipment Weight",
            "description": "Total weight of material transactions with 601, 641, 643, and Z43 movement types. Weight is given in the material master data.",
            "expression": [
              "",
              "ABS(",
              "    CALCULATE(",
              "        SUM( 'Inventory Consumption'[Gross Weight] ),",
              "        FILTER(",
              "            'Inventory Consumption',",
              "            'Inventory Consumption'[Movement Type] IN { \"601\", \"641\", \"643\", \"Z43\" }",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "CW PO Open Amount",
            "description": "Total amount of open purchase orders scheduled to be delivered this week (based on delivery date in the purchase order)",
            "expression": [
              " ",
              "VAR BegDate = ([Report Date] + 1) - WEEKDAY( [Report Date] + 1 )",
              "VAR EndDate = BegDate + 7",
              "RETURN",
              "CALCULATE(",
              "    [PO Open Amount],",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] >= BegDate",
              "            && 'Calendar'[Date] <= EndDate",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "CW PO Goods Receipt Amount",
            "description": "Total amount of goods receipts of incoming purchase orders issued this week",
            "expression": [
              " ",
              "VAR BegDate = ([Report Date] + 1) - WEEKDAY( [Report Date] + 1 )",
              "VAR EndDate = BegDate + 7",
              "RETURN",
              "CALCULATE(",
              "    ABS([GRIR Amount (Local2)]),",
              "    FILTER(",
              "        'Goods and Invoice Receipts',",
              "        'Goods and Invoice Receipts'[Document Type] IN {\"WE\", \"WL\"}",
              "    ),",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] >= BegDate",
              "            && 'Calendar'[Date] <= EndDate",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PO Goods Receipt Amount",
            "expression": " SUM('Purchase Orders'[Goods Receipt Amount])",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "CW SO Internal Open Amount",
            "expression": [
              " ",
              "VAR BegDate = ([Report Date] + 1) - WEEKDAY( [Report Date] + 1 )",
              "VAR EndDate = BegDate + 7",
              "RETURN",
              "CALCULATE(",
              "    [SO Internal Open Amount],",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] >= BegDate",
              "            && 'Calendar'[Date] <= EndDate",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "CW SO Shipped Amount",
            "expression": [
              " ",
              "VAR BegDate = ([Report Date] + 1) - WEEKDAY( [Report Date] + 1 )",
              "VAR EndDate = BegDate + 7",
              "RETURN",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Shipped Amount] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[Last PGI Date] ),",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] >= BegDate",
              "            && 'Calendar'[Date] <= EndDate",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Month End WH Pending Shipment Weight",
            "description": "Weight of materials not yet shipped and scheduled to ship at the end of the month as determined by the First Requested Ship Date of the sales order",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Customer Open Weight] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] ),",
              "    FILTER(",
              "        ALL('Calendar'[Date]),",
              "        'Calendar'[Date] >= [Beginning of Month]",
              "            && 'Calendar'[Date] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Expenses Plan Var%",
            "expression": "DIVIDE([Expenses Amount] - [Expenses Plan], [Expenses Plan])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Expenses"
          },
          {
            "name": "WH Storage Bin Amount",
            "description": "Total amount (in USD) of materials in storage bin (sum of 'Current Inventory (Bins)'[Amount in USD])",
            "expression": "SUM( 'Current Inventory (Bins)'[Amount in USD] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Warehouse",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "WH Average Material Age in Days",
            "description": "Average days between the material's goods receipt date and today (average of 'Current Inventory (Bins)'[Age in Days])",
            "expression": "AVERAGE( 'Current Inventory (Bins)'[Age in Days] )",
            "formatString": "0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Storage Bin Capacity",
            "description": "Capacity per storage bin (sum of '_Storage Bin'[Capacity])",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM('_Storage Bin'[Capacity] ),",
              "    VALUES( '_Storage Bin'[StorageKey] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Storage Bin Utilization",
            "description": "[WH Storage Bin Quantity] divided by [WH Storage Bin Capacity]",
            "expression": [
              "",
              "IF(",
              "    ISFILTERED( '_Storage Bin' ),",
              "    DIVIDE(",
              "        [WH Storage Bin Quantity],",
              "        [WH Storage Bin Capacity]",
              "    ),",
              "    BLANK()",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Warehouse"
          },
          {
            "name": "Last Storage Bin Utilization Snapshot",
            "description": "Last value of snapshot of storage bin utilitization (from 'Storage Bin Utilization (Snapshots)' table)",
            "expression": [
              "",
              "VAR RefDate =",
              "    CALCULATE(",
              "        MAX('Calendar'[Date]),",
              "        FILTER( 'Calendar', 'Calendar'[Date] <= [Report Date])",
              "    )",
              "",
              "RETURN",
              "    CALCULATE(",
              "        DIVIDE(",
              "            SUM( 'Storage Bin Utilization (Snapshots)'[Utilized] ),",
              "            SUM( 'Storage Bin Utilization (Snapshots)'[Capacity] )",
              "        ),",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] = RefDate",
              "        )",
              "    )"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "WH Storage Bin Quantity",
            "description": "Total quantity in a storage bin (sum of 'Current Inventory (Bins)'[Quantity])",
            "expression": "SUM( 'Current Inventory (Bins)'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "Testing Sample Count",
            "expression": "DISTINCTCOUNT( 'Testing Results'[Result Key] )",
            "formatString": "#,0",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Average Result",
            "expression": "AVERAGE( 'Testing Results'[Result Value] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Minimum Result",
            "expression": "MIN( 'Testing Results'[Result Value] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Maximum Result",
            "expression": "MAX( 'Testing Results'[Result Value] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Standard Deviation Result",
            "expression": "STDEV.P( 'Testing Results'[Result Value] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Passing Rate",
            "expression": [
              "",
              "DIVIDE(",
              "    [Testing Passed Specimen Count],",
              "    [Testing Passed Specimen Count] + [Testing Failed Specimen Count]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Specification Lower Limit",
            "expression": "MIN( 'Testing Results'[Specification Lower Limit] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Specification Upper Limit",
            "expression": "MAX( 'Testing Results'[Specification Upper Limit] )",
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Passed Specimen Count",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA( 'Testing Results'[Is Pass] ),",
              "    'Testing Results'[Is Pass] = 1",
              ") + 0"
            ],
            "formatString": "#,0",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing Failed Specimen Count",
            "expression": [
              "",
              "CALCULATE(",
              "    COUNTA( 'Testing Results'[Is Pass] ),",
              "    'Testing Results'[Is Pass] = 0",
              ") + 0"
            ],
            "formatString": "#,0",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing 15min Dwell Adhesion Avg Result",
            "expression": [
              "",
              "CALCULATE(",
              "    [Testing Average Result],",
              "    'Testing Results'[Test Name] = \"Peel15mAT\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "Testing 24hr Dwell Adhesion Avg Result",
            "expression": [
              "",
              "CALCULATE(",
              "    [Testing Average Result],",
              "    'Testing Results'[Test Name] = \"Peel24hAT\"",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Testing"
          },
          {
            "name": "CW Absorption",
            "description": "Current week's total absorption (relative to [Report Date])",
            "expression": [
              "",
              "VAR BegDate = ([Report Date]) - WEEKDAY( [Report Date] )",
              "VAR EndDate = BegDate + 7",
              "RETURN",
              "CALCULATE(",
              "    [Absorption],",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] >= BegDate",
              "            && 'Calendar'[Date] <= EndDate",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              "CALCULATE( [Absorption], DATESYTD('Calendar'[Date], \"09/30\") )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": "CALCULATE( [FYTD Absorption], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Absorption Hours",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [Absorption Hours], DATESMTD( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Absorption Hours",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [MTD Absorption Hours], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "CONV Linear Footage",
            "expression": [
              "",
              "CALCULATE(",
              "    [GR Linear Footage],",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Machine Name] IN {\"014\", \"088\", \"182\", \"733\", \"734\", \"735\", \"736\", \"762\", \"MANUAL\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"600\", \"700\", \"733\", \"734\", \"735\", \"736\", \"88\", \"182\", \"782\", \"555\"}",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "S/O Future Scheduled Output by Month End (Upstream)",
            "description": "Total target quantity of scheduled shop orders after today until end of month (relative to [Report Date]). Scheduled data is the from the latest schedule published by Planning.",
            "expression": [
              "",
              "CALCULATE(",
              "    [S/O Scheduled Quantity (Upstream)],",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Upstream Schedule'[PlanFinishDateAltKey] ),",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Upstream Schedule'[PlanFinishDateAltKey] ),",
              "        'Upstream Schedule'[PlanFinishDateAltKey] > [Report Date]",
              "            && 'Upstream Schedule'[PlanFinishDateAltKey] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Absorption per Output (Last 3 Months)",
            "description": "Total absorption posted in the last 3 calendar months divided by the total output of departments. Casting and coating output is from machine data, Converting output is GR transaction, and others are delivered quantity of shop orders that ended in the last 3 months.",
            "expression": [
              "",
              "VAR BegDate = EDATE([Beginning of Month], -3)",
              "VAR Upstream_Out = ",
              "    CALCULATE(",
              "        [Upstream Actual Production Footage],",
              "        ALL( 'Calendar' ),",
              "        FILTER(",
              "            ALL( 'Upstream Logs - Simplified'[Start Time] ),",
              "            'Upstream Logs - Simplified'[Start Time] >= BegDate",
              "                && 'Upstream Logs - Simplified'[Start Time] < [Beginning of Month]",
              "        )",
              "    )",
              "",
              "VAR Conv_Out = ",
              "    CALCULATE(",
              "        [CONV Linear Footage],",
              "        ALL( 'Calendar' ),",
              "        FILTER(",
              "            ALL( 'Goods Issues and Receipts'[Posting Date] ),",
              "            'Goods Issues and Receipts'[Posting Date] >= BegDate",
              "                && 'Goods Issues and Receipts'[Posting Date] < [Beginning of Month]",
              "        )",
              "    )",
              "",
              "VAR Other_Out = ",
              "    CALCULATE(",
              "        SUM('Shop Orders'[Delivered Quantity] ),",
              "        ALL( 'Calendar' ),",
              "        FILTER(",
              "            ALL( 'Shop Orders'[End Date Key] ),",
              "            'Shop Orders'[End Date Key] >= BegDate",
              "                && 'Shop Orders'[End Date Key] < [Beginning of Month]",
              "        ),",
              "        'Shop Orders'[Close Indicator] = \"X\"",
              "    )",
              "",
              "RETURN",
              "DIVIDE(",
              "    CALCULATE(",
              "        [Absorption],",
              "        FILTER(",
              "            ALL( 'Calendar'[Date] ),",
              "            'Calendar'[Date] >= BegDate",
              "                && 'Calendar'[Date] < [Beginning of Month]",
              "        )",
              "    ),",
              "    SWITCH(",
              "        SELECTEDVALUE( '_Departments'[Department] ),",
              "        \"CONV\", Conv_Out,",
              "        \"CAST\", Upstream_Out,",
              "        \"COAT\", Upstream_Out,",
              "        Other_Out",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Actual Production Start Datetime",
            "description": "Actual datetime the production per department started since the beginning of the month. This value is from machine data. If not available, the beginning of month datetime is used.",
            "expression": [
              "",
              "VAR StartTime = ",
              "    CALCULATE(",
              "        MIN( 'Upstream Logs - Simplified'[Start Time] ),",
              "        ALL( 'Calendar' ),",
              "        FILTER(",
              "            ALL( 'Upstream Logs - Simplified'[Start Time] ),",
              "            'Upstream Logs - Simplified'[Start Time] >= [Beginning of Month]",
              "        ),",
              "        'Upstream Logs - Simplified'[Category] = \"Production\"",
              "    )",
              "",
              "RETURN",
              "IF( ISBLANK(StartTime) && [MTD Absorption] <> BLANK(), [Beginning of Month] + TIME(0, 0, 0), StartTime )"
            ],
            "formatString": "MM/dd/yyyy HH:mm:ss",
            "displayFolder": "Absorption (Projected)",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"MM/dd/yyyy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Scheduled Production Stop Datetime",
            "description": "The last scheduled finish date available in the schedule data. If not available, the value used is today's end datetime before midnight.",
            "expression": [
              "",
              "VAR SchedEnd = ",
              "    CALCULATE(",
              "        MAX( 'Upstream Schedule'[Plan Finish Date] ),",
              "        USERELATIONSHIP( 'Calendar'[Date], 'Upstream Schedule'[PlanFinishDateAltKey] ),",
              "        ALL( 'Calendar'[Date] ),",
              "        FILTER(",
              "            'Upstream Schedule',",
              "            'Upstream Schedule'[PlanFinishDateAltKey] <= [End of Month]",
              "        )",
              "    )",
              "",
              "RETURN",
              "IF( ISBLANK(SchedEnd) && [MTD Absorption] <> BLANK(), [Report Date] + TIME(23, 59, 59), SchedEnd )"
            ],
            "formatString": "MM/dd/yyyy HH:mm:ss",
            "displayFolder": "Absorption (Projected)",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralLongDateTime\" FormatString=\"MM/dd/yyyy HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Estimated Absorption based on Scheduled Output by Month End",
            "description": "[MTD Absorption] plus the product of [S/O Future Scheduled Output by Month End (Upstream)] and the average absorption per output in the last 3 calendar months ([Absorption per Output (Last 3 Months)])",
            "expression": [
              "",
              "SUMX( VALUES('_Departments'[Department]), [MTD Absorption] + ([S/O Future Scheduled Output by Month End (Upstream)] * [Absorption per Output (Last 3 Months)]) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Average Daily Absorption based on Estimate",
            "description": "[Estimated Absorption based on Scheduled Output by Month End] divided by the number of days between [Actual Production Start Datetime] and [Scheduled Production Stop Datetime]",
            "expression": [
              "",
              "DIVIDE(",
              "    [Estimated Absorption based on Scheduled Output by Month End],",
              "    DATEDIFF( [Actual Production Start Datetime], [Scheduled Production Stop Datetime], MINUTE ) / 1440",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Projected Absorption",
            "description": "[Average Daily Absorption based on Estimate] multiplied by the number of days between [Actual Product Start Datetime] and an end date. If current date is before 15th day of the month, the end date is the calendar month end datetime before midnight. Otherwise, it is the [Scheduled Production Stop Datetime].",
            "expression": [
              "",
              "VAR EndDate = [End of Month] + TIME(23, 59, 59)",
              "",
              "VAR MinVisibleDate = MIN('Calendar'[Date])",
              "",
              "VAR Proj =",
              "    SUMX( ",
              "        VALUES('_Departments'[Department]), ",
              "        [Estimated Absorption based on Scheduled Output by Month End]",
              "            + ([Average Daily Absorption based on Estimate] * ((DATEDIFF([Scheduled Production Stop Datetime], EndDate, MINUTE) - ([Future Off Hours After Schedule End] * 60)) / 1440)) ",
              "    )",
              "",
              "RETURN",
              "-- Only project current month",
              "-- Display MTD of previous month only. Otherwise, blank",
              "IF(",
              "    ISFILTERED( 'Calendar' ),",
              "    IF(",
              "        MinVisibleDate < [Beginning of Last Month],",
              "        BLANK(),",
              "        IF(",
              "            MinVisibleDate < [Beginning of Month],",
              "            [MTD Absorption],",
              "            Proj",
              "        )",
              "    ),",
              "    Proj",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Future Off Hours After Schedule End",
            "expression": [
              "",
              "VAR BegDate = ",
              "    DATE(",
              "        YEAR( [Scheduled Production Stop Datetime] ),",
              "        MONTH( [Scheduled Production Stop Datetime] ),",
              "        DAY( [Scheduled Production Stop Datetime])",
              "    )",
              "",
              "RETURN",
              "CALCULATE(",
              "    SUM( 'Upstream Off Days'[Off Hours] ),",
              "    ALL( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Upstream Off Days'[Date] ),",
              "        'Upstream Off Days'[Date] > BegDate",
              "            && 'Upstream Off Days'[Date] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "0.00",
            "displayFolder": "Absorption (Projected)"
          },
          {
            "name": "Absorption Hours",
            "expression": "SUM( Absorption[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Absorption"
          },
          {
            "name": "WH Shipment Quantity",
            "description": "Total weight of material transactions with 601, 641, 643, and Z43 movement types. Weight is given in the material master data.",
            "expression": [
              "",
              "ABS(",
              "    CALCULATE(",
              "        SUM( 'Inventory Consumption'[Quantity] ),",
              "        FILTER(",
              "            'Inventory Consumption',",
              "            'Inventory Consumption'[Movement Type] IN { \"601\", \"641\", \"643\", \"Z43\" }",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Future Shipment Amount",
            "expression": [
              "",
              "VAR MinVisibleDate = MIN('Calendar'[Date])",
              "",
              "RETURN",
              "-- Show previous month as actual ship amount",
              "-- Current and future shows actual ship plus customer open",
              "IF(",
              "    MinVisibleDate < [Beginning of Last Month],",
              "    BLANK(),",
              "    IF(",
              "        MinVisibleDate < [Beginning of Month],",
              "        [WH Shipment Amount],",
              "        [WH Shipment Amount] + [SO Customer Open Amount]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Warehouse",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sales Order Line Count (By First Ship Date)",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales Order Line Count],",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "WH Effective On Time Shipment",
            "description": "Daily average ratio of the number of on time lines plus exempted late lines divided by the number of lines. Date grouping: 'Sales Order Documents'[First Delivery Date].",
            "expression": [
              "",
              "VAR OTS = ",
              "    DIVIDE(",
              "        [WH SO Line Count (On Time)] + [WH SO Line Count (Exempt)],",
              "        [WH SO Line Count (All)]",
              "    )",
              "",
              "RETURN -- Weighted average by line count",
              "    DIVIDE(",
              "        SUMX(",
              "            VALUES( 'Calendar'[Date] ),",
              "            [WH SO Line Count (All)] * OTS",
              "        ),",
              "        [WH SO Line Count (All)]",
              "    )"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Effective On Time Shipment (Target)",
            "description": "Data Source: KPI Targets SharePoint List. If there is no value available, the default values are 95% for OTS and 100% for T1 OTS.",
            "expression": [
              "",
              "VAR KeyVal =",
              "    IF(",
              "        HASONEVALUE( 'Sales Order Documents'[Tier] )",
              "            && SELECTEDVALUE( 'Sales Order Documents'[Tier] ) = \"A\",",
              "        \"OTS_T1\",",
              "        \"OTS\"",
              "    )",
              "",
              "VAR Target =",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = KeyVal,",
              "        FILTER(",
              "            ALL( Target_KPI[CalendarTimeKey] ),",
              "            CONTAINS(",
              "                VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "                'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "            )",
              "        )",
              "    )",
              "",
              "RETURN",
              "IF(",
              "    ISBLANK( Target ),",
              "    SWITCH(",
              "        KeyVal,",
              "        \"OTS\", 0.95,",
              "        \"OTS_T1\", 1.00,",
              "        0.95",
              "    ),",
              "    Target",
              ")",
              ""
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Complete On Time",
            "expression": [
              "",
              "DIVIDE(",
              "    SUMX(",
              "        VALUES( 'Calendar'[Date] ),",
              "        [WH Complete On Time (Hidden)] * [WH SO Line Count (All)]",
              "    ),",
              "    [WH SO Line Count (All)]",
              ")"
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH SO Line Count (All)",
            "expression": [
              "",
              "CALCULATE(",
              "    [Sales Order Line Count (By First Ship Date)],",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] <= [Last Working Day]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH SO Line Count (On Time)",
            "expression": [
              "",
              "VAR OnTime =",
              "    CALCULATE(",
              "        [Sales Order Line Count (By First Ship Date)],",
              "        'Sales Order Documents'[Late Indicator] = 0,",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] <= [Last Working Day]",
              "        )",
              "    )",
              "",
              "RETURN",
              "-- Days with lines but no on time should show 0",
              "IF(",
              "    [WH SO Line Count (All)] <> BLANK(),",
              "    OnTime + 0,",
              "    BLANK()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH SO Line Count (Exempt)",
            "expression": [
              "",
              "VAR Exempt =",
              "    CALCULATE(",
              "        [Sales Order Line Count (By First Ship Date)],",
              "        'Sales Order Documents'[Late Indicator] = 1,",
              "        'Sales Order Documents'[Reason Type for Late Shipment] = \"3rd Party\",",
              "        FILTER(",
              "            'Calendar',",
              "            'Calendar'[Date] <= [Last Working Day]",
              "        )",
              "    )",
              "",
              "RETURN",
              "IF(",
              "    [WH SO Line Count (All)] <> BLANK(),",
              "    Exempt + 0,",
              "    BLANK()",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Complete On Time (Target)",
            "description": "Data Source: KPI Targets SharePoint List. If there is no value available, the default value is 90%.",
            "expression": [
              "",
              "VAR Target =",
              "    CALCULATE(",
              "        AVERAGE( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"COT\",",
              "        FILTER(",
              "            ALL( Target_KPI[CalendarTimeKey] ),",
              "            CONTAINS(",
              "                VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "                'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "            )",
              "        )",
              "    )",
              "",
              "RETURN",
              "IF(",
              "    ISBLANK( Target ),",
              "    0.90,",
              "    Target",
              ")",
              ""
            ],
            "formatString": "#,0.00%;-#,0.00%;#,0.00%",
            "displayFolder": "Warehouse"
          },
          {
            "name": "WH Shipment Calendar List",
            "expression": [
              "",
              "CONCATENATEX( ",
              "    'Shipment Calendar', ",
              "    LEFT([Customer Name], 15) & UNICHAR(10) & \"#\" & VALUE([Order Number]) & \" (\" & [Order Type] & \")\",",
              "    UNICHAR(10),",
              "    [Order Amount], DESC",
              ")"
            ],
            "displayFolder": "Warehouse"
          },
          {
            "name": "Last Working Day",
            "expression": [
              "",
              "CALCULATE(",
              "    MAX( 'Calendar'[Date] ),",
              "    FILTER(",
              "        ALL( 'Calendar' ),",
              "        'Calendar'[Date] <= [Report Date]",
              "            && 'Calendar'[Is Weekday]",
              "    )",
              ")"
            ],
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "WH Complete On Time (Hidden)",
            "expression": [
              "",
              "AVERAGEX(",
              "    VALUES( 'Customer Master'[Customer Name] ),",
              "    IF(",
              "        [WH SO Line Count (All)] = BLANK(),",
              "        BLANK(),",
              "        IF(",
              "            [WH SO Line Count (All)] = ( [WH SO Line Count (On Time)] + [WH SO Line Count (Exempt)] ),",
              "            1,",
              "            0",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "isHidden": true,
            "displayFolder": "Warehouse"
          },
          {
            "name": "SO Late Quantity",
            "description": "Difference between [SO Order Quantity] and [SO Shipped On Time Quantity]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Late Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "WH Days of Perfect On Time Shipment",
            "description": "Number of days when [WH Effective On Time Shipment] equals to 100%",
            "expression": [
              "",
              "VAR CountPerfectDays =",
              "    COUNTROWS(",
              "        FILTER(",
              "            VALUES('Calendar'[Date]),",
              "            [WH Effective On Time Shipment] >= 1",
              "        )",
              "    )",
              "",
              "RETURN",
              "CALCULATE(",
              "    CountPerfectDays + 0,",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] <= [Last Working Day]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Warehouse"
          },
          {
            "name": "Sales Discount",
            "description": "Sum of CE110US.KWKDRB",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Discount Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents',  'Sales Invoice Documents'[Discount Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Discount Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Discount Amount] )    ",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Sales"
          }
        ]
      },
      {
        "name": "Sales Invoice Documents",
        "description": "SAP Source: CE110US, VBRP, TVFKT; Active filters: PALEDGER = 01 & VRGAR = F & FKART not equal (IV, IVS) & RBELN starts with 009",
        "columns": [
          {
            "name": "Invoice Number",
            "dataType": "string",
            "description": "SAP Source: CE110US.RBELN; Reference document number for CO-PA line item",
            "sourceColumn": "SaleDocNoKey"
          },
          {
            "name": "Invoice Line Number",
            "dataType": "string",
            "description": "SAP Source: CE110US.RPOSN; Item number from reference document (CO-PA)",
            "sourceColumn": "SaleLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.BUDAT ",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: CE110US.ABSMG",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.ERLOS",
            "sourceColumn": "GrossSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.ERLOS, CE110US.KWKDRB; Difference between gross sales and discount",
            "sourceColumn": "NetSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Overall Cost Amount",
            "dataType": "double",
            "description": "SAP Source: VBRP.WAVWR",
            "sourceColumn": "CostValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Material Cost Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.VVMEP",
            "sourceColumn": "MaterialExtPriceUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.KWKDRB",
            "sourceColumn": "DiscountValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: CE110US.FKART",
            "sourceColumn": "DocType"
          },
          {
            "name": "Document Type Text",
            "dataType": "string",
            "description": "SAP Source: TVFKT.VTEXT",
            "sourceColumn": "DocTypeText"
          },
          {
            "name": "Create Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.HZDAT",
            "sourceColumn": "CreateDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Invoice Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.FADAT",
            "sourceColumn": "InvoiceDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity Unit",
            "dataType": "string",
            "description": "SAP Source: CE110US.ABSMG_ME",
            "sourceColumn": "QuantityUoM"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "description": "SAP Source: CE110US.KURSF",
            "sourceColumn": "ExchangeRate",
            "formatString": "0.0000"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: CE110US.FRWAE",
            "sourceColumn": "Currency"
          },
          {
            "name": "Was New Product",
            "dataType": "int64",
            "description": "Indicates whether the material is less than or equal to 3 years as of the invoice posting date from Commercialization Date",
            "sourceColumn": "WasNewProduct",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "Gross Margin Amount",
            "dataType": "double",
            "description": "Difference between gross sales and cost value",
            "sourceColumn": "GrossMarginValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Ship To Name",
            "dataType": "string",
            "description": "SAP Source: ADRC.NAME1",
            "sourceColumn": "ShipToName"
          },
          {
            "name": "Ship To City",
            "dataType": "string",
            "description": "SAP Source: ADRC.CITY1",
            "sourceColumn": "ShipToCity"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES = Source{[Schema=\"dbo\",Item=\"VW_SALES\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_SALES,{\"SaleDocNoKey\", \"SaleLineNo\", \"DocType\", \"DocTypeText\", \"CreateDate\", \"InvoiceDate\", \"PostingDateKey\", \"WasNewProduct\", \"MaterialNoKey\", \"CustomerNoKey\", \"CustomerOrgKey\", \"ShipToName\", \"ShipToCity\", \"QuantityUoM\", \"QuantityValue\", \"Currency\", \"ExchangeRate\", \"GrossSalesValueUSD\", \"NetSalesValueUSD\", \"CostValueUSD\", \"MaterialExtPriceUSD\", \"DiscountValueUSD\", \"GrossMarginValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Hold Tag Documents",
        "columns": [
          {
            "name": "Notification Number",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Notification Type",
            "dataType": "string",
            "sourceColumn": "NotificationType"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Reference Number",
            "dataType": "string",
            "sourceColumn": "ReferenceNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "HoldQuantityValue",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "HoldValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "description": "SAP Source: QMEL.ERNAM",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: QMEL.MGEIN",
            "sourceColumn": "QuantityUoM"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: QMEL.FERTAUFNR",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Notification Code",
            "dataType": "string",
            "sourceColumn": "NotificationCode"
          },
          {
            "name": "Notification Text",
            "dataType": "string",
            "sourceColumn": "NotificationText"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_HOLDTAGS = Source{[Schema=\"dbo\",Item=\"VW_HOLDTAGS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_HOLDTAGS,{\"NotificationNoKey\", \"NotificationType\", \"NotificationCode\", \"EnterDateKey\", \"EnteredBy\", \"ReferenceNo\", \"MaterialNoKey\", \"BatchNoKey\", \"OrderNoKey\", \"NotificationText\", \"QuantityUoM\", \"HoldQuantityValue\", \"HoldValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expired Inventory",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "sourceColumn": "MfgDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Goods Receipt Date",
            "dataType": "dateTime",
            "sourceColumn": "GoodsReceiptDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Expiration Date",
            "dataType": "dateTime",
            "sourceColumn": "ExpirationDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "ExpiredQuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "ExpiredAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Stock Quantity",
            "dataType": "double",
            "sourceColumn": "StockQuantityValue",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Stock Amount",
            "dataType": "double",
            "sourceColumn": "StockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_EXPIRED = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_EXPIRED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_EXPIRED,{\"MaterialNoKey\", \"BatchNo\", \"PlantNo\", \"MfgDate\", \"GoodsReceiptDate\", \"ExpirationDate\", \"StockQuantityValue\", \"ExpiredQuantityValue\", \"StockAmountUSD\", \"ExpiredAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory Snapshots",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "SBlock Value",
            "dataType": "double",
            "sourceColumn": "SBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Value",
            "dataType": "double",
            "sourceColumn": "QBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expired Value",
            "dataType": "double",
            "sourceColumn": "ExpiredValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Blocked Inv Value",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " 'Blocked Inventory Snapshots'[SBlock Value] + 'Blocked Inventory Snapshots'[QBlock Value] + 'Blocked Inventory Snapshots'[Expired Value] + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_DAILY_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"DAILY_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DAILY_INVENTORY_BLOCK,{{\"SnapshotDateKey\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"SnapshotDateKey\", \"PlantNoKey\", \"SBlockValueUSD\", \"QBlockValueUSD\", \"ExpiredValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Material Master",
        "description": "SAP Source: MARA, MAKT, and AUSP",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: MARA.MATNR",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "MaterialNoKey",
            "displayFolder": "Master"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: MAKT.MAKTG",
            "sourceColumn": "MaterialDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Number - Description",
            "dataType": "string",
            "sourceColumn": "MaterialNoDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "description": "SAP Source: MARA.MTART",
            "sourceColumn": "MaterialType",
            "displayFolder": "Master"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: MARA.MATKL",
            "sourceColumn": "MaterialGroup",
            "displayFolder": "Master"
          },
          {
            "name": "X Distribution Status",
            "dataType": "string",
            "description": "SAP Source: MARA.MSTAV",
            "sourceColumn": "XDistributionStatus",
            "displayFolder": "Master"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: MARA.MEINS",
            "sourceColumn": "UnitOfMeasure",
            "displayFolder": "Master"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "Brand",
            "displayFolder": "Classification"
          },
          {
            "name": "Color Number",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "ColorNumber",
            "displayFolder": "Classification"
          },
          {
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "description": "SAP Source: AUSP.ATFLV",
            "sourceColumn": "CommercializationDate",
            "formatString": "Short Date",
            "displayFolder": "Classification",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Film Type",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "FilmType",
            "displayFolder": "Classification"
          },
          {
            "name": "Liner",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "Liner",
            "displayFolder": "Classification"
          },
          {
            "name": "Product Series",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "ProductSeries",
            "displayFolder": "Classification"
          },
          {
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL1",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL2",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL3",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Is New Product",
            "dataType": "int64",
            "description": "Indicates whether the material is less than or equal to 3 years as of today from Commercialization Date",
            "sourceColumn": "IsNewProduct",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "Classification"
          },
          {
            "name": "Length (ft)",
            "dataType": "double",
            "description": "SAP Source: MARM.LAENG OR MARM.UMREN; Some data cleanup is involved. Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "LengthValue",
            "formatString": "#,0",
            "displayFolder": "Dimensions"
          },
          {
            "name": "Width (in)",
            "dataType": "double",
            "description": "SAP Source: MARM.BREIT. Some data cleanup is involved. Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "WidthValue",
            "formatString": "#,0.00",
            "displayFolder": "Dimensions"
          },
          {
            "name": "Square Feet",
            "dataType": "double",
            "description": "Product of length and width (in to ft). Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "SquareFeetValue",
            "formatString": "#,0",
            "displayFolder": "Dimensions"
          },
          {
            "name": "Color Name",
            "dataType": "string",
            "description": "SAP Source: CAWNT.ATWTB",
            "sourceColumn": "ColorName",
            "displayFolder": "Classification"
          },
          {
            "name": "Size Code",
            "dataType": "string",
            "description": "SAP Source: CAWNT.ATWTB",
            "sourceColumn": "SizeCode",
            "displayFolder": "Classification"
          },
          {
            "name": "Type Code",
            "dataType": "string",
            "description": "SAP Source: CAWNT.ATWTB",
            "sourceColumn": "TypeCode",
            "displayFolder": "Classification"
          },
          {
            "name": "Created By",
            "dataType": "string",
            "description": "SAP Source: MARA.ERNAM",
            "sourceColumn": "CreatedBy",
            "displayFolder": "Master"
          },
          {
            "name": "Material Type Text",
            "dataType": "string",
            "description": "SAP Source: T134T.MTBEZ",
            "sourceColumn": "MaterialTypeText",
            "displayFolder": "Master"
          },
          {
            "name": "Created Date",
            "dataType": "dateTime",
            "description": "SAP Source: MARA.ERSDA",
            "sourceColumn": "CreatedDate",
            "formatString": "Short Date",
            "displayFolder": "Master",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Material Number Prefix",
            "dataType": "string",
            "description": "The next 2nd to 5th characters of the [Material Number]. Applies to those with FERT, HAWA, and HALB (coated only) material types",
            "sourceColumn": "MaterialNoPrefix",
            "displayFolder": "Other"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_MASTER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Center Names",
        "description": "List of cost centers in SAP with custom categories manually in a Sharepoint List",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Cost Center Name",
            "dataType": "string",
            "sourceColumn": "CostCenterName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "sortByColumn": "DepartmentSortKey"
          },
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Operations Category",
            "dataType": "string",
            "sourceColumn": "OperationsCategory"
          },
          {
            "name": "DepartmentSortKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DepartmentSortKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COST_CENTER_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_CENTER_NAMES\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_COST_CENTER_NAMES, \"DepartmentSortKey\", each if [Department] = \"COMP\" then 0",
                "else if [Department] = \"CAST\" then 1",
                "else if [Department] = \"PC\" then 2",
                "else if [Department] = \"COAT\" then 3",
                "else if [Department] = \"CONV\" then 4",
                "else 999)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Element Names",
        "description": "List of cost elements (G/L accounts) with custom categories and indicators manually assigned in a Sharepoint list",
        "columns": [
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Sub Category",
            "dataType": "string",
            "sourceColumn": "SubCategory",
            "sortByColumn": "CustomOrder"
          },
          {
            "name": "Category Renamed",
            "dataType": "string",
            "sourceColumn": "CatRenamed"
          },
          {
            "name": "Is Controllable Expense",
            "dataType": "boolean",
            "sourceColumn": "IsControllableExpense"
          },
          {
            "name": "Is Labor",
            "dataType": "boolean",
            "sourceColumn": "IsLabor"
          },
          {
            "name": "Is Supplies",
            "dataType": "boolean",
            "sourceColumn": "IsSupplies"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Cost Element Name",
            "dataType": "string",
            "sourceColumn": "CostElementName"
          },
          {
            "name": "CustomOrder",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomOrder"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COST_ELEMENT_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_ELEMENT_NAMES\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_COST_ELEMENT_NAMES, \"CustomOrder\", each if [SubCategory] = \"Labor\" then 1 else if [SubCategory] = \"Setup\" then 2 else if [SubCategory] = \"Overhead\" then 3 else 0, type number),",
                "    #\"Removed Errors\" = Table.RemoveRowsWithErrors(#\"Added Custom\", {\"SubCategory\"})",
                "in",
                "    #\"Removed Errors\""
              ]
            }
          }
        ]
      },
      {
        "name": "Plant",
        "description": "List of warehouse numbers in SAP (best used for filtering/grouping by plant across multiple fact tables)",
        "columns": [
          {
            "name": "Plant",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "PlantDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_PLANT = Source{[Schema=\"dbo\",Item=\"VW_PLANT\"]}[Data]",
                "in",
                "    dbo_VW_PLANT"
              ]
            }
          }
        ]
      },
      {
        "name": "Pending Specification Documents",
        "isHidden": true,
        "columns": [
          {
            "name": "Approver Name",
            "dataType": "string",
            "sourceColumn": "ApproverName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Pending Count",
            "dataType": "int64",
            "sourceColumn": "PendingCount",
            "formatString": "0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SPECAPPROVAL_PENDING = Source{[Schema=\"dbo\",Item=\"VW_SPECAPPROVAL_PENDING\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_SPECAPPROVAL_PENDING,{\"ApproverName\", \"Department\", \"PendingCount\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expenses",
        "description": "Controlling document line items posted in expenses related G/L accounts in the current and last fiscal year",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "CreateDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "sourceColumn": "DocumentDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "UserName"
          },
          {
            "name": "OffsetAcctNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctNoKey"
          },
          {
            "name": "OffsetAcctType",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctType"
          },
          {
            "name": "Document Number",
            "dataType": "string",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Document Line Number",
            "dataType": "string",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Referenced Document Line Number",
            "dataType": "string",
            "sourceColumn": "RefDocLineNo"
          },
          {
            "name": "Is Reversal Document",
            "dataType": "string",
            "sourceColumn": "IsRvrslDoc"
          },
          {
            "name": "Reversal Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RvrslRefDocNo"
          },
          {
            "name": "Is Reversed",
            "dataType": "string",
            "sourceColumn": "IsReversed"
          },
          {
            "name": "PurchaseDocLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseDocLineKey"
          },
          {
            "name": "Document Header Text",
            "dataType": "string",
            "sourceColumn": "DocHeaderText"
          },
          {
            "name": "Document Item Text",
            "dataType": "string",
            "sourceColumn": "ItemText"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "Expenses amount are in company currency while Open POs are already converted to USD",
            "sourceColumn": "Amount",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expense Type",
            "dataType": "string",
            "description": "Expense are line items posted by Accounting; Open PO are open purchase orders",
            "sourceColumn": "ExpenseType"
          },
          {
            "name": "Offset Account Name",
            "dataType": "string",
            "sourceColumn": "OffsetAcctName"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_EXPENSES = Source{[Schema=\"dbo\",Item=\"VW_EXPENSES\"]}[Data]",
                "in",
                "    dbo_VW_EXPENSES"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Orders",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.EBELN",
            "sourceColumn": "PurchaseOrderNoKey"
          },
          {
            "name": "Purchase Line Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.EBELN",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKKO.AEDAT",
            "sourceColumn": "DocumentDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "VendorNoKey",
            "dataType": "string",
            "description": "SAP Source: EKKO.LIFNR",
            "isHidden": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATKL",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: EKPO.TXZ01",
            "sourceColumn": "MaterialText"
          },
          {
            "name": "Req Track Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.BEDNR",
            "sourceColumn": "RequisitionTrackNo"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "description": "SAP Source: EKPO.NETPR",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: EKPO.MEINS",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: EKKO.BSART",
            "sourceColumn": "PurchaseDocType"
          },
          {
            "name": "Is Complete Delivery",
            "dataType": "string",
            "description": "SAP Source: EKPO.ELIKZ",
            "sourceColumn": "CompleteDeliverIndicator"
          },
          {
            "name": "Is Goods Receipt Required",
            "dataType": "string",
            "description": "SAP Source: EKPO.WEPOS",
            "sourceColumn": "GoodsReceiptIndicator"
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKET.SLFDT",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "MM/dd/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Issuing Plant",
            "dataType": "string",
            "description": "SAP Source: EKKO.RESWK",
            "sourceColumn": "IssuingPlantNo"
          },
          {
            "name": "Receiving Plant",
            "dataType": "string",
            "description": "SAP Source: EKPO.WERKS",
            "sourceColumn": "ReceivingPlantNo"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "description": "SAP Source: EKPO.MTART",
            "sourceColumn": "MaterialType"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: EKKO.WAERS",
            "sourceColumn": "Currency"
          },
          {
            "name": "Ordered Quantity",
            "dataType": "double",
            "description": "SAP Source: EKPO.MENGE",
            "sourceColumn": "OrderedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Ordered Amount",
            "dataType": "double",
            "description": "SAP Source: EKPO.NETWR",
            "sourceColumn": "OrderedAmount",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Open Quantity",
            "dataType": "double",
            "description": "Difference between the ordered and delivered quantity. SAP Source: EKPO.MENGE and EKET.WEMNG",
            "sourceColumn": "OpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "description": "Open quantity converted to amount based on unit price from ordered amount and quantity. SAP Source: EKPO.MENGE, EKET.WEMNG, and EKPO.NETWR",
            "sourceColumn": "OpenAmount",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Purchase Order Unit",
            "dataType": "string",
            "description": "SAP Source: EKPO.BPRME",
            "sourceColumn": "POUnitOfMeasure"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: EKKO.BUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "Goods Receipt Quantity",
            "dataType": "double",
            "sourceColumn": "GoodsReceiptQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Goods Receipt Amount",
            "dataType": "double",
            "sourceColumn": "GoodsReceiptAmount",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_PURCHASE_ORDERS = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE\"]}[Data]",
                "in",
                "    dbo_VW_PURCHASE_ORDERS"
              ]
            }
          }
        ]
      },
      {
        "name": "_Time Intelligence",
        "description": "The \"Time Calculation\" field allows multiple versions of a measure under \"DAX Measures\" (i.e. MTD, YTD, CD, PD, etc). This is best use on measures in \"DAX Measures\" that are not under the \"Time Intelligence\" folder.",
        "calculationGroup": {
          "description": "Used for analyzing measures in multiple time intelligence modes such as MTD, YTD, FYTD, etc.",
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Current",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 1
            },
            {
              "name": "MTD",
              "expression": [
                "CALCULATE(",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        DATESMTD( 'Calendar'[Date] )",
                "    ),",
                "    FILTER(",
                "        'Calendar',",
                "        'Calendar'[Date] <= [Report Date]",
                "    )",
                ")"
              ],
              "ordinal": 4
            },
            {
              "name": "YTD",
              "expression": [
                "CALCULATE(",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        DATESYTD('Calendar'[Date])",
                "    ),",
                "    FILTER(",
                "        'Calendar',",
                "        'Calendar'[Date] <= [Report Date]",
                "    )",
                ")"
              ],
              "ordinal": 7
            },
            {
              "name": "PY",
              "expression": "CALCULATE( SELECTEDMEASURE(), SAMEPERIODLASTYEAR('Calendar'[Date]) )",
              "ordinal": 13
            },
            {
              "name": "PY YTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"YTD\"",
                ")"
              ],
              "ordinal": 8
            },
            {
              "name": "PY MTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"MTD\"",
                ")"
              ],
              "ordinal": 5
            },
            {
              "name": "FYTD",
              "expression": [
                "CALCULATE(",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        DATESYTD('Calendar'[Date], \"09/30\")",
                "    ),",
                "    FILTER(",
                "        'Calendar',",
                "        'Calendar'[Date] <= [Report Date]",
                "    )",
                ")"
              ],
              "ordinal": 10
            },
            {
              "name": "PY FYTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"FYTD\"",
                ")"
              ],
              "ordinal": 11
            },
            {
              "name": "YOY",
              "expression": [
                "IF(",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        '_Time Intelligence'[Time Calculation] = \"PY\"",
                "    ),",
                "    SELECTEDMEASURE() - ",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        '_Time Intelligence'[Time Calculation] = \"PY\"",
                "    ),",
                "    BLANK()",
                ")"
              ],
              "ordinal": 14
            },
            {
              "name": "CD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    FILTER(",
                "        'Calendar',",
                "        'Calendar'[Date] <= [Last Working Day]",
                "            && 'Calendar'[Date] = LASTDATE( ALLSELECTED('Calendar'[Date]) )",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "PD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    PREVIOUSDAY( 'Calendar'[Date] )",
                ")"
              ],
              "ordinal": 3
            },
            {
              "name": "MTD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"MTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY MTD\"",
                ")"
              ],
              "ordinal": 6
            },
            {
              "name": "YTD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"YTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY YTD\"",
                ")"
              ],
              "ordinal": 9
            },
            {
              "name": "FTYD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"FYTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY FYTD\"",
                ")"
              ],
              "ordinal": 12
            }
          ]
        },
        "columns": [
          {
            "name": "Time Calculation",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "_Refresh Date",
        "columns": [
          {
            "name": "Report Name",
            "dataType": "string",
            "description": "Filter this column using a slicer with the name of this report/dashboard",
            "sourceColumn": "ReportNameKey"
          },
          {
            "name": "Refresh Date",
            "dataType": "dateTime",
            "sourceColumn": "ProcessDatetime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zPROCESSDATE_REPORTS = Source{[Schema=\"dbo\",Item=\"zPROCESSDATE_REPORTS\"]}[Data]",
                "in",
                "    dbo_zPROCESSDATE_REPORTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Target_Expenses",
        "isHidden": true,
        "columns": [
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "CostElementKey",
            "dataType": "string",
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "TargetValue",
            "dataType": "double",
            "sourceColumn": "TargetValue"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_EXPENSES = Source{[Schema=\"dbo\",Item=\"zTARGETS_EXPENSES\"]}[Data]",
                "in",
                "    dbo_zTARGETS_EXPENSES"
              ]
            }
          }
        ]
      },
      {
        "name": "_Expenses Mode",
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Actual",
              "expression": "[Expenses Amount]",
              "ordinal": 0
            },
            {
              "name": "PY",
              "expression": "CALCULATE( [Expenses Amount], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
              "ordinal": 1
            },
            {
              "name": "PY Var",
              "expression": [
                "VAR PreviousPeriod = CALCULATE( [Expenses Amount], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
                "RETURN",
                "    IF (",
                "        NOT ISBLANK( [Expenses Amount] )",
                "            && NOT ISBLANK( PreviousPeriod ),",
                "        [Expenses Amount] - PreviousPeriod",
                "    )"
              ],
              "ordinal": 2
            },
            {
              "name": "AOP",
              "expression": "[Expenses Plan]",
              "ordinal": 3
            },
            {
              "name": "AOP Var",
              "expression": [
                "IF (",
                "    NOT ISBLANK( [Expenses Amount] )",
                "        && NOT ISBLANK( [Expenses Plan] ),",
                "    [Expenses Amount] - [Expenses Plan]",
                ")"
              ],
              "ordinal": 4
            }
          ]
        },
        "columns": [
          {
            "name": "Mode",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Reason Code",
        "columns": [
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Reason Code Description",
            "dataType": "string",
            "sourceColumn": "ReasonCodeDescription"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Class",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Class"
          }
        ],
        "partitions": [
          {
            "name": "Partition - Copy",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(dbo_VW_REASON_CODE, {\"ReasonCodeKey\"})",
                "in",
                "    #\"Removed Duplicates\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"ARLPBI_STAGE\",",
                  "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data]",
                  "in",
                  "    dbo_VW_REASON_CODE</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Complaint Documents - Credited",
        "isHidden": true,
        "columns": [
          {
            "name": "ComplaintLineKey",
            "dataType": "string",
            "sourceColumn": "ComplaintLineKey"
          },
          {
            "name": "Credit Issued Date",
            "dataType": "dateTime",
            "sourceColumn": "CreditDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS_CREDITED = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS_CREDITED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS_CREDITED,{\"ComplaintLineKey\", \"CreditDateKey\", \"CreditIssueValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Target_KPI",
        "isHidden": true,
        "columns": [
          {
            "name": "KpiKey",
            "dataType": "string",
            "sourceColumn": "KpiKey"
          },
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "TargetValue",
            "dataType": "double",
            "sourceColumn": "TargetValue"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_KPI = Source{[Schema=\"dbo\",Item=\"zTARGETS_KPI\"]}[Data]",
                "in",
                "    dbo_zTARGETS_KPI"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Order Documents",
        "description": "SAP Source: VBAK, VBAP, VBUK, VBUP, VBUK, VBPA, VBEP, LIKP, LIPS, and KNMT; Granularity: One row per sales order document and line number; Contains general and status information about sales order documents.",
        "columns": [
          {
            "name": "OrderNoLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OrderNoLineKey"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "description": "SAP Source: VBAK.VBELN",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Order Line Number",
            "dataType": "string",
            "description": "SAP Source: VBAP.POSNR",
            "sourceColumn": "OrderLineNo"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "description": "SAP Source: VBAK.AUART",
            "sourceColumn": "OrderType"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "description": "SAP Source: VBAK.ERDAT",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "description": "SAP Source: VBEP.EDATU",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Last PGI Date",
            "dataType": "dateTime",
            "description": "SAP Source: LIKP.WADAT_IST; If the values is 12/31/9999, then there is no PGI date for the sales order item",
            "sourceColumn": "LastPgiDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "description": "SAP Source: VBAK.ERNAM",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Organization",
            "dataType": "string",
            "description": "SAP Source: VBAK.VKORG",
            "sourceColumn": "OrgNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: VBAP.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "CustomerNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: VBAP.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: VBAP.ARKTX",
            "sourceColumn": "MaterialText"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: VBAP.MATKL",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Credit Block",
            "dataType": "string",
            "description": "SAP Source: VBUP.CMGST",
            "sourceColumn": "CreditBlock"
          },
          {
            "name": "Route Type",
            "dataType": "string",
            "description": "SAP Source: VBAP.ROUTE",
            "sourceColumn": "RouteType"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: VBAP.MEINS",
            "sourceColumn": "OrderUoM"
          },
          {
            "name": "Order Quantity",
            "dataType": "double",
            "description": "SAP Source: VBAP.KWMENG",
            "sourceColumn": "OrderQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Currency",
            "dataType": "string",
            "description": "SAP Source: VBAP.WAERK",
            "sourceColumn": "OrderCurrency"
          },
          {
            "name": "Order Amount",
            "dataType": "double",
            "description": "SAP Source: VBAP.NETWR; Converted to USD using the exchange rate",
            "sourceColumn": "OrderAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Cost Amount",
            "dataType": "double",
            "description": "SAP Source: VBAP.WAVWR; Converted to USD using the exchange rate",
            "sourceColumn": "CostAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Billing Status",
            "dataType": "string",
            "description": "SAP Source: VBUP.FKSAA",
            "sourceColumn": "BillingStatBlock"
          },
          {
            "name": "Allocated Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued without an actual PGI date yet",
            "sourceColumn": "AllocatedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued with actual PGI date set",
            "sourceColumn": "ShippedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped On Time Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued with PGI date on or before the first schedule delivery date",
            "sourceColumn": "OnTimeShippedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Quantity",
            "dataType": "double",
            "description": "Order quantity minus allocated and shipped quantity",
            "sourceColumn": "InternalOpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Open Quantity",
            "dataType": "double",
            "description": "Order quantity minus shipped quantity",
            "sourceColumn": "CustomerOpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "description": "SAP Source: VBAP.NETPR",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "description": "SAP Source: VBAP.STCUR or VBKD.KURSK; Exchange rate to USD. Due to errors in some orders, this exchange is a calculated column. If the currency is USD, then the value is 1.0. Else if the currency is not USD but the exchange rate in the order is 1.0, use the VBKD.KURSK. Else, use VBAP.STCUR.",
            "sourceColumn": "ExchangeRate",
            "formatString": "0.0000"
          },
          {
            "name": "Cost Amount Local",
            "dataType": "double",
            "description": "SAP Source: WAVWR",
            "isHidden": true,
            "sourceColumn": "CostAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Amount Local",
            "dataType": "double",
            "description": "SAP Source: NETWR",
            "sourceColumn": "OrderAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Amount Local",
            "dataType": "double",
            "description": "Total value of internal open quantity",
            "sourceColumn": "InternalOpenAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Amount",
            "dataType": "double",
            "description": "Total value of internal open quantity",
            "sourceColumn": "InternalOpenAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Customer Open Amount Local",
            "dataType": "double",
            "sourceColumn": "CustomerOpenAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Open Amount",
            "dataType": "double",
            "sourceColumn": "CustomerOpenAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Margin Amount Local",
            "dataType": "double",
            "description": "Net of order and cost amount",
            "sourceColumn": "MarginAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin Amount",
            "dataType": "double",
            "description": "Net of order and cost amount",
            "sourceColumn": "MarginAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "External Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: VBEP.BSTKD",
            "sourceColumn": "ExtPurchaseOrderNo"
          },
          {
            "name": "Customer Material Number",
            "dataType": "string",
            "description": "SAP Source: KNMT.KDMAT",
            "sourceColumn": "CustomerMaterialNo"
          },
          {
            "name": "Ship To Name",
            "dataType": "string",
            "description": "SAP Source: ADRC.NAME1",
            "sourceColumn": "ShipToName"
          },
          {
            "name": "Ship To City",
            "dataType": "string",
            "description": "SAP Source: ADRC.CITY1",
            "sourceColumn": "ShipToCity"
          },
          {
            "name": "In Stock",
            "dataType": "int64",
            "description": "Applies to open orders only; Indicates if an item is available in stock (FIFO by first scheduled ship date)",
            "isHidden": true,
            "sourceColumn": "InStockIndicator"
          },
          {
            "name": "Has Changes (CS)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "HasChanges_CS"
          },
          {
            "name": "Customer Open Margin Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomerOpenMarginAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Customer Open Margin Amount (Local)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomerOpenMarginAmount",
            "formatString": "#,0"
          },
          {
            "name": "Tier",
            "dataType": "string",
            "description": "SAP Source: MARC.MAABC",
            "sourceColumn": "TierCode"
          },
          {
            "name": "Processing Status",
            "dataType": "string",
            "sourceColumn": "ProcessingBlock"
          },
          {
            "name": "Allocated Amount Local",
            "dataType": "double",
            "sourceColumn": "AllocatedAmount",
            "formatString": "#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Allocated Amount",
            "dataType": "double",
            "sourceColumn": "AllocatedAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Shipped Amount Local",
            "dataType": "double",
            "sourceColumn": "ShippedAmount",
            "formatString": "#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped Amount",
            "dataType": "double",
            "sourceColumn": "ShippedAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sample Category",
            "dataType": "string",
            "description": "Calculated column: If the order type is 'KL', then 'Full Rolls'. Else if the order type is 'ZSMP' and order reason is 'Tradeshow Requests' then 'Tradeshow'. Else if order type is 'ZSMP' and material group is 'MARKETG', then 'Literature'. Else if order type is 'ZSMP' and not a tradeshow nor literature, then 'Samples'. Otherwise, 'Not Applicable'.",
            "sourceColumn": "FOCCategory"
          },
          {
            "name": "MaterialPlantKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialPlantKey"
          },
          {
            "name": "Weight Unit",
            "dataType": "string",
            "sourceColumn": "WeightUoM"
          },
          {
            "name": "Gross Weight",
            "dataType": "double",
            "sourceColumn": "GrossWeight",
            "formatString": "#,0.00"
          },
          {
            "name": "Shipped Weight",
            "dataType": "double",
            "sourceColumn": "ShippedWeight",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Customer Open Weight",
            "dataType": "double",
            "sourceColumn": "CustomerOpenWeight",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: VBFA.VBELN",
            "sourceColumn": "PurchaseOrderNo"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: VBFA.POSNN",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "Late Indicator",
            "dataType": "int64",
            "sourceColumn": "LateIndicator",
            "formatString": "#,0"
          },
          {
            "name": "Reason for Late Shipment",
            "dataType": "string",
            "sourceColumn": "LateReasonText"
          },
          {
            "name": "Reason Type for Late Shipment",
            "dataType": "string",
            "sourceColumn": "LateReasonType"
          },
          {
            "name": "Late Exclude Indicator",
            "dataType": "string",
            "description": "Value is 'X' if this line is indicated to be excluded in On Time Shipping metrics.",
            "sourceColumn": "LateExcludeIndicator"
          },
          {
            "name": "Late Quantity",
            "dataType": "double",
            "description": "Difference between [Order Quantity] and [Shipped On Time Quantity]",
            "sourceColumn": "LateQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_ORDER_SALES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_SALES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_SALES"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Region",
        "columns": [
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesDistrictKey"
          },
          {
            "name": "Sales Region Name",
            "dataType": "string",
            "sourceColumn": "SalesDistrictName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES_REGION = Source{[Schema=\"dbo\",Item=\"VW_SALES_REGION\"]}[Data]",
                "in",
                "    dbo_VW_SALES_REGION"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Territory",
        "columns": [
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "Sales Territory Name",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES_TERRITORY = Source{[Schema=\"dbo\",Item=\"VW_SALES_TERRITORY\"]}[Data]",
                "in",
                "    dbo_VW_SALES_TERRITORY"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_Territory",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_TERRITORY = Source{[Schema=\"dbo\",Item=\"VW_RLS_TERRITORY\"]}[Data]",
                "in",
                "    dbo_VW_RLS_TERRITORY"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_Region",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesRegionKey",
            "dataType": "string",
            "sourceColumn": "SalesRegionKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_REGION = Source{[Schema=\"dbo\",Item=\"VW_RLS_REGION\"]}[Data]",
                "in",
                "    dbo_VW_RLS_REGION"
              ]
            }
          }
        ]
      },
      {
        "name": "Target_Sales",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "GrossSales",
            "dataType": "double",
            "sourceColumn": "GrossSales",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "GrossMarginMTD",
            "dataType": "double",
            "sourceColumn": "GrossMarginMTD",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "GrossMarginYTD",
            "dataType": "double",
            "sourceColumn": "GrossMarginYTD",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_SALES = Source{[Schema=\"dbo\",Item=\"zTARGETS_SALES\"]}[Data]",
                "in",
                "    dbo_zTARGETS_SALES"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_CostCenter",
        "isHidden": true,
        "columns": [
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_COSTCENTER = Source{[Schema=\"dbo\",Item=\"VW_RLS_COSTCENTER\"]}[Data]",
                "in",
                "    dbo_VW_RLS_COSTCENTER"
              ]
            }
          }
        ]
      },
      {
        "name": "_Currency to Use",
        "description": "This table is mainly used as a slicer to dynamically switch the calculation of measures from USD to local currency. Not all measures are applicable.",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Currency",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " { \"USD\", \"Local\" }"
            }
          }
        ]
      },
      {
        "name": "Stock Transfer Orders",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.EBELN",
            "sourceColumn": "PurchaseOrderNoKey"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.EBELP",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "description": "SAP Source: MBEW.BKLAS; This field is not directly related to the '_Valuation Class' table",
            "isHidden": true,
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Delivered Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.MENGE; Criteria: EKBE.BEWTP = 'U'",
            "sourceColumn": "DeliveredQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Goods Receipt Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.MENGE; Criteria: EKBE.BEWTP = 'E'",
            "sourceColumn": "GoodsReceiptQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "In Transit Quantity",
            "dataType": "double",
            "description": "Net of delivered and goods receipt",
            "sourceColumn": "InTransitQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Delivered Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.WRBTR; Criteria: EKBE.BEWTP = 'U'",
            "sourceColumn": "DeliveredAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "Goods Receipt Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.WRBTR; Criteria: EKBE.BEWTP = 'E'",
            "sourceColumn": "GoodsReceiptAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "In Transit Amount",
            "dataType": "double",
            "description": "Net of delivered and goods receipt",
            "sourceColumn": "InTransitAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.XBLNR",
            "sourceColumn": "ReferencedDocumentNo"
          },
          {
            "name": "Shipment Document Number",
            "dataType": "string",
            "description": "SAP Source: VTTP.TPNUM",
            "sourceColumn": "ShipmentDocumentNo"
          },
          {
            "name": "Shipment Document Line Number",
            "dataType": "string",
            "description": "SAP Source: VTTP.TKNUM",
            "sourceColumn": "ShipmentLineNo"
          },
          {
            "name": "ValuationClassKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ValuationClassKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_INTRANSIT = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_INTRANSIT\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_INTRANSIT"
              ]
            }
          }
        ]
      },
      {
        "name": "Goods and Invoice Receipts",
        "description": "; Granularity: One row per account document and line number",
        "columns": [
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "G/L Account",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.HKONT",
            "sourceColumn": "GeneralLedgerAcctNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.WERKS",
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Cost Center",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.KOSTL",
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Accounting Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BELNR",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Accounting Document Line Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUZEI",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BLART",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BLDAT",
            "sourceColumn": "DocumentDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.MONAT",
            "sourceColumn": "FiscalPeriod"
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.GJAHR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "First GR Year",
            "dataType": "string",
            "description": "First year of posted goods receipt based on assignment number",
            "sourceColumn": "FirstGRYear"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: ACCTIT.ERFMG",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.ERFME",
            "sourceColumn": "UnitOfMeasure",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Amount (Document)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.WRBTR",
            "sourceColumn": "AmountInDocCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Document Currency",
            "dataType": "string",
            "description": "SAP Source: BKPF.WAERS",
            "sourceColumn": "DocCurrency",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount (Local)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBTR",
            "sourceColumn": "AmountInLocalCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAER",
            "sourceColumn": "LocalCurrency",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount (Local2)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBE2",
            "sourceColumn": "AmountInLocalCurrency2",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency 2",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAE2",
            "sourceColumn": "LocalCurrency2",
            "displayFolder": "_Values"
          },
          {
            "name": "Clearing Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.AUGDT",
            "sourceColumn": "ClearingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Clearing Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.AUGBL",
            "sourceColumn": "ClearingDocNo"
          },
          {
            "name": "Assignment Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.ZUONR",
            "sourceColumn": "AssignmentNo"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELN",
            "sourceColumn": "PurchaseOrderNo"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELP",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.AUFNR",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.XBLNR",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Item Text",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.SGTXT",
            "sourceColumn": "ItemText"
          },
          {
            "name": "Vendor Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.LIFNR",
            "isHidden": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.KUNNR",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "PostingRank",
            "dataType": "int64",
            "sourceColumn": "PostingRank"
          },
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_GOODS_AND_INVOICE_RECEIPTS = Source{[Schema=\"dbo\",Item=\"VW_GOODS_AND_INVOICE_RECEIPTS\"]}[Data]",
                "in",
                "    dbo_VW_GOODS_AND_INVOICE_RECEIPTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Vendor Master",
        "description": "SAP Source: LFA1",
        "columns": [
          {
            "name": "Vendor Number",
            "dataType": "string",
            "description": "SAP Source: LFA1.LIFNR",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Vendor Name",
            "dataType": "string",
            "description": "SAP Source: LFA1.NAME1",
            "sourceColumn": "VendorName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_VENDOR_MASTER = Source{[Schema=\"dbo\",Item=\"VW_VENDOR_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_VENDOR_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Order Invoices",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Material Document Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.BELNR",
            "sourceColumn": "MaterialDocNo"
          },
          {
            "name": "Material Document Line Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.BUZEI",
            "sourceColumn": "MaterialLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKBE.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "PostingRank",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PostingRank"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.BPMNG; Value is in purchase order unit (see 'Purchase Orders' table)",
            "sourceColumn": "InvoiceQty",
            "formatString": "#,0.00"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: EKBE.WAERS",
            "sourceColumn": "InvoiceCurrency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.REEWR",
            "sourceColumn": "InvoiceValue",
            "formatString": "#,0.00"
          },
          {
            "name": "Amount at Last PY Price",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceValue_LastPYPrice"
          },
          {
            "name": "Last PY Quantity",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LastInvoiceQty_PY"
          },
          {
            "name": "Last PY Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LastInvoiceValue_PY",
            "formatString": "#,0.00"
          },
          {
            "name": "Price Difference",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "PriceDifference",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_PURCHASE_INVOICES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE_INVOICES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_PURCHASE_INVOICES"
              ]
            }
          }
        ]
      },
      {
        "name": "Absorption",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Business Transaction Type",
            "dataType": "string",
            "sourceColumn": "BusTransType"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "AmountValue",
            "formatString": "0.00"
          },
          {
            "name": "HighestBomKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "HighestBomKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_ABSORPTION\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "SAP Users",
        "description": "SAP Source: USR21 and ADCP",
        "isHidden": true,
        "columns": [
          {
            "name": "UsernameKey",
            "dataType": "string",
            "description": "SAP Source: USR21.BNAME",
            "sourceColumn": "UsernameKey"
          },
          {
            "name": "Department",
            "dataType": "string",
            "description": "SAP Source: ADCP.DEPARTMENT",
            "sourceColumn": "Department"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_USERS_SAP = Source{[Schema=\"dbo\",Item=\"VW_USERS_SAP\"]}[Data]",
                "in",
                "    dbo_VW_USERS_SAP"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Order Document Changes",
        "description": "SAP Source: CDHDR; Granularity: Multiple rows per sales order document number",
        "columns": [
          {
            "name": "OrderNoKey",
            "dataType": "string",
            "description": "SAP Source: CDHDR.OBJECTID",
            "isHidden": true,
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Changed By",
            "dataType": "string",
            "description": "SAP Source: CDHDR.USERNAME",
            "sourceColumn": "ChangedBy"
          },
          {
            "name": "Change Date",
            "dataType": "dateTime",
            "description": "SAP Source: CDHDR.UDATE",
            "sourceColumn": "ChangedDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Change Time",
            "dataType": "dateTime",
            "description": "SAP Source: CDHDR.UTIME",
            "sourceColumn": "ChangedTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_SALES_CHANGES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_SALES_CHANGES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_SALES_CHANGES"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Orders - Deliveries",
        "isHidden": true,
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Open Quantity",
            "dataType": "double",
            "sourceColumn": "OpenQuantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenAmount",
            "formatString": "#,0.00"
          },
          {
            "name": "Goods Receipt Quantity",
            "dataType": "double",
            "sourceColumn": "GoodsReceiptQuantity",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Goods Receipt Amount",
            "dataType": "double",
            "sourceColumn": "GoodsReceiptAmount",
            "formatString": "0.00",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_PURCHASE_DELIVERIES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE_DELIVERIES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_PURCHASE_DELIVERIES"
              ]
            }
          }
        ]
      },
      {
        "name": "Backorder Snapshots",
        "description": "A daily snapshot (near midnight) of backordered sales orders; Each value is the daily closing backorder value per plant and material number.",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Incoming Amount",
            "dataType": "double",
            "sourceColumn": "IncomingAmt",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Outgoing Amount",
            "dataType": "double",
            "sourceColumn": "OutgoingAmt",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Unrestricted Stock Amount",
            "dataType": "double",
            "sourceColumn": "UnrestrictStockAmt",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Remaining by Month End Transit Stock Amount",
            "dataType": "double",
            "sourceColumn": "TransitStockEOMAmt",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Incoming Quantity",
            "dataType": "double",
            "sourceColumn": "IncomingQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Outgoing Quantity",
            "dataType": "double",
            "sourceColumn": "OutgoingQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Unrestricted Stock Quantity",
            "dataType": "double",
            "sourceColumn": "UnrestrictStockQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Remaining by Month End Transit Stock Quantity",
            "dataType": "double",
            "sourceColumn": "TransitStockEOMQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Shortage Amount",
            "dataType": "double",
            "sourceColumn": "ShortageAmt",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Shortage Quantity",
            "dataType": "double",
            "sourceColumn": "ShortageQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zDAILY_BACKORDER = Source{[Schema=\"dbo\",Item=\"zDAILY_BACKORDER\"]}[Data]",
                "in",
                "    dbo_zDAILY_BACKORDER"
              ]
            }
          }
        ]
      },
      {
        "name": "Converting Man Hours",
        "columns": [
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date starts at 6am and ends at 5:59am the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Shift",
            "dataType": "string",
            "sourceColumn": "Shift",
            "summarizeBy": "none"
          },
          {
            "name": "Production Hours",
            "dataType": "double",
            "description": "The number of hours across all converting employees when they are producing material",
            "sourceColumn": "ProductionHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Non Production Hours",
            "dataType": "double",
            "description": "The total number of hours across all converting employees when they are doing trainings, FEs, and other non-production activities",
            "sourceColumn": "NonProductionHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Available Hours",
            "dataType": "double",
            "description": "The total number of hours converting is scheduled to work within a shift (excluding breaks and lunch)",
            "sourceColumn": "AvailableHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Notes",
            "dataType": "string",
            "sourceColumn": "Notes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_CONV_HOURS\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "Converting Uptime",
        "columns": [
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date starts at 6am and ends at 5:59am the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Machine Name",
            "dataType": "string",
            "sourceColumn": "MachineName"
          },
          {
            "name": "Uptime Seconds",
            "dataType": "int64",
            "sourceColumn": "UptimeSeconds"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_CONV_UPTIME = Source{[Schema=\"dbo\",Item=\"VW_CONV_UPTIME\"]}[Data]",
                "in",
                "    dbo_VW_CONV_UPTIME"
              ]
            }
          }
        ]
      },
      {
        "name": "Upstream Logs - Raw",
        "description": "Similar to machine log queries that includes job data and primary structure tables",
        "columns": [
          {
            "name": "Machine Name",
            "dataType": "string",
            "description": "Calculated column derived from the name of the database",
            "sourceColumn": "Machine"
          },
          {
            "name": "Job Index",
            "dataType": "int64",
            "description": "Source: jobindex.JobIndex",
            "sourceColumn": "JobIndex",
            "summarizeBy": "none"
          },
          {
            "name": "Start Time",
            "dataType": "dateTime",
            "description": "Source: jobdata.Date_Time",
            "sourceColumn": "StartTime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Stop Time",
            "dataType": "dateTime",
            "description": "Source: jobdata.Date_Time",
            "sourceColumn": "StopTime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Footage",
            "dataType": "int64",
            "description": "Source: jobdata.LastRollFt",
            "sourceColumn": "Footage",
            "formatString": "#,0",
            "summarizeBy": "sum"
          },
          {
            "name": "Ideal Footage",
            "dataType": "int64",
            "description": "Calculated column derived from the duration between 'Start Time' and 'Stop Time' and primarystruct.SpecLS",
            "sourceColumn": "IdealFootage",
            "formatString": "#,0",
            "summarizeBy": "sum"
          },
          {
            "name": "Category",
            "dataType": "string",
            "description": "Source: primarystruct.Category",
            "sourceColumn": "Category"
          },
          {
            "name": "Causes",
            "dataType": "string",
            "description": "Source: primarystruct.Causes",
            "sourceColumn": "Causes"
          },
          {
            "name": "Further Detail",
            "dataType": "string",
            "description": "Source: primarystruct.FurtherDetail",
            "sourceColumn": "FurtherDetail"
          },
          {
            "name": "Comments",
            "dataType": "string",
            "description": "Source: primarystruct.Comments",
            "sourceColumn": "Comments"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "Source: primarystruct.ProcessOrder",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Specification Number",
            "dataType": "string",
            "description": "Source: primarystruct.Spec",
            "sourceColumn": "SpecNo"
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date of the 'Start Time'; A production day is between 6:00AM and 5:59:59AM the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Production Shift",
            "dataType": "int64",
            "description": "Production shift of 'Start Time' where 1st shift is 6AM-2PM, 2nd shift is 2PM-10PM, and 3rd shift is 10PM-6AM next day",
            "sourceColumn": "ShiftNum"
          },
          {
            "name": "Specification Linespeed",
            "dataType": "int64",
            "description": "Source: primarystruct.SpecLS",
            "sourceColumn": "SpecLinespeed",
            "formatString": "#,0",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Linespeed",
            "dataType": "int64",
            "description": "Calculated column derived from the duration between 'Start Time' and 'Stop Time' in minutes and 'Footage'",
            "sourceColumn": "ActualLinespeed"
          },
          {
            "name": "Duration Minutes",
            "dataType": "double",
            "description": "Duration between [Start Time] and [Stop Time] in minutes",
            "sourceColumn": "DurationMinutes",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_UPSTREAM_LOG_RAW = Source{[Schema=\"dbo\",Item=\"VW_UPSTREAM_LOG_RAW\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(dbo_VW_UPSTREAM_LOG_RAW,{{\"Machine\", Order.Ascending}, {\"StartTime\", Order.Ascending}, {\"StopTime\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "Upstream Logs - Simplified",
        "description": "Similar to 'Upstream Logs - Raw' except Production/Downtime records are split if the record occurs in between different shifts or calendar day. Also, consecutively similar clean up records (by category, causes, further detail/comments, and PO) are combined",
        "columns": [
          {
            "name": "Machine Name",
            "dataType": "string",
            "description": "Calculated column derived from the name of the database",
            "sourceColumn": "Machine"
          },
          {
            "name": "Start Time",
            "dataType": "dateTime",
            "description": "Source: jobdata.Date_Time",
            "sourceColumn": "StartTime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Stop Time",
            "dataType": "dateTime",
            "description": "Source: jobdata.Date_Time",
            "sourceColumn": "StopTime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Duration Minutes",
            "dataType": "double",
            "description": "Duration between 'Start Time' and 'Stop Time' in minutes",
            "sourceColumn": "DurationMinute",
            "formatString": "#,0.00"
          },
          {
            "name": "Footage",
            "dataType": "int64",
            "description": "Source: jobdata.LastRollFt",
            "sourceColumn": "Footage",
            "formatString": "#,0"
          },
          {
            "name": "Ideal Footage",
            "dataType": "int64",
            "description": "Calculated column derived from the duration between 'Start Time' and 'Stop Time' and primarystruct.SpecLS",
            "sourceColumn": "IdealFootage",
            "formatString": "#,0"
          },
          {
            "name": "Scrap Footage",
            "dataType": "int64",
            "description": "Total footage of caliper or setup scrap during clean ups",
            "sourceColumn": "ScrapFootage",
            "formatString": "#,0"
          },
          {
            "name": "Category",
            "dataType": "string",
            "description": "Source: primarystruct.Category",
            "sourceColumn": "Category"
          },
          {
            "name": "Causes",
            "dataType": "string",
            "description": "Source: primarystruct.Causes",
            "sourceColumn": "Causes"
          },
          {
            "name": "Further Detail",
            "dataType": "string",
            "description": "Source: primarystruct.FurtherDetail",
            "sourceColumn": "FurtherDetail"
          },
          {
            "name": "Comments",
            "dataType": "string",
            "description": "Source: primarystruct.Comments",
            "sourceColumn": "Comments"
          },
          {
            "name": "Non Uptime Reason",
            "dataType": "string",
            "description": "Calculated column derived from 'Further Detail' and 'Comments' of non-production records; Used for grouping big hitters of availability",
            "sourceColumn": "NonUptimeReason"
          },
          {
            "name": "Efficiency Hitter",
            "dataType": "string",
            "description": "Calculated column derived from 'Further Detail', 'Comments', and 'Specification Number'; Used for grouping big hitters of overall equipment efficiency",
            "sourceColumn": "EfficiencyHitter"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Specification Number",
            "dataType": "string",
            "description": "Source: primarystruct.Spec",
            "sourceColumn": "SpecNo"
          },
          {
            "name": "Is Transition",
            "dataType": "boolean",
            "description": "A record is transition if it is end of production, downtime, unplanned clean up, or planned clean ups that occur before/after the previous types of records mentioned",
            "sourceColumn": "IsTransition"
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date of the 'Start Time'; A production day is between 6:00AM and 5:59:59AM the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Production Shift",
            "dataType": "int64",
            "description": "Production shift of 'Start Time' where 1st shift is 6AM-2PM, 2nd shift is 2PM-10PM, and 3rd shift is 10PM-6AM next day",
            "sourceColumn": "ShiftNum"
          },
          {
            "name": "Specification Linespeed",
            "dataType": "int64",
            "description": "Source: primarystruct.SpecLS",
            "sourceColumn": "SpecLinespeed",
            "formatString": "#,0",
            "summarizeBy": "none"
          },
          {
            "name": "Actual Linespeed",
            "dataType": "int64",
            "description": "Calculated column derived from the duration between 'Start Time' and 'Stop Time' in minutes and 'Footage'",
            "sourceColumn": "ActualLinespeed"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_UPSTREAM_LOG_SIMPLIFIED = Source{[Schema=\"dbo\",Item=\"VW_UPSTREAM_LOG_SIMPLIFIED\"]}[Data],",
                "    #\"Sorted Rows\" = Table.Sort(dbo_VW_UPSTREAM_LOG_SIMPLIFIED,{{\"Machine\", Order.Ascending}, {\"StartTime\", Order.Ascending}, {\"StopTime\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "_Machines",
        "description": "Contains machine names used to filter related tables with 'Machine Name' fields",
        "columns": [
          {
            "name": "Machine Name",
            "dataType": "string",
            "sourceColumn": "MachineName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zMACHINE = Source{[Schema=\"dbo\",Item=\"zMACHINE\"]}[Data]",
                "in",
                "    dbo_zMACHINE"
              ]
            }
          }
        ]
      },
      {
        "name": "_Production Shifts",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Production Shift",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value1]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Shift Name",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value2]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{ (\"1\", \"1st\"), (\"2\", \"2nd\"), (\"3\", \"3rd\") }"
            }
          }
        ]
      },
      {
        "name": "Current Inventory",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: MARD.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: MARD.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Unrestricted Stock Quantity",
            "dataType": "double",
            "description": "SAP Source: MARD.LABST",
            "sourceColumn": "UnrestrictStockQty",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Safety Stock Quantity",
            "dataType": "double",
            "description": "SAP Source: MARC.EISBE",
            "sourceColumn": "SafetyStockQty",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Tier Code",
            "dataType": "string",
            "description": "SAP Source: MARC.MAABC",
            "sourceColumn": "TierCode"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: MCHB.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Expiration Date",
            "dataType": "dateTime",
            "description": "SAP Source: MCH1.VFDAT",
            "sourceColumn": "ExpirationDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Inspection Stock Quantity",
            "dataType": "double",
            "description": "SAP Source: MCHB.CINSM",
            "sourceColumn": "InspectionStockQty",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Blocked Stock Quantity",
            "dataType": "double",
            "description": "SAP Source: MCHB.CSPEM",
            "sourceColumn": "BlockedStockQty",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "MaterialPlantKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialPlantKey"
          },
          {
            "name": "Standard Price",
            "dataType": "double",
            "description": "SAP Source: MBEW.STPRS and MBEW.PEINH; This is a calculated field (MBEW.STPRS / MBEW.PEINH)",
            "sourceColumn": "StandardPrice",
            "formatString": "#,0.00",
            "summarizeBy": "none"
          },
          {
            "name": "Unrestricted Stock Amount (USD)",
            "dataType": "double",
            "sourceColumn": "UnrestrictStockAmtUSD",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Inspection Stock Amount (USD)",
            "dataType": "double",
            "sourceColumn": "InspectionStockAmtUSD",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Blocked Stock Amount (USD)",
            "dataType": "double",
            "sourceColumn": "BlockedStockAmtUSD",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Standard Price (USD)",
            "dataType": "double",
            "description": "SAP Source: MBEW.STPRS and MBEW.PEINH; This is a calculated field (MBEW.STPRS / MBEW.PEINH * Today's exchange rate)",
            "sourceColumn": "StandardPriceUSD",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "none"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "description": "SAP Source: MBEW.BKLAS",
            "sourceColumn": "ValuationClass"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_INVENTORY_CURRENT = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_CURRENT\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_INVENTORY_CURRENT,{{\"ExpirationDate\", type date}}),",
                "    #\"Sorted Rows\" = Table.Sort(#\"Changed Type\",{{\"MaterialPlantKey\", Order.Ascending}})",
                "in",
                "    #\"Sorted Rows\""
              ]
            }
          }
        ]
      },
      {
        "name": "Support_MthlyConsume",
        "isHidden": true,
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "ConsumptionQty",
            "dataType": "double",
            "sourceColumn": "ConsumptionQty",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_MATERIAL_CONSUME_MTHLY = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_CONSUME_MTHLY\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_CONSUME_MTHLY"
              ]
            }
          }
        ]
      },
      {
        "name": "Target_Absorption",
        "isHidden": true,
        "columns": [
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "ForecastType",
            "dataType": "string",
            "sourceColumn": "ForecastType"
          },
          {
            "name": "Labor",
            "dataType": "double",
            "sourceColumn": "Labor",
            "formatString": "#,0.00"
          },
          {
            "name": "Overhead",
            "dataType": "double",
            "sourceColumn": "Overhead",
            "formatString": "#,0.00"
          },
          {
            "name": "RawMaterial",
            "dataType": "double",
            "sourceColumn": "RawMaterial",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TARGETS_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_TARGETS_ABSORPTION\"]}[Data]",
                "in",
                "    dbo_VW_TARGETS_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "_Valuation Class",
        "description": "SAP Source: T025T. Contains valuation class mainly used for categorizing inventory",
        "columns": [
          {
            "name": "Valuation Class",
            "dataType": "string",
            "description": "SAP Source: T025T.BKLAS",
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Description",
            "dataType": "string",
            "description": "SAP Source: T025T.BKBEZ",
            "sourceColumn": "DescriptionText"
          },
          {
            "name": "Rename",
            "dataType": "string",
            "description": "Custom value to rename the description of valuation class",
            "sourceColumn": "RenameText",
            "sortByColumn": "SortKey"
          },
          {
            "name": "SortKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SortKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_VALUATION_CLASS = Source{[Schema=\"dbo\",Item=\"VW_VALUATION_CLASS\"]}[Data]",
                "in",
                "    dbo_VW_VALUATION_CLASS"
              ]
            }
          }
        ]
      },
      {
        "name": "Open WIP",
        "columns": [
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "ValuationClassKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ValuationClassKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Net Cost Amount",
            "dataType": "double",
            "sourceColumn": "NetCostVal",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_INVENTORY_OPENWIP = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_OPENWIP\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_OPENWIP"
              ]
            }
          }
        ]
      },
      {
        "name": "Current Inventory Snapshots",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "AmountUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zDAILY_INVENTORY = Source{[Schema=\"dbo\",Item=\"zDAILY_INVENTORY\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_zDAILY_INVENTORY,{{\"SnapshotDateKey\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Shop Orders",
        "description": "Contains general information of all process orders. Related to 'Calendar' table via [End Date Key]",
        "columns": [
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: AFKO.AUFNR",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Item Number",
            "dataType": "string",
            "description": "SAP Source: AFPO.POSNR",
            "sourceColumn": "ItemNo"
          },
          {
            "name": "Cost Center",
            "dataType": "string",
            "description": "SAP Source: CRCO.KOSTL",
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Work Center",
            "dataType": "string",
            "description": "SAP Source: CRHD.ARBPL or AFVC.KTSCH",
            "sourceColumn": "WorkCenterKey"
          },
          {
            "name": "Deliver Indicator",
            "dataType": "string",
            "description": "SAP Source: AFPO.ELIKZ",
            "sourceColumn": "DeliverIndicator"
          },
          {
            "name": "Final Deliver Indicator",
            "dataType": "string",
            "description": "SAP Source: AFPO.WEPOS",
            "sourceColumn": "FinalDeliverIndicator"
          },
          {
            "name": "Same Day Indicator",
            "dataType": "string",
            "description": "Calculated column. Value is 'X' if the order comment contains 'SAMEDAY' or 'SAME-DAY'.",
            "sourceColumn": "SameDayIndicator"
          },
          {
            "name": "Comment",
            "dataType": "string",
            "description": "SAP Source: AFPO.ABLAD",
            "sourceColumn": "OrderComment"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: AFKO.PLNBEZ",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Document Group",
            "dataType": "string",
            "description": "SAP Source: AFKO.PLNNR",
            "sourceColumn": "DocGroup"
          },
          {
            "name": "Basic Start Date",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GSTRP",
            "sourceColumn": "StartDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Basic Start Time",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GSUZP",
            "sourceColumn": "StartTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Basic End Date",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GLTRP",
            "sourceColumn": "EndDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Basic End Time",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GLUZP",
            "sourceColumn": "EndTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Actual Start Date",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GSTRI",
            "sourceColumn": "ActualStartDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Actual Start Time",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GSUZI",
            "sourceColumn": "ActualStartTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Actual End Date",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GLTRI or AFPO.LTRMI",
            "sourceColumn": "ActualEndDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Actual End Time",
            "dataType": "dateTime",
            "description": "SAP Source: AFKO.GEUZI",
            "sourceColumn": "ActualEndTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Confirm Date",
            "dataType": "dateTime",
            "description": "SAP Source: AFPO.LTRMI",
            "sourceColumn": "ConfirmDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: AFKO.GMEIN",
            "sourceColumn": "QtyUoM"
          },
          {
            "name": "Order Quantity",
            "dataType": "double",
            "description": "SAP Source: AFKO.GAMNG",
            "sourceColumn": "OrderQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Delivered Quantity",
            "dataType": "double",
            "description": "SAP Source: AFPO.WEMNG",
            "sourceColumn": "DeliverQty",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "End Date Key",
            "dataType": "dateTime",
            "description": "Calculated column; If Actual End Date is available, use it. Otherwise, use the Basic End Date. Related to 'Calendar'[Date]",
            "sourceColumn": "EndDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Notification Number",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              "CALCULATE(",
              "    FIRSTNONBLANK( 'Hold Tag Documents'[Notification Number], TRUE() ),",
              "    FILTER(",
              "        'Hold Tag Documents',",
              "        'Hold Tag Documents'[Process Order Number] = 'Shop Orders'[Process Order Number]",
              "    )",
              ")",
              ""
            ]
          },
          {
            "name": "Close Indicator",
            "dataType": "string",
            "description": "Calculated column; Value is 'X' if the order has TECO, CLSD, or DLFL status. ",
            "sourceColumn": "CloseIndicator"
          },
          {
            "name": "Department",
            "dataType": "string",
            "description": "Custom value assigned per work center",
            "sourceColumn": "Department"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_PROCESS = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PROCESS\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_PROCESS"
              ]
            }
          }
        ]
      },
      {
        "name": "Upstream Schedule",
        "columns": [
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Remake Code",
            "dataType": "string",
            "sourceColumn": "RemakeCode"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNo"
          },
          {
            "name": "Machine Name",
            "dataType": "string",
            "sourceColumn": "Machine"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Publish Date",
            "dataType": "dateTime",
            "sourceColumn": "PublishDate",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Processing Hour",
            "dataType": "double",
            "sourceColumn": "ProcessingHour",
            "formatString": "#,0.000"
          },
          {
            "name": "Plan Finish Date",
            "dataType": "dateTime",
            "sourceColumn": "PlanFinishDate",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Plan Production Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "PlanProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Target Quantity",
            "dataType": "int64",
            "sourceColumn": "TargetQuantity",
            "formatString": "#,0"
          },
          {
            "name": "Adhesive Quantity",
            "dataType": "int64",
            "sourceColumn": "AdhesiveQuantity",
            "formatString": "#,0"
          },
          {
            "name": "Remake Code Text",
            "dataType": "string",
            "sourceColumn": "RemakeCodeText"
          },
          {
            "name": "Plan Start Date",
            "dataType": "dateTime",
            "sourceColumn": "PlanStartDate",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Ranking Desc",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "RankingDesc"
          },
          {
            "name": "PlanFinishDateAltKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "PlanFinishDateAltKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_UPSTREAM_SCHEDULE = Source{[Schema=\"dbo\",Item=\"VW_UPSTREAM_SCHEDULE\"]}[Data]",
                "in",
                "    dbo_VW_UPSTREAM_SCHEDULE"
              ]
            }
          }
        ]
      },
      {
        "name": "Machine Status - Prep",
        "isHidden": true,
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Machine Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Upstream Logs - Raw[Machine Name]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Process Order Number",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Upstream Logs - Raw[Process Order Number]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Start",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "isHidden": true,
            "sourceColumn": "[Plan Start]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Start",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "isHidden": true,
            "sourceColumn": "[Actual Start]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Stop",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "isHidden": true,
            "sourceColumn": "[Plan Stop]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Stop",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": false,
            "isHidden": true,
            "sourceColumn": "[Actual Stop]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Ft",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Plan Ft]",
            "formatString": "#,0"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Ft",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Actual Ft]",
            "formatString": "#,0"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Dur",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Plan Dur]",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Dur",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Actual Dur]",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "VAR Actuals =",
                "    SUMMARIZE(",
                "        FILTER(",
                "            'Upstream Logs - Raw',",
                "            'Upstream Logs - Raw'[Stop Time] >= [Report Production Date] - 14",
                "                && 'Upstream Logs - Raw'[Start Time] <= [Now Date]",
                "                && 'Upstream Logs - Raw'[Category] = \"Production\"",
                "                && 'Upstream Logs - Raw'[Process Order Number] <> \"000000000000\"",
                "        ),",
                "        'Upstream Logs - Raw'[Machine Name],",
                "        'Upstream Logs - Raw'[Process Order Number],",
                "        \"Plan Start\", BLANK(),",
                "        \"Plan Stop\", BLANK(),",
                "        \"Actual Start\", MIN( 'Upstream Logs - Raw'[Start Time] ),",
                "        \"Actual Stop\", MAX( 'Upstream Logs - Raw'[Stop Time] ),",
                "        \"Plan Ft\", BLANK(),",
                "        \"Actual Ft\", SUM( 'Upstream Logs - Raw'[Footage] ),",
                "        \"Plan Dur\", BLANK(),",
                "        \"Actual Dur\", SUM( 'Upstream Logs - Raw'[Duration Minutes] ) / 60.0",
                "    )",
                "",
                "VAR Schedule =",
                "    SUMMARIZE(",
                "        FILTER(",
                "            'Upstream Schedule',",
                "            'Upstream Schedule'[Plan Finish Date] >= [Report Production Date] - 14",
                "                && 'Upstream Schedule'[Plan Start Date] < [Report Production Date] + 14",
                "                && 'Upstream Schedule'[Publish Date] <= [Now Date]",
                "                && 'Upstream Schedule'[Ranking Desc] = 1",
                "                && 'Upstream Schedule'[Target Quantity] > 0",
                "        ),",
                "        'Upstream Schedule'[Machine Name],",
                "        'Upstream Schedule'[Process Order Number],",
                "        \"Plan Start\", MIN( 'Upstream Schedule'[Plan Start Date] ),",
                "        \"Plan Stop\", MAX( 'Upstream Schedule'[Plan Finish Date] ),",
                "        \"Actual Start\", BLANK(),",
                "        \"Actual Stop\", BLANK(),",
                "        \"Plan Ft\", SUM( 'Upstream Schedule'[Target Quantity] ),",
                "        \"Actual Ft\", BLANK(),",
                "        \"Plan Dur\", SUM( 'Upstream Schedule'[Processing Hour] ),",
                "        \"Actual Dur\", BLANK()",
                "    )",
                "",
                "RETURN ",
                "    UNION(Actuals, Schedule)"
              ]
            }
          }
        ]
      },
      {
        "name": "Machine Status",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Machine Name",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Machine Status - Prep[Machine Name]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Process Order Number",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "Machine Status - Prep[Process Order Number]"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Start Time",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Plan Start Time]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Stop Time",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Plan Stop Time]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Start Time",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Actual Start Time]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Stop Time",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Actual Stop Time]",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Footage",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Plan Footage]",
            "formatString": "#,0",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Footage",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Actual Footage]",
            "formatString": "#,0",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Plan Duration Hour",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Plan Duration Hour]",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Actual Duration Hour",
            "dataType": "double",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Actual Duration Hour]",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Status",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Status]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SUMMARIZE(",
                "    'Machine Status - Prep',",
                "    'Machine Status - Prep'[Machine Name],",
                "    'Machine Status - Prep'[Process Order Number],",
                "    \"Plan Start Time\", MIN( 'Machine Status - Prep'[Plan Start] ),",
                "    \"Plan Stop Time\", MAX( 'Machine Status - Prep'[Plan Stop] ),",
                "    \"Actual Start Time\", MIN( 'Machine Status - Prep'[Actual Start] ),",
                "    \"Actual Stop Time\", MAX( 'Machine Status - Prep'[Actual Stop] ),",
                "    \"Plan Footage\", SUM( 'Machine Status - Prep'[Plan Ft] ),",
                "    \"Actual Footage\", SUM( 'Machine Status - Prep'[Actual Ft] ),",
                "    \"Plan Duration Hour\", SUM( 'Machine Status - Prep'[Plan Dur] ),",
                "    \"Actual Duration Hour\", SUM( 'Machine Status - Prep'[Actual Dur] ),",
                "    \"Status\",",
                "        SWITCH( TRUE(),",
                "            NOT(ISBLANK( MIN( 'Machine Status - Prep'[Actual Start] ) ) )",
                "                && ISBLANK( MIN( 'Machine Status - Prep'[Plan Start] ) )",
                "                && MAX( 'Machine Status - Prep'[Actual Stop] ) >= [Report Production Date]",
                "                && MIN( 'Machine Status - Prep'[Actual Start] ) <= [Now Date], -1,",
                "            ISBLANK( MIN( 'Machine Status - Prep'[Actual Start] ) )",
                "                && NOT(ISBLANK( MIN( 'Machine Status - Prep'[Plan Start] ) ) )",
                "                && MAX( 'Machine Status - Prep'[Plan Stop] ) >= [Report Production Date]",
                "                && MAX( 'Machine Status - Prep'[Plan Stop] ) <= [Now Date], 0,",
                "            NOT(ISBLANK( MIN( 'Machine Status - Prep'[Actual Start] ) ) )",
                "                && NOT(ISBLANK( MIN( 'Machine Status - Prep'[Plan Start] ) ) )",
                "                && MAX( 'Machine Status - Prep'[Actual Stop] ) >= [Report Production Date]",
                "                && MIN( 'Machine Status - Prep'[Actual Start] ) <= [Now Date], 1,",
                "            NOT( ISBLANK( MIN( 'Machine Status - Prep'[Actual Start] ) ) )",
                "                && MIN( 'Machine Status - Prep'[Actual Start] ) < [Report Production Date]",
                "                && MIN( 'Machine Status - Prep'[Actual Start] ) >= [Report Production Date] - 2, -2,",
                "            NOT( ISBLANK( MIN( 'Machine Status - Prep'[Plan Start] ) ) )",
                "                && MIN( 'Machine Status - Prep'[Plan Start] ) < [Report Production Date]",
                "                && MIN( 'Machine Status - Prep'[Plan Start] ) >= [Report Production Date] - 2, -2,",
                "            BLANK()",
                "        )",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "Goods Issues and Receipts",
        "description": "SAP Source: MKPF and MSEG. Contains postings of goods issue and goods receipts posted in the last 3 fiscal years.",
        "columns": [
          {
            "name": "Material Document Number",
            "dataType": "string",
            "description": "SAP Source: MKPF.MBLNR",
            "sourceColumn": "MaterialDocNo"
          },
          {
            "name": "Material Document Line Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.ZEILE",
            "sourceColumn": "MaterialDocItemNo"
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: MKPF.MJAHR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "Movement Type",
            "dataType": "string",
            "description": "SAP Source: MSEG.BWART",
            "sourceColumn": "MovementType"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.AUFNR",
            "isHidden": true,
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: MSEG.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGORT",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "Storage Bin",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGPLA",
            "sourceColumn": "StorageBin"
          },
          {
            "name": "Storage Type",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGTYP",
            "sourceColumn": "StorageType"
          },
          {
            "name": "Reason Code",
            "dataType": "string",
            "description": "SAP Source: MSEG.GRUND",
            "sourceColumn": "ReasonCode"
          },
          {
            "name": "Material Document Header Text",
            "dataType": "string",
            "description": "SAP Source: MKPF.BKTXT",
            "sourceColumn": "DocHeaderText"
          },
          {
            "name": "Machine Name",
            "dataType": "string",
            "description": "Extracted from Document Header Text",
            "sourceColumn": "MachineName"
          },
          {
            "name": "Posted By",
            "dataType": "string",
            "description": "SAP Source: MKPF.USNAM",
            "sourceColumn": "PostingUsername"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: MSEG.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Time",
            "dataType": "dateTime",
            "description": "SAP Source: MSEG.CPUTM",
            "sourceColumn": "PostingTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Calculated from posting date and time. Production dates starts at 6AM and ends at 5:59AM the next day.",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: MSEG.ERFME",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: MSEG.ERFMG",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Linear Feet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LinearFeet",
            "formatString": "#,0",
            "displayFolder": "_Values"
          },
          {
            "name": "Square Feet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SquareFeet",
            "formatString": "#,0",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "SAP Source: MSEG.DMBTR",
            "sourceColumn": "Amount",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TRANSACTIONS_MATERIAL = Source{[Schema=\"dbo\",Item=\"VW_TRANSACTIONS_MATERIAL\"]}[Data]",
                "in",
                "    dbo_VW_TRANSACTIONS_MATERIAL"
              ]
            }
          }
        ]
      },
      {
        "name": "Inventory Balance (Items)",
        "description": "Accounting document items posted to inventory balance G/L accounts in the last 3 fiscal years. SAP Source: BSIS, BSAS, BKPF, ACCTIT, and EKKO",
        "columns": [
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "G/L Account Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.HKONT",
            "sourceColumn": "GLAccountNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Accounting Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BELNR",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Accounting Document Line Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUZEI",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BLART",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BLDAT",
            "sourceColumn": "DocumentDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.GJAHR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "Fiscal Period",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.MONAT",
            "sourceColumn": "FiscalPeriod"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.BKLAS",
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Movement Type",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.BWART",
            "sourceColumn": "MovementType"
          },
          {
            "name": "Movement Type Category",
            "dataType": "string",
            "description": "Custom value assigned per movement type; Values are from RFAUST's inventory roll forward reference spreadsheet",
            "sourceColumn": "MovementTypeCategory"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: ACCTIT.ERFMG (negated if BSIS/BSAS.SHKZG = 'H')",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.ERFME",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Amount (Document Currency)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.WRBTR (negated if BSIS/BSAS.SHKZG = 'H')",
            "sourceColumn": "AmountInDocCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Document Currency",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.WAERS",
            "sourceColumn": "DocCurrency"
          },
          {
            "name": "Amount (Local Currency)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBTR (negated if BSIS/BSAS.SHKZG = 'H')",
            "sourceColumn": "AmountInLocalCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAER",
            "sourceColumn": "LocalCurrency"
          },
          {
            "name": "Amount (Local Currency 2)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBE2 (negated if BSIS/BSAS.SHKZG = 'H')",
            "sourceColumn": "AmountInLocalCurrency2",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency 2",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAE2",
            "sourceColumn": "LocalCurrency2"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELN",
            "sourceColumn": "PurchaseOrderNo"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELP",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Vendor Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.LIFNR",
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.KUNNR",
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.AUFNR",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Reference Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.XBLNR",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Item Text",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.SGTXT",
            "sourceColumn": "ItemText"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_INVENTORY_BALANCE_ITEMS = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BALANCE_ITEMS\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_BALANCE_ITEMS"
              ]
            }
          }
        ]
      },
      {
        "name": "Inventory Balance (Totals)",
        "description": "Unpivotted version of SAP table FAGLFLEXT. Only the columns HSLxx are extracted as values. Filters: RCLNT = '105'; RLDNR = '0L'; HKONT = inventory balance accounts ",
        "columns": [
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: FAGLFLEXT.RYEAR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "description": "Calculated column after unpivoting HSLxx columns in FAGLFLEXT.",
            "sourceColumn": "FiscalPeriod"
          },
          {
            "name": "Ledger",
            "dataType": "string",
            "description": "SAP Source: FAGLFLEXT.RLDNR",
            "sourceColumn": "LedgerType"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: FAGLFLEXT.RBUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "G/L Account Number",
            "dataType": "string",
            "description": "SAP Source: FAGLFLEXT.RACCT",
            "sourceColumn": "AccountNo"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: FAGLFLEXT.RTCUR",
            "sourceColumn": "Currency"
          },
          {
            "name": "Amount (Group Currency)",
            "dataType": "double",
            "description": "SAP Source: FAGLFLEXT.HSL01 to HSL12",
            "sourceColumn": "AmountInGroup",
            "formatString": "0.00"
          },
          {
            "name": "MonthDateKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "MonthDateKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_INVENTORY_BALANCE_TOTALS = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BALANCE_TOTALS\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_BALANCE_TOTALS"
              ]
            }
          }
        ]
      },
      {
        "name": "GL Account Names",
        "description": "List of G/L accounts in 'AGCA' chart of accounts",
        "columns": [
          {
            "name": "G/L Account Number",
            "dataType": "string",
            "description": "SAP Source: SKAT.SAKNR",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "AccountNoKey"
          },
          {
            "name": "G/L Account Description",
            "dataType": "string",
            "description": "SAP Source: SKAT.TXT50",
            "sourceColumn": "AccountDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_GL_ACCOUNT_NAMES = Source{[Schema=\"dbo\",Item=\"VW_GL_ACCOUNT_NAMES\"]}[Data]",
                "in",
                "    dbo_VW_GL_ACCOUNT_NAMES"
              ]
            }
          }
        ]
      },
      {
        "name": "Company Code",
        "description": "List of company codes (SAP Source: T001)",
        "columns": [
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: T001.BUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: T001.WAERS",
            "sourceColumn": "Currency"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_COMPCODE = Source{[Schema=\"dbo\",Item=\"VW_COMPCODE\"]}[Data]",
                "in",
                "    dbo_VW_COMPCODE"
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Notification Number",
            "dataType": "string",
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "SBlock Quantity",
            "dataType": "double",
            "sourceColumn": "SBlockQuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "SBlock Amount",
            "dataType": "double",
            "sourceColumn": "SBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Quantity",
            "dataType": "double",
            "sourceColumn": "QBlockQuantityValue",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "QBlock Amount",
            "dataType": "double",
            "sourceColumn": "QBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Notification Text",
            "dataType": "string",
            "sourceColumn": "NotificationText"
          },
          {
            "name": "Notification Code",
            "dataType": "string",
            "sourceColumn": "NotificationCode"
          },
          {
            "name": "Notification Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "NotificationEnterDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Notification Author",
            "dataType": "string",
            "sourceColumn": "NotificationAuthor"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BLOCK\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_BLOCK"
              ]
            }
          }
        ]
      },
      {
        "name": "Odoo Sample Requests (Open)",
        "columns": [
          {
            "name": "Ticket Number",
            "dataType": "int64",
            "sourceColumn": "TicketNo"
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "StatusName"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Assigned To",
            "dataType": "string",
            "sourceColumn": "AssignedTo"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Company Name",
            "dataType": "string",
            "sourceColumn": "CompanyName"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesRegion"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritory"
          },
          {
            "name": "Ticket Description",
            "dataType": "string",
            "sourceColumn": "SampleText"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialDescription"
          },
          {
            "name": "Unit Cost",
            "dataType": "double",
            "sourceColumn": "UnitCost",
            "formatString": "#,0.00"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost Amount",
            "dataType": "double",
            "sourceColumn": "CostAmount",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_SAMPLEREQUEST_OPEN_ODOO = Source{[Schema=\"dbo\",Item=\"VW_SAMPLEREQUEST_OPEN_ODOO\"]}[Data]",
                "in",
                "    dbo_VW_SAMPLEREQUEST_OPEN_ODOO"
              ]
            }
          }
        ]
      },
      {
        "name": "_Sample Category",
        "columns": [
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zSAMPLE_CATEGORY = Source{[Schema=\"dbo\",Item=\"zSAMPLE_CATEGORY\"]}[Data]",
                "in",
                "    dbo_zSAMPLE_CATEGORY"
              ]
            }
          }
        ]
      },
      {
        "name": "Inventory Consumption",
        "columns": [
          {
            "name": "Material Document Number",
            "dataType": "string",
            "sourceColumn": "MaterialDocNo"
          },
          {
            "name": "Material Document Line Number",
            "dataType": "string",
            "sourceColumn": "MaterialDocItemNo"
          },
          {
            "name": "Movement Type",
            "dataType": "string",
            "sourceColumn": "MovementType"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "Storage Bin",
            "dataType": "string",
            "sourceColumn": "StorageBin"
          },
          {
            "name": "Storage Type",
            "dataType": "string",
            "sourceColumn": "StorageType"
          },
          {
            "name": "Posted By",
            "dataType": "string",
            "sourceColumn": "PostingUsername"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: MSEG.BUDAT_MKPF",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Time",
            "dataType": "dateTime",
            "sourceColumn": "PostingTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount",
            "formatString": "#,0.00"
          },
          {
            "name": "Amount (In Current Price)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "AmountInCurrentPrice",
            "formatString": "#,0.00"
          },
          {
            "name": "Weight Unit",
            "dataType": "string",
            "sourceColumn": "WeightUnit"
          },
          {
            "name": "Gross Weight",
            "dataType": "double",
            "sourceColumn": "GrossWeight",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TRANSACTIONS_CONSUMPTION = Source{[Schema=\"dbo\",Item=\"VW_TRANSACTIONS_CONSUMPTION\"]}[Data]",
                "in",
                "    dbo_VW_TRANSACTIONS_CONSUMPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "_Value to Use",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Value",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{\"Amount\", \"Quantity\"}"
            }
          }
        ]
      },
      {
        "name": "Transfer Orders (Shipping)",
        "description": "List of transfer orders issued by shipping department involving finished good racks and 901 555",
        "columns": [
          {
            "name": "Transfer Order Number",
            "dataType": "string",
            "description": "SAP Source: LTAP.TANUM",
            "sourceColumn": "TransferOrderNo"
          },
          {
            "name": "Transfer Order Line Number",
            "dataType": "string",
            "description": "SAP Source: LTAP.TAPOS",
            "sourceColumn": "TransferOrderLineNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "description": "SAP Source: LTAP.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Confirm Date",
            "dataType": "dateTime",
            "description": "SAP Source: LTAP.QDATU",
            "sourceColumn": "ConfirmDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Confirm Time",
            "dataType": "dateTime",
            "description": "SAP Source: LTAP.QZEIT",
            "sourceColumn": "ConfirmTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Transferred By",
            "dataType": "string",
            "description": "SAP Source: LTAP.QNAME",
            "sourceColumn": "TransferAuthor"
          },
          {
            "name": "Source Storage Type",
            "dataType": "string",
            "description": "SAP Source: LTAP.VLTYP",
            "sourceColumn": "SrcStrType"
          },
          {
            "name": "Source Storage Bin",
            "dataType": "string",
            "description": "SAP Source: LTAP.VLPLA",
            "sourceColumn": "SrcStrBin"
          },
          {
            "name": "Destination Storage Type",
            "dataType": "string",
            "description": "SAP Source: LTAP.NLTYP",
            "sourceColumn": "DestStrType"
          },
          {
            "name": "Destination Storage Bin",
            "dataType": "string",
            "description": "SAP Source: LTAP.NLPLA",
            "sourceColumn": "DestStrBin"
          },
          {
            "name": "Quantity Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: LTAP.MEINS",
            "sourceColumn": "QtyUoM"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: LTAP.VSOLM",
            "sourceColumn": "QtyVal",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Weight Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: LTAP.GEWEI",
            "sourceColumn": "WeightUoM"
          },
          {
            "name": "Weight",
            "dataType": "double",
            "description": "SAP Source: LTAP.BRGEW",
            "sourceColumn": "WeightVal",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "SrcStorageKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SrcStrKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TRANSFERORD_SHIPPING = Source{[Schema=\"dbo\",Item=\"VW_TRANSFERORD_SHIPPING\"]}[Data]",
                "in",
                "    dbo_VW_TRANSFERORD_SHIPPING"
              ]
            }
          }
        ]
      },
      {
        "name": "Current Inventory (Bins)",
        "description": "Current inventory per storage bin",
        "columns": [
          {
            "name": "Storage Type",
            "dataType": "string",
            "description": "SAP Source: LAGP.LGTYP",
            "sourceColumn": "StorageType"
          },
          {
            "name": "Storage Bin",
            "dataType": "string",
            "description": "SAP Source: LAGP.LGPLA",
            "sourceColumn": "StorageBin"
          },
          {
            "name": "Is Empty",
            "dataType": "int64",
            "description": "SAP Source: LAGP.KZLER",
            "sourceColumn": "EmptyIndicator",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "description": "SAP Source: LQUA.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "description": "SAP Source: LQUA.WERKS",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: LQUA.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Goods Receipt Date",
            "dataType": "dateTime",
            "description": "SAP Source: LQUA.WDATU",
            "sourceColumn": "GoodsReceiptDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: LQUA.MEINS",
            "sourceColumn": "QuantityUoM"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: LQUA.GESME",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount in USD",
            "dataType": "double",
            "description": "Calculated column based on the quantity and standard price of material (by plant and converted to USD using today's exchange rate)",
            "sourceColumn": "AmountUSD",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Age in Days",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "description": "Calculated column between [Goods Receipt Date] and today",
            "expression": "DATEDIFF( 'Current Inventory (Bins)'[Goods Receipt Date], [Report Date], DAY )"
          },
          {
            "type": "calculated",
            "name": "Day Age Group",
            "dataType": "string",
            "isDataTypeInferred": true,
            "description": "Calculated column based on [Age in Days]",
            "expression": [
              "",
              "SWITCH(",
              "    TRUE(),",
              "    'Current Inventory (Bins)'[Age in Days] = BLANK(), BLANK(),",
              "    'Current Inventory (Bins)'[Age in Days] <= 30, \"0 - 30\",",
              "    'Current Inventory (Bins)'[Age in Days] <= 60, \"31 - 60\",",
              "    'Current Inventory (Bins)'[Age in Days] <= 90, \"61 - 90\",",
              "    \"Above 90\"",
              ")"
            ]
          },
          {
            "name": "StorageKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "StorageKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_INVENTORY_STRBIN = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_STRBIN\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_STRBIN"
              ]
            }
          }
        ]
      },
      {
        "name": "_Storage Bin",
        "columns": [
          {
            "name": "Storage Type",
            "dataType": "string",
            "description": "SAP Source: LAGP.LGTYP",
            "sourceColumn": "StorageType"
          },
          {
            "name": "Storage Bin",
            "dataType": "string",
            "description": "SAP Source: LAGP.LGPLA",
            "sourceColumn": "StorageBin"
          },
          {
            "name": "Cell Group",
            "dataType": "string",
            "description": "First 3 characters of the storage bin (assuming it follows the FG rack name format)",
            "sourceColumn": "CellGroup",
            "sortByColumn": "CellGroupSort"
          },
          {
            "name": "Cell Group Number",
            "dataType": "int64",
            "description": "Numerical value in the [Cell Group]",
            "sourceColumn": "CellGroupNo"
          },
          {
            "name": "Cell Height Number",
            "dataType": "int64",
            "description": "Last character in the storage bin name (assuming it follows the FG rack name format)",
            "sourceColumn": "CellHeightNo"
          },
          {
            "name": "Cell Row",
            "dataType": "string",
            "description": "The 4th character in the storage bin name (assuming it follows the FG rack name format)",
            "sourceColumn": "CellRow"
          },
          {
            "name": "Cell Column",
            "dataType": "int64",
            "description": "A custom value assigned to order cell groups in order from left to right (X18 to X00)",
            "sourceColumn": "CellColumn"
          },
          {
            "name": "StorageKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "StorageKey"
          },
          {
            "name": "CellGroupSort",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CellGroupSort"
          },
          {
            "name": "Storage Bin Type",
            "dataType": "string",
            "description": "SAP Source: LAGP.LPTYP",
            "sourceColumn": "StorageBinType"
          },
          {
            "name": "Capacity",
            "dataType": "double",
            "description": "SAP Source: LAGP.LKAPV",
            "sourceColumn": "Capacity",
            "formatString": "#,0.00"
          },
          {
            "name": "Remaining Capacity",
            "dataType": "double",
            "description": "SAP Source: LAGP.RKAPV",
            "sourceColumn": "RemainCapacity",
            "formatString": "#,0.00"
          },
          {
            "name": "Storage Bin Type Description",
            "dataType": "string",
            "description": "SAP Source: T303T.PTYPT",
            "sourceColumn": "StorageBinTypeText"
          },
          {
            "name": "Storage Type Description",
            "dataType": "string",
            "description": "SAP Source: T301T.LTYPT",
            "sourceColumn": "StorageTypeText"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_STRBIN = Source{[Schema=\"dbo\",Item=\"VW_STRBIN\"]}[Data]",
                "in",
                "    dbo_VW_STRBIN"
              ]
            }
          }
        ]
      },
      {
        "name": "Storage Bin Utilization (Snapshots)",
        "description": "Snapshots of quantity and capacity per storage bin at midnight",
        "isHidden": true,
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "description": "Date when the script is ran",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "StorageKey",
            "dataType": "string",
            "description": "SAP Source: LAGP.LGTYP and LAGP.LGPLA",
            "sourceColumn": "StorageKey"
          },
          {
            "name": "Utilized",
            "dataType": "double",
            "description": "SAP Source: LAGP.LKAPV and LAGP.RKAPV; Calculated by taking the difference between capacity and remaining capacity",
            "sourceColumn": "Utilized",
            "formatString": "#,0.00"
          },
          {
            "name": "Capacity",
            "dataType": "double",
            "description": "SAP Source: LAGP.LKAPV",
            "sourceColumn": "Capacity",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zDAILY_STRBIN_UTIL = Source{[Schema=\"dbo\",Item=\"zDAILY_STRBIN_UTIL\"]}[Data]",
                "in",
                "    dbo_zDAILY_STRBIN_UTIL"
              ]
            }
          }
        ]
      },
      {
        "name": "_Test Names",
        "description": "List of tests supported by performance related reports in QA",
        "columns": [
          {
            "name": "TestNameKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "TestNameKey"
          },
          {
            "name": "Test Rename",
            "dataType": "string",
            "sourceColumn": "TestRename",
            "sortByColumn": "SortKey"
          },
          {
            "name": "SortKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SortKey"
          },
          {
            "name": "Test Unit",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Shorter Name",
            "dataType": "string",
            "sourceColumn": "ShortRename"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zTEST_NAMES = Source{[Schema=\"dbo\",Item=\"zTEST_NAMES\"]}[Data]",
                "in",
                "    dbo_zTEST_NAMES"
              ]
            }
          }
        ]
      },
      {
        "name": "Support_FG2FilmLink_Testing",
        "isHidden": true,
        "columns": [
          {
            "name": "MaterialNo",
            "dataType": "string",
            "sourceColumn": "MaterialNo"
          },
          {
            "name": "HighestBomKey",
            "dataType": "string",
            "sourceColumn": "HighestBomKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_FG2FILM_BOMLINK = Source{[Schema=\"dbo\",Item=\"VW_FG2FILM_BOMLINK\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_FG2FILM_BOMLINK,{\"MaterialNo\", \"HighestBomKey\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Testing Results",
        "columns": [
          {
            "name": "Result Key",
            "dataType": "string",
            "sourceColumn": "ResultKey",
            "summarizeBy": "none"
          },
          {
            "name": "Inspection Lot Number",
            "dataType": "string",
            "sourceColumn": "InspectionLotNoKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Test Name",
            "dataType": "string",
            "sourceColumn": "TestName"
          },
          {
            "name": "Inspection Date",
            "dataType": "dateTime",
            "sourceColumn": "InspectionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Inspector Name",
            "dataType": "string",
            "sourceColumn": "InspectorName"
          },
          {
            "name": "Result Unit of Measure",
            "dataType": "string",
            "sourceColumn": "ResultUoM"
          },
          {
            "name": "Result Value",
            "dataType": "double",
            "sourceColumn": "ResultValue",
            "formatString": "#,0.00"
          },
          {
            "name": "Specification Lower Limit",
            "dataType": "double",
            "sourceColumn": "SpecLowerLimit",
            "formatString": "#,0.00"
          },
          {
            "name": "Specification Upper Limit",
            "dataType": "double",
            "sourceColumn": "SpecUpperLimit",
            "formatString": "#,0.00"
          },
          {
            "name": "Is Pass",
            "dataType": "int64",
            "sourceColumn": "IsPass",
            "formatString": "0"
          },
          {
            "name": "Test Category",
            "dataType": "string",
            "sourceColumn": "TestCategory"
          },
          {
            "name": "CoatBomKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CoatBomKey"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "description": "SAP Source: MCH1.HSDAT",
            "sourceColumn": "MfgDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "DateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Work Center",
            "dataType": "string",
            "sourceColumn": "WorkCenter"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialDescription"
          },
          {
            "name": "Specimen Number",
            "dataType": "int64",
            "sourceColumn": "SpecimenNo"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TESTING_RESULTS = Source{[Schema=\"dbo\",Item=\"VW_TESTING_RESULTS\"]}[Data]",
                "in",
                "    dbo_VW_TESTING_RESULTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Bill of Material (Adhesive)",
        "columns": [
          {
            "name": "BomKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BomKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "CompMaterialNo"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "CompMaterialDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_MATERIAL_BOM_ADHESIVE = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_BOM_ADHESIVE\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_BOM_ADHESIVE"
              ]
            }
          }
        ]
      },
      {
        "name": "Bill of Material (Liner)",
        "columns": [
          {
            "name": "BomKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BomKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "CompMaterialNo"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "CompMaterialDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_MATERIAL_BOM_LINER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_BOM_LINER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_BOM_LINER"
              ]
            }
          }
        ]
      },
      {
        "name": "Bill of Material (Facestock)",
        "columns": [
          {
            "name": "BomKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "BomKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "CompMaterialNo"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "CompMaterialDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_MATERIAL_BOM_FACESTOCK = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_BOM_FACESTOCK\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_BOM_FACESTOCK"
              ]
            }
          }
        ]
      },
      {
        "name": "Support_FG2FilmLink_Absorption",
        "isHidden": true,
        "columns": [
          {
            "name": "MaterialNo",
            "dataType": "string",
            "sourceColumn": "MaterialNo"
          },
          {
            "name": "HighestBomKey",
            "dataType": "string",
            "sourceColumn": "HighestBomKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_FG2FILM_BOMLINK = Source{[Schema=\"dbo\",Item=\"VW_FG2FILM_BOMLINK\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_FG2FILM_BOMLINK,{\"MaterialNo\", \"HighestBomKey\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "_Departments",
        "columns": [
          {
            "name": "Department",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "DepartmentKey",
            "sortByColumn": "SortKey"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          },
          {
            "name": "SortKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "SortKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_DEPARTMENTS = Source{[Schema=\"dbo\",Item=\"VW_DEPARTMENTS\"]}[Data]",
                "in",
                "    dbo_VW_DEPARTMENTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Upstream Off Days",
        "isHidden": true,
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "sourceColumn": "DateKey"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Off Hours",
            "dataType": "double",
            "sourceColumn": "OffHours",
            "formatString": "0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_DEPARTMENTS_OFFDAYS = Source{[Schema=\"dbo\",Item=\"VW_DEPARTMENTS_OFFDAYS\"]}[Data]",
                "in",
                "    dbo_VW_DEPARTMENTS_OFFDAYS"
              ]
            }
          }
        ]
      },
      {
        "name": "Shipment Calendar",
        "description": "A specialized tabled used to visualize Shipping department's shipment schedule of sales orders. [First Scheduled Ship Date] is used as columns and [Shipment Rank] as rows while values are concatenated strings of customer name, and order number/type.",
        "isHidden": true,
        "columns": [
          {
            "name": "First Scheduled Ship Date",
            "dataType": "dateTime",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Order Amount",
            "dataType": "double",
            "sourceColumn": "OrderAmountUSD",
            "formatString": "#,0.00"
          },
          {
            "name": "Shipment Rank",
            "dataType": "int64",
            "sourceColumn": "ShipmentRank",
            "formatString": "#,0"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "sourceColumn": "OrderType"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_SALES_SHIPCAL = Source{[Schema=\"dbo\",Item=\"VW_ORDER_SALES_SHIPCAL\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_SALES_SHIPCAL"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7ad599af-e270-40c4-9adb-251c9dca4378",
        "fromTable": "Complaint Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "7bc6c5a0-4655-407a-bc13-1cd3a65eca38",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "9aea2de3-d4c1-473e-bf03-55a3a8d409f5",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "90d80725-4955-4415-8778-f3b670ded05f",
        "fromTable": "Complaint Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "1196625d-915c-4f90-8a7e-4a4e307c34c4",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "3f9dd1f7-3ac5-4bce-b233-68a54ac9862f",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "22d61dbe-0265-4bd3-b686-8d76e4f1d50f",
        "fromTable": "Complaint Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "c2395825-7531-4dd0-9c3e-d4e7a214fb64",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "d104f71c-fb20-42c2-a158-df74a0040f19",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "75f7059e-5891-4145-8c3b-08cf13009c2f",
        "fromTable": "Expired Inventory",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "64d69090-8c95-4cfd-bae5-098fdca2fd7c",
        "fromTable": "Complaint Documents",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "392923c6-b921-4da9-a0eb-847df9a9ca69",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "ec941efc-23a0-4e1e-8fee-379eafa01610",
        "fromTable": "Complaint Documents",
        "fromColumn": "Last Credit Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "d5fde41f-6d8d-49a1-b78d-1db50db9cab6",
        "fromTable": "Expenses",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "e23eac90-b677-4be3-8b2e-bdaa9a94dc93",
        "fromTable": "Expenses",
        "fromColumn": "Cost Element",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "43dc6699-1755-45fc-989b-be3676e258f3",
        "fromTable": "Expenses",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "d8be19f9-8a2d-4705-87ba-97ce6a35808d",
        "fromTable": "Purchase Orders",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "7c3dbb62-0337-4cc5-9e9c-df847491f72f",
        "fromTable": "Complaint Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey"
      },
      {
        "name": "ae51b0d3-b4c7-4f09-a508-4760ecf542bc",
        "fromTable": "Complaint Documents - Credited",
        "fromColumn": "ComplaintLineKey",
        "toTable": "Complaint Documents",
        "toColumn": "ComplaintLineKey"
      },
      {
        "name": "bb994812-edd5-4866-b953-2c6a4947a747",
        "fromTable": "Complaint Documents - Credited",
        "fromColumn": "Credit Issued Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6f4a4e75-689a-4bd1-8fe0-321e1b128db2",
        "fromTable": "Sales Order Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey"
      },
      {
        "name": "4c4cdf75-2716-4c3e-b281-b08eaee90a8b",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "24ac2122-cadb-486a-a099-9ca4d9472ced",
        "fromTable": "Sales Order Documents",
        "fromColumn": "First Delivery Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "b8c16a52-5847-4775-8abd-8bb356d4b1e3",
        "fromTable": "RLS_Region",
        "fromColumn": "SalesRegionKey",
        "toTable": "Sales Region",
        "toColumn": "Sales Region",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "6c7f5d85-c9b6-4d16-b9d9-96554aad9745",
        "fromTable": "RLS_Territory",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "bbf17c5a-1360-4ff5-8464-c1322342394c",
        "fromTable": "Customer Master",
        "fromColumn": "Sales Region",
        "toTable": "Sales Region",
        "toColumn": "Sales Region"
      },
      {
        "name": "0133610b-f474-47c4-a3e2-612f4360d565",
        "fromTable": "Customer Master",
        "fromColumn": "Sales Territory",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory"
      },
      {
        "name": "dc5f18dd-e738-46d9-a5c9-5306f5255523",
        "fromTable": "RLS_CostCenter",
        "fromColumn": "CostCenterKey",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "2dfef6b6-28fb-4b3a-aced-5bc2cb76c009",
        "fromTable": "Stock Transfer Orders",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "8157dd03-c7e0-468a-b864-e8ab717607f1",
        "fromTable": "Goods and Invoice Receipts",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "982c3aae-a31d-40c1-92a1-5b55611d01da",
        "fromTable": "Purchase Order Invoices",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "ba1918f0-89e6-4284-93df-d56a390a189e",
        "fromTable": "Purchase Order Invoices",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "ce291ef4-f6d6-43db-989e-e636805941b6",
        "fromTable": "Purchase Orders",
        "fromColumn": "VendorNoKey",
        "toTable": "Vendor Master",
        "toColumn": "Vendor Number"
      },
      {
        "name": "2c9b5b75-14a7-45ae-849d-a78e7f8033cd",
        "fromTable": "Goods and Invoice Receipts",
        "fromColumn": "Vendor Number",
        "toTable": "Vendor Master",
        "toColumn": "Vendor Number"
      },
      {
        "name": "d3f017b1-44bd-4645-8deb-8c26d0ecde96",
        "fromTable": "Absorption",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "aa32963f-d2e9-4965-839d-1354c85503d6",
        "fromTable": "Absorption",
        "fromColumn": "Cost Element",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "749c05b1-49f2-4a5c-899b-3801eaaa0f52",
        "fromTable": "Absorption",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "be0acd87-ca5c-487c-9366-d05855204388",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Entered By",
        "toTable": "SAP Users",
        "toColumn": "UsernameKey"
      },
      {
        "name": "2db43657-5faa-4957-981b-1815c9ecf050",
        "toCardinality": "many",
        "fromTable": "Sales Order Document Changes",
        "fromColumn": "OrderNoKey",
        "toTable": "Sales Order Documents",
        "toColumn": "Order Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "3df54883-286b-415a-a9ca-e9431f57d2f4",
        "fromTable": "Sales Order Document Changes",
        "fromColumn": "Changed By",
        "toTable": "SAP Users",
        "toColumn": "UsernameKey"
      },
      {
        "name": "9428d940-fbc3-4bdb-8689-20a209035670",
        "fromTable": "Purchase Orders - Deliveries",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "48cb8180-79ac-45f5-b7ad-8912c6e44e15",
        "fromTable": "Purchase Orders - Deliveries",
        "fromColumn": "First Delivery Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "d1ed3275-cbe1-4844-937e-a4d48686f5a3",
        "fromTable": "Backorder Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "c8527d3a-4ba0-4eee-b9b7-2e8ab62b7327",
        "fromTable": "Purchase Orders",
        "fromColumn": "Receiving Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "29b9c765-765f-47b2-99ab-83bc3b93a8b8",
        "fromTable": "Goods Issues and Receipts",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "55be127a-f081-4dd0-ae15-9cea0b6b081c",
        "fromTable": "Goods Issues and Receipts",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "92d76df7-af86-4843-9820-c0dc4d79be5d",
        "fromTable": "Converting Man Hours",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6985a741-d8a9-4d99-bee9-693dd4e5011c",
        "fromTable": "Converting Uptime",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fbe75965-0259-4a21-9f85-7ec85969c6b3",
        "toCardinality": "many",
        "fromTable": "Converting Uptime",
        "fromColumn": "Machine Name",
        "toTable": "Goods Issues and Receipts",
        "toColumn": "Machine Name",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "2a7d8317-b122-4a81-b5ba-c855ebccc8c2",
        "fromTable": "Upstream Logs - Raw",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "ab46bd23-f168-453a-9da6-0f7839a7504a",
        "fromTable": "Upstream Logs - Raw",
        "fromColumn": "Machine Name",
        "toTable": "_Machines",
        "toColumn": "Machine Name"
      },
      {
        "name": "c43d17ba-58df-49a4-a1f2-f33e0a1c591c",
        "fromTable": "Upstream Logs - Simplified",
        "fromColumn": "Machine Name",
        "toTable": "_Machines",
        "toColumn": "Machine Name"
      },
      {
        "name": "10344338-100d-447d-9f74-b27f469d26d0",
        "fromTable": "Goods Issues and Receipts",
        "fromColumn": "Machine Name",
        "toTable": "_Machines",
        "toColumn": "Machine Name"
      },
      {
        "name": "3dfea972-a6c3-4217-a6f9-2e2df7e2eecb",
        "fromTable": "Upstream Logs - Raw",
        "fromColumn": "Production Shift",
        "toTable": "_Production Shifts",
        "toColumn": "Production Shift"
      },
      {
        "name": "becaf1fd-b98b-4518-8016-1bf2f89b99fa",
        "fromTable": "Upstream Logs - Simplified",
        "fromColumn": "Production Shift",
        "toTable": "_Production Shifts",
        "toColumn": "Production Shift"
      },
      {
        "name": "ae929e18-a212-4e3a-887a-33676a5d28cb",
        "fromTable": "Upstream Logs - Simplified",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "edb1d743-a11d-4e2b-b292-ab8dba773adb",
        "fromTable": "Expired Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "bae672e2-0554-48c6-b380-2eac585b1aae",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "844c8296-06d1-4a91-b5f5-cf5d22120e79",
        "fromTable": "Current Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "08202d37-043e-42f0-918e-9410bf04d838",
        "fromTable": "Current Inventory",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "4f04be4c-5336-42f0-a551-4e0849e86e45",
        "fromTable": "Support_MthlyConsume",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "d38b7e48-148a-4017-aa85-cb8e8542cd82",
        "fromTable": "Support_MthlyConsume",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "75fd0308-cb04-42b6-bae3-c8567bd4ca01",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "23344e6c-9867-45da-ab6b-e547eda438bc",
        "fromTable": "Sales Order Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "ee1a5083-509b-40ff-b7b4-6c386bad6dc5",
        "fromTable": "Current Inventory",
        "fromColumn": "Valuation Class",
        "toTable": "_Valuation Class",
        "toColumn": "Valuation Class"
      },
      {
        "name": "8bb9fd92-a42c-4ac4-984a-03efddb6b978",
        "fromTable": "Stock Transfer Orders",
        "fromColumn": "ValuationClassKey",
        "toTable": "_Valuation Class",
        "toColumn": "Valuation Class"
      },
      {
        "name": "9c9472c7-7f2d-4c47-8494-4c48136d7537",
        "fromTable": "Open WIP",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "40c6d0d8-249b-46f8-8e23-ac83c22b9b42",
        "fromTable": "Open WIP",
        "fromColumn": "ValuationClassKey",
        "toTable": "_Valuation Class",
        "toColumn": "Valuation Class"
      },
      {
        "name": "06dd5de3-8791-422a-9058-b4fa8f0ab14b",
        "fromTable": "Current Inventory Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fde30517-6684-4145-979d-5dc8561c26e9",
        "fromTable": "Current Inventory Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "d8687cfd-d586-4083-ab77-ae3b4c894ab3",
        "fromTable": "Current Inventory Snapshots",
        "fromColumn": "Valuation Class",
        "toTable": "_Valuation Class",
        "toColumn": "Valuation Class"
      },
      {
        "name": "347ad7db-de48-4877-b20b-016915340cc1",
        "fromTable": "Current Inventory Snapshots",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "4b317c1f-63e0-4239-9ebb-797489c7b214",
        "fromTable": "Shop Orders",
        "fromColumn": "End Date Key",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "e19a146a-9bb5-4d0b-917c-89dbb52fa2c6",
        "fromTable": "Shop Orders",
        "fromColumn": "Process Order Number",
        "toTable": "Open WIP",
        "toColumn": "Process Order Number"
      },
      {
        "name": "1fe727ce-d640-4f9b-9406-0e31ca90416e",
        "fromTable": "Shop Orders",
        "fromColumn": "Basic Start Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "9e3d8325-575b-4183-9f36-c00277724088",
        "fromTable": "Upstream Schedule",
        "fromColumn": "Plan Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fc38a22e-bdd7-41aa-8806-a4bac5a049cb",
        "fromTable": "Upstream Schedule",
        "fromColumn": "Machine Name",
        "toTable": "_Machines",
        "toColumn": "Machine Name"
      },
      {
        "name": "658d9e4a-953d-40c9-bd24-176d803ed9bd",
        "fromTable": "Machine Status",
        "fromColumn": "Machine Name",
        "toTable": "_Machines",
        "toColumn": "Machine Name"
      },
      {
        "name": "b273bbb0-3dc8-4e3c-a061-37e7b82f33c9",
        "fromTable": "Backorder Snapshots",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "b9425909-7f44-42d9-b4d9-ef825068889a",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "G/L Account Number",
        "toTable": "GL Account Names",
        "toColumn": "G/L Account Number"
      },
      {
        "name": "9c1e5864-9a35-4c31-9aae-dc1865981c33",
        "fromTable": "Inventory Balance (Totals)",
        "fromColumn": "G/L Account Number",
        "toTable": "GL Account Names",
        "toColumn": "G/L Account Number"
      },
      {
        "name": "e009df4d-6e8a-4df2-b04d-a3ac28c61edc",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Valuation Class",
        "toTable": "_Valuation Class",
        "toColumn": "Valuation Class"
      },
      {
        "name": "459c6d4a-2a16-433d-b42a-a821930060c5",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "368813ea-602e-4b41-afa2-b0f16320b642",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Vendor Number",
        "toTable": "Vendor Master",
        "toColumn": "Vendor Number"
      },
      {
        "name": "c027290f-a4f9-402e-b864-9e24d3be2c9c",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "a2d417b9-fe0d-4ef0-b1c0-5939f526a813",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "18e3a975-a427-437e-876a-7203858f128d",
        "fromTable": "Inventory Balance (Totals)",
        "fromColumn": "MonthDateKey",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "e2773836-79ea-4759-a754-9a5012eabbc3",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Company Code",
        "toTable": "Company Code",
        "toColumn": "Company Code"
      },
      {
        "name": "e6397c5c-7400-48d1-a482-adf7843b82c1",
        "fromTable": "Inventory Balance (Totals)",
        "fromColumn": "Company Code",
        "toTable": "Company Code",
        "toColumn": "Company Code"
      },
      {
        "name": "18573a26-b074-4d4c-8ce6-6ec9f7ff6506",
        "fromTable": "Inventory Balance (Items)",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "774c8489-a2be-42c4-8a1b-8dffc10c2904",
        "fromTable": "Blocked Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "69c625ce-25c0-497d-9c3e-a2d15262abe1",
        "fromTable": "Blocked Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "def38767-e23d-4a2c-b94b-f024d4394589",
        "fromTable": "Backorder Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "db31a6cf-aa59-456a-9f13-dd196ad9c0ff",
        "fromTable": "Expired Inventory",
        "fromColumn": "Expiration Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "72c7c6a1-aabc-4bfc-8491-7d49d9138e2e",
        "fromTable": "Blocked Inventory",
        "fromColumn": "Notification Number",
        "toTable": "Hold Tag Documents",
        "toColumn": "Notification Number",
        "isActive": false
      },
      {
        "name": "de55efee-f414-4fd4-ac01-40cda075e4a8",
        "fromTable": "Odoo Sample Requests (Open)",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "c6c95f64-58b7-4f76-a10a-45457fe3e0db",
        "fromTable": "Odoo Sample Requests (Open)",
        "fromColumn": "Sales Region",
        "toTable": "Sales Region",
        "toColumn": "Sales Region"
      },
      {
        "name": "2438a1ab-8937-4e85-a1f5-d980e2d96609",
        "fromTable": "Odoo Sample Requests (Open)",
        "fromColumn": "Sales Territory",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory"
      },
      {
        "name": "5f253841-6767-45ca-aea6-e69e887e1f75",
        "fromTable": "Odoo Sample Requests (Open)",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "b3ec39da-bf21-470a-925c-5b91d827d998",
        "fromTable": "Odoo Sample Requests (Open)",
        "fromColumn": "Category",
        "toTable": "_Sample Category",
        "toColumn": "Category"
      },
      {
        "name": "bfa66b5a-4915-428d-8974-17c99c685303",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Sample Category",
        "toTable": "_Sample Category",
        "toColumn": "Category"
      },
      {
        "name": "125ee949-3779-48ac-be35-91c4ecd577d1",
        "fromTable": "Inventory Consumption",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6cf878d5-6db1-43b5-958d-72a06c81444a",
        "fromTable": "Inventory Consumption",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "c8dcceac-17e9-4c4a-aed7-c2e642757d24",
        "fromTable": "Inventory Consumption",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "e1e1dfda-2cb9-40ec-bef9-a0209e5dd320",
        "fromTable": "Transfer Orders (Shipping)",
        "fromColumn": "Confirm Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "3acb9a2a-f9a9-419a-95ba-e35b6014077d",
        "fromTable": "Transfer Orders (Shipping)",
        "fromColumn": "Transferred By",
        "toTable": "SAP Users",
        "toColumn": "UsernameKey"
      },
      {
        "name": "bc18db34-4d77-4553-8325-9c3fac3345ff",
        "fromTable": "Transfer Orders (Shipping)",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "e2cd18b1-4914-469d-98a2-86f65e9cdbb6",
        "fromTable": "Expenses",
        "fromColumn": "PurchaseDocLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "38bd7d9e-00ca-4269-9665-ab39abff8b56",
        "fromTable": "Purchase Orders",
        "fromColumn": "Issuing Plant",
        "toTable": "Plant",
        "toColumn": "Plant",
        "isActive": false
      },
      {
        "name": "4c9e8d56-e6c0-418e-a497-9403fd192815",
        "fromTable": "Current Inventory (Bins)",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "f6612288-1ff1-43c9-9c3f-69c9f8adb26c",
        "fromTable": "Current Inventory (Bins)",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "539df02a-d0ec-4aa8-8ef6-eda5f70b7197",
        "fromTable": "Transfer Orders (Shipping)",
        "fromColumn": "SrcStorageKey",
        "toTable": "_Storage Bin",
        "toColumn": "StorageKey"
      },
      {
        "name": "dfe7e862-70ed-4e14-9351-e5f9590e618f",
        "fromTable": "Current Inventory (Bins)",
        "fromColumn": "StorageKey",
        "toTable": "_Storage Bin",
        "toColumn": "StorageKey"
      },
      {
        "name": "1fca97fb-d181-45f7-817a-c1a071a9af1f",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Last PGI Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "7d175b71-c76b-4560-93c5-ac93c1e82667",
        "fromTable": "Storage Bin Utilization (Snapshots)",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6c11c2d3-a614-41d8-a8c3-9bc3f421fe04",
        "fromTable": "Storage Bin Utilization (Snapshots)",
        "fromColumn": "StorageKey",
        "toTable": "_Storage Bin",
        "toColumn": "StorageKey"
      },
      {
        "name": "6d0e8d43-0e5b-497a-b2ee-a7c35c42aa16",
        "fromTable": "Support_FG2FilmLink_Testing",
        "fromColumn": "MaterialNo",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "2e995f2d-e7ae-43f5-978c-e1d12483227d",
        "fromTable": "Testing Results",
        "fromColumn": "Test Name",
        "toTable": "_Test Names",
        "toColumn": "TestNameKey"
      },
      {
        "name": "4b749270-1754-4ee6-b32b-fd47dcdd8887",
        "fromTable": "Testing Results",
        "fromColumn": "DateKey",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "66b3a37a-1be3-4e8b-8afe-ba494c06b724",
        "toCardinality": "many",
        "fromTable": "Bill of Material (Adhesive)",
        "fromColumn": "BomKey",
        "toTable": "Testing Results",
        "toColumn": "CoatBomKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "d58ad0be-49b0-4ac2-9b5a-0955712676ff",
        "toCardinality": "many",
        "fromTable": "Bill of Material (Liner)",
        "fromColumn": "BomKey",
        "toTable": "Testing Results",
        "toColumn": "CoatBomKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "1abcb04d-2002-47b5-ad22-b3380eb0796d",
        "toCardinality": "many",
        "fromTable": "Bill of Material (Facestock)",
        "fromColumn": "BomKey",
        "toTable": "Testing Results",
        "toColumn": "CoatBomKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "71e73ae0-d271-4eca-999c-e1189b2dffed",
        "toCardinality": "many",
        "fromTable": "Testing Results",
        "fromColumn": "CoatBomKey",
        "toTable": "Support_FG2FilmLink_Testing",
        "toColumn": "HighestBomKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "55834398-f79e-44c8-8293-312a3d27462f",
        "toCardinality": "many",
        "fromTable": "Absorption",
        "fromColumn": "HighestBomKey",
        "toTable": "Support_FG2FilmLink_Absorption",
        "toColumn": "HighestBomKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "f03144f1-1946-4ce0-a175-e737bebd6926",
        "fromTable": "Support_FG2FilmLink_Absorption",
        "fromColumn": "MaterialNo",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "bd6c2dc5-52cb-4bb0-8c2e-4f5c566cc8d2",
        "fromTable": "Shop Orders",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "c0270be3-3c6b-448a-a3c3-9d5a1fdf85c1",
        "fromTable": "Upstream Schedule",
        "fromColumn": "PlanFinishDateAltKey",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "a56ef07b-71d5-4c0d-9d9d-480f99a5d2bc",
        "fromTable": "_Machines",
        "fromColumn": "Department",
        "toTable": "_Departments",
        "toColumn": "Department"
      },
      {
        "name": "43d9454b-1030-4290-8210-eb1e5a4cce0e",
        "fromTable": "Cost Center Names",
        "fromColumn": "Department",
        "toTable": "_Departments",
        "toColumn": "Department"
      },
      {
        "name": "f62e6263-5dd5-4966-9c15-4458042b2ff0",
        "fromTable": "Upstream Off Days",
        "fromColumn": "Department",
        "toTable": "_Departments",
        "toColumn": "Department"
      },
      {
        "name": "3f06226d-bea6-43eb-956c-a55e1b441f87",
        "fromTable": "Upstream Off Days",
        "fromColumn": "Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fcc869c7-9d1b-40ed-b3f5-d6ded66e06f3",
        "fromTable": "Shipment Calendar",
        "fromColumn": "First Scheduled Ship Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "a9bcafad-8953-41cb-8cd3-060a40d99f86",
        "fromTable": "Shipment Calendar",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      }
    ],
    "perspectives": [
      {
        "name": "QA Dashboard",
        "tables": [
          {
            "name": "Blocked Inventory Snapshots",
            "columns": [
              {
                "name": "Blocked Inv Value"
              },
              {
                "name": "Expired Value"
              },
              {
                "name": "QBlock Value"
              },
              {
                "name": "SBlock Value"
              },
              {
                "name": "Snapshot Date"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Complaint Documents",
            "columns": [
              {
                "name": "Billing Block Indicator"
              },
              {
                "name": "Complaint Amount"
              },
              {
                "name": "Complaint Line Number"
              },
              {
                "name": "Complaint Number"
              },
              {
                "name": "Complaint Type"
              },
              {
                "name": "Credit Issued Amount"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Last Credit Date"
              },
              {
                "name": "Category"
              },
              {
                "name": "Department"
              },
              {
                "name": "Reason Code Description"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Complaint Count"
              },
              {
                "name": "Complaint Value"
              },
              {
                "name": "Credit Issued"
              },
              {
                "name": "Current Blocked Inv Value"
              },
              {
                "name": "Current Q-Block Value"
              },
              {
                "name": "Current S-Block Value"
              },
              {
                "name": "Hold Amount"
              },
              {
                "name": "Hold Quantity"
              },
              {
                "name": "Hold Tag Count"
              },
              {
                "name": "Open Value"
              },
              {
                "name": "PQ Complaint Count"
              },
              {
                "name": "PQ Complaint Value"
              },
              {
                "name": "PQ Credit Issued"
              },
              {
                "name": "PQ Open Value"
              },
              {
                "name": "Product Quality Index"
              },
              {
                "name": "Product Quality Index (Credited)"
              },
              {
                "name": "Product Quality Index (Open)"
              },
              {
                "name": "Current Expired Value"
              },
              {
                "name": "Product Quality Index (Target)"
              },
              {
                "name": "PQ Complaint Cycle Time"
              },
              {
                "name": "Current Q-Block Quantity"
              },
              {
                "name": "Current S-Block Quantity"
              },
              {
                "name": "Current Expired Quantity"
              },
              {
                "name": "Report Date"
              },
              {
                "name": "Testing Average Result"
              },
              {
                "name": "Testing Sample Count"
              },
              {
                "name": "Testing Maximum Result"
              },
              {
                "name": "Testing Minimum Result"
              },
              {
                "name": "Testing Passing Rate"
              },
              {
                "name": "Testing Standard Deviation Result"
              },
              {
                "name": "Testing Specification Lower Limit"
              },
              {
                "name": "Testing Specification Upper Limit"
              },
              {
                "name": "Testing Failed Specimen Count"
              },
              {
                "name": "Testing Passed Specimen Count"
              },
              {
                "name": "Testing 15min Dwell Adhesion Avg Result"
              },
              {
                "name": "Testing 24hr Dwell Adhesion Avg Result"
              }
            ]
          },
          {
            "name": "Expired Inventory",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "Hold Tag Documents",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Notification Number"
              },
              {
                "name": "Notification Type"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reference Number"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Text"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Pending Specification Documents",
            "columns": [
              {
                "name": "Approver Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "Pending Count"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Report Name"
              },
              {
                "name": "Refresh Date"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Blocked Inventory",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Plant"
              },
              {
                "name": "QBlock Amount"
              },
              {
                "name": "QBlock Quantity"
              },
              {
                "name": "SBlock Amount"
              },
              {
                "name": "SBlock Quantity"
              },
              {
                "name": "Storage Location"
              }
            ]
          },
          {
            "name": "_Test Names",
            "columns": [
              {
                "name": "Test Rename"
              },
              {
                "name": "TestNameKey"
              },
              {
                "name": "SortKey"
              },
              {
                "name": "Test Unit"
              },
              {
                "name": "Shorter Name"
              }
            ]
          },
          {
            "name": "Testing Results",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Inspection Date"
              },
              {
                "name": "Inspection Lot Number"
              },
              {
                "name": "Inspector Name"
              },
              {
                "name": "Is Pass"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Result Key"
              },
              {
                "name": "Result Unit of Measure"
              },
              {
                "name": "Result Value"
              },
              {
                "name": "Specification Lower Limit"
              },
              {
                "name": "Specification Upper Limit"
              },
              {
                "name": "Test Name"
              },
              {
                "name": "Test Category"
              },
              {
                "name": "CoatBomKey"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "DateKey"
              },
              {
                "name": "Work Center"
              },
              {
                "name": "Department"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Specimen Number"
              }
            ]
          },
          {
            "name": "Bill of Material (Adhesive)",
            "columns": [
              {
                "name": "BomKey"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Number"
              }
            ]
          },
          {
            "name": "Bill of Material (Facestock)",
            "columns": [
              {
                "name": "BomKey"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Description"
              }
            ]
          },
          {
            "name": "Bill of Material (Liner)",
            "columns": [
              {
                "name": "BomKey"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Number"
              }
            ]
          }
        ]
      },
      {
        "name": "Expenses",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Expenses",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Creation Date"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Header Text"
              },
              {
                "name": "Document Item Text"
              },
              {
                "name": "Document Line Number"
              },
              {
                "name": "Document Number"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Is Reversal Document"
              },
              {
                "name": "Is Reversed"
              },
              {
                "name": "OffsetAcctNoKey"
              },
              {
                "name": "OffsetAcctType"
              },
              {
                "name": "PlantNoKey"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "PurchaseDocLineKey"
              },
              {
                "name": "Referenced Document Line Number"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Reversal Referenced Document Number"
              },
              {
                "name": "Expense Type"
              },
              {
                "name": "Offset Account Name"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Description"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Is Controllable Expense"
              },
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Req Track Number"
              }
            ]
          },
          {
            "name": "_Expenses Mode",
            "columns": [
              {
                "name": "Mode"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Expenses Amount"
              },
              {
                "name": "Expenses Plan"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Report Name"
              },
              {
                "name": "Refresh Date"
              }
            ]
          }
        ]
      },
      {
        "name": "CS Dashboard",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Complaint Documents",
            "columns": [
              {
                "name": "Billing Block Indicator"
              },
              {
                "name": "Category"
              },
              {
                "name": "Complaint Amount"
              },
              {
                "name": "Complaint Line Number"
              },
              {
                "name": "Complaint Number"
              },
              {
                "name": "Complaint Type"
              },
              {
                "name": "Credit Issued Amount"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Last Credit Date"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Department"
              },
              {
                "name": "Reason Code Description"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "CA Complaint Count"
              },
              {
                "name": "CA Complaint Value"
              },
              {
                "name": "Customer Accommodation Index"
              },
              {
                "name": "Service Quality Index"
              },
              {
                "name": "SQ Complaint Count"
              },
              {
                "name": "SQ Complaint Value"
              },
              {
                "name": "Customer Accommodation Index (Target)"
              },
              {
                "name": "Service Quality Index (Target)"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Sales Order Count"
              },
              {
                "name": "Report Date"
              },
              {
                "name": "Sample Request Cost Amount"
              },
              {
                "name": "Sample Request Count"
              },
              {
                "name": "Sales Order Line Count"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Cost Amount"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "Tier"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              }
            ]
          },
          {
            "name": "Odoo Sample Requests (Open)",
            "columns": [
              {
                "name": "Assigned To"
              },
              {
                "name": "Category"
              },
              {
                "name": "Company Name"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Status"
              },
              {
                "name": "Ticket Description"
              },
              {
                "name": "Ticket Number"
              },
              {
                "name": "Unit Cost"
              }
            ]
          },
          {
            "name": "_Sample Category",
            "columns": [
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "Sales Region",
            "columns": [
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Region Name"
              }
            ]
          },
          {
            "name": "Sales Territory",
            "columns": [
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              }
            ]
          }
        ]
      },
      {
        "name": "Generic Sales",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Account Creation Date"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "Price List Code"
              },
              {
                "name": "Price List Name"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Gross Margin"
              },
              {
                "name": "FYTD Gross Margin%"
              },
              {
                "name": "FYTD Gross Sales"
              },
              {
                "name": "FYTD PY Gross Margin"
              },
              {
                "name": "FYTD PY Gross Margin%"
              },
              {
                "name": "FYTD PY Gross Sales"
              },
              {
                "name": "FYTD PY Var Gross Sales"
              },
              {
                "name": "Gross Margin"
              },
              {
                "name": "Gross Margin %"
              },
              {
                "name": "MTD Gross Margin"
              },
              {
                "name": "MTD Gross Margin%"
              },
              {
                "name": "MTD Gross Sales"
              },
              {
                "name": "MTD PY Gross Margin"
              },
              {
                "name": "MTD PY Gross Margin%"
              },
              {
                "name": "MTD PY Gross Sales"
              },
              {
                "name": "Gross Sales Budget"
              },
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Quantity Sold"
              },
              {
                "name": "Gross Sales"
              },
              {
                "name": "Sales Order Margin"
              },
              {
                "name": "MTD PY Var Gross Sales"
              },
              {
                "name": "FYTD PY Var% Gross Sales"
              },
              {
                "name": "MTD PY Var% Gross Sales"
              },
              {
                "name": "FYTD Quantity Sold"
              },
              {
                "name": "MTD Quantity Sold"
              },
              {
                "name": "FYTD Gross Margin% Budget"
              },
              {
                "name": "MTD Gross Margin% Budget"
              },
              {
                "name": "FYTD Gross Sales & Backorder"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "FYTD Gross Sales Budget"
              },
              {
                "name": "MTD Gross Sales & Backorder"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "MTD Gross Sales Budget"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "Overall Cost"
              },
              {
                "name": "YTD Gross Margin"
              },
              {
                "name": "YTD Gross Margin%"
              },
              {
                "name": "YTD Gross Sales"
              },
              {
                "name": "YTD PY Gross Margin"
              },
              {
                "name": "YTD PY Gross Margin%"
              },
              {
                "name": "YTD PY Gross Sales"
              },
              {
                "name": "YTD PY Var Gross Sales"
              },
              {
                "name": "YTD PY Var% Gross Sales"
              },
              {
                "name": "Sales Discount"
              },
              {
                "name": "Net Margin"
              },
              {
                "name": "Net Sales"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Sales Invoice Documents",
            "columns": [
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Discount Amount"
              },
              {
                "name": "Gross Sales Amount"
              },
              {
                "name": "Invoice Line Number"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Material Cost Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Net Sales Amount"
              },
              {
                "name": "Overall Cost Amount"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Document Type Text"
              },
              {
                "name": "Create Date"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Quantity Unit"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Gross Margin Amount"
              },
              {
                "name": "Was New Product"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Ship To City"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              }
            ]
          },
          {
            "name": "_Currency to Use",
            "columns": [
              {
                "name": "Currency"
              }
            ]
          }
        ]
      },
      {
        "name": "BI Morning Dashboard",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "Price List Code"
              },
              {
                "name": "Price List Name"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Gross Margin"
              },
              {
                "name": "FYTD Gross Margin%"
              },
              {
                "name": "FYTD Gross Sales"
              },
              {
                "name": "FYTD PY Gross Margin"
              },
              {
                "name": "FYTD PY Gross Margin%"
              },
              {
                "name": "FYTD PY Gross Sales"
              },
              {
                "name": "FYTD PY Var Gross Sales"
              },
              {
                "name": "FYTD PY Var% Gross Sales"
              },
              {
                "name": "Gross Margin"
              },
              {
                "name": "Gross Margin %"
              },
              {
                "name": "Gross Sales"
              },
              {
                "name": "MTD Gross Margin"
              },
              {
                "name": "MTD Gross Margin%"
              },
              {
                "name": "MTD Gross Sales"
              },
              {
                "name": "MTD PY Gross Margin"
              },
              {
                "name": "MTD PY Gross Margin%"
              },
              {
                "name": "MTD PY Gross Sales"
              },
              {
                "name": "MTD PY Var Gross Sales"
              },
              {
                "name": "MTD PY Var% Gross Sales"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Beginning of Month"
              },
              {
                "name": "End of Month"
              },
              {
                "name": "Yesterday"
              },
              {
                "name": "FYTD PY Sales Order Amount"
              },
              {
                "name": "FYTD PY Var Sales Order Amount"
              },
              {
                "name": "FYTD PY Var% Sales Order Amount"
              },
              {
                "name": "MTD PY Sales Order Amount"
              },
              {
                "name": "MTD PY Var Sales Order Amount"
              },
              {
                "name": "MTD PY Var% Sales Order Amount"
              },
              {
                "name": "FYTD Sales Order Amount"
              },
              {
                "name": "MTD Sales Order Amount"
              },
              {
                "name": "Backorder Amount"
              },
              {
                "name": "FYTD Gross Sales & Backorder"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "MTD Gross Sales & Backorder"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "Backorder Amount (Beyond Next Month)"
              },
              {
                "name": "Backorder Amount (Current Month)"
              },
              {
                "name": "Backorder Amount (Next Month)"
              },
              {
                "name": "Backorder Amount (Past Due)"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "Absorption"
              },
              {
                "name": "Earned Labor"
              },
              {
                "name": "Earned Overhead"
              },
              {
                "name": "MTD Absorption"
              },
              {
                "name": "MTD PY Absorption"
              },
              {
                "name": "MTD Sales Order Amount %Grand"
              },
              {
                "name": "FYTD Gross Margin% Budget"
              },
              {
                "name": "FYTD Gross Sales Budget"
              },
              {
                "name": "MTD Gross Margin% Budget"
              },
              {
                "name": "MTD Gross Sales Budget"
              },
              {
                "name": "FYTD Budget Var% Gross Sales"
              },
              {
                "name": "MTD Budget Var% Gross Sales"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "Report Date"
              },
              {
                "name": "End of Next Month"
              },
              {
                "name": "Quantity Sold"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Allocated Amount"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "Absorption (Budget)"
              },
              {
                "name": "Earned Labor (Budget)"
              },
              {
                "name": "Earned Overhead (Budget)"
              },
              {
                "name": "FYTD Absorption (Budget)"
              },
              {
                "name": "FYTD Earned Labor (Budget)"
              },
              {
                "name": "FYTD Earned Overhead (Budget)"
              },
              {
                "name": "MTD Absorption (Budget)"
              },
              {
                "name": "MTD Earned Labor (Budget)"
              },
              {
                "name": "MTD Earned Overhead (Budget)"
              },
              {
                "name": "MTD Earned Labor"
              },
              {
                "name": "MTD Earned Overhead"
              },
              {
                "name": "Net Margin"
              },
              {
                "name": "Net Sales"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Sales Invoice Documents",
            "columns": [
              {
                "name": "Create Date"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Discount Amount"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Document Type Text"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Gross Sales Amount"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Invoice Line Number"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Material Cost Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Net Sales Amount"
              },
              {
                "name": "Overall Cost Amount"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Quantity Unit"
              },
              {
                "name": "Gross Margin Amount"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Was New Product"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              },
              {
                "name": "Shipped Weight"
              },
              {
                "name": "Customer Open Weight"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Late Indicator"
              },
              {
                "name": "Reason for Late Shipment"
              },
              {
                "name": "Reason Type for Late Shipment"
              },
              {
                "name": "Late Exclude Indicator"
              },
              {
                "name": "Late Quantity"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "DepartmentSortKey"
              },
              {
                "name": "Operations Category"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Sub Category"
              }
            ]
          },
          {
            "name": "Absorption",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Business Transaction Type"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "HighestBomKey"
              }
            ]
          }
        ]
      },
      {
        "name": "Open Orders Report",
        "tables": [
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "SalesRegionSortKey"
              },
              {
                "name": "Price List Code"
              },
              {
                "name": "Price List Name"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "In Stock Measure"
              },
              {
                "name": "PO Delivered Quantity"
              },
              {
                "name": "PO In Transit Quantity"
              },
              {
                "name": "PO Open Amount"
              },
              {
                "name": "PO Open Quantity"
              },
              {
                "name": "PO Ordered Amount"
              },
              {
                "name": "PO Ordered Quantity"
              },
              {
                "name": "PD PO Backorder Amount"
              },
              {
                "name": "PD Var PO Open Amount"
              },
              {
                "name": "PD SO Customer Open Amount"
              },
              {
                "name": "PD Var SO Customer Open Amount"
              },
              {
                "name": "SO Allocated Amount"
              },
              {
                "name": "SO Customer Open Margin"
              },
              {
                "name": "SO Shipped Amount"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              },
              {
                "name": "Shipped Weight"
              },
              {
                "name": "Customer Open Weight"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Late Indicator"
              },
              {
                "name": "Reason for Late Shipment"
              },
              {
                "name": "Reason Type for Late Shipment"
              },
              {
                "name": "Late Exclude Indicator"
              },
              {
                "name": "Late Quantity"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Stock Transfer Orders",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Delivered Amount"
              },
              {
                "name": "Delivered Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "In Transit Amount"
              },
              {
                "name": "In Transit Quantity"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Shipment Document Number"
              },
              {
                "name": "Shipment Document Line Number"
              },
              {
                "name": "ValuationClassKey"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "Backorder Snapshots",
            "columns": [
              {
                "name": "Plant"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "Incoming Amount"
              },
              {
                "name": "Outgoing Amount"
              },
              {
                "name": "Unrestricted Stock Amount"
              },
              {
                "name": "Remaining by Month End Transit Stock Amount"
              },
              {
                "name": "Incoming Quantity"
              },
              {
                "name": "Outgoing Quantity"
              },
              {
                "name": "Unrestricted Stock Quantity"
              },
              {
                "name": "Remaining by Month End Transit Stock Quantity"
              },
              {
                "name": "Shortage Amount"
              },
              {
                "name": "Shortage Quantity"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          }
        ]
      },
      {
        "name": "Goods and Invoice Receipts",
        "tables": [
          {
            "name": "_Currency to Use",
            "columns": [
              {
                "name": "Currency"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Goods and Invoice Receipts",
            "columns": [
              {
                "name": "Accounting Document Line Number"
              },
              {
                "name": "Accounting Document Number"
              },
              {
                "name": "Amount (Document)"
              },
              {
                "name": "Amount (Local)"
              },
              {
                "name": "Amount (Local2)"
              },
              {
                "name": "Assignment Number"
              },
              {
                "name": "Clearing Date"
              },
              {
                "name": "Clearing Document Number"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Document Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First GR Year"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "G/L Account"
              },
              {
                "name": "Item Text"
              },
              {
                "name": "Local Currency"
              },
              {
                "name": "Local Currency 2"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Vendor Number"
              },
              {
                "name": "PostingRank"
              },
              {
                "name": "PurchaseOrderLineKey"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "GRIR Amount (Document)"
              },
              {
                "name": "GRIR Amount (Local)"
              },
              {
                "name": "GRIR Amount (Local2)"
              },
              {
                "name": "GRIR Quantity"
              },
              {
                "name": "GRIR Open Amount"
              },
              {
                "name": "GRIR Open Quantity"
              }
            ]
          }
        ]
      },
      {
        "name": "Purchase Orders",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Purchase Order Invoices",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "PostingRank"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Amount at Last PY Price"
              },
              {
                "name": "Last PY Quantity"
              },
              {
                "name": "Last PY Amount"
              },
              {
                "name": "Price Difference"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Last PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD Last PO Invoice Receipt Quantity"
              },
              {
                "name": "FYTD Last PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PO Invoice Receipt Amount in PY Price"
              },
              {
                "name": "FYTD PO Invoice Receipt Quantity"
              },
              {
                "name": "FYTD PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD Purchase Price Difference"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Quantity"
              },
              {
                "name": "PO Delivered Quantity"
              },
              {
                "name": "PO In Transit Quantity"
              },
              {
                "name": "PO Invoice Receipt Amount"
              },
              {
                "name": "PO Invoice Receipt Quantity"
              },
              {
                "name": "PO Open Amount"
              },
              {
                "name": "PO Open Quantity"
              },
              {
                "name": "PO Ordered Amount"
              },
              {
                "name": "PO Ordered Quantity"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD Purchase Price Index"
              },
              {
                "name": "FYTD Purchase Price Index%"
              },
              {
                "name": "FYTD PY PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PY PO Invoice Receipt Quantity"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Orders",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              },
              {
                "name": "Shipped Weight"
              },
              {
                "name": "Customer Open Weight"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Late Indicator"
              },
              {
                "name": "Reason for Late Shipment"
              },
              {
                "name": "Reason Type for Late Shipment"
              },
              {
                "name": "Late Exclude Indicator"
              },
              {
                "name": "Late Quantity"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Backorder Amount (Beyond Next Month)"
              },
              {
                "name": "Backorder Amount (Current Month)"
              },
              {
                "name": "Backorder Amount (Next Month)"
              },
              {
                "name": "Backorder Amount (Past Due)"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "FYTD PY Sales Order Amount"
              },
              {
                "name": "FYTD PY Var Sales Order Amount"
              },
              {
                "name": "FYTD PY Var% Sales Order Amount"
              },
              {
                "name": "FYTD Sales Order Amount"
              },
              {
                "name": "MTD PY Sales Order Amount"
              },
              {
                "name": "MTD PY Var Sales Order Amount"
              },
              {
                "name": "MTD PY Var% Sales Order Amount"
              },
              {
                "name": "MTD Sales Order Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Count"
              },
              {
                "name": "Sales Order Line Count"
              },
              {
                "name": "Sales Order Lines Automated"
              },
              {
                "name": "Sales Order Lines Automated Entry%"
              },
              {
                "name": "Sales Order Margin"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "Sales Order Lines Manual"
              },
              {
                "name": "FYTD PY Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Lines Automated Entry%"
              },
              {
                "name": "MTD Sales Order Lines Automated Entry%"
              },
              {
                "name": "MTD Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Automation Efficiency%"
              },
              {
                "name": "MTD Sales Order Automation Efficiency%"
              },
              {
                "name": "Sales Order Automation Efficiency%"
              },
              {
                "name": "Sales Order Lines Automated (No Changes)"
              },
              {
                "name": "Sales Order Lines Manual Entry%"
              },
              {
                "name": "Sales Order Line Count (Automated + Manual)"
              },
              {
                "name": "SO Allocated Amount"
              },
              {
                "name": "SO Customer Open Margin"
              },
              {
                "name": "SO Shipped Amount"
              }
            ]
          },
          {
            "name": "Sales Order Document Changes",
            "columns": [
              {
                "name": "Change Date"
              },
              {
                "name": "Change Time"
              },
              {
                "name": "Changed By"
              },
              {
                "name": "OrderNoKey"
              }
            ]
          }
        ]
      },
      {
        "name": "Engineering",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "GI Linear Footage"
              },
              {
                "name": "GI Scrap Rate"
              },
              {
                "name": "GR Linear Footage"
              },
              {
                "name": "GR Square Footage"
              },
              {
                "name": "Yesterday"
              },
              {
                "name": "GIR Amount"
              },
              {
                "name": "GIR Linear Footage"
              },
              {
                "name": "GIR Quantity"
              },
              {
                "name": "GIR Square Footage"
              },
              {
                "name": "CONV Available Hours"
              },
              {
                "name": "CONV Production Hours"
              },
              {
                "name": "CONV Square Feet per Man Hour"
              },
              {
                "name": "CONV Square Feet per Man Hour (Target)"
              },
              {
                "name": "CONV Square Feet per Man Hour (Target Variance)"
              },
              {
                "name": "CONV Availability"
              },
              {
                "name": "CONV Uptime Hours"
              },
              {
                "name": "PD GI Linear Footage"
              },
              {
                "name": "PD GI Scrap Rate"
              },
              {
                "name": "PD GR Linear Footage"
              },
              {
                "name": "Upstream Actual Production Footage"
              },
              {
                "name": "Upstream Ideal Production Footage"
              },
              {
                "name": "Upstream Runtime Minutes"
              },
              {
                "name": "Upstream Uptime Minutes"
              },
              {
                "name": "Upstream Actual Footage"
              },
              {
                "name": "Upstream Ideal Footage"
              },
              {
                "name": "Upstream Downtime Hours"
              },
              {
                "name": "Upstream Planned CU Count"
              },
              {
                "name": "Upstream Unplanned CU Count"
              },
              {
                "name": "Upstream Availability"
              },
              {
                "name": "Upstream Overall Equipment Efficiency"
              },
              {
                "name": "Upstream Performance"
              },
              {
                "name": "Upstream First Pass Reliability"
              },
              {
                "name": "Upstream Changeover Time"
              },
              {
                "name": "Upstream Overall Equipment Efficiency (Target)"
              },
              {
                "name": "Upstream First Pass Reliability (Target)"
              },
              {
                "name": "Upstream Changeover Time (Target)"
              },
              {
                "name": "Upstream Performance Impact"
              },
              {
                "name": "Upstream Availability Impact"
              },
              {
                "name": "Upstream Overall Equipment Efficiency Impact"
              },
              {
                "name": "Upstream Quality"
              },
              {
                "name": "Upstream Days Since Last Unplanned Clean Up"
              },
              {
                "name": "Upstream Changeover Scrap"
              },
              {
                "name": "Report Date"
              },
              {
                "name": "Upstream Overall Equipment Efficiency (Target Var)"
              },
              {
                "name": "CONV Linear Footage"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Converting Man Hours",
            "columns": [
              {
                "name": "Available Hours"
              },
              {
                "name": "Non Production Hours"
              },
              {
                "name": "Notes"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Production Hours"
              },
              {
                "name": "Shift"
              }
            ]
          },
          {
            "name": "Converting Uptime",
            "columns": [
              {
                "name": "Machine Name"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Uptime Seconds"
              }
            ]
          },
          {
            "name": "Upstream Logs - Raw",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Causes"
              },
              {
                "name": "Comments"
              },
              {
                "name": "Footage"
              },
              {
                "name": "Further Detail"
              },
              {
                "name": "Ideal Footage"
              },
              {
                "name": "Job Index"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Production Shift"
              },
              {
                "name": "Specification Number"
              },
              {
                "name": "Start Time"
              },
              {
                "name": "Stop Time"
              },
              {
                "name": "Specification Linespeed"
              },
              {
                "name": "Actual Linespeed"
              },
              {
                "name": "Duration Minutes"
              }
            ]
          },
          {
            "name": "Upstream Logs - Simplified",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Causes"
              },
              {
                "name": "Comments"
              },
              {
                "name": "Duration Minutes"
              },
              {
                "name": "Efficiency Hitter"
              },
              {
                "name": "Footage"
              },
              {
                "name": "Further Detail"
              },
              {
                "name": "Ideal Footage"
              },
              {
                "name": "Is Transition"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Non Uptime Reason"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Production Shift"
              },
              {
                "name": "Scrap Footage"
              },
              {
                "name": "Specification Number"
              },
              {
                "name": "Start Time"
              },
              {
                "name": "Stop Time"
              },
              {
                "name": "Specification Linespeed"
              },
              {
                "name": "Actual Linespeed"
              }
            ]
          },
          {
            "name": "_Machines",
            "columns": [
              {
                "name": "Department"
              },
              {
                "name": "Machine Name"
              }
            ]
          },
          {
            "name": "_Production Shifts",
            "columns": [
              {
                "name": "Production Shift"
              },
              {
                "name": "Shift Name"
              }
            ]
          },
          {
            "name": "Goods Issues and Receipts",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Linear Feet"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Material Document Header Text"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Movement Type"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posted By"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Posting Time"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reason Code"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "Unit of Measure"
              }
            ]
          }
        ]
      },
      {
        "name": "Inventory",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "PO In Transit Quantity"
              },
              {
                "name": "Current Blocked Inv Value"
              },
              {
                "name": "Current Expired Quantity"
              },
              {
                "name": "Current Expired Value"
              },
              {
                "name": "Current Q-Block Quantity"
              },
              {
                "name": "Current Q-Block Value"
              },
              {
                "name": "Current Safety Stock Quantity"
              },
              {
                "name": "Current S-Block Quantity"
              },
              {
                "name": "Current S-Block Value"
              },
              {
                "name": "Current Unrestricted Stock Quantity"
              },
              {
                "name": "Current Available Quantity"
              },
              {
                "name": "PO Delivered Quantity"
              },
              {
                "name": "PO Open Amount"
              },
              {
                "name": "PO Open Quantity"
              },
              {
                "name": "PO Ordered Amount"
              },
              {
                "name": "PO Ordered Quantity"
              },
              {
                "name": "PO Goods Receipt Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "MTD Accumulated Inventory Balance"
              },
              {
                "name": "MTD Prior Accumulated Inventory Balance"
              },
              {
                "name": "MTD Inventory Balance (Accruals)"
              },
              {
                "name": "MTD Inventory Balance (Produced)"
              },
              {
                "name": "MTD Inventory Balance (Purchases)"
              },
              {
                "name": "MTD Inventory Balance (Reversals)"
              },
              {
                "name": "MTD Inventory Balance (Sales)"
              },
              {
                "name": "MTD Inventory Balance (Scrap)"
              },
              {
                "name": "MTD Inventory Balance (Transfers)"
              },
              {
                "name": "MTD Inventory Balance (Write-offs)"
              },
              {
                "name": "Inventory Balance"
              },
              {
                "name": "MTD Inventory Balance (PPV)"
              },
              {
                "name": "Check Inventory Balance"
              },
              {
                "name": "MTD Inventory Balance"
              },
              {
                "name": "Average Monthly Consumption (Last 3 Months)"
              },
              {
                "name": "Average Monthly Consumption (Last 12 Months)"
              },
              {
                "name": "Average Monthly Consumption (Last 6 Months)"
              },
              {
                "name": "Average Monthly Consumption (Last 24 Months)"
              },
              {
                "name": "Average Monthly Consumption (Last 36 Months)"
              },
              {
                "name": "Inventory Annual Consumption (Next 12 Months)"
              },
              {
                "name": "Inventory Annual Consumption (After 12th Month)"
              },
              {
                "name": "Inventory Time Supply"
              },
              {
                "name": "Inventory Annual Consumption (After 36th Month)"
              },
              {
                "name": "Inventory Annual Consumption (After 24th Month)"
              },
              {
                "name": "SO Customer Open Quantity"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Current Inventory",
            "columns": [
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Safety Stock Quantity"
              },
              {
                "name": "Unrestricted Stock Quantity"
              },
              {
                "name": "Tier Code"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Inspection Stock Quantity"
              },
              {
                "name": "Blocked Stock Quantity"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Standard Price"
              },
              {
                "name": "Unrestricted Stock Amount (USD)"
              },
              {
                "name": "Inspection Stock Amount (USD)"
              },
              {
                "name": "Blocked Stock Amount (USD)"
              },
              {
                "name": "Standard Price (USD)"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Company Code"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Purchase Orders - Deliveries",
            "columns": [
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Stock Transfer Orders",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Delivered Amount"
              },
              {
                "name": "Delivered Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "In Transit Amount"
              },
              {
                "name": "In Transit Quantity"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Shipment Document Line Number"
              },
              {
                "name": "Shipment Document Number"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "ValuationClassKey"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              },
              {
                "name": "Shipped Weight"
              },
              {
                "name": "Customer Open Weight"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Late Indicator"
              },
              {
                "name": "Reason for Late Shipment"
              },
              {
                "name": "Reason Type for Late Shipment"
              },
              {
                "name": "Late Exclude Indicator"
              },
              {
                "name": "Late Quantity"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Price List Code"
              },
              {
                "name": "Price List Name"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "Current Inventory Snapshots",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "GL Account Names",
            "columns": [
              {
                "name": "G/L Account Description"
              },
              {
                "name": "G/L Account Number"
              }
            ]
          },
          {
            "name": "Inventory Balance (Items)",
            "columns": [
              {
                "name": "Accounting Document Line Number"
              },
              {
                "name": "Accounting Document Number"
              },
              {
                "name": "Amount (Document Currency)"
              },
              {
                "name": "Amount (Local Currency 2)"
              },
              {
                "name": "Amount (Local Currency)"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Document Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "G/L Account Number"
              },
              {
                "name": "Item Text"
              },
              {
                "name": "Local Currency"
              },
              {
                "name": "Local Currency 2"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Movement Type"
              },
              {
                "name": "Movement Type Category"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reference Document Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "Inventory Balance (Totals)",
            "columns": [
              {
                "name": "Amount (Group Currency)"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "G/L Account Number"
              },
              {
                "name": "Ledger"
              },
              {
                "name": "MonthDateKey"
              }
            ]
          },
          {
            "name": "_Currency to Use",
            "columns": [
              {
                "name": "Currency"
              }
            ]
          },
          {
            "name": "Company Code",
            "columns": [
              {
                "name": "Company Code"
              },
              {
                "name": "Currency"
              }
            ]
          },
          {
            "name": "_Valuation Class",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Rename"
              },
              {
                "name": "SortKey"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "Inventory Consumption",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Movement Type"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posted By"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Posting Time"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Amount (In Current Price)"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              }
            ]
          },
          {
            "name": "Expired Inventory",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Stock Amount"
              },
              {
                "name": "Stock Quantity"
              }
            ]
          },
          {
            "name": "_Value to Use",
            "columns": [
              {
                "name": "Value"
              }
            ]
          }
        ]
      },
      {
        "name": "Planning",
        "tables": [
          {
            "name": "_Machines",
            "columns": [
              {
                "name": "Department"
              },
              {
                "name": "Machine Name"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Current Inventory",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Safety Stock Quantity"
              },
              {
                "name": "Tier Code"
              },
              {
                "name": "Unrestricted Stock Quantity"
              },
              {
                "name": "Inspection Stock Quantity"
              },
              {
                "name": "Blocked Stock Quantity"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Standard Price"
              },
              {
                "name": "Unrestricted Stock Amount (USD)"
              },
              {
                "name": "Inspection Stock Amount (USD)"
              },
              {
                "name": "Blocked Stock Amount (USD)"
              },
              {
                "name": "Standard Price (USD)"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "Hold Tag Documents",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Notification Number"
              },
              {
                "name": "Notification Type"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reference Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Text"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Stock Transfer Orders",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Delivered Amount"
              },
              {
                "name": "Delivered Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "In Transit Amount"
              },
              {
                "name": "In Transit Quantity"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Shipment Document Line Number"
              },
              {
                "name": "Shipment Document Number"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "ValuationClassKey"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Current Available Quantity"
              },
              {
                "name": "Current Blocked Inv Value"
              },
              {
                "name": "Current Expired Quantity"
              },
              {
                "name": "Current Expired Value"
              },
              {
                "name": "Current Q-Block Quantity"
              },
              {
                "name": "Current Q-Block Value"
              },
              {
                "name": "Current Safety Stock Quantity"
              },
              {
                "name": "Current S-Block Quantity"
              },
              {
                "name": "Current S-Block Value"
              },
              {
                "name": "Current Unrestricted Stock Quantity"
              },
              {
                "name": "Upstream Actual Production Footage"
              },
              {
                "name": "Cumulative Expired Value"
              },
              {
                "name": "Current Inventory Amount"
              },
              {
                "name": "Report Date"
              },
              {
                "name": "Beginning of Month"
              },
              {
                "name": "Date 12 Months Ago"
              },
              {
                "name": "End of Month"
              },
              {
                "name": "End of Next Month"
              },
              {
                "name": "Last Inventory Amount"
              },
              {
                "name": "PD Inventory Amount"
              },
              {
                "name": "PD Var Inventory Amount"
              },
              {
                "name": "S/O Count"
              },
              {
                "name": "S/O Delivered Quantity"
              },
              {
                "name": "S/O Ordered Quantity"
              },
              {
                "name": "S/O Completed Count"
              },
              {
                "name": "S/O Scheduled Count"
              },
              {
                "name": "S/O With Hold Tag Count"
              },
              {
                "name": "S/O With Hold Tag %"
              },
              {
                "name": "Max Date"
              },
              {
                "name": "Min Date"
              },
              {
                "name": "FYTD PY S/O Completed Count"
              },
              {
                "name": "FYTD S/O Completed Count"
              },
              {
                "name": "FYTD S/O Scheduled Count"
              },
              {
                "name": "S/O Scheduled Quantity (Upstream)"
              },
              {
                "name": "MTD S/O Remake Reason Hour"
              },
              {
                "name": "Month End S/O Remake Reason Hour"
              },
              {
                "name": "Report Production Date"
              },
              {
                "name": "MStat Effective Net Hours Loss/Gain"
              },
              {
                "name": "MStat Last Actual Start Time"
              },
              {
                "name": "MStat Last Plan Start Time"
              },
              {
                "name": "MStat Last Process Order Number"
              },
              {
                "name": "MStat Net Hours Loss/Gain"
              },
              {
                "name": "MStat Skipped S/O Duration Hour"
              },
              {
                "name": "MStat Net Footage Variance"
              },
              {
                "name": "MStat Data Integrity"
              },
              {
                "name": "Now Date"
              },
              {
                "name": "Prior Production Date"
              },
              {
                "name": "Last Backorder Snapshot Amount"
              },
              {
                "name": "Last Shortage Amount% Snapshot"
              },
              {
                "name": "MStat Indicator"
              },
              {
                "name": "Absorption"
              },
              {
                "name": "Absorption (Budget)"
              },
              {
                "name": "Earned Labor"
              },
              {
                "name": "Earned Labor (Budget)"
              },
              {
                "name": "Earned Overhead"
              },
              {
                "name": "Earned Overhead (Budget)"
              },
              {
                "name": "FYTD Absorption (Budget)"
              },
              {
                "name": "FYTD Earned Labor (Budget)"
              },
              {
                "name": "FYTD Earned Overhead (Budget)"
              },
              {
                "name": "MTD Absorption"
              },
              {
                "name": "MTD Absorption (Budget)"
              },
              {
                "name": "MTD Earned Labor"
              },
              {
                "name": "MTD Earned Labor (Budget)"
              },
              {
                "name": "MTD Earned Overhead"
              },
              {
                "name": "MTD Earned Overhead (Budget)"
              },
              {
                "name": "MTD PY Absorption"
              },
              {
                "name": "CW Absorption"
              },
              {
                "name": "FYTD Absorption"
              },
              {
                "name": "FYTD PY Absorption"
              },
              {
                "name": "MTD Absorption Hours"
              },
              {
                "name": "MTD PY Absorption Hours"
              },
              {
                "name": "Absorption per Output (Last 3 Months)"
              },
              {
                "name": "S/O Future Scheduled Output by Month End (Upstream)"
              },
              {
                "name": "Actual Production Start Datetime"
              },
              {
                "name": "Estimated Absorption based on Scheduled Output by Month End"
              },
              {
                "name": "Scheduled Production Stop Datetime"
              },
              {
                "name": "Average Daily Absorption based on Estimate"
              },
              {
                "name": "Projected Absorption"
              },
              {
                "name": "Future Off Hours After Schedule End"
              },
              {
                "name": "Absorption Hours"
              }
            ]
          },
          {
            "name": "Expired Inventory",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Stock Amount"
              },
              {
                "name": "Stock Quantity"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "_Valuation Class",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Rename"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "SortKey"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Company Code"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Open WIP",
            "columns": [
              {
                "name": "Material Number"
              },
              {
                "name": "Net Cost Amount"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "ValuationClassKey"
              }
            ]
          },
          {
            "name": "Current Inventory Snapshots",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "Shop Orders",
            "columns": [
              {
                "name": "Actual End Date"
              },
              {
                "name": "Actual End Time"
              },
              {
                "name": "Actual Start Date"
              },
              {
                "name": "Actual Start Time"
              },
              {
                "name": "Basic End Date"
              },
              {
                "name": "Basic End Time"
              },
              {
                "name": "Basic Start Date"
              },
              {
                "name": "Basic Start Time"
              },
              {
                "name": "Comment"
              },
              {
                "name": "Confirm Date"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Deliver Indicator"
              },
              {
                "name": "Delivered Quantity"
              },
              {
                "name": "Document Group"
              },
              {
                "name": "End Date Key"
              },
              {
                "name": "Final Deliver Indicator"
              },
              {
                "name": "Item Number"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Same Day Indicator"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Work Center"
              },
              {
                "name": "Close Indicator"
              },
              {
                "name": "Notification Number"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Upstream Schedule",
            "columns": [
              {
                "name": "Adhesive Quantity"
              },
              {
                "name": "Department"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plan Finish Date"
              },
              {
                "name": "Plan Production Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Processing Hour"
              },
              {
                "name": "Publish Date"
              },
              {
                "name": "Remake Code"
              },
              {
                "name": "Target Quantity"
              },
              {
                "name": "Remake Code Text"
              },
              {
                "name": "Plan Start Date"
              },
              {
                "name": "Ranking Desc"
              },
              {
                "name": "PlanFinishDateAltKey"
              }
            ]
          },
          {
            "name": "Machine Status",
            "columns": [
              {
                "name": "Actual Duration Hour"
              },
              {
                "name": "Actual Footage"
              },
              {
                "name": "Actual Start Time"
              },
              {
                "name": "Actual Stop Time"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Plan Duration Hour"
              },
              {
                "name": "Plan Footage"
              },
              {
                "name": "Plan Start Time"
              },
              {
                "name": "Plan Stop Time"
              },
              {
                "name": "Process Order Number"
              }
            ]
          },
          {
            "name": "Backorder Snapshots",
            "columns": [
              {
                "name": "Incoming Amount"
              },
              {
                "name": "Incoming Quantity"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Outgoing Amount"
              },
              {
                "name": "Outgoing Quantity"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Remaining by Month End Transit Stock Amount"
              },
              {
                "name": "Remaining by Month End Transit Stock Quantity"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Unrestricted Stock Amount"
              },
              {
                "name": "Unrestricted Stock Quantity"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "Shortage Amount"
              },
              {
                "name": "Shortage Quantity"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "DepartmentSortKey"
              },
              {
                "name": "Operations Category"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Sub Category"
              },
              {
                "name": "Is Supplies"
              },
              {
                "name": "Is Labor"
              },
              {
                "name": "Is Controllable Expense"
              },
              {
                "name": "CustomOrder"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "Absorption",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Business Transaction Type"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "HighestBomKey"
              }
            ]
          },
          {
            "name": "_Departments",
            "columns": [
              {
                "name": "Department"
              },
              {
                "name": "Name"
              },
              {
                "name": "SortKey"
              }
            ]
          }
        ]
      },
      {
        "name": "Warehouse",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Next 3 Months"
              },
              {
                "name": "Is Recent Weeks"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Start of Month"
              },
              {
                "name": "Week Group"
              },
              {
                "name": "Weekday"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Year_Week_Sort_Key"
              },
              {
                "name": "Weekday Name"
              },
              {
                "name": "Is After 13 Months Ago"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "DepartmentSortKey"
              },
              {
                "name": "Operations Category"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "CustomOrder"
              },
              {
                "name": "Is Controllable Expense"
              },
              {
                "name": "Is Labor"
              },
              {
                "name": "Is Supplies"
              },
              {
                "name": "Sub Category"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Price List Code"
              },
              {
                "name": "Price List Name"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Name"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Created By"
              },
              {
                "name": "Created Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Material Type Text"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Size Code"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Type Code"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Material Number Prefix"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "MaterialPlantKey"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              },
              {
                "name": "Shipped Weight"
              },
              {
                "name": "Customer Open Weight"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Late Indicator"
              },
              {
                "name": "Reason for Late Shipment"
              },
              {
                "name": "Reason Type for Late Shipment"
              },
              {
                "name": "Late Exclude Indicator"
              },
              {
                "name": "Late Quantity"
              }
            ]
          },
          {
            "name": "Transfer Orders (Shipping)",
            "columns": [
              {
                "name": "Confirm Date"
              },
              {
                "name": "Confirm Time"
              },
              {
                "name": "Destination Storage Bin"
              },
              {
                "name": "Destination Storage Type"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Quantity Unit of Measure"
              },
              {
                "name": "Source Storage Bin"
              },
              {
                "name": "Source Storage Type"
              },
              {
                "name": "Transfer Order Line Number"
              },
              {
                "name": "Transfer Order Number"
              },
              {
                "name": "Transferred By"
              },
              {
                "name": "Weight"
              },
              {
                "name": "Weight Unit of Measure"
              },
              {
                "name": "SrcStorageKey"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Company Code"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              }
            ]
          },
          {
            "name": "Inventory Consumption",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Amount (In Current Price)"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Movement Type"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posted By"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Posting Time"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Weight Unit"
              },
              {
                "name": "Gross Weight"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "WH Picked Weight (Shipping)"
              },
              {
                "name": "WH Shipment Amount"
              },
              {
                "name": "WH Expenses per Units Picked"
              },
              {
                "name": "Expenses Amount"
              },
              {
                "name": "Expenses Plan"
              },
              {
                "name": "CW PO Open Amount"
              },
              {
                "name": "CW PO Goods Receipt Amount"
              },
              {
                "name": "CW SO Internal Open Amount"
              },
              {
                "name": "CW SO Shipped Amount"
              },
              {
                "name": "WH Shipment Weight"
              },
              {
                "name": "Month End WH Pending Shipment Weight"
              },
              {
                "name": "Expenses Plan Var%"
              },
              {
                "name": "WH Average Material Age in Days"
              },
              {
                "name": "WH Storage Bin Amount"
              },
              {
                "name": "WH Storage Bin Capacity"
              },
              {
                "name": "WH Storage Bin Utilization"
              },
              {
                "name": "Last Storage Bin Utilization Snapshot"
              },
              {
                "name": "WH Storage Bin Quantity"
              },
              {
                "name": "Last Backorder Snapshot Amount"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "WH Shipment Quantity"
              },
              {
                "name": "WH Future Shipment Amount"
              },
              {
                "name": "Sales Order Line Count"
              },
              {
                "name": "MTD Sales Order Line Count"
              },
              {
                "name": "WH Effective On Time Shipment"
              },
              {
                "name": "Sales Order Line Count (By First Ship Date)"
              },
              {
                "name": "WH Effective On Time Shipment (Target)"
              },
              {
                "name": "WH Complete On Time"
              },
              {
                "name": "WH SO Line Count (All)"
              },
              {
                "name": "WH SO Line Count (Exempt)"
              },
              {
                "name": "WH SO Line Count (On Time)"
              },
              {
                "name": "WH Complete On Time (Target)"
              },
              {
                "name": "WH Shipment Calendar List"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "SO Late Quantity"
              },
              {
                "name": "WH Days of Perfect On Time Shipment"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Current Inventory (Bins)",
            "columns": [
              {
                "name": "Age in Days"
              },
              {
                "name": "Amount in USD"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Day Age Group"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Is Empty"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "PlantNoKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "Unit of Measure"
              }
            ]
          },
          {
            "name": "_Storage Bin",
            "columns": [
              {
                "name": "Cell Column"
              },
              {
                "name": "Cell Group"
              },
              {
                "name": "Cell Group Number"
              },
              {
                "name": "Cell Height Number"
              },
              {
                "name": "Cell Row"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "StorageKey"
              },
              {
                "name": "CellGroupSort"
              },
              {
                "name": "Storage Bin Type"
              },
              {
                "name": "Capacity"
              },
              {
                "name": "Remaining Capacity"
              },
              {
                "name": "Storage Bin Type Description"
              },
              {
                "name": "Storage Type Description"
              }
            ]
          },
          {
            "name": "Backorder Snapshots",
            "columns": [
              {
                "name": "Incoming Amount"
              },
              {
                "name": "Incoming Quantity"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Outgoing Amount"
              },
              {
                "name": "Outgoing Quantity"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Remaining by Month End Transit Stock Amount"
              },
              {
                "name": "Remaining by Month End Transit Stock Quantity"
              },
              {
                "name": "Shortage Amount"
              },
              {
                "name": "Shortage Quantity"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Unrestricted Stock Amount"
              },
              {
                "name": "Unrestricted Stock Quantity"
              },
              {
                "name": "Valuation Class"
              }
            ]
          },
          {
            "name": "Shipment Calendar",
            "columns": [
              {
                "name": "Customer Name"
              },
              {
                "name": "First Scheduled Ship Date"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Shipment Rank"
              },
              {
                "name": "Order Type"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "All Data",
        "description": "Can read all data in the model",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\LBabilo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1731"
          },
          {
            "memberName": "DOMAIN\\JSipkovich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1457"
          },
          {
            "memberName": "DOMAIN\\rfaust",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21470"
          },
          {
            "memberName": "DOMAIN\\jmilliken",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8848"
          },
          {
            "memberName": "DOMAIN\\ahuddlestone",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7281"
          },
          {
            "memberName": "DOMAIN\\amcneill",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7269"
          },
          {
            "memberName": "DOMAIN\\CRussell",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1426"
          },
          {
            "memberName": "DOMAIN\\abratter",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8513"
          },
          {
            "memberName": "DOMAIN\\mebin",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8453"
          },
          {
            "memberName": "DOMAIN\\jmody",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8514"
          },
          {
            "memberName": "DOMAIN\\jmcmanus",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8437"
          },
          {
            "memberName": "DOMAIN\\jjing",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7288"
          },
          {
            "memberName": "DOMAIN\\bmoore",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21012"
          },
          {
            "memberName": "DOMAIN\\sdong",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8750"
          },
          {
            "memberName": "DOMAIN\\rraymundo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2857"
          },
          {
            "memberName": "DOMAIN\\kbesse",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8862"
          },
          {
            "memberName": "DOMAIN\\mqadir",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20430"
          },
          {
            "memberName": "DOMAIN\\lkemp",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8596"
          },
          {
            "memberName": "DOMAIN\\pbitest1",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20421"
          }
        ]
      },
      {
        "name": "By Sales Region",
        "description": "Reads data by sales region",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\bgraiff",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7297"
          },
          {
            "memberName": "DOMAIN\\cjames",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8752"
          },
          {
            "memberName": "DOMAIN\\DCastro",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1777"
          },
          {
            "memberName": "DOMAIN\\DDuncan",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1424"
          },
          {
            "memberName": "DOMAIN\\dpiechocki",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8767"
          },
          {
            "memberName": "DOMAIN\\jsmith",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8622"
          },
          {
            "memberName": "DOMAIN\\lcalma",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6987"
          },
          {
            "memberName": "DOMAIN\\mbraswell",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8601"
          },
          {
            "memberName": "DOMAIN\\mjaffre",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8526"
          },
          {
            "memberName": "DOMAIN\\mpopovich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7298"
          },
          {
            "memberName": "DOMAIN\\ngomez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8600"
          },
          {
            "memberName": "DOMAIN\\pcinski",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7213"
          },
          {
            "memberName": "DOMAIN\\RDaize",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1678"
          },
          {
            "memberName": "DOMAIN\\sterenzi",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8498"
          },
          {
            "memberName": "DOMAIN\\pplessis",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2848"
          },
          {
            "memberName": "DOMAIN\\pbitest1",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20421"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Region",
            "filterExpression": "RLS_Region[DomainName]=USERNAME() && RLS_Region[InactiveDate] < TODAY()",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Territory",
            "metadataPermission": "none"
          }
        ]
      },
      {
        "name": "By Sales Territory",
        "description": "Reads data by sales region",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\aedrei",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4956"
          },
          {
            "memberName": "DOMAIN\\aflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7300"
          },
          {
            "memberName": "DOMAIN\\arodriguez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8655"
          },
          {
            "memberName": "DOMAIN\\cdicillo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8571"
          },
          {
            "memberName": "DOMAIN\\DOrtega",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1408"
          },
          {
            "memberName": "DOMAIN\\gwiant",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8443"
          },
          {
            "memberName": "DOMAIN\\jventola",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8549"
          },
          {
            "memberName": "DOMAIN\\LBurke",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3178"
          },
          {
            "memberName": "DOMAIN\\maybinder",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7141"
          },
          {
            "memberName": "DOMAIN\\tswartout",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8664"
          },
          {
            "memberName": "DOMAIN\\acourtois",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8499"
          },
          {
            "memberName": "DOMAIN\\ajoki",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7308"
          },
          {
            "memberName": "DOMAIN\\jnagel",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7261"
          },
          {
            "memberName": "DOMAIN\\pvangelder",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8484"
          },
          {
            "memberName": "DOMAIN\\rplenzich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7305"
          },
          {
            "memberName": "DOMAIN\\redwards",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-19929"
          },
          {
            "memberName": "DOMAIN\\jkozlowski",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7200"
          },
          {
            "memberName": "DOMAIN\\GDebes",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1711"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Territory",
            "filterExpression": "RLS_Territory[DomainName]=USERNAME() && RLS_Territory[InactiveDate] < TODAY()",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Region",
            "metadataPermission": "none"
          }
        ]
      },
      {
        "name": "Default",
        "description": "Default; Reads data by cost center (mainly for expenses data)",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\amendes",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8652"
          },
          {
            "memberName": "DOMAIN\\aboal",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8718"
          },
          {
            "memberName": "DOMAIN\\CDagher",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1274"
          },
          {
            "memberName": "DOMAIN\\LTorres",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2683"
          },
          {
            "memberName": "DOMAIN\\lurias",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7278"
          },
          {
            "memberName": "DOMAIN\\moconnor",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8550"
          },
          {
            "memberName": "DOMAIN\\RNicholson",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1369"
          },
          {
            "memberName": "DOMAIN\\SabineS",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1423"
          },
          {
            "memberName": "DOMAIN\\sshishani",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8496"
          },
          {
            "memberName": "DOMAIN\\skline",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2799"
          },
          {
            "memberName": "DOMAIN\\tlaunay",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8525"
          },
          {
            "memberName": "DOMAIN\\WSaadat",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1091"
          },
          {
            "memberName": "DOMAIN\\rchen",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8758"
          },
          {
            "memberName": "DOMAIN\\bnovotny",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8604"
          },
          {
            "memberName": "DOMAIN\\edeleon",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6984"
          },
          {
            "memberName": "DOMAIN\\JPerez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1053"
          },
          {
            "memberName": "DOMAIN\\maustria",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6989"
          },
          {
            "memberName": "DOMAIN\\iabarca",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8573"
          },
          {
            "memberName": "DOMAIN\\jcarrizal",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8663"
          },
          {
            "memberName": "DOMAIN\\BDiaz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3188"
          },
          {
            "memberName": "DOMAIN\\pbitest2",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20422"
          },
          {
            "memberName": "DOMAIN\\nnguyen",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8899"
          },
          {
            "memberName": "DOMAIN\\ausandoval",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21488"
          },
          {
            "memberName": "DOMAIN\\efung",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8884"
          },
          {
            "memberName": "DOMAIN\\lmartinez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8901"
          },
          {
            "memberName": "DOMAIN\\JPaciotta",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1641"
          },
          {
            "memberName": "DOMAIN\\caguilar",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21008"
          },
          {
            "memberName": "DOMAIN\\eldiaz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8700"
          },
          {
            "memberName": "DOMAIN\\SCarino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1134"
          },
          {
            "memberName": "DOMAIN\\aarzate",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4946"
          },
          {
            "memberName": "DOMAIN\\agonzalez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8541"
          },
          {
            "memberName": "DOMAIN\\AGutierrez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1795"
          },
          {
            "memberName": "DOMAIN\\arubio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8524"
          },
          {
            "memberName": "DOMAIN\\cflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8506"
          },
          {
            "memberName": "DOMAIN\\cgarcia",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2747"
          },
          {
            "memberName": "DOMAIN\\clopez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7254"
          },
          {
            "memberName": "DOMAIN\\cpham",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8719"
          },
          {
            "memberName": "DOMAIN\\dmendoza",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2760"
          },
          {
            "memberName": "DOMAIN\\EAnuu",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1279"
          },
          {
            "memberName": "DOMAIN\\fesparza",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8456"
          },
          {
            "memberName": "DOMAIN\\GArguello",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4929"
          },
          {
            "memberName": "DOMAIN\\GCatalasan",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1049"
          },
          {
            "memberName": "DOMAIN\\GJimenez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1552"
          },
          {
            "memberName": "DOMAIN\\grosales",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4954"
          },
          {
            "memberName": "DOMAIN\\icruz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8492"
          },
          {
            "memberName": "DOMAIN\\ILopez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1772"
          },
          {
            "memberName": "DOMAIN\\jcandias",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8545"
          },
          {
            "memberName": "DOMAIN\\jfigueroa",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8435"
          },
          {
            "memberName": "DOMAIN\\jignacio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7164"
          },
          {
            "memberName": "DOMAIN\\jluisa",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7160"
          },
          {
            "memberName": "DOMAIN\\jmaradiaga",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7165"
          },
          {
            "memberName": "DOMAIN\\jnicholson",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6995"
          },
          {
            "memberName": "DOMAIN\\jpino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2783"
          },
          {
            "memberName": "DOMAIN\\jsanchez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7229"
          },
          {
            "memberName": "DOMAIN\\jsandoval",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3249"
          },
          {
            "memberName": "DOMAIN\\jvelazquez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7270"
          },
          {
            "memberName": "DOMAIN\\kcamero",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8754"
          },
          {
            "memberName": "DOMAIN\\kmoreno",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2762"
          },
          {
            "memberName": "DOMAIN\\laguilar",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7055"
          },
          {
            "memberName": "DOMAIN\\lflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2784"
          },
          {
            "memberName": "DOMAIN\\LLebron",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3043"
          },
          {
            "memberName": "DOMAIN\\mfranco",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8666"
          },
          {
            "memberName": "DOMAIN\\mignacio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7479"
          },
          {
            "memberName": "DOMAIN\\mpavia",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7053"
          },
          {
            "memberName": "DOMAIN\\rmartinez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7230"
          },
          {
            "memberName": "DOMAIN\\rrivera",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7235"
          },
          {
            "memberName": "DOMAIN\\schio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8653"
          },
          {
            "memberName": "DOMAIN\\TDinh",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1185"
          },
          {
            "memberName": "DOMAIN\\YOrdiano",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1432"
          },
          {
            "memberName": "DOMAIN\\mferraro",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8849"
          },
          {
            "memberName": "DOMAIN\\jdasilva",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7293"
          },
          {
            "memberName": "DOMAIN\\nmartino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8641"
          },
          {
            "memberName": "DOMAIN\\xcai",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21504"
          },
          {
            "memberName": "DOMAIN\\htolla",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20437"
          },
          {
            "memberName": "DOMAIN\\lmota",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21494"
          },
          {
            "memberName": "DOMAIN\\mbenterli",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21472"
          },
          {
            "memberName": "DOMAIN\\rmatteson",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7238"
          },
          {
            "memberName": "DOMAIN\\fzanfi",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21014"
          },
          {
            "memberName": "DOMAIN\\sdiederich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20472"
          },
          {
            "memberName": "DOMAIN\\cchan",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7267"
          },
          {
            "memberName": "DOMAIN\\jnguyen",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8575"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Territory",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Region",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_CostCenter",
            "filterExpression": "RLS_CostCenter[DomainName]=USERNAME() && RLS_CostCenter[InactiveDate] < TODAY()"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}