{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ARLPBIDEV;ARLPBI_STAGE",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ARLPBIDEV",
            "database": "ARLPBI_STAGE"
          },
          "authentication": null,
          "query": null
        },
        "credential": {
          "AuthenticationKind": "Windows",
          "kind": "SQL",
          "path": "arlpbidev;ARLPBI_STAGE",
          "Username": "DOMAIN\\PBI-ETL",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Customer Master",
        "columns": [
          {
            "name": "Customer Number",
            "dataType": "string",
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Account Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "AcctCreateDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Sales Organization",
            "dataType": "string",
            "sourceColumn": "SalesOrganization"
          },
          {
            "name": "Default Ship Plant",
            "dataType": "string",
            "sourceColumn": "DefaultPlant"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesDistrict"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritory"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_CUSTOMER_MASTER = Source{[Schema=\"dbo\",Item=\"VW_CUSTOMER_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_CUSTOMER_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Complaint Documents",
        "columns": [
          {
            "name": "Complaint Number",
            "dataType": "string",
            "sourceColumn": "ComplaintNoKey"
          },
          {
            "name": "Complaint Line Number",
            "dataType": "string",
            "sourceColumn": "ComplaintLineNo"
          },
          {
            "name": "Complaint Type",
            "dataType": "string",
            "sourceColumn": "ComplaintType"
          },
          {
            "name": "Billing Block Indicator",
            "dataType": "string",
            "sourceColumn": "BillingBlockIndicator"
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Complaint Amount",
            "dataType": "double",
            "sourceColumn": "ComplaintValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Last Credit Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "LastCreditDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "type": "calculated",
            "name": "Cycle Time",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " IF([Last Credit Date], DATEDIFF('Complaint Documents'[Enter Date], [Last Credit Date], DAY), BLANK())"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS,{\"ComplaintNoKey\", \"ComplaintLineNo\", \"ComplaintType\", \"BillingBlockIndicator\", \"EnteredBy\", \"EnterDateKey\", \"LastCreditDateKey\", \"ReasonCodeKey\", \"CustomerOrgKey\", \"PlantNoKey\", \"MaterialNoKey\", \"ComplaintValueUSD\", \"CreditIssueValueUSD\", \"OpenValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Reason Code",
        "columns": [
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Reason Code Description",
            "dataType": "string",
            "sourceColumn": "ReasonCodeDescription"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data]",
                "in",
                "    dbo_VW_REASON_CODE"
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PK_Date",
            "formatString": "MM/dd/yyyy",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Year Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal_Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Fiscal_Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month_Name_Abbrev",
            "sortByColumn": "Year_Month_Sort_Key",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Current Month",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Month",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is MTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Mtd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Calendar YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Calendar_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Fiscal YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Fiscal_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Year_Month_Sort_Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Year_Month_Sort_Key"
          },
          {
            "name": "Calendar Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Week_Of_Year"
          },
          {
            "name": "Is Last 2 Fiscal Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last2_Fiscal_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 13 Months",
            "dataType": "boolean",
            "sourceColumn": "Is_Last13_Months",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is_Current_Fiscal_Year",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Fiscal_Year"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_Calendar = Source{[Schema=\"dbo\",Item=\"VW_Calendar\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_Calendar,{{\"PK_Date\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"PK_Date\", \"Year_Name\", \"Month_Of_Year\", \"Quarter_Of_Year_Name\", \"Fiscal_Year_Name\", \"Fiscal_Month_Of_Year\", \"Fiscal_Quarter_Of_Year_Name\", \"Month_Name_Abbrev\", \"Week_Of_Year\", \"Year_Month_Sort_Key\", \"Is_Current_Month\", \"Is_Current_Fiscal_Year\", \"Is_Mtd\", \"Is_Calendar_Ytd\", \"Is_Fiscal_Ytd\", \"Is_Last2_Fiscal_Years\", \"Is_Last13_Months\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year Number"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Calendar Quarter Name"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          },
          {
            "name": "Fiscal Hierarchy",
            "levels": [
              {
                "name": "Fiscal Quarter",
                "ordinal": 1,
                "column": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Number"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DAX Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Measure Column",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{1}"
            }
          }
        ],
        "measures": [
          {
            "name": "Gross Sales",
            "expression": " SUM('Sales Invoice Documents'[Gross Sales Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales",
            "expression": " SUM('Sales Invoice Documents'[Net Sales Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Cost of Goods",
            "expression": " SUM('Sales Invoice Documents'[Overall Cost Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Gross Margin",
            "expression": " [Gross Sales] - [Cost of Goods]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Margin",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Margin",
            "expression": " [Net Sales] - [Cost of Goods]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales\\Margin",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Gross Margin %",
            "expression": " DIVIDE([Gross Margin], [Gross Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales\\Margin"
          },
          {
            "name": "Net Margin %",
            "expression": " DIVIDE( [Net Margin], [Net Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales\\Margin"
          },
          {
            "name": "Complaint Value",
            "expression": " SUM('Complaint Documents'[Complaint Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued",
            "expression": " SUM('Complaint Documents'[Credit Issued Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Value",
            "expression": " SUM('Complaint Documents'[Open Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Complaint Count",
            "expression": " DISTINCTCOUNT( 'Complaint Documents'[Complaint Number] ) + 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Complaints\\Count"
          },
          {
            "name": "PQ Complaint Count",
            "expression": " CALCULATE( [Complaint Count], FILTER( 'Reason Code', 'Reason Code'[Department] = \"Q\") )",
            "formatString": "#,0",
            "displayFolder": "Complaints\\Count"
          },
          {
            "name": "PQ Complaint Value",
            "expression": " CALCULATE( [Complaint Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Credit Issued",
            "expression": " CALCULATE( [Credit Issued], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Open Value",
            "expression": " CALCULATE( [Open Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index",
            "expression": " DIVIDE( [PQ Complaint Value], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Credited)",
            "expression": " DIVIDE( [PQ Credit Issued], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Open)",
            "expression": " DIVIDE( [PQ Open Value], [Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Hold Amount",
            "expression": " SUM('Hold Tag Documents'[Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Hold Tags\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Hold Quantity",
            "expression": " SUM('Hold Tag Documents'[Quantity]) + 0",
            "formatString": "#,0.00",
            "displayFolder": "Hold Tags\\Sum"
          },
          {
            "name": "Hold Tag Count",
            "expression": " DISTINCTCOUNT( 'Hold Tag Documents'[Notification Number] ) + 0",
            "formatString": "#,0",
            "displayFolder": "Hold Tags\\Count"
          },
          {
            "name": "Current S-Block Value",
            "expression": " SUM('Blocked Inventory'[SBlock Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Q-Block Value",
            "expression": " SUM('Blocked Inventory'[QBlock Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Blocked Inv Value",
            "expression": " [Current S-Block Value] + [Current Q-Block Value] + [Current Expired Value]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor Cost",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Cost]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && ('Cost Element Names'[Sub Category] = \"Labor\" || 'Cost Element Names'[Sub Category] = \"Setup\")",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Overhead Cost",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Cost]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Absorption Cost",
            "expression": " [Earned Labor Cost] + [Earned Overhead Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Earned Labor Hours",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Hours]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && ('Cost Element Names'[Sub Category] = \"Labor\" || 'Cost Element Names'[Sub Category] = \"Setup\")",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption\\Sum"
          },
          {
            "name": "Earned Overhead Hours",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM(Absorption[Hours]) + 0,",
              "    FILTER(",
              "        Absorption,",
              "        Absorption[Transaction Type] = \"RKL\"",
              "    ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Company Category] = \"Absorption\" && 'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption\\Sum"
          },
          {
            "name": "MTD Absorption Cost",
            "expression": " [MTD Earned Labor Cost] + [MTD Earned Overhead Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Prior Year Absorption Cost",
            "expression": " [MTD Prior Year Earned Labor Cost] + [MTD Prior Year Earned Overhead Cost]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Earned Labor Cost",
            "expression": " TOTALMTD( [Earned Labor Cost], 'Calendar'[Date] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Prior Year Earned Labor Cost",
            "expression": " TOTALMTD( [Earned Labor Cost], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Earned Overhead Cost",
            "expression": " TOTALMTD( [Earned Overhead Cost], 'Calendar'[Date] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Prior Year Earned Overhead Cost",
            "expression": [
              " TOTALMTD( [Earned Overhead Cost], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
              ""
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "MTD Earned Labor Hours",
            "expression": " TOTALMTD( [Earned Labor Hours], 'Calendar'[Date] )",
            "formatString": "#,0",
            "displayFolder": "Absorption\\Time Intelligence"
          },
          {
            "name": "MTD Prior Year Earned Labor Hours",
            "expression": " TOTALMTD( [Earned Labor Hours], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
            "formatString": "#,0",
            "displayFolder": "Absorption\\Time Intelligence"
          },
          {
            "name": "YTD FY Earned Overhead Cost",
            "expression": [
              "",
              "TOTALYTD( [Earned Overhead Cost], 'Calendar'[Date], ALL('Calendar'), \"09/30\" )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD FY Prior Year Earned Overhead Cost",
            "expression": [
              "",
              "TOTALYTD( [Earned Overhead Cost], SAMEPERIODLASTYEAR( 'Calendar'[Date]), ALL('Calendar'), \"09/30\" )"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Absorption\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Expired Value",
            "expression": " SUM('Expired Inventory'[Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current S-Block Value with Hold Tags",
            "expression": " CALCULATE( SUM('Blocked Inventory'[SBlock Amount])+0, USERELATIONSHIP('Blocked Inventory'[NotificationNoKey], 'Hold Tag Documents'[Notification Number]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index (Target)",
            "expression": "AVERAGE(Target_PQI[TargetValue])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "PQ Complaint Cycle Time",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Complaint Documents'[Cycle Time] ),",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\"",
              "    ),",
              "    USERELATIONSHIP('Calendar'[Date], 'Complaint Documents'[Last Credit Date])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints\\Average"
          },
          {
            "name": "Expenses Amount",
            "expression": " SUM(Expenses[Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Expenses\\Sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "YTD FY Expenses",
            "expression": " TOTALYTD( [Expenses Amount], 'Calendar'[Date] )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Expenses\\Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Invoice Documents",
        "columns": [
          {
            "name": "Invoice Number",
            "dataType": "string",
            "sourceColumn": "SaleDocNoKey"
          },
          {
            "name": "Invoice Line Number",
            "dataType": "string",
            "sourceColumn": "SaleLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales Amount",
            "dataType": "double",
            "sourceColumn": "GrossSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales Amount",
            "dataType": "double",
            "sourceColumn": "NetSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Overall Cost Amount",
            "dataType": "double",
            "sourceColumn": "CostValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Material Cost Amount",
            "dataType": "double",
            "sourceColumn": "MaterialExtPriceUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "double",
            "sourceColumn": "DiscountValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_SALES = Source{[Schema=\"dbo\",Item=\"VW_SALES\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_VW_SALES,{\"MANDT\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Hold Tag Documents",
        "columns": [
          {
            "name": "Notification Number",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Notification Type",
            "dataType": "string",
            "sourceColumn": "NotificationType"
          },
          {
            "name": "Notification Code",
            "dataType": "string",
            "sourceColumn": "NotificationCode"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Reference Number",
            "dataType": "string",
            "sourceColumn": "ReferenceNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Notification Text",
            "dataType": "string",
            "sourceColumn": "NotificationText"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "HoldQuantityValue",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "HoldValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_HOLDTAGS = Source{[Schema=\"dbo\",Item=\"VW_HOLDTAGS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_HOLDTAGS,{\"NotificationNoKey\", \"NotificationType\", \"NotificationCode\", \"EnterDateKey\", \"ReferenceNo\", \"MaterialNoKey\", \"BatchNoKey\", \"NotificationText\", \"QuantityUoM\", \"HoldQuantityValue\", \"HoldValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "NotificationNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "SBlock Quantity",
            "dataType": "double",
            "sourceColumn": "SBlockQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "SBlock Amount",
            "dataType": "double",
            "sourceColumn": "SBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Quantity",
            "dataType": "double",
            "sourceColumn": "QBlockQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "QBlock Amount",
            "dataType": "double",
            "sourceColumn": "QBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Notification Text",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK(LOOKUPVALUE( 'Hold Tag Documents'[Notification Text], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[NotificationNoKey] )), \"NO TAG\", LOOKUPVALUE( 'Hold Tag Documents'[Notification Text], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[NotificationNoKey] ))"
          },
          {
            "type": "calculated",
            "name": "Notification Code",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " IF( ISBLANK(LOOKUPVALUE( 'Hold Tag Documents'[Notification Code], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[NotificationNoKey] )), \"NO TAG\", LOOKUPVALUE( 'Hold Tag Documents'[Notification Code], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[NotificationNoKey] ))"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_BLOCK,{\"MaterialNoKey\", \"BatchNoKey\", \"NotificationNoKey\", \"PlantNo\", \"StorageLoc\", \"SBlockQuantityValue\", \"SBlockAmountUSD\", \"QBlockQuantityValue\", \"QBlockAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expired Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "sourceColumn": "MfgDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Goods Receipt Date",
            "dataType": "dateTime",
            "sourceColumn": "GoodsReceiptDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Expiration Date",
            "dataType": "dateTime",
            "sourceColumn": "ExpirationDate",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "ExpiredQuantityValue",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "ExpiredAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_EXPIRED = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_EXPIRED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_EXPIRED,{\"MaterialNoKey\", \"BatchNo\", \"PlantNo\", \"MfgDate\", \"GoodsReceiptDate\", \"ExpirationDate\", \"StockQuantityValue\", \"ExpiredQuantityValue\", \"StockAmountUSD\", \"ExpiredAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory Snapshots",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "SBlock Value",
            "dataType": "double",
            "sourceColumn": "SBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Value",
            "dataType": "double",
            "sourceColumn": "QBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expired Value",
            "dataType": "double",
            "sourceColumn": "ExpiredValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Blocked Inv Value",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " 'Blocked Inventory Snapshots'[SBlock Value] + 'Blocked Inventory Snapshots'[QBlock Value] + 'Blocked Inventory Snapshots'[Expired Value] + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_DAILY_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"DAILY_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DAILY_INVENTORY_BLOCK,{{\"SnapshotDateKey\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"SnapshotDateKey\", \"PlantNoKey\", \"SBlockValueUSD\", \"QBlockValueUSD\", \"ExpiredValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Absorption",
        "columns": [
          {
            "name": "Process Order",
            "dataType": "string",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "SuperiorMaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SuperiorMaterialNoKey"
          },
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "CostElementKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "BusTransType"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Hours",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "#,0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Cost",
            "dataType": "double",
            "sourceColumn": "NetValue",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_ABSORPTION\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Classification",
        "isHidden": true,
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color Number",
            "dataType": "string",
            "sourceColumn": "ColorNumber"
          },
          {
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "sourceColumn": "CommercializationDate"
          },
          {
            "name": "Film Type",
            "dataType": "string",
            "sourceColumn": "FilmType"
          },
          {
            "name": "Liner",
            "dataType": "string",
            "sourceColumn": "Liner"
          },
          {
            "name": "Product Series",
            "dataType": "string",
            "sourceColumn": "ProductSeries"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_CLASSIFICATION = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_CLASSIFICATION\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_CLASSIFICATION"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Master",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "MaterialNoKey",
            "displayFolder": "Master"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Number - Description",
            "dataType": "string",
            "sourceColumn": "MaterialNoDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "sourceColumn": "MaterialType",
            "displayFolder": "Master"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "sourceColumn": "MaterialGroup",
            "displayFolder": "Master"
          },
          {
            "name": "X Distribution Status",
            "dataType": "string",
            "sourceColumn": "XDistributionStatus",
            "displayFolder": "Master"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasure",
            "displayFolder": "Master"
          },
          {
            "type": "calculated",
            "name": "Brand",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED( 'Material Classification'[Brand] )",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Color Number",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "RELATED( 'Material Classification'[Color Number] )",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Film Type",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Material Classification'[Film Type] )",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Liner",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Material Classification'[Liner] )",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Product Series",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Material Classification'[Product Series] )",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Material Classification'[Commercialization Date] )",
            "formatString": "MM/dd/yyyy",
            "displayFolder": "Classification"
          },
          {
            "type": "calculated",
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Product Hierarchy'[Product Hierarchy L1] )",
            "displayFolder": "Product Hierarchy"
          },
          {
            "type": "calculated",
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Product Hierarchy'[Product Hierarchy L2] )",
            "displayFolder": "Product Hierarchy"
          },
          {
            "type": "calculated",
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Product Hierarchy'[Product Hierarchy L3] )",
            "displayFolder": "Product Hierarchy"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_MASTER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Product Hierarchy",
        "isHidden": true,
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL1"
          },
          {
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL2"
          },
          {
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL3"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_PRODHIERARCHY = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_PRODHIERARCHY\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_PRODHIERARCHY"
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Center Names",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Cost Center Name",
            "dataType": "string",
            "sourceColumn": "CostCenterName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "sortByColumn": "DepartmentSortKey"
          },
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Operations Category",
            "dataType": "string",
            "sourceColumn": "OperationsCategory"
          },
          {
            "name": "DepartmentSortKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DepartmentSortKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COST_CENTER_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_CENTER_NAMES\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_COST_CENTER_NAMES, \"DepartmentSortKey\", each if [Department] = \"COMP\" then 0",
                "else if [Department] = \"CAST\" then 1",
                "else if [Department] = \"PC\" then 2",
                "else if [Department] = \"COAT\" then 3",
                "else if [Department] = \"CONV\" then 4",
                "else 999)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Element Names",
        "columns": [
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Sub Category",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "Category Renamed",
            "dataType": "string",
            "sourceColumn": "CatRenamed"
          },
          {
            "name": "Is Controllable Expense",
            "dataType": "boolean",
            "sourceColumn": "IsControllableExpense"
          },
          {
            "name": "Is Labor",
            "dataType": "boolean",
            "sourceColumn": "IsLabor"
          },
          {
            "name": "Is Supplies",
            "dataType": "boolean",
            "sourceColumn": "IsSupplies"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Cost Element Name",
            "dataType": "string",
            "sourceColumn": "CostElementName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_COST_ELEMENT_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_ELEMENT_NAMES\"]}[Data]",
                "in",
                "    dbo_VW_COST_ELEMENT_NAMES"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_Departments",
        "isHidden": true,
        "columns": [
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_RLS_DEPARTMENT = Source{[Schema=\"dbo\",Item=\"RLS_DEPARTMENT\"]}[Data]",
                "in",
                "    dbo_RLS_DEPARTMENT"
              ]
            }
          }
        ]
      },
      {
        "name": "Departments",
        "isHidden": true,
        "columns": [
          {
            "name": "DepartmentKey",
            "dataType": "string",
            "sourceColumn": "DepartmentKey"
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_zDEPARTMENTS = Source{[Schema=\"dbo\",Item=\"zDEPARTMENTS\"]}[Data]",
                "in",
                "    dbo_zDEPARTMENTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Plant",
        "columns": [
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "PlantDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_PLANT = Source{[Schema=\"dbo\",Item=\"VW_PLANT\"]}[Data]",
                "in",
                "    dbo_VW_PLANT"
              ]
            }
          }
        ]
      },
      {
        "name": "Pending Specification Documents",
        "columns": [
          {
            "name": "Approver Name",
            "dataType": "string",
            "sourceColumn": "ApproverName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Pending Count",
            "dataType": "int64",
            "sourceColumn": "PendingCount",
            "formatString": "0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_SPECAPPROVAL_PENDING = Source{[Schema=\"dbo\",Item=\"VW_SPECAPPROVAL_PENDING\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_SPECAPPROVAL_PENDING,{\"ApproverName\", \"Department\", \"PendingCount\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Target_PQI",
        "isHidden": true,
        "columns": [
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "TargetValue",
            "dataType": "double",
            "sourceColumn": "TargetValue",
            "summarizeBy": "average"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_KPITARGET_PQI = Source{[Schema=\"dbo\",Item=\"VW_KPITARGET_PQI\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_KPITARGET_PQI,{{\"CalendarTimeKey\", type text}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expenses",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "CreateDate",
            "formatString": "MM/dd/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "sourceColumn": "DocumentDate",
            "formatString": "MM/dd/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "UserName"
          },
          {
            "name": "OffsetAcctNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctNoKey"
          },
          {
            "name": "OffsetAcctType",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctType"
          },
          {
            "name": "Document Number",
            "dataType": "string",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Document Line Number",
            "dataType": "string",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Referenced Document Line Number",
            "dataType": "string",
            "sourceColumn": "RefDocLineNo"
          },
          {
            "name": "Is Reversal Document",
            "dataType": "string",
            "sourceColumn": "IsRvrslDoc"
          },
          {
            "name": "Reversal Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RvrslRefDocNo"
          },
          {
            "name": "Is Reversed",
            "dataType": "string",
            "sourceColumn": "IsReversed"
          },
          {
            "name": "PurchaseDocLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseDocLineKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Document Header Text",
            "dataType": "string",
            "sourceColumn": "DocHeaderText"
          },
          {
            "name": "Document Item Text",
            "dataType": "string",
            "sourceColumn": "ItemText"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "Amount",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_EXPENSES = Source{[Schema=\"dbo\",Item=\"VW_EXPENSES\"]}[Data]",
                "in",
                "    dbo_VW_EXPENSES"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7a5e16ad-98c3-4fca-972e-81cd14cf4bdc",
        "toCardinality": "many",
        "fromTable": "Complaint Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "7ad599af-e270-40c4-9adb-251c9dca4378",
        "fromTable": "Complaint Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "7bc6c5a0-4655-407a-bc13-1cd3a65eca38",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "9aea2de3-d4c1-473e-bf03-55a3a8d409f5",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "90d80725-4955-4415-8778-f3b670ded05f",
        "fromTable": "Complaint Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "1196625d-915c-4f90-8a7e-4a4e307c34c4",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "72c7c6a1-aabc-4bfc-8491-7d49d9138e2e",
        "fromTable": "Blocked Inventory",
        "fromColumn": "NotificationNoKey",
        "toTable": "Hold Tag Documents",
        "toColumn": "Notification Number",
        "isActive": false
      },
      {
        "name": "3f9dd1f7-3ac5-4bce-b233-68a54ac9862f",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "bf66fd75-c362-4675-abd4-420fb281ca3f",
        "fromTable": "Absorption",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "637bbb79-1df9-41df-9f01-6327cb2e1ca5",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Material Classification",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "8dbdc264-a57e-48f4-8ccf-064f378c4788",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Product Hierarchy",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "22d61dbe-0265-4bd3-b686-8d76e4f1d50f",
        "fromTable": "Complaint Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "c2395825-7531-4dd0-9c3e-d4e7a214fb64",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "d104f71c-fb20-42c2-a158-df74a0040f19",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "774c8489-a2be-42c4-8a1b-8dffc10c2904",
        "fromTable": "Blocked Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "75f7059e-5891-4145-8c3b-08cf13009c2f",
        "fromTable": "Expired Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "22f5ffae-1a73-4d36-815b-33b46aefbcf9",
        "fromTable": "Absorption",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "48c5cf15-f0eb-40f5-94a2-1dc0d8170fe9",
        "fromTable": "Absorption",
        "fromColumn": "CostCenterKey",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "d066ae9e-c823-4e02-a04e-d7efc467199e",
        "fromTable": "Cost Center Names",
        "fromColumn": "Department",
        "toTable": "Departments",
        "toColumn": "DepartmentKey"
      },
      {
        "name": "640c6b8d-8fc6-40db-ba05-4fb811f6bcc8",
        "fromTable": "RLS_Departments",
        "fromColumn": "Department",
        "toTable": "Departments",
        "toColumn": "DepartmentKey",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "64d69090-8c95-4cfd-bae5-098fdca2fd7c",
        "fromTable": "Complaint Documents",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "69c625ce-25c0-497d-9c3e-a2d15262abe1",
        "fromTable": "Blocked Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "82e0b1e4-2025-48e8-ade7-938129650e46",
        "fromTable": "Expired Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "392923c6-b921-4da9-a0eb-847df9a9ca69",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "04b0a60f-707b-449b-a2cd-587ae883ce11",
        "fromTable": "Calendar",
        "fromColumn": "Year_Month_Sort_Key",
        "toTable": "Target_PQI",
        "toColumn": "CalendarTimeKey",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "ec941efc-23a0-4e1e-8fee-379eafa01610",
        "fromTable": "Complaint Documents",
        "fromColumn": "Last Credit Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "d5fde41f-6d8d-49a1-b78d-1db50db9cab6",
        "fromTable": "Expenses",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "5caa4e78-184b-4b81-8308-65501c7e23e7",
        "fromTable": "Absorption",
        "fromColumn": "CostElementKey",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "e23eac90-b677-4be3-8b2e-bdaa9a94dc93",
        "fromTable": "Expenses",
        "fromColumn": "Cost Element",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "43dc6699-1755-45fc-989b-be3676e258f3",
        "fromTable": "Expenses",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "8dd87143-9d38-46ac-920d-6517fe79d0ed",
        "fromTable": "Expenses",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      }
    ],
    "perspectives": [
      {
        "name": "Absorption Dashboard",
        "tables": [
          {
            "name": "Absorption",
            "columns": [
              {
                "name": "Cost"
              },
              {
                "name": "CostCenterKey"
              },
              {
                "name": "CostElementKey"
              },
              {
                "name": "Hours"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order"
              },
              {
                "name": "SuperiorMaterialNoKey"
              },
              {
                "name": "Transaction Type"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Absorption Cost"
              },
              {
                "name": "Earned Labor Cost"
              },
              {
                "name": "Earned Overhead Cost"
              },
              {
                "name": "Earned Labor Hours"
              },
              {
                "name": "Earned Overhead Hours"
              },
              {
                "name": "MTD Absorption Cost"
              },
              {
                "name": "MTD Earned Labor Cost"
              },
              {
                "name": "MTD Earned Overhead Cost"
              },
              {
                "name": "MTD Prior Year Absorption Cost"
              },
              {
                "name": "MTD Prior Year Earned Labor Cost"
              },
              {
                "name": "MTD Prior Year Earned Overhead Cost"
              },
              {
                "name": "MTD Earned Labor Hours"
              },
              {
                "name": "MTD Prior Year Earned Labor Hours"
              },
              {
                "name": "YTD FY Earned Overhead Cost"
              },
              {
                "name": "YTD FY Prior Year Earned Overhead Cost"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is_Current_Fiscal_Year"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Material Classification",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Product Series"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              }
            ]
          },
          {
            "name": "Product Hierarchy",
            "columns": [
              {
                "name": "Material Number"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Sub Category"
              }
            ]
          },
          {
            "name": "RLS_Departments",
            "columns": [
              {
                "name": "Department"
              },
              {
                "name": "DomainName"
              }
            ]
          },
          {
            "name": "Departments",
            "columns": [
              {
                "name": "DepartmentKey"
              },
              {
                "name": "Name"
              }
            ]
          }
        ]
      },
      {
        "name": "QA Dashboard",
        "tables": [
          {
            "name": "Blocked Inventory",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "NotificationNoKey"
              },
              {
                "name": "Plant"
              },
              {
                "name": "QBlock Amount"
              },
              {
                "name": "QBlock Quantity"
              },
              {
                "name": "SBlock Amount"
              },
              {
                "name": "SBlock Quantity"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Text"
              }
            ]
          },
          {
            "name": "Blocked Inventory Snapshots",
            "columns": [
              {
                "name": "Blocked Inv Value"
              },
              {
                "name": "Expired Value"
              },
              {
                "name": "Plant"
              },
              {
                "name": "QBlock Value"
              },
              {
                "name": "SBlock Value"
              },
              {
                "name": "Snapshot Date"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is_Current_Fiscal_Year"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Complaint Documents",
            "columns": [
              {
                "name": "Billing Block Indicator"
              },
              {
                "name": "Complaint Amount"
              },
              {
                "name": "Complaint Line Number"
              },
              {
                "name": "Complaint Number"
              },
              {
                "name": "Complaint Type"
              },
              {
                "name": "Credit Issued Amount"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "PlantNoKey"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Last Credit Date"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Complaint Count"
              },
              {
                "name": "Complaint Value"
              },
              {
                "name": "Credit Issued"
              },
              {
                "name": "Current Blocked Inv Value"
              },
              {
                "name": "Current Q-Block Value"
              },
              {
                "name": "Current S-Block Value"
              },
              {
                "name": "Gross Sales"
              },
              {
                "name": "Hold Amount"
              },
              {
                "name": "Hold Quantity"
              },
              {
                "name": "Hold Tag Count"
              },
              {
                "name": "Open Value"
              },
              {
                "name": "PQ Complaint Count"
              },
              {
                "name": "PQ Complaint Value"
              },
              {
                "name": "PQ Credit Issued"
              },
              {
                "name": "PQ Open Value"
              },
              {
                "name": "Product Quality Index"
              },
              {
                "name": "Product Quality Index (Credited)"
              },
              {
                "name": "Product Quality Index (Open)"
              },
              {
                "name": "Current Expired Value"
              },
              {
                "name": "Current S-Block Value with Hold Tags"
              },
              {
                "name": "Product Quality Index (Target)"
              },
              {
                "name": "PQ Complaint Cycle Time"
              }
            ]
          },
          {
            "name": "Expired Inventory",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "Hold Tag Documents",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Number"
              },
              {
                "name": "Notification Text"
              },
              {
                "name": "Notification Type"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reference Number"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Reason Code",
            "columns": [
              {
                "name": "Class"
              },
              {
                "name": "Department"
              },
              {
                "name": "Reason Code Description"
              },
              {
                "name": "ReasonCodeKey"
              }
            ]
          },
          {
            "name": "Pending Specification Documents",
            "columns": [
              {
                "name": "Approver Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "Pending Count"
              }
            ]
          }
        ]
      },
      {
        "name": "Expenses",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is_Current_Fiscal_Year"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Expenses",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Creation Date"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Header Text"
              },
              {
                "name": "Document Item Text"
              },
              {
                "name": "Document Line Number"
              },
              {
                "name": "Document Number"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Is Reversal Document"
              },
              {
                "name": "Is Reversed"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "OffsetAcctNoKey"
              },
              {
                "name": "OffsetAcctType"
              },
              {
                "name": "PlantNoKey"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "PurchaseDocLineKey"
              },
              {
                "name": "Referenced Document Line Number"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Reversal Referenced Document Number"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Is Controllable Expense"
              },
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "YTD FY Expenses"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "TestRole",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\pbitest1",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20421"
          },
          {
            "memberName": "DOMAIN\\pbitest2",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20422"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Departments",
            "filterExpression": "RLS_Departments[DomainName]=USERNAME()"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}