{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "type": "structured",
        "name": "ARLPBI_STAGE",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ARLPBIDEV",
            "database": "ARLPBI_STAGE"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "Windows",
          "Username": "DOMAIN\\PBI-ETL",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Customer Master",
        "columns": [
          {
            "name": "Customer Number",
            "dataType": "string",
            "description": "SAP Source: KNA1.KUNNR",
            "sourceColumn": "CustomerNoKey",
            "displayFolder": "Master"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Country",
            "dataType": "string",
            "description": "SAP Source: KNA1.LAND1",
            "sourceColumn": "Country",
            "displayFolder": "Master"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "description": "SAP Source: KNA1.NAME1",
            "sourceColumn": "CustomerName",
            "displayFolder": "Master"
          },
          {
            "name": "Account Creation Date",
            "dataType": "dateTime",
            "description": "SAP Source: KNA1.ERDAT",
            "sourceColumn": "AcctCreateDate",
            "formatString": "Short Date",
            "displayFolder": "Master",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Sales Organization",
            "dataType": "string",
            "description": "SAP Source: KNVV.VKORG",
            "sourceColumn": "SalesOrganization",
            "displayFolder": "Sales Related"
          },
          {
            "name": "Default Ship Plant",
            "dataType": "string",
            "description": "SAP Source: KNVV.VWERK",
            "sourceColumn": "DefaultPlant",
            "displayFolder": "Master"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "description": "SAP Source: KNVV.BZIRK; If the sales territory name contains \"Fleet\", this value is changed to \"FLEET\"",
            "sourceColumn": "SalesDistrict",
            "sortByColumn": "SalesRegionSortKey",
            "displayFolder": "Sales Related"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "description": "SAP Source: KNVV.VKBUR",
            "sourceColumn": "SalesTerritory",
            "displayFolder": "Sales Related"
          },
          {
            "type": "calculated",
            "name": "Is New Customer",
            "dataType": "boolean",
            "isDataTypeInferred": true,
            "description": "A customer is new if the account is created in the last 12 months",
            "expression": " 'Customer Master'[Account Creation Date] >= [Date 12 Months Ago]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "Master"
          },
          {
            "name": "Sales Person",
            "dataType": "string",
            "description": "Assigned manually; Contact IT for more details",
            "sourceColumn": "SalesPerson",
            "displayFolder": "Sales Related"
          },
          {
            "name": "SalesRegionSortKey",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SalesRegionSortKey"
          },
          {
            "name": "Sales Territory Name",
            "dataType": "string",
            "description": "SAP Source: TVKBT.BEZEI",
            "sourceColumn": "SalesTerritoryName",
            "displayFolder": "Sales Related"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_CUSTOMER_MASTER = Source{[Schema=\"dbo\",Item=\"VW_CUSTOMER_MASTER\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_CUSTOMER_MASTER, \"SalesRegionSortKey\", each if [SalesDistrict] = \"DOM\" then 1 else if [SalesDistrict] = \"FLEET\" then 2 else if [SalesDistrict] = \"EUROPE\" then 3 else if [SalesDistrict] = \"LA\" then 4 else if [SalesDistrict] = \"AUS\" then 5 else if [SalesDistrict] = \"ASIA\" then 6 else 9999, type number)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ]
      },
      {
        "name": "Complaint Documents",
        "columns": [
          {
            "name": "Complaint Number",
            "dataType": "string",
            "sourceColumn": "ComplaintNoKey"
          },
          {
            "name": "Complaint Line Number",
            "dataType": "string",
            "sourceColumn": "ComplaintLineNo"
          },
          {
            "name": "Complaint Type",
            "dataType": "string",
            "sourceColumn": "ComplaintType"
          },
          {
            "name": "Billing Block Indicator",
            "dataType": "string",
            "sourceColumn": "BillingBlockIndicator"
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Complaint Amount",
            "dataType": "double",
            "sourceColumn": "ComplaintValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Last Credit Date",
            "dataType": "dateTime",
            "sourceColumn": "LastCreditDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Cycle Time",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": " IF([Last Credit Date], DATEDIFF('Complaint Documents'[Enter Date], [Last Credit Date], DAY), BLANK())"
          },
          {
            "type": "calculated",
            "name": "Category",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": [
              " IF(",
              "    AND(",
              "        RELATED( 'Reason Code'[Department] ) = \"Q\",",
              "        RELATED( 'Material Master'[Material Type] ) = \"HAWA\"",
              "    ),",
              "    \"Buyout\",",
              "    RELATED( 'Reason Code'[Class] )",
              ")"
            ],
            "displayFolder": "Reason Code"
          },
          {
            "name": "ComplaintLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ComplaintLineKey"
          },
          {
            "type": "calculated",
            "name": "Reason Code Description",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Reason Code'[Reason Code Description] )",
            "displayFolder": "Reason Code"
          },
          {
            "type": "calculated",
            "name": "Department",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " RELATED( 'Reason Code'[Department] )",
            "displayFolder": "Reason Code"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS,{\"ComplaintLineKey\", \"ComplaintNoKey\", \"ComplaintLineNo\", \"ComplaintType\", \"BillingBlockIndicator\", \"EnteredBy\", \"EnterDateKey\", \"LastCreditDateKey\", \"ReasonCodeKey\", \"CustomerOrgKey\", \"PlantNoKey\", \"MaterialNoKey\", \"ComplaintValueUSD\", \"CreditIssueValueUSD\", \"OpenValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Calendar",
        "description": "Calendar table used to filter or group multiple fact tables",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PK_Date",
            "formatString": "Short Date",
            "displayFolder": "Individual Attributes",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Calendar Year Number",
            "dataType": "string",
            "sourceColumn": "Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "sourceColumn": "Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Calendar Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "sourceColumn": "Fiscal_Month_Of_Year",
            "displayFolder": "Individual Attributes",
            "summarizeBy": "none"
          },
          {
            "name": "Fiscal Quarter Name",
            "dataType": "string",
            "sourceColumn": "Fiscal_Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "description": "Sorted by fiscal period",
            "sourceColumn": "Month_Name_Abbrev",
            "sortByColumn": "Fiscal Period",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Current Month",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Month",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is MTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Mtd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Calendar YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Calendar_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Fiscal YTD",
            "dataType": "boolean",
            "sourceColumn": "Is_Fiscal_Ytd",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Year_Month_Sort_Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Year_Month_Sort_Key"
          },
          {
            "name": "Calendar Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Week_Of_Year"
          },
          {
            "name": "Is Last 2 Fiscal Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last2_Fiscal_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 13 Months",
            "dataType": "boolean",
            "sourceColumn": "Is_Last13_Months",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Current Fiscal Year",
            "dataType": "boolean",
            "sourceColumn": "Is_Current_Fiscal_Year",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Day",
            "dataType": "int64",
            "sourceColumn": "Day_Of_Month",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Weekday",
            "dataType": "boolean",
            "sourceColumn": "Is_Weekday",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 2 Calendar Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last2_Calendar_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Fiscal Year Month Name",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year_Month_Name",
            "sortByColumn": "Year_Month_Sort_Key",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name (Calendar)",
            "dataType": "string",
            "sourceColumn": "Month_Name_Abbrev_Calendar",
            "sortByColumn": "Calendar Month Number",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Is Last 3 Fiscal Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last3_Fiscal_Years",
            "displayFolder": "Helper Attributes"
          },
          {
            "name": "Is Last 3 Calendar Years",
            "dataType": "boolean",
            "sourceColumn": "Is_Last3_Calendar_Years",
            "displayFolder": "Helper Attributes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_Calendar = Source{[Schema=\"dbo\",Item=\"VW_Calendar\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_Calendar,{{\"PK_Date\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"PK_Date\", \"Year_Name\", \"Month_Of_Year\", \"Quarter_Of_Year_Name\", \"Fiscal_Year_Name\", \"Fiscal_Month_Of_Year\", \"Fiscal_Quarter_Of_Year_Name\", \"Day_Of_Month\", \"Fiscal_Year_Month_Name\", \"Month_Name_Abbrev\", \"Month_Name_Abbrev_Calendar\", \"Week_Of_Year\", \"Year_Month_Sort_Key\", \"Is_Weekday\", \"Is_Current_Month\", \"Is_Current_Fiscal_Year\", \"Is_Mtd\", \"Is_Calendar_Ytd\", \"Is_Fiscal_Ytd\", \"Is_Last2_Fiscal_Years\", \"Is_Last2_Calendar_Years\", \"Is_Last3_Fiscal_Years\", \"Is_Last3_Calendar_Years\", \"Is_Last13_Months\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Calendar Hierarchy",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year Number"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Calendar Quarter Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name (Calendar)"
              }
            ]
          },
          {
            "name": "Fiscal Hierarchy",
            "levels": [
              {
                "name": "Fiscal Quarter",
                "ordinal": 1,
                "column": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Number"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 3,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "DAX Measures",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Value]"
          },
          {
            "type": "calculated",
            "name": "Sales Invoice",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Complaints",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Inventory",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Expenses",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Sales Orders",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Purchase Orders",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "GRIR",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "Absorption Measure",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          },
          {
            "type": "calculated",
            "name": "CONV Dashboard",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": "{1}"
            }
          }
        ],
        "measures": [
          {
            "name": "Gross Sales",
            "description": "(SAP Source: Sum of CE110US.ERLOS)",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Gross Sales Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents', 'Sales Invoice Documents'[Gross Sales Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Gross Sales Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Gross Sales Amount] )    ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Sales",
            "description": "Net of gross sales and discounts; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Net Sales Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents',  'Sales Invoice Documents'[Net Sales Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Net Sales Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Net Sales Amount] )    ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales"
          },
          {
            "name": "Overall Cost",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Invoice Documents'[Overall Cost Amount] ),",
              "        \"Local\", SUMX( 'Sales Invoice Documents', 'Sales Invoice Documents'[Overall Cost Amount] * 'Sales Invoice Documents'[Exchange Rate] ),",
              "        SUM('Sales Invoice Documents'[Overall Cost Amount] )",
              "    ),",
              "    SUM('Sales Invoice Documents'[Overall Cost Amount] )    ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales"
          },
          {
            "name": "Gross Margin",
            "description": "Net of gross sales and overall cost; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " SUM( 'Sales Invoice Documents'[Gross Margin Amount] )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [Net Sales] - [Overall Cost]",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales"
          },
          {
            "name": "Gross Margin %",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE([Gross Margin], [Gross Sales])",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales"
          },
          {
            "name": "Net Margin %",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [Net Margin], [Net Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales"
          },
          {
            "name": "Complaint Value",
            "expression": " SUM('Complaint Documents'[Complaint Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Credit Issued",
            "expression": " SUM('Complaint Documents'[Credit Issued Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Open Value",
            "expression": " SUM('Complaint Documents'[Open Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "isHidden": true,
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Complaint Count",
            "expression": " DISTINCTCOUNT( 'Complaint Documents'[Complaint Number] ) + 0",
            "formatString": "#,0",
            "isHidden": true,
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Complaint Count], FILTER( 'Reason Code', 'Reason Code'[Department] = \"Q\") )",
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Value",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Complaint Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Credit Issued",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Credit Issued], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "PQ Open Value",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " CALCULATE( [Open Value], FILTER('Reason Code', 'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\") )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Credited)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Credit Issued], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Product Quality Index (Open)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": " DIVIDE( [PQ Open Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Hold Amount",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " SUM('Hold Tag Documents'[Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Hold Tags",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Hold Quantity",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " SUM('Hold Tag Documents'[Quantity])",
            "formatString": "#,0.00",
            "displayFolder": "Hold Tags"
          },
          {
            "name": "Hold Tag Count",
            "description": "Date grouping: 'Hold Tag Documents'[Enter Date]",
            "expression": " DISTINCTCOUNT( 'Hold Tag Documents'[Notification Number] )",
            "formatString": "#,0",
            "displayFolder": "Hold Tags"
          },
          {
            "name": "Current S-Block Value",
            "expression": " SUM('Blocked Inventory'[SBlock Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Q-Block Value",
            "expression": " SUM('Blocked Inventory'[QBlock Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Blocked Inv Value",
            "expression": " [Current S-Block Value] + [Current Q-Block Value] + [Current Expired Value]",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current Expired Value",
            "expression": " SUM('Expired Inventory'[Amount])",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Current S-Block Value with Hold Tags",
            "expression": " CALCULATE( SUM('Blocked Inventory'[SBlock Amount])+0, USERELATIONSHIP('Blocked Inventory'[Notification Number], 'Hold Tag Documents'[Notification Number]) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Blocked Inv",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Product Quality Index (Target)",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"PQI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "PQ Complaint Cycle Time",
            "description": "Date grouping: 'Complaint Documents'[Last Credit Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( 'Complaint Documents'[Cycle Time] ),",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"Q\" && LEFT('Reason Code'[Reason Code Description], 8) <> \"WARRANTY\"",
              "    ),",
              "    USERELATIONSHIP('Calendar'[Date], 'Complaint Documents'[Last Credit Date])",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "Expenses Amount",
            "description": "Date grouping: 'Expenses'[Posting Date]",
            "expression": " SUM(Expenses[Amount]) + 0",
            "formatString": "$#,##0;($#,##0);\"-\"",
            "displayFolder": "Expenses"
          },
          {
            "name": "Expenses Plan",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( Target_Expenses[TargetValue]) + 0,",
              "    FILTER(",
              "        ALL( Target_Expenses[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_Expenses[CalendarTimeKey]",
              "        )",
              "    ),",
              "    FILTER(",
              "        ALL( Target_Expenses[CostCenterKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Cost Center Names'[Cost Center] ),",
              "            'Cost Center Names'[Cost Center], Target_Expenses[CostCenterKey]",
              "        )",
              "    ),",
              "    FILTER(",
              "        ALL( Target_Expenses[CostElementKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Cost Element Names'[Cost Element] ),",
              "            'Cost Element Names'[Cost Element], Target_Expenses[CostElementKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "$#,##0;($#,##0);\"-\"",
            "isHidden": true,
            "displayFolder": "Expenses"
          },
          {
            "name": "SQ Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complaint Count], ",
              "    FILTER(",
              "        'Reason Code', ",
              "        'Reason Code'[Department] = \"S\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "SQ Complaint Value",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Complaint Documents - Credited'[Credit Issued Amount] ) + 0,",
              "    'Complaint Documents'[Billing Block Indicator] = \"\",",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"S\"",
              "    ),",
              "    USERELATIONSHIP(",
              "        'Calendar'[Date],",
              "        'Complaint Documents - Credited'[Credit Issued Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CA Complaint Value",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Complaint Documents - Credited'[Credit Issued Amount] ) + 0,",
              "    'Complaint Documents'[Billing Block Indicator] = \"\",",
              "    FILTER(",
              "        'Reason Code',",
              "        'Reason Code'[Department] = \"S1\"",
              "    ),",
              "    USERELATIONSHIP(",
              "        'Calendar'[Date],",
              "        'Complaint Documents - Credited'[Credit Issued Date]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Complaints",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "CA Complaint Count",
            "description": "Date grouping: 'Complaint Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [Complaint Count], ",
              "    FILTER(",
              "        'Reason Code', ",
              "        'Reason Code'[Department] = \"S1\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Complaints"
          },
          {
            "name": "Service Quality Index",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": " DIVIDE( [SQ Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "Customer Accommodation Index",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": " DIVIDE( [CA Complaint Value], CALCULATE( [Gross Sales], ALL( 'Customer Master' ) ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints"
          },
          {
            "name": "Service Quality Index (Target)",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"SQI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Customer Accommodation Index (Target)",
            "description": "Date grouping: 'Complaint Documents - Credited'[Credit Issued Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    AVERAGE( Target_KPI[TargetValue] ),",
              "    Target_KPI[KpiKey] = \"CAI\",",
              "    FILTER(",
              "        ALL( Target_KPI[CalendarTimeKey] ),",
              "        CONTAINS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            'Calendar'[Year_Month_Sort_Key], Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Complaints\\KPI"
          },
          {
            "name": "Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " SUM( 'Sales Order Documents'[Order Amount]) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales Orders",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sales Order Cost Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " SUM( 'Sales Order Documents'[Cost Amount] ) + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales Orders",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Date 12 Months Ago",
            "expression": " EOMONTH( EDATE( TODAY() - 1, -12), -1) + 1",
            "formatString": "Short Date",
            "isHidden": true,
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Sales Order Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DISTINCTCOUNT(  'Sales Order Documents'[Order Number] )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Sales], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Sales], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Margin], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin %], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Margin %], DATESYTD( 'Calendar'[Date], \"9/30\" ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Margin%], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Gross Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [FYTD Gross Margin%], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "0%;-0%;\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Gross Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [MTD Gross Margin], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " IF( NOT( OR(ISBLANK([FYTD Gross Sales]), ISBLANK([FYTD PY Gross Sales]) ) ), [FYTD Gross Sales] - [FYTD PY Gross Sales], BLANK() )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Gross Sales Budget",
            "description": "Budget numbers submitted by Sales to IT; Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Targets_Sales[GrossSales] ),",
              "    TREATAS(",
              "        VALUES( 'Customer Master'[Sales Territory] ),",
              "        Targets_Sales[SalesTerritoryKey]",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "        Targets_Sales[CalendarTimeKey]",
              "    )",
              ")"
            ],
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Sales",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Backorder Amount",
            "description": "Total customer open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship on or before the end of current month; Internal open amount is ordered minus allocated minus shipped amount; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] <= [End of Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Margin",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "IF(",
              "    HASONEVALUE( '_Currency to Use'[Currency] ),",
              "    SWITCH(",
              "        VALUES( '_Currency to Use'[Currency] ),",
              "        \"USD\", SUM( 'Sales Order Documents'[Margin Amount] ),",
              "        \"Local\", SUM( 'Sales Order Documents'[Margin Amount Local] ),",
              "        SUM( 'Sales Order Documents'[Margin Amount] )",
              "    ),",
              "    SUM( 'Sales Order Documents'[Margin Amount] )  ",
              ") + 0"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Margin",
            "description": "Total margin of internally open sales order items (TA, ZCON, and ZDSP) originally scheduled to ship on or before the end of current month; Internal open amount is ordered minus allocated minus shipped amount; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Margin],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] <= [End of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " SUM( 'Sales Invoice Documents'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Sales"
          },
          {
            "name": "MTD PY Var Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " IF( NOT( OR(ISBLANK([MTD Gross Sales]), ISBLANK([MTD PY Gross Sales]) ) ), [MTD Gross Sales] - [MTD PY Gross Sales], BLANK() )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var% Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [MTD PY Var Gross Sales], [MTD PY Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var% Gross Sales",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [FYTD PY Var Gross Sales], [FYTD PY Gross Sales] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Quantity Sold], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Quantity Sold",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Quantity Sold], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Yesterday",
            "expression": " TODAY() - 1",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Beginning of Month",
            "expression": " EOMONTH( [Yesterday], -1 ) + 1",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "End of Month",
            "expression": " EOMONTH( [Yesterday], 0 )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "MTD Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Amount], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [MTD Sales Order Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "IF( ",
              "    AND( ",
              "        NOT(ISBLANK([MTD Sales Order Amount])), ",
              "        NOT(ISBLANK([MTD PY Sales Order Amount])) ",
              "    ), ",
              "    [MTD Sales Order Amount] - [MTD PY Sales Order Amount], ",
              "    BLANK() ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Var% Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [MTD PY Var Sales Order Amount], [MTD PY Sales Order Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Amount], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [FYTD Sales Order Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "IF( ",
              "    AND( ",
              "        NOT(ISBLANK([FYTD Sales Order Amount])), ",
              "        NOT(ISBLANK([FYTD PY Sales Order Amount])) ",
              "    ), ",
              "    [FYTD Sales Order Amount] - [FYTD PY Sales Order Amount], ",
              "    BLANK() ",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Var% Sales Order Amount",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [FYTD PY Var Sales Order Amount], [FYTD PY Sales Order Amount] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "SO Internal Open Quantity",
            "description": "If processing status is not complete, this value is ordered minus allocated minus shipped quantities; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Internal Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Customer Open Quantity",
            "description": "If billing status is not complete, this value is ordered minus shipped quantities; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              "  ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Customer Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")",
              ""
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Internal Open Amount",
            "description": "If processing status is not complete, this value is ordered minus allocated minus shipped amount;Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Internal Open Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Internal Open Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Internal Open Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Internal Open Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Customer Open Amount",
            "description": "If billing status is not complete, this value is ordered minus shipped amount; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Customer Open Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Customer Open Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Customer Open Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Customer Open Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Ordered Quantity",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": "SUM( 'Sales Order Documents'[Order Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Allocated Quantity",
            "description": "Total quantity in delivery notes issued without an actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Allocated Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Shipped Quantity",
            "description": "Total quantity in delivery notes issued with actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Sales Order Documents'[Shipped Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "In Stock Measure",
            "description": "Applies to open orders only; Indicates if an item is available in stock (FIFO by first scheduled ship date); Note that this calculation is report-side which means the material is not actually allocated to the order in SAP",
            "expression": " PRODUCT( 'Sales Order Documents'[In Stock] )",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Gross Margin% Budget",
            "description": "Budget numbers submitted by Sales to IT",
            "expression": [
              "",
              "CALCULATE(",
              "\tCALCULATE(",
              "        SUM( Targets_Sales[GrossMarginMTD] ),",
              "        FILTER( Targets_Sales, Targets_Sales[GrossMarginMTD] <> 0 ),",
              "        TREATAS(",
              "            VALUES( 'Customer Master'[Sales Territory] ),",
              "            Targets_Sales[SalesTerritoryKey]",
              "        ),",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Targets_Sales[CalendarTimeKey]",
              "        )",
              "    ),",
              "    DATESMTD( 'Calendar'[Date] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Margin% Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    CALCULATE(",
              "        AVERAGE( Targets_Sales[GrossMarginYTD] ),",
              "        FILTER( Targets_Sales, Targets_Sales[GrossMarginYTD] <> 0 ),",
              "        TREATAS(",
              "            VALUES( 'Customer Master'[Sales Territory] ),",
              "            Targets_Sales[SalesTerritoryKey]",
              "        ),",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Targets_Sales[CalendarTimeKey]",
              "        )",
              "    ),",
              "    DATESMTD( 'Calendar'[Date] )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [MTD Gross Sales] + [Backorder Amount]",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [MTD Gross Margin] + [Backorder Margin]",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales & Backorder Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [MTD Gross Sales & Backorder Margin], [MTD Gross Sales & Backorder] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Gross Sales Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales Budget], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "FYTD Gross Sales Budget",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " CALCULATE( [Gross Sales Budget], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "Time Intelligence",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "FYTD Gross Sales & Backorder",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [FYTD Gross Sales] + [Backorder Amount]",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales & Backorder Margin",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " [FYTD Gross Margin] + [Backorder Margin]",
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Gross Sales & Backorder Margin%",
            "description": "Date grouping: 'Sales Invoice Documents'[Posting Date]",
            "expression": " DIVIDE( [FYTD Gross Sales & Backorder Margin], [FYTD Gross Sales & Backorder] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PO Ordered Quantity",
            "expression": " SUM( 'Purchase Orders'[Ordered Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Open Quantity",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Orders - Deliveries'[Open Quantity] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Purchase Orders - Deliveries'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Ordered Amount",
            "expression": " SUM( 'Purchase Orders'[Ordered Amount] )",
            "formatString": "#,0",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Open Amount",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Orders - Deliveries'[Open Amount] ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Purchase Orders - Deliveries'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Delivered Quantity",
            "expression": " SUM( 'Stock Transfer Orders'[Delivered Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO In Transit Quantity",
            "expression": " SUM( 'Stock Transfer Orders'[In Transit Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "GRIR Amount (Document)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM('Goods and Invoice Receipts'[Amount (Document)])",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Amount (Local)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM('Goods and Invoice Receipts'[Amount (Local)])",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Amount (Local2)",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM( 'Goods and Invoice Receipts'[Amount (Local2)] )",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Quantity",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": " SUM( 'Goods and Invoice Receipts'[Quantity] )",
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Open Amount",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", [GRIR Amount (Local2)],",
              "            \"Local\", [GRIR Amount (Local)],",
              "            [GRIR Amount (Local2)]",
              "        ),",
              "        [GRIR Amount (Local2)]",
              "    ),",
              "    FILTER(",
              "        'Goods and Invoice Receipts',",
              "        'Goods and Invoice Receipts'[Clearing Date] > MAX( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "GRIR Open Quantity",
            "description": "Date grouping: 'Goods and Invoice Receipts'[Posting Date]",
            "expression": [
              "",
              "CALCULATE(",
              "    [GRIR Quantity],",
              "    FILTER(",
              "        'Goods and Invoice Receipts',",
              "        'Goods and Invoice Receipts'[Clearing Date] > MAX( 'Calendar'[Date] )",
              "    )",
              ")"
            ],
            "formatString": "#,##0.00;(#,##0.00);\"-\"",
            "displayFolder": "GRIR"
          },
          {
            "name": "PO Invoice Receipt Amount",
            "description": "Sum of invoice receipt amount in purchase order history. See 'Time Intelligence' folder for the FYTD versions; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " SUM( 'Purchase Order Invoices'[Amount] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "PO Invoice Receipt Quantity",
            "description": "Sum of invoice receipt quantity in purchase order history (in purchase order unit). See 'Time Intelligence' folder for the FYTD versions; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " SUM( 'Purchase Order Invoices'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Purchase Orders"
          },
          {
            "name": "FYTD PO Invoice Receipt Amount",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [PO Invoice Receipt Amount], DATESYTD( 'Calendar'[Date] , \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Quantity",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [PO Invoice Receipt Quantity], DATESYTD( 'Calendar'[Date] , \"09/30\" ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Amount",
            "description": "Last positive invoice receipt amount from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number.",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Amount], FILTER( 'Purchase Order Invoices', 'Purchase Order Invoices'[PostingRank] = 1 ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Quantity",
            "description": "Last positive invoice receipt quantity from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Quantity], FILTER( 'Purchase Order Invoices', 'Purchase Order Invoices'[PostingRank] = 1 ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Amount",
            "description": "Last positive invoice receipt amount from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD Last PO Invoice Receipt Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Quantity",
            "description": "Last positive invoice receipt quantity from purchase order history based on material number, posting fiscal year, and purchase order unit ordered by posting date, material document number, and material document line number; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD Last PO Invoice Receipt Quantity], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Unit Price",
            "description": "FYTD total invoice receipt amount divided quantity; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Last PO Invoice Receipt Unit Price",
            "description": "Amount divided quantity of the last invoice receipt in purchase order history on current fiscal year; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD Last PO Invoice Receipt Amount], [FYTD Last PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PO Invoice Receipt Amount in PY Price",
            "description": "Current year's invoice receipt amount using prior fiscal year's last unit price. If the material is not sold in the previous fiscal year, use current fiscal year's amount; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Order Invoices'[Amount at Last PY Price] ),",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Difference",
            "description": "Difference between current fiscal year's actual invoice receipt amount and the amount using prior fiscal year's last unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( 'Purchase Order Invoices'[Price Difference] ),",
              "    DATESYTD( 'Calendar'[Date], \"09/30\" )",
              ")"
            ],
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Last PO Invoice Receipt Unit Price",
            "description": "Amount divided quantity of the last invoice receipt in purchase order history on previous fiscal year; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " DIVIDE( [FYTD PY Last PO Invoice Receipt Amount], [FYTD PY Last PO Invoice Receipt Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Index%",
            "description": "Current fiscal year's invoice receipt amount as a percentage of the same amount using prior fiscal year's unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": [
              " ",
              "IF(",
              "    [FYTD PO Invoice Receipt Amount in PY Price] = 0,",
              "    BLANK(),",
              "    DIVIDE([FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Amount in PY Price]) - 1",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Purchase Price Index",
            "description": "Current fiscal year's invoice receipt amount divided by the same amount using prior fiscal year's unit price; Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " ROUND(DIVIDE( [FYTD PO Invoice Receipt Amount], [FYTD PO Invoice Receipt Amount in PY Price] ), 4)",
            "formatString": "0.0000",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY PO Invoice Receipt Amount",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Amount], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY PO Invoice Receipt Quantity",
            "description": "Date grouping: 'Purchase Order Invoices'[Posting Date]",
            "expression": " CALCULATE( [FYTD PO Invoice Receipt Quantity], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0.00",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Backorder Amount (Past Due)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship before the current month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] < [Beginning of Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] < [Beginning of Month]",
              "    )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Amount (Current Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship on current month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] >= [Beginning of Month]",
              "            && 'Sales Order Documents'[First Delivery Date] <= [End of Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] >= [Beginning of Month]",
              "            && 'Calendar'[Date] <= [End of Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "End of Next Month",
            "expression": " EOMONTH( [Yesterday], 1 )",
            "formatString": "Short Date",
            "displayFolder": ".Dates",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Backorder Amount (Next Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship starting next month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] > [End of Month]",
              "            && 'Sales Order Documents'[First Delivery Date] <= [End of Next Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] > [End of Month]",
              "            && 'Calendar'[Date] <= [End of Next Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Backorder Amount (Beyond Next Month)",
            "description": "Total internal open amount of sales orders (TA, ZCON, and ZDSP) originally scheduled to ship after next month; Internal open amount is ordered minus allocated minus shipped amount.",
            "expression": [
              "",
              "CALCULATE(",
              "    [SO Customer Open Amount],",
              "    FILTER(",
              "        ALL( 'Sales Order Documents'[First Delivery Date] ),",
              "        'Sales Order Documents'[First Delivery Date] > [End of Next Month]",
              "    ),",
              "    FILTER(",
              "        ALL( 'Calendar'[Date] ),",
              "        'Calendar'[Date] > [End of Next Month]",
              "    )",
              ")",
              ""
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Earned Labor",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Absorption[Amount] ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Sub Category] IN {\"Labor\", \"Setup\"}",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Earned Overhead",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM( Absorption[Amount] ),",
              "    FILTER(",
              "        'Cost Element Names',",
              "        'Cost Element Names'[Sub Category] = \"Overhead\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": " [Earned Labor] + [Earned Overhead]",
            "formatString": "#,0",
            "displayFolder": "Absorption"
          },
          {
            "name": "Sales Order Lines Automated",
            "description": "Number of sales order line items entered by BATCHUSER (sales order automation); Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " COUNTROWS( FILTER( 'Sales Order Documents', 'Sales Order Documents'[Entered By] = \"BATCHUSER\" ) )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Line Count",
            "description": "Number of sales order line items; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " COUNTROWS( 'Sales Order Documents' )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Lines Automated Entry%",
            "description": "Number of sales order line items entered by BATCHUSER divided by sales order line count entered by Customer Service and BATCHUSER; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "DIVIDE( ",
              "    [Sales Order Lines Automated],",
              "    [Sales Order Line Count (Automated + Manual)]",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Lines Manual",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], FILTER( 'SAP Users', 'SAP Users'[Department] = \"CUSTOMER SERVICE\") )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "FYTD Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD PY Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [FYTD Sales Order Line Count], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "FYTD Sales Order Lines Automated Entry%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated Entry%], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Lines Automated Entry%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated Entry%], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Line Count",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Line Count], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Sales Order Lines Automated (No Changes)",
            "description": "Number of sales order line items entered by BATCHUSER (sales order automation) without manual changes from Customer Service; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Lines Automated], 'Sales Order Documents'[Has Changes (CS)] = 0 )",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [Sales Order Lines Automated (No Changes)], [Sales Order Lines Automated] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "FYTD Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Automation Efficiency%], DATESYTD( 'Calendar'[Date], \"09/30\" ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD Sales Order Automation Efficiency%",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " CALCULATE( [Sales Order Automation Efficiency%], DATESMTD( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Sales Order Lines Manual Entry%",
            "description": "Number of sales order line items entered by Customer Service divided by sales order line count entered by Customer Service and BATCHUSER; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " DIVIDE( [Sales Order Lines Manual], [Sales Order Line Count (Automated + Manual)] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "Sales Order Line Count (Automated + Manual)",
            "description": "Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": " [Sales Order Lines Manual] + [Sales Order Lines Automated]",
            "formatString": "#,0",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "MTD Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [Absorption], DATESMTD( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "MTD PY Absorption",
            "description": "Date grouping: 'Absorption'[Posting Date]",
            "expression": [
              " CALCULATE( [MTD Absorption], SAMEPERIODLASTYEAR( 'Calendar'[Date] ) )",
              ""
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD PO Backorder Amount",
            "description": "Sum of open UB, NB, and ZNB purchase orders with GR requirement scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": [
              " ",
              "CALCULATE( ",
              "    SUM( 'Backorder Snapshots'[Incoming] ), ",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] = MAX( 'Calendar'[Date] ) - 1",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Material Master'[Material Type] ),",
              "        'Backorder Snapshots'[Material Type]",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Purchase Orders'[Document Type] ),",
              "        'Backorder Snapshots'[Order Type]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD Var PO Open Amount",
            "description": "Variance of PO Open Amount to prior day's open amount (PD PO Backorder Amount) which is the sum of open UB, NB, and ZNB purchase orders with GR requirement scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": " [PO Open Amount] - [PD PO Backorder Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "SO Customer Open Margin",
            "description": "If billing status is not complete, this value is margin amount of non-shipped; Date grouping: 'Sales Order Documents'[Enter Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Customer Open Margin Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Customer Open Margin Amount (Local)] ),",
              "            SUM( 'Sales Order Documents'[Customer Open Margin Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Customer Open Margin Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "PD SO Customer Open Amount",
            "description": "Sum of open TA and ZCON sales orders with with active/pre-launch product status, no credit block, has product tier code, and scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date]). Excludes BURLINGTON GRAPHICS customer.",
            "expression": [
              " ",
              "CALCULATE(",
              "    SUM('Backorder Snapshots'[Outgoing]),",
              "    FILTER(",
              "        'Calendar',",
              "        'Calendar'[Date] = MAX( 'Calendar'[Date] ) - 1",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Material Master'[Material Type] ),",
              "        'Backorder Snapshots'[Material Type]",
              "    ),",
              "    TREATAS(",
              "        VALUES( 'Sales Order Documents'[Order Type] ),",
              "        'Backorder Snapshots'[Order Type]",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD Var SO Customer Open Amount",
            "description": "Variance of SO Customer Open Amount to prior day's open amount (PD SO Customer Open Amount) which is the sum of open TA and ZCON sales orders with with active/pre-launch product status, no credit block, has product tier code, and scheduled to be delivered up to prior day (date context: Snapshot Date or 'Calendar'[Date])",
            "expression": " [SO Customer Open Amount] - [PD SO Customer Open Amount]",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "GR Linear Footage",
            "description": "Total footage of postings with movement types 101, 102, 531, and 532.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Goods Issues and Receipts'[Linear Feet] ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"101\", \"531\", \"102\", \"532\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"555\", \"700\" }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GR Square Footage",
            "description": "Total square footage of postings with movement types 101, 102, 531, and 532.",
            "expression": [
              "",
              "CALCULATE(",
              "    SUM( 'Goods Issues and Receipts'[Square Feet] ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"101\", \"531\", \"102\", \"532\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"555\", \"700\" }",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GI Linear Footage",
            "description": "Total footage of postings with movement types 261, 262, 551, and 552.",
            "expression": [
              "",
              "CALCULATE(",
              "    ABS( SUM( 'Goods Issues and Receipts'[Linear Feet] ) ),",
              "    FILTER(",
              "        'Goods Issues and Receipts',",
              "        'Goods Issues and Receipts'[Movement Type] IN {\"261\", \"551\", \"262\", \"552\"}",
              "            && 'Goods Issues and Receipts'[Storage Bin] IN {\"600\", \"700\", \"733\", \"734\", \"735\", \"736\", \"88\", \"182\", \"782\"}",
              "            && 'Goods Issues and Receipts'[Reason Code] <> \"0000\"",
              "    )",
              ")"
            ],
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GI Scrap Rate",
            "description": "GI Footage over GR Footage",
            "expression": " DIVIDE( [GI Linear Footage], [GR Linear Footage] )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Linear Footage",
            "expression": " SUM ('Goods Issues and Receipts'[Linear Feet])",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Square Footage",
            "expression": " SUM ('Goods Issues and Receipts'[Square Feet])",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Quantity",
            "expression": " SUM( 'Goods Issues and Receipts'[Quantity])",
            "formatString": "#,0.00",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "GIR Amount",
            "expression": " SUM( 'Goods Issues and Receipts'[Amount] )",
            "formatString": "#,0",
            "displayFolder": "Goods Receipts and Issues"
          },
          {
            "name": "SO Allocated Amount",
            "description": "Total value of items in delivery notes issued without an actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              " ",
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Allocated Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Allocated Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Allocated Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Allocated Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "SO Shipped Amount",
            "description": "Total value of items in delivery notes issued with actual PGI date set; Date grouping: 'Sales Order Documents'[First Delivery Date]",
            "expression": [
              "CALCULATE(",
              "    IF(",
              "        HASONEVALUE( '_Currency to Use'[Currency] ),",
              "        SWITCH(",
              "            VALUES( '_Currency to Use'[Currency] ),",
              "            \"USD\", SUM( 'Sales Order Documents'[Shipped Amount] ),",
              "            \"Local\", SUM( 'Sales Order Documents'[Shipped Amount Local] ),",
              "            SUM( 'Sales Order Documents'[Shipped Amount] )",
              "        ),",
              "        SUM( 'Sales Order Documents'[Shipped Amount] )   ",
              "    ),",
              "    USERELATIONSHIP( 'Calendar'[Date], 'Sales Order Documents'[First Delivery Date] )",
              ")"
            ],
            "formatString": "#,##0;(#,##0);\"-\"",
            "displayFolder": "Sales Orders"
          },
          {
            "name": "CONV Production Hours",
            "description": "The number of hours across all converting employees when they are producing material",
            "expression": " SUM( 'Converting Man Hours'[Production Hours] )",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Available Hours",
            "description": "The total number of hours converting is scheduled to work within a shift (excluding breaks and lunch)",
            "expression": " SUM( 'Converting Man Hours'[Available Hours] )",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour",
            "description": "Total number of square footage over total production hours in Converting",
            "expression": " DIVIDE( [GR Square Footage], [CONV Production Hours] )",
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour (Target)",
            "description": "These values are provided by Converting at the beginning of the fiscal year. If none provided, the default value used is 5,000.",
            "expression": [
              " ",
              "VAR TargetVal = ",
              "    CALCULATE(",
              "        SUM( Target_KPI[TargetValue] ),",
              "        Target_KPI[KpiKey] = \"Sqftmh\",",
              "        TREATAS(",
              "            VALUES( 'Calendar'[Year_Month_Sort_Key] ),",
              "            Target_KPI[CalendarTimeKey]",
              "        )",
              "    )",
              "RETURN",
              "    IF(",
              "        ISBLANK( TargetVal ),",
              "        5000,",
              "        TargetVal",
              "    )",
              " "
            ],
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Square Feet per Man Hour (Target Variance)",
            "expression": " [CONV Square Feet per Man Hour] - [CONV Square Feet per Man Hour (Target)]",
            "formatString": "#,0",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Uptime Hours",
            "expression": " SUM( 'Converting Uptime'[Uptime Seconds] ) / 60 / 60",
            "formatString": "#,0.00",
            "displayFolder": "Converting"
          },
          {
            "name": "CONV Availability",
            "description": "Converting uptime hours divided by available hours",
            "expression": [
              " ",
              "AVERAGEX(",
              "    VALUES( 'Converting Uptime'[Machine Name] ),",
              "    CALCULATE(",
              "        AVERAGEX(",
              "            VALUES( 'Calendar'[Date] ),",
              "            DIVIDE( [CONV Uptime Hours], [CONV Available Hours] )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Converting"
          },
          {
            "name": "PD GR Linear Footage",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GR Linear Footage],PREVIOUSDAY('Calendar'[Date]) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD GI Linear Footage",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GI Linear Footage], PREVIOUSDAY( 'Calendar'[Date] ) )",
            "formatString": "#,0",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "PD GI Scrap Rate",
            "description": "If this is used without the date field, this measure requires a 'Time Intelligence[Time Calculation]' filter to be active.",
            "expression": " CALCULATE( [GI Scrap Rate], PREVIOUSDAY( 'Calendar'[Date] ) )",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Time Intelligence"
          },
          {
            "name": "Current S-Block Quantity",
            "expression": " SUM( 'Blocked Inventory'[SBlock Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Blocked Inv"
          },
          {
            "name": "Current Q-Block Quantity",
            "expression": " SUM( 'Blocked Inventory'[QBlock Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Blocked Inv"
          },
          {
            "name": "Current Expired Quantity",
            "expression": " SUM( 'Expired Inventory'[Quantity] )",
            "formatString": "#,0.00",
            "displayFolder": "Blocked Inv"
          }
        ]
      },
      {
        "name": "Sales Invoice Documents",
        "description": "SAP Source: CE110US, VBRP, TVFKT; Active filters: PALEDGER = 01 & VRGAR = F & FKART not equal (IV, IVS) & RBELN starts with 009",
        "columns": [
          {
            "name": "Invoice Number",
            "dataType": "string",
            "description": "SAP Source: CE110US.RBELN; Reference document number for CO-PA line item",
            "sourceColumn": "SaleDocNoKey"
          },
          {
            "name": "Invoice Line Number",
            "dataType": "string",
            "description": "SAP Source: CE110US.RPOSN; Item number from reference document (CO-PA)",
            "sourceColumn": "SaleLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.BUDAT ",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: CE110US.ABSMG",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Gross Sales Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.ERLOS",
            "sourceColumn": "GrossSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.ERLOS, CE110US.KWKDRB; Difference between gross sales and discount",
            "sourceColumn": "NetSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Overall Cost Amount",
            "dataType": "double",
            "description": "SAP Source: VBRP.WAVWR",
            "sourceColumn": "CostValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Material Cost Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.VVMEP",
            "sourceColumn": "MaterialExtPriceUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "double",
            "description": "SAP Source: CE110US.KWKDRB",
            "sourceColumn": "DiscountValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: CE110US.FKART",
            "sourceColumn": "DocType"
          },
          {
            "name": "Document Type Text",
            "dataType": "string",
            "description": "SAP Source: TVFKT.VTEXT",
            "sourceColumn": "DocTypeText"
          },
          {
            "name": "Create Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.HZDAT",
            "sourceColumn": "CreateDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Invoice Date",
            "dataType": "dateTime",
            "description": "SAP Source: CE110US.FADAT",
            "sourceColumn": "InvoiceDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity Unit",
            "dataType": "string",
            "description": "SAP Source: CE110US.ABSMG_ME",
            "sourceColumn": "QuantityUoM"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "description": "SAP Source: CE110US.KURSF",
            "sourceColumn": "ExchangeRate",
            "formatString": "0.0000"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: CE110US.FRWAE",
            "sourceColumn": "Currency"
          },
          {
            "name": "Was New Product",
            "dataType": "int64",
            "description": "Indicates whether the material is less than or equal to 3 years as of the invoice posting date from Commercialization Date",
            "sourceColumn": "WasNewProduct",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\""
          },
          {
            "name": "Gross Margin Amount",
            "dataType": "double",
            "description": "Difference between gross sales and cost value",
            "sourceColumn": "GrossMarginValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Ship To Name",
            "dataType": "string",
            "description": "SAP Source: ADRC.NAME1",
            "sourceColumn": "ShipToName"
          },
          {
            "name": "Ship To City",
            "dataType": "string",
            "description": "SAP Source: ADRC.CITY1",
            "sourceColumn": "ShipToCity"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES = Source{[Schema=\"dbo\",Item=\"VW_SALES\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_SALES,{\"SaleDocNoKey\", \"SaleLineNo\", \"DocType\", \"DocTypeText\", \"CreateDate\", \"InvoiceDate\", \"PostingDateKey\", \"WasNewProduct\", \"MaterialNoKey\", \"CustomerNoKey\", \"CustomerOrgKey\", \"ShipToName\", \"ShipToCity\", \"QuantityUoM\", \"QuantityValue\", \"Currency\", \"ExchangeRate\", \"GrossSalesValueUSD\", \"NetSalesValueUSD\", \"CostValueUSD\", \"MaterialExtPriceUSD\", \"DiscountValueUSD\", \"GrossMarginValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Hold Tag Documents",
        "columns": [
          {
            "name": "Notification Number",
            "dataType": "string",
            "isKey": true,
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Notification Type",
            "dataType": "string",
            "sourceColumn": "NotificationType"
          },
          {
            "name": "Notification Code",
            "dataType": "string",
            "sourceColumn": "NotificationCode"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Reference Number",
            "dataType": "string",
            "sourceColumn": "ReferenceNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Notification Text",
            "dataType": "string",
            "sourceColumn": "NotificationText"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "HoldQuantityValue",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "HoldValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_HOLDTAGS = Source{[Schema=\"dbo\",Item=\"VW_HOLDTAGS\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_HOLDTAGS,{\"NotificationNoKey\", \"NotificationType\", \"NotificationCode\", \"EnterDateKey\", \"ReferenceNo\", \"MaterialNoKey\", \"BatchNoKey\", \"NotificationText\", \"QuantityUoM\", \"HoldQuantityValue\", \"HoldValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory",
        "columns": [
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNoKey"
          },
          {
            "name": "Notification Number",
            "dataType": "string",
            "sourceColumn": "NotificationNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "SBlock Quantity",
            "dataType": "double",
            "sourceColumn": "SBlockQuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "SBlock Amount",
            "dataType": "double",
            "sourceColumn": "SBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Quantity",
            "dataType": "double",
            "sourceColumn": "QBlockQuantityValue",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "QBlock Amount",
            "dataType": "double",
            "sourceColumn": "QBlockAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Notification Text",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": "IF(ISBLANK(LOOKUPVALUE( 'Hold Tag Documents'[Notification Text], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[Notification Number] )), \"NO TAG\", LOOKUPVALUE( 'Hold Tag Documents'[Notification Text], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[Notification Number] ))"
          },
          {
            "type": "calculated",
            "name": "Notification Code",
            "dataType": "string",
            "isDataTypeInferred": true,
            "expression": " IF( ISBLANK(LOOKUPVALUE( 'Hold Tag Documents'[Notification Code], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[Notification Number] )), \"NO TAG\", LOOKUPVALUE( 'Hold Tag Documents'[Notification Code], 'Hold Tag Documents'[Notification Number], 'Blocked Inventory'[Notification Number] ))"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_BLOCK,{\"MaterialNoKey\", \"BatchNoKey\", \"NotificationNoKey\", \"PlantNo\", \"StorageLoc\", \"SBlockQuantityValue\", \"SBlockAmountUSD\", \"QBlockQuantityValue\", \"QBlockAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expired Inventory",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Manufacturing Date",
            "dataType": "dateTime",
            "sourceColumn": "MfgDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Goods Receipt Date",
            "dataType": "dateTime",
            "sourceColumn": "GoodsReceiptDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Expiration Date",
            "dataType": "dateTime",
            "sourceColumn": "ExpirationDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "ExpiredQuantityValue",
            "formatString": "0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "ExpiredAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_EXPIRED = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_EXPIRED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_INVENTORY_EXPIRED,{\"MaterialNoKey\", \"BatchNo\", \"PlantNo\", \"MfgDate\", \"GoodsReceiptDate\", \"ExpirationDate\", \"StockQuantityValue\", \"ExpiredQuantityValue\", \"StockAmountUSD\", \"ExpiredAmountUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Blocked Inventory Snapshots",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "SBlock Value",
            "dataType": "double",
            "sourceColumn": "SBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "QBlock Value",
            "dataType": "double",
            "sourceColumn": "QBlockValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expired Value",
            "dataType": "double",
            "sourceColumn": "ExpiredValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Blocked Inv Value",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": " 'Blocked Inventory Snapshots'[SBlock Value] + 'Blocked Inventory Snapshots'[QBlock Value] + 'Blocked Inventory Snapshots'[Expired Value] + 0",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_DAILY_INVENTORY_BLOCK = Source{[Schema=\"dbo\",Item=\"DAILY_INVENTORY_BLOCK\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_DAILY_INVENTORY_BLOCK,{{\"SnapshotDateKey\", type date}}),",
                "    #\"Removed Other Columns\" = Table.SelectColumns(#\"Changed Type\",{\"SnapshotDateKey\", \"PlantNoKey\", \"SBlockValueUSD\", \"QBlockValueUSD\", \"ExpiredValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Material Master",
        "description": "SAP Source: MARA, MAKT, and AUSP",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: MARA.MATNR",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "MaterialNoKey",
            "displayFolder": "Master"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: MAKT.MAKTG",
            "sourceColumn": "MaterialDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Number - Description",
            "dataType": "string",
            "sourceColumn": "MaterialNoDescription",
            "displayFolder": "Master"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "description": "SAP Source: MARA.MTART",
            "sourceColumn": "MaterialType",
            "displayFolder": "Master"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: MARA.MATKL",
            "sourceColumn": "MaterialGroup",
            "displayFolder": "Master"
          },
          {
            "name": "X Distribution Status",
            "dataType": "string",
            "description": "SAP Source: MARA.MSTAV",
            "sourceColumn": "XDistributionStatus",
            "displayFolder": "Master"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: MARA.MEINS",
            "sourceColumn": "UnitOfMeasure",
            "displayFolder": "Master"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "Brand",
            "displayFolder": "Classification"
          },
          {
            "name": "Color Number",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "ColorNumber",
            "displayFolder": "Classification"
          },
          {
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "description": "SAP Source: AUSP.ATFLV",
            "sourceColumn": "CommercializationDate",
            "formatString": "Short Date",
            "displayFolder": "Classification",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Film Type",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "FilmType",
            "displayFolder": "Classification"
          },
          {
            "name": "Liner",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "Liner",
            "displayFolder": "Classification"
          },
          {
            "name": "Product Series",
            "dataType": "string",
            "description": "SAP Source: AUSP.ATWRT",
            "sourceColumn": "ProductSeries",
            "displayFolder": "Classification"
          },
          {
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL1",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL2",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "description": "SAP Source: T179T.VTEXT",
            "sourceColumn": "ProductHierarchyDescriptionL3",
            "displayFolder": "Product Hierarchy"
          },
          {
            "name": "Is New Product",
            "dataType": "int64",
            "description": "Indicates whether the material is less than or equal to 3 years as of today from Commercialization Date",
            "sourceColumn": "IsNewProduct",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "Classification"
          },
          {
            "name": "Length (ft)",
            "dataType": "double",
            "description": "SAP Source: MARM.LAENG OR MARM.UMREN; Some data cleanup is involved. Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "LengthValue",
            "formatString": "#,0",
            "displayFolder": "Dimensions"
          },
          {
            "name": "Width (in)",
            "dataType": "double",
            "description": "SAP Source: MARM.BREIT. Some data cleanup is involved. Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "WidthValue",
            "formatString": "#,0.00",
            "displayFolder": "Dimensions"
          },
          {
            "name": "Square Feet",
            "dataType": "double",
            "description": "Product of length and width (in to ft). Applies to 'FERT' and 'HAWA' materials only.",
            "sourceColumn": "SquareFeetValue",
            "formatString": "#,0",
            "displayFolder": "Dimensions"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_MASTER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Center Names",
        "description": "List of cost centers in SAP with custom categories manually in a Sharepoint List",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Cost Center Name",
            "dataType": "string",
            "sourceColumn": "CostCenterName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department",
            "sortByColumn": "DepartmentSortKey"
          },
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Operations Category",
            "dataType": "string",
            "sourceColumn": "OperationsCategory"
          },
          {
            "name": "DepartmentSortKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "DepartmentSortKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COST_CENTER_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_CENTER_NAMES\"]}[Data],",
                "    #\"Added Custom\" = Table.AddColumn(dbo_VW_COST_CENTER_NAMES, \"DepartmentSortKey\", each if [Department] = \"COMP\" then 0",
                "else if [Department] = \"CAST\" then 1",
                "else if [Department] = \"PC\" then 2",
                "else if [Department] = \"COAT\" then 3",
                "else if [Department] = \"CONV\" then 4",
                "else 999)",
                "in",
                "    #\"Added Custom\""
              ]
            }
          }
        ]
      },
      {
        "name": "Cost Element Names",
        "description": "List of cost elements (G/L accounts) with custom categories and indicators manually assigned in a Sharepoint list",
        "columns": [
          {
            "name": "Company Category",
            "dataType": "string",
            "sourceColumn": "CompanyCategory"
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category"
          },
          {
            "name": "Sub Category",
            "dataType": "string",
            "sourceColumn": "SubCategory"
          },
          {
            "name": "Category Renamed",
            "dataType": "string",
            "sourceColumn": "CatRenamed"
          },
          {
            "name": "Is Controllable Expense",
            "dataType": "boolean",
            "sourceColumn": "IsControllableExpense"
          },
          {
            "name": "Is Labor",
            "dataType": "boolean",
            "sourceColumn": "IsLabor"
          },
          {
            "name": "Is Supplies",
            "dataType": "boolean",
            "sourceColumn": "IsSupplies"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Cost Element Name",
            "dataType": "string",
            "sourceColumn": "CostElementName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COST_ELEMENT_NAMES = Source{[Schema=\"dbo\",Item=\"VW_COST_ELEMENT_NAMES\"]}[Data]",
                "in",
                "    dbo_VW_COST_ELEMENT_NAMES"
              ]
            }
          }
        ]
      },
      {
        "name": "Plant",
        "description": "List of warehouse numbers in SAP (best used for filtering/grouping by plant across multiple fact tables)",
        "columns": [
          {
            "name": "Plant",
            "dataType": "string",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "PlantDescription"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_PLANT = Source{[Schema=\"dbo\",Item=\"VW_PLANT\"]}[Data]",
                "in",
                "    dbo_VW_PLANT"
              ]
            }
          }
        ]
      },
      {
        "name": "Pending Specification Documents",
        "columns": [
          {
            "name": "Approver Name",
            "dataType": "string",
            "sourceColumn": "ApproverName"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Pending Count",
            "dataType": "int64",
            "sourceColumn": "PendingCount",
            "formatString": "0",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SPECAPPROVAL_PENDING = Source{[Schema=\"dbo\",Item=\"VW_SPECAPPROVAL_PENDING\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_SPECAPPROVAL_PENDING,{\"ApproverName\", \"Department\", \"PendingCount\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Expenses",
        "description": "Controlling document line items posted in expenses related G/L accounts in the current and last fiscal year",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "PlantNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "CreateDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "sourceColumn": "DocumentDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "sourceColumn": "UserName"
          },
          {
            "name": "OffsetAcctNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctNoKey"
          },
          {
            "name": "OffsetAcctType",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OffsetAcctType"
          },
          {
            "name": "Document Number",
            "dataType": "string",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Document Line Number",
            "dataType": "string",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Referenced Document Line Number",
            "dataType": "string",
            "sourceColumn": "RefDocLineNo"
          },
          {
            "name": "Is Reversal Document",
            "dataType": "string",
            "sourceColumn": "IsRvrslDoc"
          },
          {
            "name": "Reversal Referenced Document Number",
            "dataType": "string",
            "sourceColumn": "RvrslRefDocNo"
          },
          {
            "name": "Is Reversed",
            "dataType": "string",
            "sourceColumn": "IsReversed"
          },
          {
            "name": "PurchaseDocLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseDocLineKey"
          },
          {
            "name": "Document Header Text",
            "dataType": "string",
            "sourceColumn": "DocHeaderText"
          },
          {
            "name": "Document Item Text",
            "dataType": "string",
            "sourceColumn": "ItemText"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "sourceColumn": "Currency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "Expenses amount are in company currency while Open POs are already converted to USD",
            "sourceColumn": "Amount",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Expense Type",
            "dataType": "string",
            "description": "Expense are line items posted by Accounting; Open PO are open purchase orders",
            "sourceColumn": "ExpenseType"
          },
          {
            "name": "Offset Account Name",
            "dataType": "string",
            "sourceColumn": "OffsetAcctName"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "sourceColumn": "MaterialName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_EXPENSES = Source{[Schema=\"dbo\",Item=\"VW_EXPENSES\"]}[Data]",
                "in",
                "    dbo_VW_EXPENSES"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Orders",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.EBELN",
            "sourceColumn": "PurchaseOrderNoKey"
          },
          {
            "name": "Purchase Line Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.EBELN",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKKO.AEDAT",
            "sourceColumn": "DocumentDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "VendorNoKey",
            "dataType": "string",
            "description": "SAP Source: EKKO.LIFNR",
            "isHidden": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATKL",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: EKPO.TXZ01",
            "sourceColumn": "MaterialText"
          },
          {
            "name": "Req Track Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.BEDNR",
            "sourceColumn": "RequisitionTrackNo"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "description": "SAP Source: EKPO.NETPR",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: EKPO.MEINS",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: EKKO.BSART",
            "sourceColumn": "PurchaseDocType"
          },
          {
            "name": "Is Complete Delivery",
            "dataType": "string",
            "description": "SAP Source: EKPO.ELIKZ",
            "sourceColumn": "CompleteDeliverIndicator"
          },
          {
            "name": "Is Goods Receipt Required",
            "dataType": "string",
            "description": "SAP Source: EKPO.WEPOS",
            "sourceColumn": "GoodsReceiptIndicator"
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKET.SLFDT",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "MM/dd/yyyy",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"ShortDate\" FormatString=\"MM/dd/yyyy\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Issuing Plant",
            "dataType": "string",
            "description": "SAP Source: EKKO.RESWK",
            "sourceColumn": "IssuingPlantNo"
          },
          {
            "name": "Receiving Plant",
            "dataType": "string",
            "description": "SAP Source: EKPO.WERKS",
            "sourceColumn": "ReceivingPlantNo"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "description": "SAP Source: EKPO.MTART",
            "sourceColumn": "MaterialType"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: EKKO.WAERS",
            "sourceColumn": "Currency"
          },
          {
            "name": "Ordered Quantity",
            "dataType": "double",
            "description": "SAP Source: EKPO.MENGE",
            "sourceColumn": "OrderedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Ordered Amount",
            "dataType": "double",
            "description": "SAP Source: EKPO.NETWR",
            "sourceColumn": "OrderedAmount",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Open Quantity",
            "dataType": "double",
            "description": "Difference between the ordered and delivered quantity. SAP Source: EKPO.MENGE and EKET.WEMNG",
            "sourceColumn": "OpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "description": "Open quantity converted to amount based on unit price from ordered amount and quantity. SAP Source: EKPO.MENGE, EKET.WEMNG, and EKPO.NETWR",
            "sourceColumn": "OpenAmount",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Purchase Order Unit",
            "dataType": "string",
            "description": "SAP Source: EKPO.BPRME",
            "sourceColumn": "POUnitOfMeasure"
          },
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: EKKO.BUKRS",
            "sourceColumn": "CompanyCode"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_PURCHASE_ORDERS = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE\"]}[Data]",
                "in",
                "    dbo_VW_PURCHASE_ORDERS"
              ]
            }
          }
        ]
      },
      {
        "name": "_Time Intelligence",
        "description": "The \"Time Calculation\" field allows multiple versions of a measure under \"DAX Measures\" (i.e. MTD, YTD, CD, PD, etc). This is best use on measures in \"DAX Measures\" that are not under the \"Time Intelligence\" folder.",
        "calculationGroup": {
          "description": "Used for analyzing measures in multiple time intelligence modes such as MTD, YTD, FYTD, etc.",
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Current",
              "expression": "SELECTEDMEASURE()",
              "ordinal": 1
            },
            {
              "name": "MTD",
              "expression": "CALCULATE( SELECTEDMEASURE(), DATESMTD('Calendar'[Date]) )",
              "ordinal": 4
            },
            {
              "name": "YTD",
              "expression": "CALCULATE( SELECTEDMEASURE(), DATESYTD('Calendar'[Date]) )",
              "ordinal": 7
            },
            {
              "name": "PY",
              "expression": "CALCULATE( SELECTEDMEASURE(), SAMEPERIODLASTYEAR('Calendar'[Date]) )",
              "ordinal": 13
            },
            {
              "name": "PY YTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"YTD\"",
                ")"
              ],
              "ordinal": 8
            },
            {
              "name": "PY MTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"MTD\"",
                ")"
              ],
              "ordinal": 5
            },
            {
              "name": "FYTD",
              "expression": "CALCULATE( SELECTEDMEASURE(), DATESYTD('Calendar'[Date], \"09/30\") )",
              "ordinal": 10
            },
            {
              "name": "PY FYTD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    SAMEPERIODLASTYEAR( 'Calendar'[Date] ),",
                "    '_Time Intelligence'[Time Calculation] = \"FYTD\"",
                ")"
              ],
              "ordinal": 11
            },
            {
              "name": "YOY",
              "expression": [
                "IF(",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        '_Time Intelligence'[Time Calculation] = \"PY\"",
                "    ),",
                "    SELECTEDMEASURE() - ",
                "    CALCULATE(",
                "        SELECTEDMEASURE(),",
                "        '_Time Intelligence'[Time Calculation] = \"PY\"",
                "    ),",
                "    BLANK()",
                ")"
              ],
              "ordinal": 14
            },
            {
              "name": "CD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    LASTDATE( 'Calendar'[Date] )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "PD",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    PREVIOUSDAY( 'Calendar'[Date] )",
                ")"
              ],
              "ordinal": 3
            },
            {
              "name": "MTD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"MTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY MTD\"",
                ")"
              ],
              "ordinal": 6
            },
            {
              "name": "YTD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"YTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY YTD\"",
                ")"
              ],
              "ordinal": 9
            },
            {
              "name": "FTYD PY Var",
              "expression": [
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"FYTD\"",
                ") - ",
                "CALCULATE(",
                "    SELECTEDMEASURE(),",
                "    '_Time Intelligence'[Time Calculation] = \"PY FYTD\"",
                ")"
              ],
              "ordinal": 12
            }
          ]
        },
        "columns": [
          {
            "name": "Time Calculation",
            "dataType": "string",
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "_Refresh Date",
        "columns": [
          {
            "name": "Report Name",
            "dataType": "string",
            "description": "Filter this column using a slicer with the name of this report/dashboard",
            "sourceColumn": "ReportNameKey"
          },
          {
            "name": "Refresh Date",
            "dataType": "dateTime",
            "sourceColumn": "ProcessDatetime",
            "formatString": "MM/dd/yyyy HH:mm",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"GeneralShortDateTime\" FormatString=\"MM/dd/yyyy HH:mm\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zPROCESSDATE_REPORTS = Source{[Schema=\"dbo\",Item=\"zPROCESSDATE_REPORTS\"]}[Data]",
                "in",
                "    dbo_zPROCESSDATE_REPORTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Target_Expenses",
        "isHidden": true,
        "columns": [
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "CostElementKey",
            "dataType": "string",
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "TargetValue",
            "dataType": "double",
            "sourceColumn": "TargetValue"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_EXPENSES = Source{[Schema=\"dbo\",Item=\"zTARGETS_EXPENSES\"]}[Data]",
                "in",
                "    dbo_zTARGETS_EXPENSES"
              ]
            }
          }
        ]
      },
      {
        "name": "_Expenses Mode",
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Actual",
              "expression": "[Expenses Amount]",
              "ordinal": 0
            },
            {
              "name": "PY",
              "expression": "CALCULATE( [Expenses Amount], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
              "ordinal": 1
            },
            {
              "name": "PY Var",
              "expression": [
                "VAR PreviousPeriod = CALCULATE( [Expenses Amount], SAMEPERIODLASTYEAR('Calendar'[Date]) )",
                "RETURN",
                "    IF (",
                "        NOT ISBLANK( [Expenses Amount] )",
                "            && NOT ISBLANK( PreviousPeriod ),",
                "        [Expenses Amount] - PreviousPeriod",
                "    )"
              ],
              "ordinal": 2
            },
            {
              "name": "AOP",
              "expression": "[Expenses Plan]",
              "ordinal": 3
            },
            {
              "name": "AOP Var",
              "expression": [
                "IF (",
                "    NOT ISBLANK( [Expenses Amount] )",
                "        && NOT ISBLANK( [Expenses Plan] ),",
                "    [Expenses Amount] - [Expenses Plan]",
                ")"
              ],
              "ordinal": 4
            }
          ]
        },
        "columns": [
          {
            "name": "Mode",
            "dataType": "string",
            "sourceColumn": "Name"
          }
        ],
        "partitions": [
          {
            "name": "CalculationGroup 1",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Reason Code",
        "columns": [
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Reason Code Description",
            "dataType": "string",
            "sourceColumn": "ReasonCodeDescription"
          },
          {
            "name": "Department",
            "dataType": "string",
            "sourceColumn": "Department"
          },
          {
            "name": "Class",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Class"
          }
        ],
        "partitions": [
          {
            "name": "Partition - Copy",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data],",
                "    #\"Removed Duplicates\" = Table.Distinct(dbo_VW_REASON_CODE, {\"ReasonCodeKey\"})",
                "in",
                "    #\"Removed Duplicates\""
              ]
            },
            "annotations": [
              {
                "name": "QueryEditorSerialization",
                "value": [
                  "<?xml version=\"1.0\" encoding=\"UTF-16\"?><Gemini xmlns=\"QueryEditorSerialization\"><AnnotationContent><![CDATA[<RSQueryCommandText>let",
                  "    Source = #\"ARLPBI_STAGE\",",
                  "    dbo_VW_REASON_CODE = Source{[Schema=\"dbo\",Item=\"VW_REASON_CODE\"]}[Data]",
                  "in",
                  "    dbo_VW_REASON_CODE</RSQueryCommandText><RSQueryCommandType>Text</RSQueryCommandType><RSQueryDesignState></RSQueryDesignState>]]></AnnotationContent></Gemini>"
                ]
              }
            ]
          }
        ]
      },
      {
        "name": "Complaint Documents - Credited",
        "isHidden": true,
        "columns": [
          {
            "name": "ComplaintLineKey",
            "dataType": "string",
            "sourceColumn": "ComplaintLineKey"
          },
          {
            "name": "Credit Issued Date",
            "dataType": "dateTime",
            "sourceColumn": "CreditDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Credit Issued Amount",
            "dataType": "double",
            "sourceColumn": "CreditIssueValueUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_COMPLAINTS_CREDITED = Source{[Schema=\"dbo\",Item=\"VW_COMPLAINTS_CREDITED\"]}[Data],",
                "    #\"Removed Other Columns\" = Table.SelectColumns(dbo_VW_COMPLAINTS_CREDITED,{\"ComplaintLineKey\", \"CreditDateKey\", \"CreditIssueValueUSD\"})",
                "in",
                "    #\"Removed Other Columns\""
              ]
            }
          }
        ]
      },
      {
        "name": "Target_KPI",
        "isHidden": true,
        "columns": [
          {
            "name": "KpiKey",
            "dataType": "string",
            "sourceColumn": "KpiKey"
          },
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "TargetValue",
            "dataType": "double",
            "sourceColumn": "TargetValue"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_KPI = Source{[Schema=\"dbo\",Item=\"zTARGETS_KPI\"]}[Data]",
                "in",
                "    dbo_zTARGETS_KPI"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Order Documents",
        "description": "SAP Source: VBAK, VBAP, VBUK, VBUP, VBUK, VBPA, VBEP, LIKP, LIPS, and KNMT; Granularity: One row per sales order document and line number; Contains general and status information about sales order documents.",
        "columns": [
          {
            "name": "OrderNoLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "OrderNoLineKey"
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "description": "SAP Source: VBAK.VBELN",
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Order Line Number",
            "dataType": "string",
            "description": "SAP Source: VBAP.POSNR",
            "sourceColumn": "OrderLineNo"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "description": "SAP Source: VBAK.AUART",
            "sourceColumn": "OrderType"
          },
          {
            "name": "Enter Date",
            "dataType": "dateTime",
            "description": "SAP Source: VBAK.ERDAT",
            "sourceColumn": "EnterDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "description": "SAP Source: VBEP.EDATU",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Last PGI Date",
            "dataType": "dateTime",
            "description": "SAP Source: LIKP.WADAT_IST; If the values is 12/31/9999, then there is no PGI date for the sales order item",
            "sourceColumn": "LastPgiDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Entered By",
            "dataType": "string",
            "description": "SAP Source: VBAK.ERNAM",
            "sourceColumn": "EnteredBy"
          },
          {
            "name": "Organization",
            "dataType": "string",
            "description": "SAP Source: VBAK.VKORG",
            "sourceColumn": "OrgNoKey"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: VBAP.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "CustomerNoKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: VBAP.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Material Description",
            "dataType": "string",
            "description": "SAP Source: VBAP.ARKTX",
            "sourceColumn": "MaterialText"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "description": "SAP Source: VBAP.MATKL",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "ReasonCodeKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ReasonCodeKey"
          },
          {
            "name": "Credit Block",
            "dataType": "string",
            "description": "SAP Source: VBUP.CMGST",
            "sourceColumn": "CreditBlock"
          },
          {
            "name": "Route Type",
            "dataType": "string",
            "description": "SAP Source: VBAP.ROUTE",
            "sourceColumn": "RouteType"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: VBAP.MEINS",
            "sourceColumn": "OrderUoM"
          },
          {
            "name": "Order Quantity",
            "dataType": "double",
            "description": "SAP Source: VBAP.KWMENG",
            "sourceColumn": "OrderQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Currency",
            "dataType": "string",
            "description": "SAP Source: VBAP.WAERK",
            "sourceColumn": "OrderCurrency"
          },
          {
            "name": "Order Amount",
            "dataType": "double",
            "description": "SAP Source: VBAP.NETWR; Converted to USD using the exchange rate",
            "sourceColumn": "OrderAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Cost Amount",
            "dataType": "double",
            "description": "SAP Source: VBAP.WAVWR; Converted to USD using the exchange rate",
            "sourceColumn": "CostAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Billing Status",
            "dataType": "string",
            "description": "SAP Source: VBUP.FKSAA",
            "sourceColumn": "BillingStatBlock"
          },
          {
            "name": "Allocated Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued without an actual PGI date yet",
            "sourceColumn": "AllocatedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued with actual PGI date set",
            "sourceColumn": "ShippedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped On Time Quantity",
            "dataType": "double",
            "description": "SAP Source: LIPS.LFIMG; Total quantity in delivery notes issued with PGI date on or before the first schedule delivery date",
            "sourceColumn": "OnTimeShippedQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Quantity",
            "dataType": "double",
            "description": "Order quantity minus allocated and shipped quantity",
            "sourceColumn": "InternalOpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Open Quantity",
            "dataType": "double",
            "description": "Order quantity minus shipped quantity",
            "sourceColumn": "CustomerOpenQuantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit Price",
            "dataType": "double",
            "description": "SAP Source: VBAP.NETPR",
            "sourceColumn": "UnitPrice"
          },
          {
            "name": "Exchange Rate",
            "dataType": "double",
            "description": "SAP Source: VBAP.STCUR or VBKD.KURSK; Exchange rate to USD. Due to errors in some orders, this exchange is a calculated column. If the currency is USD, then the value is 1.0. Else if the currency is not USD but the exchange rate in the order is 1.0, use the VBKD.KURSK. Else, use VBAP.STCUR.",
            "sourceColumn": "ExchangeRate",
            "formatString": "0.0000"
          },
          {
            "name": "Cost Amount Local",
            "dataType": "double",
            "description": "SAP Source: WAVWR",
            "isHidden": true,
            "sourceColumn": "CostAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Amount Local",
            "dataType": "double",
            "description": "SAP Source: NETWR",
            "sourceColumn": "OrderAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Amount Local",
            "dataType": "double",
            "description": "Total value of internal open quantity",
            "sourceColumn": "InternalOpenAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Internal Open Amount",
            "dataType": "double",
            "description": "Total value of internal open quantity",
            "sourceColumn": "InternalOpenAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Customer Open Amount Local",
            "dataType": "double",
            "sourceColumn": "CustomerOpenAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Open Amount",
            "dataType": "double",
            "sourceColumn": "CustomerOpenAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Margin Amount Local",
            "dataType": "double",
            "description": "Net of order and cost amount",
            "sourceColumn": "MarginAmount",
            "formatString": "#,0",
            "displayFolder": "_Local Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Margin Amount",
            "dataType": "double",
            "description": "Net of order and cost amount",
            "sourceColumn": "MarginAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_USD Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "External Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: VBEP.BSTKD",
            "sourceColumn": "ExtPurchaseOrderNo"
          },
          {
            "name": "Customer Material Number",
            "dataType": "string",
            "description": "SAP Source: KNMT.KDMAT",
            "sourceColumn": "CustomerMaterialNo"
          },
          {
            "name": "Ship To Name",
            "dataType": "string",
            "description": "SAP Source: ADRC.NAME1",
            "sourceColumn": "ShipToName"
          },
          {
            "name": "Ship To City",
            "dataType": "string",
            "description": "SAP Source: ADRC.CITY1",
            "sourceColumn": "ShipToCity"
          },
          {
            "name": "In Stock",
            "dataType": "int64",
            "description": "Applies to open orders only; Indicates if an item is available in stock (FIFO by first scheduled ship date)",
            "isHidden": true,
            "sourceColumn": "InStockIndicator"
          },
          {
            "name": "Has Changes (CS)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "HasChanges_CS"
          },
          {
            "name": "Customer Open Margin Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomerOpenMarginAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Customer Open Margin Amount (Local)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "CustomerOpenMarginAmount",
            "formatString": "#,0"
          },
          {
            "name": "Tier",
            "dataType": "string",
            "description": "SAP Source: MARC.MAABC",
            "sourceColumn": "TierCode"
          },
          {
            "name": "Processing Status",
            "dataType": "string",
            "sourceColumn": "ProcessingBlock"
          },
          {
            "name": "Allocated Amount Local",
            "dataType": "double",
            "sourceColumn": "AllocatedAmount",
            "formatString": "#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Allocated Amount",
            "dataType": "double",
            "sourceColumn": "AllocatedAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Shipped Amount Local",
            "dataType": "double",
            "sourceColumn": "ShippedAmount",
            "formatString": "#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Shipped Amount",
            "dataType": "double",
            "sourceColumn": "ShippedAmountUSD",
            "formatString": "\\$#,0;(\\$#,0);\\$#,0",
            "displayFolder": "_Values",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Sample Category",
            "dataType": "string",
            "description": "Calculated column: If the order type is 'KL', then 'Full Rolls'. Else if the order type is 'ZSMP' and order reason is 'Tradeshow Requests' then 'Tradeshow'. Else if order type is 'ZSMP' and material group is 'MARKETG', then 'Literature'. Else if order type is 'ZSMP' and not a tradeshow nor literature, then 'Samples'. Otherwise, 'Not Applicable'.",
            "sourceColumn": "FOCCategory"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_ORDER_SALES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_SALES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_SALES"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Region",
        "isHidden": true,
        "columns": [
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesDistrictKey"
          },
          {
            "name": "Sales Region Name",
            "dataType": "string",
            "sourceColumn": "SalesDistrictName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES_REGION = Source{[Schema=\"dbo\",Item=\"VW_SALES_REGION\"]}[Data]",
                "in",
                "    dbo_VW_SALES_REGION"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Territory",
        "isHidden": true,
        "columns": [
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "Sales Territory Name",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_SALES_TERRITORY = Source{[Schema=\"dbo\",Item=\"VW_SALES_TERRITORY\"]}[Data]",
                "in",
                "    dbo_VW_SALES_TERRITORY"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_Territory",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_TERRITORY = Source{[Schema=\"dbo\",Item=\"VW_RLS_TERRITORY\"]}[Data]",
                "in",
                "    dbo_VW_RLS_TERRITORY"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_Region",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesRegionKey",
            "dataType": "string",
            "sourceColumn": "SalesRegionKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_REGION = Source{[Schema=\"dbo\",Item=\"VW_RLS_REGION\"]}[Data]",
                "in",
                "    dbo_VW_RLS_REGION"
              ]
            }
          }
        ]
      },
      {
        "name": "Targets_Sales",
        "isHidden": true,
        "columns": [
          {
            "name": "SalesTerritoryKey",
            "dataType": "string",
            "sourceColumn": "SalesTerritoryKey"
          },
          {
            "name": "CalendarTimeKey",
            "dataType": "string",
            "sourceColumn": "CalendarTimeKey"
          },
          {
            "name": "GrossSales",
            "dataType": "double",
            "sourceColumn": "GrossSales",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "GrossMarginMTD",
            "dataType": "double",
            "sourceColumn": "GrossMarginMTD",
            "formatString": "0.00%;-0.00%;0.00%"
          },
          {
            "name": "GrossMarginYTD",
            "dataType": "double",
            "sourceColumn": "GrossMarginYTD",
            "formatString": "0.00%;-0.00%;0.00%"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_zTARGETS_SALES = Source{[Schema=\"dbo\",Item=\"zTARGETS_SALES\"]}[Data]",
                "in",
                "    dbo_zTARGETS_SALES"
              ]
            }
          }
        ]
      },
      {
        "name": "RLS_CostCenter",
        "isHidden": true,
        "columns": [
          {
            "name": "CostCenterKey",
            "dataType": "string",
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "DomainName",
            "dataType": "string",
            "sourceColumn": "DomainName"
          },
          {
            "name": "InactiveDate",
            "dataType": "dateTime",
            "sourceColumn": "InactiveDate"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_RLS_COSTCENTER = Source{[Schema=\"dbo\",Item=\"VW_RLS_COSTCENTER\"]}[Data]",
                "in",
                "    dbo_VW_RLS_COSTCENTER"
              ]
            }
          }
        ]
      },
      {
        "name": "_Currency to Use",
        "description": "This table is mainly used as a slicer to dynamically switch the calculation of measures from USD to local currency. Not all measures are applicable.",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Currency",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Value]"
          }
        ],
        "partitions": [
          {
            "name": "CalculatedTable 1",
            "source": {
              "type": "calculated",
              "expression": " { \"USD\", \"Local\" }"
            }
          }
        ]
      },
      {
        "name": "Stock Transfer Orders",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.EBELN",
            "sourceColumn": "PurchaseOrderNoKey"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: EKPO.EBELP",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "MaterialNoKey",
            "dataType": "string",
            "description": "SAP Source: EKPO.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Valuation Class",
            "dataType": "string",
            "description": "SAP Source: MBEW.BKLAS",
            "sourceColumn": "ValuationClass"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Delivered Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.MENGE; Criteria: EKBE.BEWTP = 'U'",
            "sourceColumn": "DeliveredQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Goods Receipt Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.MENGE; Criteria: EKBE.BEWTP = 'E'",
            "sourceColumn": "GoodsReceiptQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "In Transit Quantity",
            "dataType": "double",
            "description": "Net of delivered and goods receipt",
            "sourceColumn": "InTransitQuantity",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Delivered Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.WRBTR; Criteria: EKBE.BEWTP = 'U'",
            "sourceColumn": "DeliveredAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "Goods Receipt Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.WRBTR; Criteria: EKBE.BEWTP = 'E'",
            "sourceColumn": "GoodsReceiptAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "In Transit Amount",
            "dataType": "double",
            "description": "Net of delivered and goods receipt",
            "sourceColumn": "InTransitAmount",
            "displayFolder": "_Values"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.XBLNR",
            "sourceColumn": "ReferencedDocumentNo"
          },
          {
            "name": "Shipment Document Number",
            "dataType": "string",
            "description": "SAP Source: VTTP.TPNUM",
            "sourceColumn": "ShipmentDocumentNo"
          },
          {
            "name": "Shipment Document Line Number",
            "dataType": "string",
            "description": "SAP Source: VTTP.TKNUM",
            "sourceColumn": "ShipmentLineNo"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_INVENTORY_INTRANSIT = Source{[Schema=\"dbo\",Item=\"VW_INVENTORY_INTRANSIT\"]}[Data]",
                "in",
                "    dbo_VW_INVENTORY_INTRANSIT"
              ]
            }
          }
        ]
      },
      {
        "name": "Goods and Invoice Receipts",
        "description": "; Granularity: One row per account document and line number",
        "columns": [
          {
            "name": "Company Code",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUKRS",
            "sourceColumn": "CompanyCode"
          },
          {
            "name": "G/L Account",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.HKONT",
            "sourceColumn": "GeneralLedgerAcctNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.WERKS",
            "sourceColumn": "PlantNo"
          },
          {
            "name": "Cost Center",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.KOSTL",
            "sourceColumn": "CostCenter"
          },
          {
            "name": "Accounting Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BELNR",
            "sourceColumn": "DocumentNo"
          },
          {
            "name": "Accounting Document Line Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BUZEI",
            "sourceColumn": "DocumentLineNo"
          },
          {
            "name": "Document Type",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.BLART",
            "sourceColumn": "DocumentType"
          },
          {
            "name": "Document Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BLDAT",
            "sourceColumn": "DocumentDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Fiscal Period",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.MONAT",
            "sourceColumn": "FiscalPeriod"
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.GJAHR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "First GR Year",
            "dataType": "string",
            "description": "First year of posted goods receipt based on assignment number",
            "sourceColumn": "FirstGRYear"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.MATNR",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: ACCTIT.ERFMG",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "displayFolder": "_Quantities",
            "summarizeBy": "sum"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.ERFME",
            "sourceColumn": "UnitOfMeasure",
            "displayFolder": "_Quantities"
          },
          {
            "name": "Amount (Document)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.WRBTR",
            "sourceColumn": "AmountInDocCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Document Currency",
            "dataType": "string",
            "description": "SAP Source: BKPF.WAERS",
            "sourceColumn": "DocCurrency",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount (Local)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBTR",
            "sourceColumn": "AmountInLocalCurrency",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAER",
            "sourceColumn": "LocalCurrency",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount (Local2)",
            "dataType": "double",
            "description": "SAP Source: BSIS/BSAS.DMBE2",
            "sourceColumn": "AmountInLocalCurrency2",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Local Currency 2",
            "dataType": "string",
            "description": "SAP Source: BKPF.HWAE2",
            "sourceColumn": "LocalCurrency2",
            "displayFolder": "_Values"
          },
          {
            "name": "Clearing Date",
            "dataType": "dateTime",
            "description": "SAP Source: BSIS/BSAS.AUGDT",
            "sourceColumn": "ClearingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Clearing Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.AUGBL",
            "sourceColumn": "ClearingDocNo"
          },
          {
            "name": "Assignment Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.ZUONR",
            "sourceColumn": "AssignmentNo"
          },
          {
            "name": "Purchase Order Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELN",
            "sourceColumn": "PurchaseOrderNo"
          },
          {
            "name": "Purchase Order Line Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.EBELP",
            "sourceColumn": "PurchaseOrderLineNo"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.AUFNR",
            "sourceColumn": "ProcessOrderNo"
          },
          {
            "name": "Referenced Document Number",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.XBLNR",
            "sourceColumn": "RefDocNo"
          },
          {
            "name": "Item Text",
            "dataType": "string",
            "description": "SAP Source: BSIS/BSAS.SGTXT",
            "sourceColumn": "ItemText"
          },
          {
            "name": "Vendor Number",
            "dataType": "string",
            "description": "SAP Source: EKKO.LIFNR",
            "isHidden": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "description": "SAP Source: ACCTIT.KUNNR",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "PostingRank",
            "dataType": "int64",
            "sourceColumn": "PostingRank"
          },
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_GOODS_AND_INVOICE_RECEIPTS = Source{[Schema=\"dbo\",Item=\"VW_GOODS_AND_INVOICE_RECEIPTS\"]}[Data]",
                "in",
                "    dbo_VW_GOODS_AND_INVOICE_RECEIPTS"
              ]
            }
          }
        ]
      },
      {
        "name": "Vendor Master",
        "description": "SAP Source: LFA1",
        "columns": [
          {
            "name": "Vendor Number",
            "dataType": "string",
            "description": "SAP Source: LFA1.LIFNR",
            "isUnique": true,
            "isKey": true,
            "sourceColumn": "VendorNoKey"
          },
          {
            "name": "Vendor Name",
            "dataType": "string",
            "description": "SAP Source: LFA1.NAME1",
            "sourceColumn": "VendorName"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"ARLPBI_STAGE\",",
                "    dbo_VW_VENDOR_MASTER = Source{[Schema=\"dbo\",Item=\"VW_VENDOR_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_VENDOR_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Order Invoices",
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "Material Document Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.BELNR",
            "sourceColumn": "MaterialDocNo"
          },
          {
            "name": "Material Document Line Number",
            "dataType": "string",
            "description": "SAP Source: EKBE.BUZEI",
            "sourceColumn": "MaterialLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: EKBE.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "PostingRank",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PostingRank"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: EKBE.BPMNG; Value is in purchase order unit (see 'Purchase Orders' table)",
            "sourceColumn": "InvoiceQty",
            "formatString": "#,0.00"
          },
          {
            "name": "Currency",
            "dataType": "string",
            "description": "SAP Source: EKBE.WAERS",
            "sourceColumn": "InvoiceCurrency"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "SAP Source: EKBE.REEWR",
            "sourceColumn": "InvoiceValue",
            "formatString": "#,0.00"
          },
          {
            "name": "Amount at Last PY Price",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "InvoiceValue_LastPYPrice"
          },
          {
            "name": "Last PY Quantity",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LastInvoiceQty_PY"
          },
          {
            "name": "Last PY Amount",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LastInvoiceValue_PY",
            "formatString": "#,0.00"
          },
          {
            "name": "Price Difference",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "PriceDifference",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_PURCHASE_INVOICES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE_INVOICES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_PURCHASE_INVOICES"
              ]
            }
          }
        ]
      },
      {
        "name": "Absorption",
        "columns": [
          {
            "name": "Cost Center",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostCenterKey"
          },
          {
            "name": "Cost Element",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CostElementKey"
          },
          {
            "name": "Business Transaction Type",
            "dataType": "string",
            "sourceColumn": "BusTransType"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "sourceColumn": "AmountValue",
            "formatString": "0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_ABSORPTION\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "SAP Users",
        "description": "SAP Source: USR21 and ADCP",
        "isHidden": true,
        "columns": [
          {
            "name": "UsernameKey",
            "dataType": "string",
            "description": "SAP Source: USR21.BNAME",
            "sourceColumn": "UsernameKey"
          },
          {
            "name": "Department",
            "dataType": "string",
            "description": "SAP Source: ADCP.DEPARTMENT",
            "sourceColumn": "Department"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_USERS_SAP = Source{[Schema=\"dbo\",Item=\"VW_USERS_SAP\"]}[Data]",
                "in",
                "    dbo_VW_USERS_SAP"
              ]
            }
          }
        ]
      },
      {
        "name": "Sales Order Document Changes",
        "description": "SAP Source: CDHDR; Granularity: Multiple rows per sales order document number",
        "columns": [
          {
            "name": "OrderNoKey",
            "dataType": "string",
            "description": "SAP Source: CDHDR.OBJECTID",
            "isHidden": true,
            "sourceColumn": "OrderNoKey"
          },
          {
            "name": "Changed By",
            "dataType": "string",
            "description": "SAP Source: CDHDR.USERNAME",
            "sourceColumn": "ChangedBy"
          },
          {
            "name": "Change Date",
            "dataType": "dateTime",
            "description": "SAP Source: CDHDR.UDATE",
            "sourceColumn": "ChangedDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Change Time",
            "dataType": "dateTime",
            "description": "SAP Source: CDHDR.UTIME",
            "sourceColumn": "ChangedTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_SALES_CHANGES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_SALES_CHANGES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_SALES_CHANGES"
              ]
            }
          }
        ]
      },
      {
        "name": "Purchase Orders - Deliveries",
        "isHidden": true,
        "columns": [
          {
            "name": "PurchaseOrderLineKey",
            "dataType": "string",
            "sourceColumn": "PurchaseOrderLineKey"
          },
          {
            "name": "First Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "FirstDeliveryDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Open Quantity",
            "dataType": "double",
            "sourceColumn": "OpenQuantity",
            "formatString": "#,0.00"
          },
          {
            "name": "Open Amount",
            "dataType": "double",
            "sourceColumn": "OpenAmount",
            "formatString": "#,0.00"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ORDER_PURCHASE_DELIVERIES = Source{[Schema=\"dbo\",Item=\"VW_ORDER_PURCHASE_DELIVERIES\"]}[Data]",
                "in",
                "    dbo_VW_ORDER_PURCHASE_DELIVERIES"
              ]
            }
          }
        ]
      },
      {
        "name": "Backorder Snapshots",
        "description": "A daily snapshot (near midnight) of backordered sales orders; Each value is the daily closing backorder value per plant, material type, and order type.",
        "columns": [
          {
            "name": "Snapshot Date",
            "dataType": "dateTime",
            "sourceColumn": "SnapshotDateKey",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Plant",
            "dataType": "string",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "sourceColumn": "MaterialType"
          },
          {
            "name": "Incoming",
            "dataType": "double",
            "sourceColumn": "Incoming",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Outgoing",
            "dataType": "double",
            "sourceColumn": "Outgoing",
            "formatString": "#,0.00",
            "displayFolder": "_Values"
          },
          {
            "name": "Order Type",
            "dataType": "string",
            "sourceColumn": "OrderType"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_zDAILY_BACKORDER = Source{[Schema=\"dbo\",Item=\"zDAILY_BACKORDER\"]}[Data]",
                "in",
                "    dbo_zDAILY_BACKORDER"
              ]
            }
          }
        ]
      },
      {
        "name": "Goods Issues and Receipts",
        "description": "SAP Source: MKPF and MSEG. Contains postings of goods issue and goods receipts posted in the last 3 fiscal years.",
        "columns": [
          {
            "name": "Material Document Number",
            "dataType": "string",
            "description": "SAP Source: MKPF.MBLNR",
            "sourceColumn": "MaterialDocNo"
          },
          {
            "name": "Material Document Line Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.ZEILE",
            "sourceColumn": "MaterialDocItemNo"
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "description": "SAP Source: MKPF.MJAHR",
            "sourceColumn": "FiscalYear"
          },
          {
            "name": "Movement Type",
            "dataType": "string",
            "description": "SAP Source: MSEG.BWART",
            "sourceColumn": "MovementType"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.MATNR",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Process Order Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.AUFNR",
            "isHidden": true,
            "sourceColumn": "ProcessOrderNoKey"
          },
          {
            "name": "Batch Number",
            "dataType": "string",
            "description": "SAP Source: MSEG.CHARG",
            "sourceColumn": "BatchNo"
          },
          {
            "name": "Plant",
            "dataType": "string",
            "description": "SAP Source: MSEG.WERKS",
            "sourceColumn": "PlantNoKey"
          },
          {
            "name": "Storage Location",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGORT",
            "sourceColumn": "StorageLoc"
          },
          {
            "name": "Storage Bin",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGPLA",
            "sourceColumn": "StorageBin"
          },
          {
            "name": "Storage Type",
            "dataType": "string",
            "description": "SAP Source: MSEG.LGTYP",
            "sourceColumn": "StorageType"
          },
          {
            "name": "Reason Code",
            "dataType": "string",
            "description": "SAP Source: MSEG.GRUND",
            "sourceColumn": "ReasonCode"
          },
          {
            "name": "Material Document Header Text",
            "dataType": "string",
            "description": "SAP Source: MKPF.BKTXT",
            "sourceColumn": "DocHeaderText"
          },
          {
            "name": "Machine Name",
            "dataType": "string",
            "description": "Extracted from Document Header Text",
            "sourceColumn": "MachineName"
          },
          {
            "name": "Posted By",
            "dataType": "string",
            "description": "SAP Source: MKPF.USNAM",
            "sourceColumn": "PostingUsername"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "description": "SAP Source: MSEG.BUDAT",
            "sourceColumn": "PostingDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Posting Time",
            "dataType": "dateTime",
            "description": "SAP Source: MSEG.CPUTM",
            "sourceColumn": "PostingTime",
            "formatString": "HH:mm:ss",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeCustom\"><DateTimes><DateTime LCID=\"1033\" Group=\"LongTime\" FormatString=\"HH:mm:ss\" /></DateTimes></Format>"
              }
            ]
          },
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Calculated from posting date and time. Production dates starts at 6AM and ends at 5:59AM the next day.",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "description": "SAP Source: MSEG.ERFME",
            "sourceColumn": "UnitOfMeasure"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "description": "SAP Source: MSEG.ERFMG",
            "sourceColumn": "Quantity",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          },
          {
            "name": "Linear Feet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "LinearFeet",
            "formatString": "#,0",
            "displayFolder": "_Values"
          },
          {
            "name": "Square Feet",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "SquareFeet",
            "formatString": "#,0",
            "displayFolder": "_Values"
          },
          {
            "name": "Amount",
            "dataType": "double",
            "description": "SAP Source: MSEG.DMBTR",
            "sourceColumn": "Amount",
            "formatString": "#,0.00",
            "displayFolder": "_Values",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_TRANSACTIONS_MATERIAL = Source{[Schema=\"dbo\",Item=\"VW_TRANSACTIONS_MATERIAL\"]}[Data]",
                "in",
                "    dbo_VW_TRANSACTIONS_MATERIAL"
              ]
            }
          }
        ]
      },
      {
        "name": "Converting Man Hours",
        "columns": [
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date starts at 6am and ends at 5:59am the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Shift",
            "dataType": "string",
            "sourceColumn": "Shift",
            "summarizeBy": "none"
          },
          {
            "name": "Production Hours",
            "dataType": "double",
            "description": "The number of hours across all converting employees when they are producing material",
            "sourceColumn": "ProductionHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Non Production Hours",
            "dataType": "double",
            "description": "The total number of hours across all converting employees when they are doing trainings, FEs, and other non-production activities",
            "sourceColumn": "NonProductionHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Available Hours",
            "dataType": "double",
            "description": "The total number of hours converting is scheduled to work within a shift (excluding breaks and lunch)",
            "sourceColumn": "AvailableHours",
            "formatString": "0.00",
            "summarizeBy": "sum"
          },
          {
            "name": "Notes",
            "dataType": "string",
            "sourceColumn": "Notes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_ABSORPTION = Source{[Schema=\"dbo\",Item=\"VW_CONV_HOURS\"]}[Data]",
                "in",
                "    dbo_VW_ABSORPTION"
              ]
            }
          }
        ]
      },
      {
        "name": "Converting Uptime",
        "columns": [
          {
            "name": "Production Date",
            "dataType": "dateTime",
            "description": "Production date starts at 6am and ends at 5:59am the next day",
            "sourceColumn": "ProductionDate",
            "formatString": "Short Date",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"DateTimeShortDatePattern\" />"
              }
            ]
          },
          {
            "name": "Machine Name",
            "dataType": "string",
            "sourceColumn": "MachineName"
          },
          {
            "name": "Uptime Seconds",
            "dataType": "int64",
            "sourceColumn": "UptimeSeconds"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = ARLPBI_STAGE,",
                "    dbo_VW_CONV_UPTIME = Source{[Schema=\"dbo\",Item=\"VW_CONV_UPTIME\"]}[Data]",
                "in",
                "    dbo_VW_CONV_UPTIME"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "7ad599af-e270-40c4-9adb-251c9dca4378",
        "fromTable": "Complaint Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "7bc6c5a0-4655-407a-bc13-1cd3a65eca38",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "9aea2de3-d4c1-473e-bf03-55a3a8d409f5",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "90d80725-4955-4415-8778-f3b670ded05f",
        "fromTable": "Complaint Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "1196625d-915c-4f90-8a7e-4a4e307c34c4",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "72c7c6a1-aabc-4bfc-8491-7d49d9138e2e",
        "fromTable": "Blocked Inventory",
        "fromColumn": "Notification Number",
        "toTable": "Hold Tag Documents",
        "toColumn": "Notification Number",
        "isActive": false
      },
      {
        "name": "3f9dd1f7-3ac5-4bce-b233-68a54ac9862f",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "22d61dbe-0265-4bd3-b686-8d76e4f1d50f",
        "fromTable": "Complaint Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "c2395825-7531-4dd0-9c3e-d4e7a214fb64",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "d104f71c-fb20-42c2-a158-df74a0040f19",
        "fromTable": "Hold Tag Documents",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "774c8489-a2be-42c4-8a1b-8dffc10c2904",
        "fromTable": "Blocked Inventory",
        "fromColumn": "MaterialNoKey",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "75f7059e-5891-4145-8c3b-08cf13009c2f",
        "fromTable": "Expired Inventory",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "64d69090-8c95-4cfd-bae5-098fdca2fd7c",
        "fromTable": "Complaint Documents",
        "fromColumn": "PlantNoKey",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "69c625ce-25c0-497d-9c3e-a2d15262abe1",
        "fromTable": "Blocked Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "392923c6-b921-4da9-a0eb-847df9a9ca69",
        "fromTable": "Blocked Inventory Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "ec941efc-23a0-4e1e-8fee-379eafa01610",
        "fromTable": "Complaint Documents",
        "fromColumn": "Last Credit Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "d5fde41f-6d8d-49a1-b78d-1db50db9cab6",
        "fromTable": "Expenses",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "e23eac90-b677-4be3-8b2e-bdaa9a94dc93",
        "fromTable": "Expenses",
        "fromColumn": "Cost Element",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "43dc6699-1755-45fc-989b-be3676e258f3",
        "fromTable": "Expenses",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "e64c99ce-a3ae-4e92-a4d4-b827a2df4050",
        "fromTable": "Expenses",
        "fromColumn": "PurchaseDocLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "d8be19f9-8a2d-4705-87ba-97ce6a35808d",
        "fromTable": "Purchase Orders",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "7c3dbb62-0337-4cc5-9e9c-df847491f72f",
        "fromTable": "Complaint Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey"
      },
      {
        "name": "ae51b0d3-b4c7-4f09-a508-4760ecf542bc",
        "fromTable": "Complaint Documents - Credited",
        "fromColumn": "ComplaintLineKey",
        "toTable": "Complaint Documents",
        "toColumn": "ComplaintLineKey"
      },
      {
        "name": "bb994812-edd5-4866-b953-2c6a4947a747",
        "fromTable": "Complaint Documents - Credited",
        "fromColumn": "Credit Issued Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6f4a4e75-689a-4bd1-8fe0-321e1b128db2",
        "fromTable": "Sales Order Documents",
        "fromColumn": "ReasonCodeKey",
        "toTable": "Reason Code",
        "toColumn": "ReasonCodeKey"
      },
      {
        "name": "4c4cdf75-2716-4c3e-b281-b08eaee90a8b",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Enter Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "24ac2122-cadb-486a-a099-9ca4d9472ced",
        "fromTable": "Sales Order Documents",
        "fromColumn": "First Delivery Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "35adc316-4142-445e-9e6c-d6faae1e1044",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "96748ba5-0181-442a-ba6d-75fdceb33428",
        "fromTable": "Sales Order Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      },
      {
        "name": "f23c3ae6-b1e2-4fca-a245-be1f42e00e2b",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "b8c16a52-5847-4775-8abd-8bb356d4b1e3",
        "fromTable": "RLS_Region",
        "fromColumn": "SalesRegionKey",
        "toTable": "Sales Region",
        "toColumn": "Sales Region",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "6c7f5d85-c9b6-4d16-b9d9-96554aad9745",
        "fromTable": "RLS_Territory",
        "fromColumn": "SalesTerritoryKey",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "bbf17c5a-1360-4ff5-8464-c1322342394c",
        "fromTable": "Customer Master",
        "fromColumn": "Sales Region",
        "toTable": "Sales Region",
        "toColumn": "Sales Region"
      },
      {
        "name": "0133610b-f474-47c4-a3e2-612f4360d565",
        "fromTable": "Customer Master",
        "fromColumn": "Sales Territory",
        "toTable": "Sales Territory",
        "toColumn": "Sales Territory"
      },
      {
        "name": "dc5f18dd-e738-46d9-a5c9-5306f5255523",
        "fromTable": "RLS_CostCenter",
        "fromColumn": "CostCenterKey",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "2dfef6b6-28fb-4b3a-aced-5bc2cb76c009",
        "fromTable": "Stock Transfer Orders",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "8157dd03-c7e0-468a-b864-e8ab717607f1",
        "fromTable": "Goods and Invoice Receipts",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "982c3aae-a31d-40c1-92a1-5b55611d01da",
        "fromTable": "Purchase Order Invoices",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "ba1918f0-89e6-4284-93df-d56a390a189e",
        "fromTable": "Purchase Order Invoices",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "ce291ef4-f6d6-43db-989e-e636805941b6",
        "fromTable": "Purchase Orders",
        "fromColumn": "VendorNoKey",
        "toTable": "Vendor Master",
        "toColumn": "Vendor Number"
      },
      {
        "name": "2c9b5b75-14a7-45ae-849d-a78e7f8033cd",
        "fromTable": "Goods and Invoice Receipts",
        "fromColumn": "Vendor Number",
        "toTable": "Vendor Master",
        "toColumn": "Vendor Number"
      },
      {
        "name": "d3f017b1-44bd-4645-8deb-8c26d0ecde96",
        "fromTable": "Absorption",
        "fromColumn": "Cost Center",
        "toTable": "Cost Center Names",
        "toColumn": "Cost Center"
      },
      {
        "name": "aa32963f-d2e9-4965-839d-1354c85503d6",
        "fromTable": "Absorption",
        "fromColumn": "Cost Element",
        "toTable": "Cost Element Names",
        "toColumn": "Cost Element"
      },
      {
        "name": "749c05b1-49f2-4a5c-899b-3801eaaa0f52",
        "fromTable": "Absorption",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "be0acd87-ca5c-487c-9366-d05855204388",
        "fromTable": "Sales Order Documents",
        "fromColumn": "Entered By",
        "toTable": "SAP Users",
        "toColumn": "UsernameKey"
      },
      {
        "name": "2db43657-5faa-4957-981b-1815c9ecf050",
        "toCardinality": "many",
        "fromTable": "Sales Order Document Changes",
        "fromColumn": "OrderNoKey",
        "toTable": "Sales Order Documents",
        "toColumn": "Order Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "3df54883-286b-415a-a9ca-e9431f57d2f4",
        "fromTable": "Sales Order Document Changes",
        "fromColumn": "Changed By",
        "toTable": "SAP Users",
        "toColumn": "UsernameKey"
      },
      {
        "name": "9428d940-fbc3-4bdb-8689-20a209035670",
        "fromTable": "Purchase Orders - Deliveries",
        "fromColumn": "PurchaseOrderLineKey",
        "toTable": "Purchase Orders",
        "toColumn": "PurchaseOrderLineKey"
      },
      {
        "name": "48cb8180-79ac-45f5-b7ad-8912c6e44e15",
        "fromTable": "Purchase Orders - Deliveries",
        "fromColumn": "First Delivery Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "d1ed3275-cbe1-4844-937e-a4d48686f5a3",
        "fromTable": "Backorder Snapshots",
        "fromColumn": "Snapshot Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "56e0be47-1a9b-4c43-8428-32b03121860a",
        "fromTable": "Backorder Snapshots",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "38ba1433-fc53-4068-aa51-5947fcc2ae49",
        "fromTable": "Expired Inventory",
        "fromColumn": "Plant",
        "toTable": "Plant",
        "toColumn": "Plant",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "c8527d3a-4ba0-4eee-b9b7-2e8ab62b7327",
        "fromTable": "Purchase Orders",
        "fromColumn": "Receiving Plant",
        "toTable": "Plant",
        "toColumn": "Plant"
      },
      {
        "name": "29b9c765-765f-47b2-99ab-83bc3b93a8b8",
        "fromTable": "Goods Issues and Receipts",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "55be127a-f081-4dd0-ae15-9cea0b6b081c",
        "fromTable": "Goods Issues and Receipts",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "92d76df7-af86-4843-9820-c0dc4d79be5d",
        "fromTable": "Converting Man Hours",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "6985a741-d8a9-4d99-bee9-693dd4e5011c",
        "fromTable": "Converting Uptime",
        "fromColumn": "Production Date",
        "toTable": "Calendar",
        "toColumn": "Date"
      },
      {
        "name": "fbe75965-0259-4a21-9f85-7ec85969c6b3",
        "toCardinality": "many",
        "fromTable": "Converting Uptime",
        "fromColumn": "Machine Name",
        "toTable": "Goods Issues and Receipts",
        "toColumn": "Machine Name",
        "crossFilteringBehavior": "bothDirections"
      }
    ],
    "perspectives": [
      {
        "name": "QA Dashboard",
        "tables": [
          {
            "name": "Blocked Inventory",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "QBlock Amount"
              },
              {
                "name": "QBlock Quantity"
              },
              {
                "name": "SBlock Amount"
              },
              {
                "name": "SBlock Quantity"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Text"
              },
              {
                "name": "Notification Number"
              }
            ]
          },
          {
            "name": "Blocked Inventory Snapshots",
            "columns": [
              {
                "name": "Blocked Inv Value"
              },
              {
                "name": "Expired Value"
              },
              {
                "name": "QBlock Value"
              },
              {
                "name": "SBlock Value"
              },
              {
                "name": "Snapshot Date"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Complaint Documents",
            "columns": [
              {
                "name": "Billing Block Indicator"
              },
              {
                "name": "Complaint Amount"
              },
              {
                "name": "Complaint Line Number"
              },
              {
                "name": "Complaint Number"
              },
              {
                "name": "Complaint Type"
              },
              {
                "name": "Credit Issued Amount"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Last Credit Date"
              },
              {
                "name": "Category"
              },
              {
                "name": "Department"
              },
              {
                "name": "Reason Code Description"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Complaint Count"
              },
              {
                "name": "Complaint Value"
              },
              {
                "name": "Credit Issued"
              },
              {
                "name": "Current Blocked Inv Value"
              },
              {
                "name": "Current Q-Block Value"
              },
              {
                "name": "Current S-Block Value"
              },
              {
                "name": "Hold Amount"
              },
              {
                "name": "Hold Quantity"
              },
              {
                "name": "Hold Tag Count"
              },
              {
                "name": "Open Value"
              },
              {
                "name": "PQ Complaint Count"
              },
              {
                "name": "PQ Complaint Value"
              },
              {
                "name": "PQ Credit Issued"
              },
              {
                "name": "PQ Open Value"
              },
              {
                "name": "Product Quality Index"
              },
              {
                "name": "Product Quality Index (Credited)"
              },
              {
                "name": "Product Quality Index (Open)"
              },
              {
                "name": "Current Expired Value"
              },
              {
                "name": "Current S-Block Value with Hold Tags"
              },
              {
                "name": "Product Quality Index (Target)"
              },
              {
                "name": "PQ Complaint Cycle Time"
              },
              {
                "name": "Current Q-Block Quantity"
              },
              {
                "name": "Current S-Block Quantity"
              },
              {
                "name": "Current Expired Quantity"
              }
            ]
          },
          {
            "name": "Expired Inventory",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Expiration Date"
              },
              {
                "name": "Goods Receipt Date"
              },
              {
                "name": "Manufacturing Date"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "Hold Tag Documents",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Notification Code"
              },
              {
                "name": "Notification Number"
              },
              {
                "name": "Notification Text"
              },
              {
                "name": "Notification Type"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reference Number"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "Pending Specification Documents",
            "columns": [
              {
                "name": "Approver Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "Pending Count"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Report Name"
              },
              {
                "name": "Refresh Date"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Time Calculation"
              }
            ]
          }
        ]
      },
      {
        "name": "Expenses",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Expenses",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Creation Date"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Header Text"
              },
              {
                "name": "Document Item Text"
              },
              {
                "name": "Document Line Number"
              },
              {
                "name": "Document Number"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Is Reversal Document"
              },
              {
                "name": "Is Reversed"
              },
              {
                "name": "OffsetAcctNoKey"
              },
              {
                "name": "OffsetAcctType"
              },
              {
                "name": "PlantNoKey"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "PurchaseDocLineKey"
              },
              {
                "name": "Referenced Document Line Number"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Reversal Referenced Document Number"
              },
              {
                "name": "Expense Type"
              },
              {
                "name": "Offset Account Name"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Description"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Is Controllable Expense"
              },
              {
                "name": "Category"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Req Track Number"
              }
            ]
          },
          {
            "name": "_Expenses Mode",
            "columns": [
              {
                "name": "Mode"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Expenses Amount"
              },
              {
                "name": "Expenses Plan"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Report Name"
              },
              {
                "name": "Refresh Date"
              }
            ]
          }
        ]
      },
      {
        "name": "CS Dashboard",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Day"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Complaint Documents",
            "columns": [
              {
                "name": "Billing Block Indicator"
              },
              {
                "name": "Category"
              },
              {
                "name": "Complaint Amount"
              },
              {
                "name": "Complaint Line Number"
              },
              {
                "name": "Complaint Number"
              },
              {
                "name": "Complaint Type"
              },
              {
                "name": "Credit Issued Amount"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Last Credit Date"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Department"
              },
              {
                "name": "Reason Code Description"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "CA Complaint Count"
              },
              {
                "name": "CA Complaint Value"
              },
              {
                "name": "Customer Accommodation Index"
              },
              {
                "name": "Service Quality Index"
              },
              {
                "name": "SQ Complaint Count"
              },
              {
                "name": "SQ Complaint Value"
              },
              {
                "name": "Customer Accommodation Index (Target)"
              },
              {
                "name": "Service Quality Index (Target)"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Sales Order Count"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Cost Amount"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Sample Category"
              },
              {
                "name": "Tier"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              }
            ]
          }
        ]
      },
      {
        "name": "Generic Sales",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Account Creation Date"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Sales Territory Name"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Gross Margin"
              },
              {
                "name": "FYTD Gross Margin%"
              },
              {
                "name": "FYTD Gross Sales"
              },
              {
                "name": "FYTD PY Gross Margin"
              },
              {
                "name": "FYTD PY Gross Margin%"
              },
              {
                "name": "FYTD PY Gross Sales"
              },
              {
                "name": "FYTD PY Var Gross Sales"
              },
              {
                "name": "Gross Margin"
              },
              {
                "name": "Gross Margin %"
              },
              {
                "name": "MTD Gross Margin"
              },
              {
                "name": "MTD Gross Margin%"
              },
              {
                "name": "MTD Gross Sales"
              },
              {
                "name": "MTD PY Gross Margin"
              },
              {
                "name": "MTD PY Gross Margin%"
              },
              {
                "name": "MTD PY Gross Sales"
              },
              {
                "name": "Gross Sales Budget"
              },
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Quantity Sold"
              },
              {
                "name": "Gross Sales"
              },
              {
                "name": "Sales Order Margin"
              },
              {
                "name": "MTD PY Var Gross Sales"
              },
              {
                "name": "FYTD PY Var% Gross Sales"
              },
              {
                "name": "MTD PY Var% Gross Sales"
              },
              {
                "name": "FYTD Quantity Sold"
              },
              {
                "name": "MTD Quantity Sold"
              },
              {
                "name": "FYTD Gross Margin% Budget"
              },
              {
                "name": "MTD Gross Margin% Budget"
              },
              {
                "name": "FYTD Gross Sales & Backorder"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "FYTD Gross Sales Budget"
              },
              {
                "name": "MTD Gross Sales & Backorder"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "MTD Gross Sales Budget"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "Overall Cost"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Sales Invoice Documents",
            "columns": [
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Discount Amount"
              },
              {
                "name": "Gross Sales Amount"
              },
              {
                "name": "Invoice Line Number"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Material Cost Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Net Sales Amount"
              },
              {
                "name": "Overall Cost Amount"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Document Type Text"
              },
              {
                "name": "Create Date"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Quantity Unit"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Gross Margin Amount"
              },
              {
                "name": "Was New Product"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Ship To City"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              }
            ]
          },
          {
            "name": "_Currency to Use",
            "columns": [
              {
                "name": "Currency"
              }
            ]
          }
        ]
      },
      {
        "name": "BI Morning Dashboard",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Gross Margin"
              },
              {
                "name": "FYTD Gross Margin%"
              },
              {
                "name": "FYTD Gross Sales"
              },
              {
                "name": "FYTD PY Gross Margin"
              },
              {
                "name": "FYTD PY Gross Margin%"
              },
              {
                "name": "FYTD PY Gross Sales"
              },
              {
                "name": "FYTD PY Var Gross Sales"
              },
              {
                "name": "FYTD PY Var% Gross Sales"
              },
              {
                "name": "Gross Margin"
              },
              {
                "name": "Gross Margin %"
              },
              {
                "name": "Gross Sales"
              },
              {
                "name": "MTD Gross Margin"
              },
              {
                "name": "MTD Gross Margin%"
              },
              {
                "name": "MTD Gross Sales"
              },
              {
                "name": "MTD PY Gross Margin"
              },
              {
                "name": "MTD PY Gross Margin%"
              },
              {
                "name": "MTD PY Gross Sales"
              },
              {
                "name": "MTD PY Var Gross Sales"
              },
              {
                "name": "MTD PY Var% Gross Sales"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Beginning of Month"
              },
              {
                "name": "End of Month"
              },
              {
                "name": "Yesterday"
              },
              {
                "name": "FYTD PY Sales Order Amount"
              },
              {
                "name": "FYTD PY Var Sales Order Amount"
              },
              {
                "name": "FYTD PY Var% Sales Order Amount"
              },
              {
                "name": "MTD PY Sales Order Amount"
              },
              {
                "name": "MTD PY Var Sales Order Amount"
              },
              {
                "name": "MTD PY Var% Sales Order Amount"
              },
              {
                "name": "FYTD Sales Order Amount"
              },
              {
                "name": "MTD Sales Order Amount"
              },
              {
                "name": "Backorder Amount"
              },
              {
                "name": "FYTD Gross Sales & Backorder"
              },
              {
                "name": "FYTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "MTD Gross Sales & Backorder"
              },
              {
                "name": "MTD Gross Sales & Backorder Margin%"
              },
              {
                "name": "Backorder Amount (Beyond Next Month)"
              },
              {
                "name": "Backorder Amount (Current Month)"
              },
              {
                "name": "Backorder Amount (Next Month)"
              },
              {
                "name": "Backorder Amount (Past Due)"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "Absorption"
              },
              {
                "name": "Earned Labor"
              },
              {
                "name": "Earned Overhead"
              },
              {
                "name": "MTD Absorption"
              },
              {
                "name": "MTD PY Absorption"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Sales Invoice Documents",
            "columns": [
              {
                "name": "Create Date"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Discount Amount"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "Document Type Text"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "Gross Sales Amount"
              },
              {
                "name": "Invoice Date"
              },
              {
                "name": "Invoice Line Number"
              },
              {
                "name": "Invoice Number"
              },
              {
                "name": "Material Cost Amount"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Net Sales Amount"
              },
              {
                "name": "Overall Cost Amount"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Quantity Unit"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Customer Material Number"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "DepartmentSortKey"
              },
              {
                "name": "Operations Category"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Sub Category"
              }
            ]
          }
        ]
      },
      {
        "name": "Open Orders Report",
        "tables": [
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "In Stock Measure"
              },
              {
                "name": "PO Delivered Quantity"
              },
              {
                "name": "PO In Transit Quantity"
              },
              {
                "name": "PO Open Amount"
              },
              {
                "name": "PO Open Quantity"
              },
              {
                "name": "PO Ordered Amount"
              },
              {
                "name": "PO Ordered Quantity"
              },
              {
                "name": "PD PO Backorder Amount"
              },
              {
                "name": "PD Var PO Open Amount"
              },
              {
                "name": "PD SO Customer Open Amount"
              },
              {
                "name": "PD Var SO Customer Open Amount"
              },
              {
                "name": "SO Allocated Amount"
              },
              {
                "name": "SO Customer Open Margin"
              },
              {
                "name": "SO Shipped Amount"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Sample Category"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Stock Transfer Orders",
            "columns": [
              {
                "name": "Batch Number"
              },
              {
                "name": "Delivered Amount"
              },
              {
                "name": "Delivered Quantity"
              },
              {
                "name": "Goods Receipt Amount"
              },
              {
                "name": "Goods Receipt Quantity"
              },
              {
                "name": "In Transit Amount"
              },
              {
                "name": "In Transit Quantity"
              },
              {
                "name": "MaterialNoKey"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Valuation Class"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Shipment Document Number"
              },
              {
                "name": "Shipment Document Line Number"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "Company Code"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "Backorder Snapshots",
            "columns": [
              {
                "name": "Incoming"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Outgoing"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Snapshot Date"
              },
              {
                "name": "Order Type"
              }
            ]
          },
          {
            "name": "Plant",
            "columns": [
              {
                "name": "Description"
              },
              {
                "name": "Plant"
              }
            ]
          }
        ]
      },
      {
        "name": "Goods and Invoice Receipts",
        "tables": [
          {
            "name": "_Currency to Use",
            "columns": [
              {
                "name": "Currency"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Goods and Invoice Receipts",
            "columns": [
              {
                "name": "Accounting Document Line Number"
              },
              {
                "name": "Accounting Document Number"
              },
              {
                "name": "Amount (Document)"
              },
              {
                "name": "Amount (Local)"
              },
              {
                "name": "Amount (Local2)"
              },
              {
                "name": "Assignment Number"
              },
              {
                "name": "Clearing Date"
              },
              {
                "name": "Clearing Document Number"
              },
              {
                "name": "Company Code"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Document Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First GR Year"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "G/L Account"
              },
              {
                "name": "Item Text"
              },
              {
                "name": "Local Currency"
              },
              {
                "name": "Local Currency 2"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Purchase Order Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Referenced Document Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "Vendor Number"
              },
              {
                "name": "PostingRank"
              },
              {
                "name": "PurchaseOrderLineKey"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "GRIR Amount (Document)"
              },
              {
                "name": "GRIR Amount (Local)"
              },
              {
                "name": "GRIR Amount (Local2)"
              },
              {
                "name": "GRIR Quantity"
              },
              {
                "name": "GRIR Open Amount"
              },
              {
                "name": "GRIR Open Quantity"
              }
            ]
          }
        ]
      },
      {
        "name": "Purchase Orders",
        "tables": [
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Purchase Order Invoices",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Currency"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "PostingRank"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Amount at Last PY Price"
              },
              {
                "name": "Last PY Quantity"
              },
              {
                "name": "Last PY Amount"
              },
              {
                "name": "Price Difference"
              }
            ]
          },
          {
            "name": "Purchase Orders",
            "columns": [
              {
                "name": "Currency"
              },
              {
                "name": "Document Date"
              },
              {
                "name": "Document Type"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "Is Complete Delivery"
              },
              {
                "name": "Is Goods Receipt Required"
              },
              {
                "name": "Issuing Plant"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Open Amount"
              },
              {
                "name": "Open Quantity"
              },
              {
                "name": "Ordered Amount"
              },
              {
                "name": "Ordered Quantity"
              },
              {
                "name": "Purchase Line Number"
              },
              {
                "name": "Purchase Order Number"
              },
              {
                "name": "PurchaseOrderLineKey"
              },
              {
                "name": "Receiving Plant"
              },
              {
                "name": "Req Track Number"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "VendorNoKey"
              },
              {
                "name": "Purchase Order Unit"
              },
              {
                "name": "Company Code"
              }
            ]
          },
          {
            "name": "Vendor Master",
            "columns": [
              {
                "name": "Vendor Name"
              },
              {
                "name": "Vendor Number"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "FYTD Last PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD Last PO Invoice Receipt Quantity"
              },
              {
                "name": "FYTD Last PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PO Invoice Receipt Amount in PY Price"
              },
              {
                "name": "FYTD PO Invoice Receipt Quantity"
              },
              {
                "name": "FYTD PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD Purchase Price Difference"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Quantity"
              },
              {
                "name": "PO Delivered Quantity"
              },
              {
                "name": "PO In Transit Quantity"
              },
              {
                "name": "PO Invoice Receipt Amount"
              },
              {
                "name": "PO Invoice Receipt Quantity"
              },
              {
                "name": "PO Open Amount"
              },
              {
                "name": "PO Open Quantity"
              },
              {
                "name": "PO Ordered Amount"
              },
              {
                "name": "PO Ordered Quantity"
              },
              {
                "name": "FYTD PY Last PO Invoice Receipt Unit Price"
              },
              {
                "name": "FYTD Purchase Price Index"
              },
              {
                "name": "FYTD Purchase Price Index%"
              },
              {
                "name": "FYTD PY PO Invoice Receipt Amount"
              },
              {
                "name": "FYTD PY PO Invoice Receipt Quantity"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          }
        ]
      },
      {
        "name": "Absorption",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Absorption",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Business Transaction Type"
              },
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Quantity"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Cost Center Names",
            "columns": [
              {
                "name": "Cost Center"
              },
              {
                "name": "Cost Center Name"
              },
              {
                "name": "Department"
              },
              {
                "name": "DepartmentSortKey"
              },
              {
                "name": "Operations Category"
              }
            ]
          },
          {
            "name": "Cost Element Names",
            "columns": [
              {
                "name": "Category"
              },
              {
                "name": "Category Renamed"
              },
              {
                "name": "Company Category"
              },
              {
                "name": "Cost Element"
              },
              {
                "name": "Cost Element Name"
              },
              {
                "name": "Sub Category"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Absorption"
              },
              {
                "name": "Earned Labor"
              },
              {
                "name": "Earned Overhead"
              },
              {
                "name": "MTD Absorption"
              },
              {
                "name": "MTD PY Absorption"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Orders",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Customer Master",
            "columns": [
              {
                "name": "Account Creation Date"
              },
              {
                "name": "Country"
              },
              {
                "name": "Customer Name"
              },
              {
                "name": "Customer Number"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Default Ship Plant"
              },
              {
                "name": "Is New Customer"
              },
              {
                "name": "Sales Organization"
              },
              {
                "name": "Sales Person"
              },
              {
                "name": "Sales Region"
              },
              {
                "name": "Sales Territory"
              },
              {
                "name": "Sales Territory Name"
              },
              {
                "name": "SalesRegionSortKey"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "X Distribution Status"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "Square Feet"
              }
            ]
          },
          {
            "name": "Sales Order Documents",
            "columns": [
              {
                "name": "Allocated Quantity"
              },
              {
                "name": "Billing Status"
              },
              {
                "name": "Cost Amount"
              },
              {
                "name": "Cost Amount Local"
              },
              {
                "name": "Credit Block"
              },
              {
                "name": "Customer Material Number"
              },
              {
                "name": "Customer Open Amount"
              },
              {
                "name": "Customer Open Amount Local"
              },
              {
                "name": "Customer Open Quantity"
              },
              {
                "name": "CustomerNoKey"
              },
              {
                "name": "CustomerOrgKey"
              },
              {
                "name": "Enter Date"
              },
              {
                "name": "Entered By"
              },
              {
                "name": "Exchange Rate"
              },
              {
                "name": "External Purchase Order Number"
              },
              {
                "name": "First Delivery Date"
              },
              {
                "name": "In Stock"
              },
              {
                "name": "Internal Open Amount"
              },
              {
                "name": "Internal Open Amount Local"
              },
              {
                "name": "Internal Open Quantity"
              },
              {
                "name": "Last PGI Date"
              },
              {
                "name": "Margin Amount"
              },
              {
                "name": "Margin Amount Local"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Order Amount"
              },
              {
                "name": "Order Amount Local"
              },
              {
                "name": "Order Currency"
              },
              {
                "name": "Order Line Number"
              },
              {
                "name": "Order Number"
              },
              {
                "name": "Order Quantity"
              },
              {
                "name": "Order Type"
              },
              {
                "name": "OrderNoLineKey"
              },
              {
                "name": "Organization"
              },
              {
                "name": "Plant"
              },
              {
                "name": "ReasonCodeKey"
              },
              {
                "name": "Route Type"
              },
              {
                "name": "Ship To City"
              },
              {
                "name": "Ship To Name"
              },
              {
                "name": "Shipped On Time Quantity"
              },
              {
                "name": "Shipped Quantity"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Unit Price"
              },
              {
                "name": "Has Changes (CS)"
              },
              {
                "name": "Customer Open Margin Amount"
              },
              {
                "name": "Customer Open Margin Amount (Local)"
              },
              {
                "name": "Tier"
              },
              {
                "name": "Processing Status"
              },
              {
                "name": "Allocated Amount Local"
              },
              {
                "name": "Allocated Amount"
              },
              {
                "name": "Shipped Amount Local"
              },
              {
                "name": "Shipped Amount"
              },
              {
                "name": "Sample Category"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Year_Month_Sort_Key"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "Backorder Amount"
              },
              {
                "name": "Backorder Amount (Beyond Next Month)"
              },
              {
                "name": "Backorder Amount (Current Month)"
              },
              {
                "name": "Backorder Amount (Next Month)"
              },
              {
                "name": "Backorder Amount (Past Due)"
              },
              {
                "name": "Backorder Margin"
              },
              {
                "name": "FYTD PY Sales Order Amount"
              },
              {
                "name": "FYTD PY Var Sales Order Amount"
              },
              {
                "name": "FYTD PY Var% Sales Order Amount"
              },
              {
                "name": "FYTD Sales Order Amount"
              },
              {
                "name": "MTD PY Sales Order Amount"
              },
              {
                "name": "MTD PY Var Sales Order Amount"
              },
              {
                "name": "MTD PY Var% Sales Order Amount"
              },
              {
                "name": "MTD Sales Order Amount"
              },
              {
                "name": "Sales Order Amount"
              },
              {
                "name": "Sales Order Cost Amount"
              },
              {
                "name": "Sales Order Count"
              },
              {
                "name": "Sales Order Line Count"
              },
              {
                "name": "Sales Order Lines Automated"
              },
              {
                "name": "Sales Order Lines Automated Entry%"
              },
              {
                "name": "Sales Order Margin"
              },
              {
                "name": "SO Allocated Quantity"
              },
              {
                "name": "SO Customer Open Amount"
              },
              {
                "name": "SO Customer Open Quantity"
              },
              {
                "name": "SO Internal Open Amount"
              },
              {
                "name": "SO Internal Open Quantity"
              },
              {
                "name": "SO Ordered Quantity"
              },
              {
                "name": "SO Shipped Quantity"
              },
              {
                "name": "Sales Order Lines Manual"
              },
              {
                "name": "FYTD PY Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Lines Automated Entry%"
              },
              {
                "name": "MTD Sales Order Lines Automated Entry%"
              },
              {
                "name": "MTD Sales Order Line Count"
              },
              {
                "name": "FYTD Sales Order Automation Efficiency%"
              },
              {
                "name": "MTD Sales Order Automation Efficiency%"
              },
              {
                "name": "Sales Order Automation Efficiency%"
              },
              {
                "name": "Sales Order Lines Automated (No Changes)"
              },
              {
                "name": "Sales Order Lines Manual Entry%"
              },
              {
                "name": "Sales Order Line Count (Automated + Manual)"
              },
              {
                "name": "SO Allocated Amount"
              },
              {
                "name": "SO Customer Open Margin"
              },
              {
                "name": "SO Shipped Amount"
              }
            ]
          },
          {
            "name": "Sales Order Document Changes",
            "columns": [
              {
                "name": "Change Date"
              },
              {
                "name": "Change Time"
              },
              {
                "name": "Changed By"
              },
              {
                "name": "OrderNoKey"
              }
            ]
          }
        ]
      },
      {
        "name": "Engineering",
        "tables": [
          {
            "name": "_Refresh Date",
            "columns": [
              {
                "name": "Refresh Date"
              },
              {
                "name": "Report Name"
              }
            ]
          },
          {
            "name": "Calendar",
            "columns": [
              {
                "name": "Calendar Month Number"
              },
              {
                "name": "Calendar Quarter Name"
              },
              {
                "name": "Calendar Week Number"
              },
              {
                "name": "Calendar Year Number"
              },
              {
                "name": "Date"
              },
              {
                "name": "Day"
              },
              {
                "name": "Fiscal Period"
              },
              {
                "name": "Fiscal Quarter Name"
              },
              {
                "name": "Fiscal Year Month Name"
              },
              {
                "name": "Fiscal Year Number"
              },
              {
                "name": "Is Calendar YTD"
              },
              {
                "name": "Is Current Fiscal Year"
              },
              {
                "name": "Is Current Month"
              },
              {
                "name": "Is Fiscal YTD"
              },
              {
                "name": "Is Last 13 Months"
              },
              {
                "name": "Is Last 2 Calendar Years"
              },
              {
                "name": "Is Last 2 Fiscal Years"
              },
              {
                "name": "Is Last 3 Calendar Years"
              },
              {
                "name": "Is Last 3 Fiscal Years"
              },
              {
                "name": "Is MTD"
              },
              {
                "name": "Is Weekday"
              },
              {
                "name": "Month Name"
              },
              {
                "name": "Month Name (Calendar)"
              },
              {
                "name": "Year_Month_Sort_Key"
              }
            ],
            "hierarchies": [
              {
                "name": "Calendar Hierarchy"
              },
              {
                "name": "Fiscal Hierarchy"
              }
            ]
          },
          {
            "name": "Goods Issues and Receipts",
            "columns": [
              {
                "name": "Amount"
              },
              {
                "name": "Batch Number"
              },
              {
                "name": "Fiscal Year"
              },
              {
                "name": "Linear Feet"
              },
              {
                "name": "Machine Name"
              },
              {
                "name": "Material Document Header Text"
              },
              {
                "name": "Material Document Line Number"
              },
              {
                "name": "Material Document Number"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Movement Type"
              },
              {
                "name": "Plant"
              },
              {
                "name": "Posted By"
              },
              {
                "name": "Posting Date"
              },
              {
                "name": "Posting Time"
              },
              {
                "name": "Process Order Number"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Quantity"
              },
              {
                "name": "Reason Code"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Storage Bin"
              },
              {
                "name": "Storage Location"
              },
              {
                "name": "Storage Type"
              },
              {
                "name": "Unit of Measure"
              }
            ]
          },
          {
            "name": "Material Master",
            "columns": [
              {
                "name": "Brand"
              },
              {
                "name": "Color Number"
              },
              {
                "name": "Commercialization Date"
              },
              {
                "name": "Film Type"
              },
              {
                "name": "Is New Product"
              },
              {
                "name": "Length (ft)"
              },
              {
                "name": "Liner"
              },
              {
                "name": "Material Description"
              },
              {
                "name": "Material Group"
              },
              {
                "name": "Material Number"
              },
              {
                "name": "Material Number - Description"
              },
              {
                "name": "Material Type"
              },
              {
                "name": "Product Hierarchy L1"
              },
              {
                "name": "Product Hierarchy L2"
              },
              {
                "name": "Product Hierarchy L3"
              },
              {
                "name": "Product Series"
              },
              {
                "name": "Square Feet"
              },
              {
                "name": "Unit of Measure"
              },
              {
                "name": "Width (in)"
              },
              {
                "name": "X Distribution Status"
              }
            ]
          },
          {
            "name": "DAX Measures",
            "measures": [
              {
                "name": "GI Linear Footage"
              },
              {
                "name": "GI Scrap Rate"
              },
              {
                "name": "GR Linear Footage"
              },
              {
                "name": "GR Square Footage"
              },
              {
                "name": "Yesterday"
              },
              {
                "name": "GIR Amount"
              },
              {
                "name": "GIR Linear Footage"
              },
              {
                "name": "GIR Quantity"
              },
              {
                "name": "GIR Square Footage"
              },
              {
                "name": "CONV Available Hours"
              },
              {
                "name": "CONV Production Hours"
              },
              {
                "name": "CONV Square Feet per Man Hour"
              },
              {
                "name": "CONV Square Feet per Man Hour (Target)"
              },
              {
                "name": "CONV Square Feet per Man Hour (Target Variance)"
              },
              {
                "name": "CONV Availability"
              },
              {
                "name": "CONV Uptime Hours"
              },
              {
                "name": "PD GI Linear Footage"
              },
              {
                "name": "PD GI Scrap Rate"
              },
              {
                "name": "PD GR Linear Footage"
              }
            ]
          },
          {
            "name": "_Time Intelligence",
            "columns": [
              {
                "name": "Ordinal"
              },
              {
                "name": "Time Calculation"
              }
            ]
          },
          {
            "name": "Converting Man Hours",
            "columns": [
              {
                "name": "Available Hours"
              },
              {
                "name": "Non Production Hours"
              },
              {
                "name": "Notes"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Production Hours"
              },
              {
                "name": "Shift"
              }
            ]
          },
          {
            "name": "Converting Uptime",
            "columns": [
              {
                "name": "Machine Name"
              },
              {
                "name": "Production Date"
              },
              {
                "name": "Uptime Seconds"
              }
            ]
          }
        ]
      }
    ],
    "roles": [
      {
        "name": "All Data",
        "description": "Can read all data in the model",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\LBabilo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1731"
          },
          {
            "memberName": "DOMAIN\\JSipkovich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1457"
          },
          {
            "memberName": "DOMAIN\\rfaust",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21470"
          },
          {
            "memberName": "DOMAIN\\jmilliken",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8848"
          },
          {
            "memberName": "DOMAIN\\ahuddlestone",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7281"
          },
          {
            "memberName": "DOMAIN\\amcneill",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7269"
          },
          {
            "memberName": "DOMAIN\\CRussell",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1426"
          },
          {
            "memberName": "DOMAIN\\abratter",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8513"
          },
          {
            "memberName": "DOMAIN\\mebin",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8453"
          },
          {
            "memberName": "DOMAIN\\jmody",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8514"
          },
          {
            "memberName": "DOMAIN\\jmcmanus",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8437"
          },
          {
            "memberName": "DOMAIN\\jjing",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7288"
          },
          {
            "memberName": "DOMAIN\\bmoore",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21012"
          },
          {
            "memberName": "DOMAIN\\sdong",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8750"
          },
          {
            "memberName": "DOMAIN\\rraymundo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2857"
          },
          {
            "memberName": "DOMAIN\\kbesse",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8862"
          },
          {
            "memberName": "DOMAIN\\mqadir",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20430"
          }
        ]
      },
      {
        "name": "By Sales Region",
        "description": "Reads data by sales region",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\bgraiff",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7297"
          },
          {
            "memberName": "DOMAIN\\cjames",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8752"
          },
          {
            "memberName": "DOMAIN\\DCastro",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1777"
          },
          {
            "memberName": "DOMAIN\\DDuncan",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1424"
          },
          {
            "memberName": "DOMAIN\\dpiechocki",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8767"
          },
          {
            "memberName": "DOMAIN\\GDebes",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1711"
          },
          {
            "memberName": "DOMAIN\\jsmith",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8622"
          },
          {
            "memberName": "DOMAIN\\lcalma",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6987"
          },
          {
            "memberName": "DOMAIN\\mbraswell",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8601"
          },
          {
            "memberName": "DOMAIN\\mjaffre",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8526"
          },
          {
            "memberName": "DOMAIN\\mpopovich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7298"
          },
          {
            "memberName": "DOMAIN\\ngomez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8600"
          },
          {
            "memberName": "DOMAIN\\pcinski",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7213"
          },
          {
            "memberName": "DOMAIN\\RDaize",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1678"
          },
          {
            "memberName": "DOMAIN\\sterenzi",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8498"
          },
          {
            "memberName": "DOMAIN\\pplessis",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2848"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Region",
            "filterExpression": "RLS_Region[DomainName]=USERNAME() && RLS_Region[InactiveDate] < TODAY()",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Territory",
            "metadataPermission": "none"
          }
        ]
      },
      {
        "name": "By Sales Territory",
        "description": "Reads data by sales region",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\aedrei",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4956"
          },
          {
            "memberName": "DOMAIN\\aflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7300"
          },
          {
            "memberName": "DOMAIN\\arodriguez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8655"
          },
          {
            "memberName": "DOMAIN\\cdicillo",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8571"
          },
          {
            "memberName": "DOMAIN\\DOrtega",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1408"
          },
          {
            "memberName": "DOMAIN\\gwiant",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8443"
          },
          {
            "memberName": "DOMAIN\\jventola",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8549"
          },
          {
            "memberName": "DOMAIN\\LBurke",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3178"
          },
          {
            "memberName": "DOMAIN\\maybinder",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7141"
          },
          {
            "memberName": "DOMAIN\\tswartout",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8664"
          },
          {
            "memberName": "DOMAIN\\acourtois",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8499"
          },
          {
            "memberName": "DOMAIN\\ajoki",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7308"
          },
          {
            "memberName": "DOMAIN\\jnagel",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7261"
          },
          {
            "memberName": "DOMAIN\\pvangelder",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8484"
          },
          {
            "memberName": "DOMAIN\\rplenzich",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7305"
          },
          {
            "memberName": "DOMAIN\\redwards",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-19929"
          },
          {
            "memberName": "DOMAIN\\jkozlowski",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7200"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Territory",
            "filterExpression": "RLS_Territory[DomainName]=USERNAME() && RLS_Territory[InactiveDate] < TODAY()",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Region",
            "metadataPermission": "none"
          }
        ]
      },
      {
        "name": "Default",
        "description": "Default; Reads data by cost center (mainly for expenses data)",
        "modelPermission": "read",
        "members": [
          {
            "memberName": "DOMAIN\\amendes",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8652"
          },
          {
            "memberName": "DOMAIN\\aboal",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8718"
          },
          {
            "memberName": "DOMAIN\\CDagher",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1274"
          },
          {
            "memberName": "DOMAIN\\LTorres",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2683"
          },
          {
            "memberName": "DOMAIN\\lurias",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7278"
          },
          {
            "memberName": "DOMAIN\\moconnor",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8550"
          },
          {
            "memberName": "DOMAIN\\RNicholson",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1369"
          },
          {
            "memberName": "DOMAIN\\SabineS",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1423"
          },
          {
            "memberName": "DOMAIN\\sshishani",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8496"
          },
          {
            "memberName": "DOMAIN\\skline",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2799"
          },
          {
            "memberName": "DOMAIN\\tlaunay",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8525"
          },
          {
            "memberName": "DOMAIN\\WSaadat",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1091"
          },
          {
            "memberName": "DOMAIN\\rchen",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8758"
          },
          {
            "memberName": "DOMAIN\\bnovotny",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8604"
          },
          {
            "memberName": "DOMAIN\\edeleon",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6984"
          },
          {
            "memberName": "DOMAIN\\JPerez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1053"
          },
          {
            "memberName": "DOMAIN\\maustria",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6989"
          },
          {
            "memberName": "DOMAIN\\iabarca",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8573"
          },
          {
            "memberName": "DOMAIN\\jcarrizal",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8663"
          },
          {
            "memberName": "DOMAIN\\BDiaz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3188"
          },
          {
            "memberName": "DOMAIN\\pbitest1",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20421"
          },
          {
            "memberName": "DOMAIN\\pbitest2",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20422"
          },
          {
            "memberName": "DOMAIN\\nnguyen",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8899"
          },
          {
            "memberName": "DOMAIN\\ausandoval",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21488"
          },
          {
            "memberName": "DOMAIN\\efung",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8884"
          },
          {
            "memberName": "DOMAIN\\lmartinez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8901"
          },
          {
            "memberName": "DOMAIN\\JPaciotta",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1641"
          },
          {
            "memberName": "DOMAIN\\caguilar",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21008"
          },
          {
            "memberName": "DOMAIN\\eldiaz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8700"
          },
          {
            "memberName": "DOMAIN\\SCarino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1134"
          },
          {
            "memberName": "DOMAIN\\aarzate",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4946"
          },
          {
            "memberName": "DOMAIN\\agonzalez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8541"
          },
          {
            "memberName": "DOMAIN\\AGutierrez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1795"
          },
          {
            "memberName": "DOMAIN\\arubio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8524"
          },
          {
            "memberName": "DOMAIN\\cflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8506"
          },
          {
            "memberName": "DOMAIN\\cgarcia",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2747"
          },
          {
            "memberName": "DOMAIN\\clopez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7254"
          },
          {
            "memberName": "DOMAIN\\cpham",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8719"
          },
          {
            "memberName": "DOMAIN\\dmendoza",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2760"
          },
          {
            "memberName": "DOMAIN\\EAnuu",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1279"
          },
          {
            "memberName": "DOMAIN\\fesparza",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8456"
          },
          {
            "memberName": "DOMAIN\\GArguello",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4929"
          },
          {
            "memberName": "DOMAIN\\GCatalasan",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1049"
          },
          {
            "memberName": "DOMAIN\\GJimenez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1552"
          },
          {
            "memberName": "DOMAIN\\grosales",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-4954"
          },
          {
            "memberName": "DOMAIN\\icruz",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8492"
          },
          {
            "memberName": "DOMAIN\\ILopez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1772"
          },
          {
            "memberName": "DOMAIN\\jcandias",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8545"
          },
          {
            "memberName": "DOMAIN\\jfigueroa",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8435"
          },
          {
            "memberName": "DOMAIN\\jignacio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7164"
          },
          {
            "memberName": "DOMAIN\\jluisa",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7160"
          },
          {
            "memberName": "DOMAIN\\jmaradiaga",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7165"
          },
          {
            "memberName": "DOMAIN\\jnicholson",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-6995"
          },
          {
            "memberName": "DOMAIN\\jpino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2783"
          },
          {
            "memberName": "DOMAIN\\jsanchez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7229"
          },
          {
            "memberName": "DOMAIN\\jsandoval",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3249"
          },
          {
            "memberName": "DOMAIN\\jvelazquez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7270"
          },
          {
            "memberName": "DOMAIN\\kcamero",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8754"
          },
          {
            "memberName": "DOMAIN\\kmoreno",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2762"
          },
          {
            "memberName": "DOMAIN\\laguilar",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7055"
          },
          {
            "memberName": "DOMAIN\\lflores",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-2784"
          },
          {
            "memberName": "DOMAIN\\lkemp",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8596"
          },
          {
            "memberName": "DOMAIN\\LLebron",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-3043"
          },
          {
            "memberName": "DOMAIN\\mfranco",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8666"
          },
          {
            "memberName": "DOMAIN\\mignacio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7479"
          },
          {
            "memberName": "DOMAIN\\mpavia",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7053"
          },
          {
            "memberName": "DOMAIN\\rmartinez",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7230"
          },
          {
            "memberName": "DOMAIN\\rrivera",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7235"
          },
          {
            "memberName": "DOMAIN\\schio",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8653"
          },
          {
            "memberName": "DOMAIN\\TDinh",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1185"
          },
          {
            "memberName": "DOMAIN\\YOrdiano",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-1432"
          },
          {
            "memberName": "DOMAIN\\mferraro",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8849"
          },
          {
            "memberName": "DOMAIN\\jdasilva",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-7293"
          },
          {
            "memberName": "DOMAIN\\nmartino",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-8641"
          },
          {
            "memberName": "DOMAIN\\xcai",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21504"
          },
          {
            "memberName": "DOMAIN\\htolla",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-20437"
          },
          {
            "memberName": "DOMAIN\\lmota",
            "memberId": "S-1-5-21-1427733451-1004295795-1863928812-21494"
          }
        ],
        "tablePermissions": [
          {
            "name": "RLS_Territory",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_Region",
            "metadataPermission": "none"
          },
          {
            "name": "RLS_CostCenter",
            "filterExpression": "RLS_CostCenter[DomainName]=USERNAME() && RLS_CostCenter[InactiveDate] < TODAY()"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}