{
  "name": "SemanticModel",
  "compatibilityLevel": 1500,
  "model": {
    "culture": "en-US",
    "dataSources": [
      {
        "type": "structured",
        "name": "SQL/ARLPBIDEV;ARLPBI_STAGE",
        "connectionDetails": {
          "protocol": "tds",
          "address": {
            "server": "ARLPBIDEV",
            "database": "ARLPBI_STAGE"
          },
          "authentication": null,
          "query": null
        },
        "options": {},
        "credential": {
          "AuthenticationKind": "UsernamePassword",
          "Username": "sa",
          "EncryptConnection": false,
          "PrivacySetting": "Organizational"
        }
      }
    ],
    "tables": [
      {
        "name": "Calendar",
        "dataCategory": "Time",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isKey": true,
            "sourceColumn": "PK_Date",
            "formatString": "MM/dd/yyyy",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Year Number",
            "dataType": "string",
            "sourceColumn": "Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Month Number",
            "dataType": "int64",
            "sourceColumn": "Month_Of_Year",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Calendar Quarter Name",
            "dataType": "string",
            "sourceColumn": "Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "string",
            "sourceColumn": "Fiscal_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Period",
            "dataType": "int64",
            "sourceColumn": "Fiscal_Month_Of_Year",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Quarter Number",
            "dataType": "int64",
            "sourceColumn": "Fiscal_Quarter_Of_Year",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Fiscal Quarter Name",
            "dataType": "string",
            "sourceColumn": "Fiscal_Quarter_Of_Year_Name",
            "displayFolder": "Individual Attributes"
          },
          {
            "name": "Month Name",
            "dataType": "string",
            "sourceColumn": "Month_Name_Abbrev",
            "sortByColumn": "Calendar Month Number",
            "displayFolder": "Individual Attributes"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_Calendar = Source{[Schema=\"dbo\",Item=\"VW_Calendar\"]}[Data],",
                "    #\"Changed Type\" = Table.TransformColumnTypes(dbo_VW_Calendar,{{\"PK_Date\", type date}})",
                "in",
                "    #\"Changed Type\""
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Simple Calendar",
            "displayFolder": "Calendar Hierarchies",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Calendar Year Number"
              },
              {
                "name": "Month",
                "ordinal": 1,
                "column": "Month Name"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          },
          {
            "name": "Simple Fiscal Calendar",
            "displayFolder": "Fiscal Hierarchies",
            "levels": [
              {
                "name": "Fiscal Year",
                "ordinal": 0,
                "column": "Fiscal Year Number"
              },
              {
                "name": "Fiscal Period",
                "ordinal": 1,
                "column": "Fiscal Period"
              },
              {
                "name": "Date",
                "ordinal": 2,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "Sales Invoice Documents",
        "columns": [
          {
            "name": "SaleDocLineKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "SaleDocLineKey"
          },
          {
            "name": "Invoice Number",
            "dataType": "string",
            "sourceColumn": "SaleDocNoKey"
          },
          {
            "name": "Line Number",
            "dataType": "string",
            "sourceColumn": "SaleLineNo"
          },
          {
            "name": "Posting Date",
            "dataType": "dateTime",
            "sourceColumn": "PostingDateKey",
            "formatString": "MM/dd/yyyy"
          },
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Customer Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Quantity",
            "dataType": "double",
            "sourceColumn": "QuantityValue",
            "formatString": "0.00"
          },
          {
            "name": "Gross Sales Amount",
            "dataType": "double",
            "sourceColumn": "GrossSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Net Sales Amount",
            "dataType": "double",
            "sourceColumn": "NetSalesValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Overall Cost Amount",
            "dataType": "double",
            "sourceColumn": "CostValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Material Cost Amount",
            "dataType": "double",
            "sourceColumn": "MaterialExtPriceUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          },
          {
            "name": "Discount Amount",
            "dataType": "double",
            "sourceColumn": "DiscountValueUSD",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "annotations": [
              {
                "name": "Format",
                "value": "<Format Format=\"Currency\" Accuracy=\"2\" ThousandSeparator=\"True\"><Currency LCID=\"1033\" DisplayName=\"$ English (United States)\" Symbol=\"$\" PositivePattern=\"0\" NegativePattern=\"0\" /></Format>"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_SALES = Source{[Schema=\"dbo\",Item=\"VW_SALES\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(dbo_VW_SALES,{\"MANDT\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Gross Sales",
            "expression": " SUM('Sales Invoice Documents'[Gross Sales Amount])",
            "formatString": "$#,###0;-$#,###0;$0",
            "displayFolder": "Sales Measures"
          },
          {
            "name": "Net Sales",
            "expression": " SUM('Sales Invoice Documents'[Net Sales Amount])",
            "formatString": "$#,###0;-$#,###0;$0",
            "displayFolder": "Sales Measures"
          },
          {
            "name": "Cost of Goods",
            "expression": " SUM('Sales Invoice Documents'[Overall Cost Amount])",
            "formatString": "$#,###0;-$#,###0;$0",
            "displayFolder": "Sales Measures"
          },
          {
            "name": "Gross Margin",
            "expression": " [Gross Sales] - [Cost of Goods]",
            "formatString": "$#,###0;-$#,###0;$0",
            "displayFolder": "Sales Measures"
          },
          {
            "name": "Net Margin",
            "expression": " [Net Sales] - [Cost of Goods]",
            "formatString": "$#,###0;-$#,###0;$0",
            "displayFolder": "Sales Measures"
          },
          {
            "name": "Gross Margin %",
            "expression": " [Gross Margin] / [Gross Sales]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Measures\\Margin"
          },
          {
            "name": "Net Margin %",
            "expression": " [Net Margin] / [Net Sales]",
            "formatString": "0.00%;-0.00%;0.00%",
            "displayFolder": "Sales Measures\\Margin"
          }
        ]
      },
      {
        "name": "Customer Master",
        "columns": [
          {
            "name": "Customer Number",
            "dataType": "string",
            "sourceColumn": "CustomerNoKey"
          },
          {
            "name": "CustomerOrgKey",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "CustomerOrgKey"
          },
          {
            "name": "Country",
            "dataType": "string",
            "sourceColumn": "Country"
          },
          {
            "name": "Customer Name",
            "dataType": "string",
            "sourceColumn": "CustomerName"
          },
          {
            "name": "Account Creation Date",
            "dataType": "dateTime",
            "sourceColumn": "AcctCreateDate"
          },
          {
            "name": "Sales Organization",
            "dataType": "string",
            "sourceColumn": "SalesOrganization"
          },
          {
            "name": "Default Ship Plant",
            "dataType": "string",
            "sourceColumn": "DefaultPlant"
          },
          {
            "name": "Sales Region",
            "dataType": "string",
            "sourceColumn": "SalesDistrict"
          },
          {
            "name": "Sales Territory",
            "dataType": "string",
            "sourceColumn": "SalesTerritory"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_CUSTOMER_MASTER = Source{[Schema=\"dbo\",Item=\"VW_CUSTOMER_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_CUSTOMER_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Classification",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand"
          },
          {
            "name": "Color Number",
            "dataType": "string",
            "sourceColumn": "ColorNumber"
          },
          {
            "name": "Commercialization Date",
            "dataType": "dateTime",
            "sourceColumn": "CommercializationDate"
          },
          {
            "name": "Film Type",
            "dataType": "string",
            "sourceColumn": "FilmType"
          },
          {
            "name": "Liner",
            "dataType": "string",
            "sourceColumn": "Liner"
          },
          {
            "name": "Product Series",
            "dataType": "string",
            "sourceColumn": "ProductSeries"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_CLASSIFICATION = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_CLASSIFICATION\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_CLASSIFICATION"
              ]
            }
          }
        ]
      },
      {
        "name": "Material Master",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Description",
            "dataType": "string",
            "sourceColumn": "MaterialDescription"
          },
          {
            "name": "Material Number - Description",
            "dataType": "string",
            "sourceColumn": "MaterialNoDescription"
          },
          {
            "name": "Material Type",
            "dataType": "string",
            "sourceColumn": "MaterialType"
          },
          {
            "name": "Material Group",
            "dataType": "string",
            "sourceColumn": "MaterialGroup"
          },
          {
            "name": "X Distribution Status",
            "dataType": "string",
            "sourceColumn": "XDistributionStatus"
          },
          {
            "name": "Unit of Measure",
            "dataType": "string",
            "sourceColumn": "UnitOfMeasure"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_MASTER = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_MASTER\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_MASTER"
              ]
            }
          }
        ]
      },
      {
        "name": "Product Hierarchy",
        "columns": [
          {
            "name": "Material Number",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "MaterialNoKey"
          },
          {
            "name": "Product Hierarchy L1",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL1"
          },
          {
            "name": "Product Hierarchy L2",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL2"
          },
          {
            "name": "Product Hierarchy L3",
            "dataType": "string",
            "sourceColumn": "ProductHierarchyDescriptionL3"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "dataView": "full",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = #\"SQL/ARLPBIDEV;ARLPBI_STAGE\",",
                "    dbo_VW_MATERIAL_PRODHIERARCHY = Source{[Schema=\"dbo\",Item=\"VW_MATERIAL_PRODHIERARCHY\"]}[Data]",
                "in",
                "    dbo_VW_MATERIAL_PRODHIERARCHY"
              ]
            }
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "1c7fda87-9a06-4ade-807e-fc6215e96ae8",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Posting Date",
        "toTable": "Calendar",
        "toColumn": "Date",
        "crossFilteringBehavior": "bothDirections",
        "securityFilteringBehavior": "bothDirections"
      },
      {
        "name": "c2395825-7531-4dd0-9c3e-d4e7a214fb64",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "Material Number",
        "toTable": "Material Master",
        "toColumn": "Material Number"
      },
      {
        "name": "637bbb79-1df9-41df-9f01-6327cb2e1ca5",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Material Classification",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "8dbdc264-a57e-48f4-8ccf-064f378c4788",
        "fromCardinality": "one",
        "fromTable": "Material Master",
        "fromColumn": "Material Number",
        "toTable": "Product Hierarchy",
        "toColumn": "Material Number",
        "crossFilteringBehavior": "bothDirections"
      },
      {
        "name": "7bc6c5a0-4655-407a-bc13-1cd3a65eca38",
        "fromTable": "Sales Invoice Documents",
        "fromColumn": "CustomerOrgKey",
        "toTable": "Customer Master",
        "toColumn": "CustomerOrgKey"
      }
    ],
    "annotations": [
      {
        "name": "ClientCompatibilityLevel",
        "value": "600"
      }
    ]
  },
  "id": "SemanticModel"
}